### PR TITLE
Update Techs.json

### PR DESCRIPTION
**Pull request by Smashfanful**

### CODE REVIEW

**Comment by yairm210** [comment]
This is a lot more complicated than this.
We need to change the image, existing techs that people have, building and unit dependencies, and techs being researched

**Comment by Smashfanful** [comment]
How is this more complicated? I just rewritten the Replaceable Parts part.

**Comment by yairm210** [comment]
But that's not enough
If you don't change the image name the new tech won't have an image
If you don't change existing games then people currently researching "replacable parts" so have crashes because that tech no longer exists
Units and buildings requiring that tech won't be able to be built
Etc

**Comment by Smashfanful** [comment]
Or do you want me to reset the changes?

**Comment by Smashfanful** [comment]
Okay, okay, I'm sorry. Then what do we do? You change all that?

**Comment by yairm210** [comment]
First off, there's nothing to be sorry about - we both want the same thing, which is to make this a fun game to play, and we don't owe each other anything, it's all good :D

Second, part of the changes need to be done in code, so yes, I'll be changing them (or perhaps ninjatao)

**Comment by Smashfanful** [comment]
> First off, there's nothing to be sorry about - we both want the same thing, which is to make this a fun game to play, and we don't owe each other anything, it's all good :D
> 
> Second, part of the changes need to be done in code, so yes, I'll be changing them (or perhaps ninjatao)

Thank you so much.

**Pull request closed without merging**
