### PR TITLE
Corrected many building production costs, tech requirements and wonder effects

### PR DESCRIPTION
**Pull request by avdstaaij**
Many, and I do mean many, of the building production costs are wrong according to the wiki.
Each column of the tech tree has a building cost (of which only a few buildings deviate). The primary source of errors is that these building costs have been shifted one column over starting from column 4, the second column of the Renaissance, causing almost all buildings from that point on to be too expensive. There were a few other errors as well, all causing buildings to be too expensive. This PR corrects all of the production costs.

Furthermore, This PR also corrects many tech requirements and wonder behaviors: many of these were incorrect as well. Note that while the building corrections are exhaustive, these may not be. I would have done this in a separate PRs, but they would no doubt have had conflicts with the cost changes, so I just put everything in a single PR.

Here is the full changelog:

---

Production cost changes:
(Changes marked with "(!)" are different from the tech column cost shift)
```
Lighthouse         100 -> 75  (!)
Great Lighthouse   250 -> 185 (!)

Temple             120 -> 100
Burial Tomb        120 -> 100
Mud Pyramid Mosque 120 -> 100
Market             120 -> 100
Bazaar             120 -> 100
Mint               120 -> 100
Aqueduct           120 -> 100
The Oracle         300 -> 250
Petra              300 -> 250
Great Wall         300 -> 250
Colossus           300 -> 185 (!)

Monastery          160 -> 120
Workshop           160 -> 120
Forge              160 -> 120
Hagia Sophia       400 -> 300
Chichen Itza       400 -> 300
Machu Picchu       400 -> 300

Harbor             200 -> 120 (!)
University         200 -> 160
Wat                200 -> 160
Castle             200 -> 160
Mughal Fort        200 -> 150 (!)
Armory             200 -> 160
Angkor Wat         500 -> 400
Alhambra           500 -> 400
Notre Dame         500 -> 400

Observatory        250 -> 200
Opera House        250 -> 200
Bank               250 -> 200
Satrap's Court     250 -> 200
Hanse              250 -> 200
Theatre            250 -> 200
Sistine Chapel     625 -> 500
Forbidden Palace   625 -> 500
L. Tower of Pisa   625 -> 500
Himeji Castle      625 -> 500

Seaport            300 -> 250
Windmill           300 -> 250
Taj Mahal          750 -> 625
Porcelain Tower    750 -> 625
Kremlin            1250 -> 625 (!)

Museum             360 -> 300
Public School      360 -> 300
Military Academy   360 -> 300
Louvre             920 -> 750
Big Ben            920 -> 750
Brandenburg Gate   920 -> 750

Hospital           500 -> 360
Stock Exchange     500 -> 360

Eiffel Tower       1250 -> 1060
Statue of Liberty  1250 -> 1060
Neuschwanstein     1250 -> 1060

Manhattan Project  2000 -> 750  (!)

Solar Plant        750  -> 500
Nuclear Plant      750  -> 500
Sydney Opera House 2000 -> 1250
Apollo Program     1500 -> 750  (!)
```

Tech requirement and wonder effect changes:
```
Hanging gardens:
10 food -> 6 food
Now provides a free Garden

National Treasury:
Now unlocked with Guilds instead of Currency

Angkor Wat:
Now unlocked with Education instead of Chivalry

Leaning Tower of Pisa:
Now provides +25% great person generation in all cities

Hermitage:
Now unlocked with Architecture instead of Archaeology

Kremlin:
Now unlocked with Metallurgy instead of Railroad

Cristo Redentor:
Now unlocked with Plastics instead of Flight

Manhattan Project:
Now unlocked with Atomic Theory instead of Nuclear Fission
This does buff nuclear missiles quite a bit, since you no longer need
Nuclear Fission, but that's only because the last part of the tech tree
is very incomplete, and provides nuclear missiles too early. We need to
start correcting it somewhere.
```

---

Final note: according to the wiki, National Treasury has a base cost of 120 instead of 125. However, every single other national wonder has a base cost of 125, so I just left the base cost in Unciv at 125. EDIT: @xlenstra has confirmed that the wiki is in error on this one.

EDIT: made some more corrections, which have been included in the changelog.
EDIT: reverted some incorrect corrections identified by @ravignir and updated the changelog.

### CODE REVIEW

**Comment by xlenstra** [comment]
I have checked these with the ingame civilopedia (G&K version), and all the changes are accurate.

**Comment by logicminimal** [comment]
i really wonder where wrong policy/wonder bonuses even came from

**Comment by avdstaaij** [comment]
I made some more corrections and I have edited the changelog to include them.

**Comment by ravignir** [comment]
> 
> 
> i really wonder where wrong policy/wonder bonuses even came from (excluding vanilla/gnk/bnw interference)

some from BNW changes.

Kremlin actually gives 12 City Strength in G&K:
 
obraz

Statue of Liberty does not give Free Social Policy - that effect comes from BNW as SoL is a ideology wonder:

obraz

Also RIP OP vanilla Hanging Gardens 🤣

**Comment by avdstaaij** [comment]
I've reverted the incorrect corrections.

> Kremlin actually gives 12 City Strength in G&K:

Another one for the list of incorrect wiki pages :P (admittedly, I'm not fixing them either).

> Also RIP OP vanilla Hanging Gardens rofl

It really was ridiculous.

**Pull request merged**
