### PR TITLE
Update Russian.properties

### PR DESCRIPTION
**Pull request by SapronovMaxim**

### CODE REVIEW

**Comment by xlenstra** [comment]
Placeholder `[dimensions]` not found in `Russian` for entry `Invalid map: Area ([area]) does not match saved dimensions ([dimensions]).`
If you don't know what this means: https://github.com/yairm210/Unciv/wiki/Translating#pitfalls

**Comment by SapronovMaxim** [comment]
> ```
> Placeholder `[dimensions]` not found in `Russian` for entry `Invalid map: Area ([area]) does not match saved dimensions ([dimensions]).`
> ```
> 
> If you don't know what this means: https://github.com/yairm210/Unciv/wiki/Translating#pitfalls

Sorry, it is just my carelessness. I will be more carefully in the future.

**Comment by xlenstra** [comment]
> > ```
> > Placeholder `[dimensions]` not found in `Russian` for entry `Invalid map: Area ([area]) does not match saved dimensions ([dimensions]).`
> > ```
> > 
> > If you don't know what this means: https://github.com/yairm210/Unciv/wiki/Translating#pitfalls
> 
> Sorry, it is just my carelessness. I will be more carefully in the future.

No worries, you're not the only one. Worst case I'll just leave another message like this :)

**Comment by yairm210** [comment]
merge translations

**Pull request merged**
