### PR TITLE
Lithuanian.properties

### PR DESCRIPTION
**Pull request by teodor24-real**
fixed several errors in the text, added translation of diplomacy and cities of states

### CODE REVIEW

**Comment by teodor24-real** [comment]
Sorry ... what to do next? I don’t understand anything

**Comment by yairm210** [comment]
You can continue to edit your existing file at https://github.com/teodor24-real/Unciv/blob/patch-4/android/assets/jsons/translations/Lithuanian.properties

**Comment by yairm210** [comment]
You can make small changes at a time, and they'll be saved
When the file is full enough for basic gameplay we can add Lithuanian as a language in-game =D

**Comment by teodor24-real** [comment]
Need more translation?

**Comment by teodor24-real** [comment]
Okey

**Comment by teodor24-real** [comment]
Thank you

**Comment by yairm210** [comment]
Once we generate the "real" properties file, you'll see that there will be LOADS more stuff to translate - all unit, tech, and buildings names and descriptions
But that can wait for later ;)

**Comment by teodor24-real** [comment]
I made a full translation.

**Comment by yairm210** [comment]
merge translations

**Pull request merged**
