### PR TITLE
Update template.properties

### PR DESCRIPTION
**Pull request by Smashfanful**
Added new line

### CODE REVIEW

**Comment by SomeTroglodyte** [comment]
You sure upper/lower case is correct?
```kotlin
        if (culturalVictoryEnabled) myVictoryStatusTable.add("Complete 5 policy branches and build\n the Utopia Project to win!".toLabel())
```
`tr()` is case-sensitive, see golden ages. Also, `\n` is special-cased if I remember correctly... Best found out through testing.

**Comment by yairm210** [comment]
No problem with the \n, but yes problem with the uppercase.

**Comment by SomeTroglodyte** [comment]
But the proposal contains `"\ "` not `"\n"` - nevermind.
Idea: Take translation file writer out of core, make parallel component project like tests. Run via "Run/Debug config" like tests. Give it access to sources. Scan for toLabel & co...... 🤪

**Comment by yairm210** [comment]
Ah, now I see... you're right, of course
I thought you meant 'can \n be part of a translation key'

**Pull request closed without merging**
