### PR TITLE
Changed milestone build globally text to make it more understandable

### PR DESCRIPTION
**Pull request by xlenstra**
I could deprecate this, but have no easy way of telling it to modders anyway until I make a wiki page for this file, so I've just changed it directly for now

### CODE REVIEW

**Comment by yairm210** [comment]
I would change to "[building] is built by anyone" personally, but at the very least change "build" to "built"

**Comment by xlenstra** [comment]
I've tried to make it more imperative, to make it similar to all other milestones ('do this', 'complete that', 'build that'), but the weird thing here is that its an imperative to all players. I'd say 'anyone do this' so 'anyone build UN' would then be the closest version. '[building] is built by anyone' is something you'd say when you've completed the milestone, which is not how all other milestones are worded, which is why I chose for the other version.

**Comment by yairm210** [comment]
Ah
I see

**Review by yairm210 — APPROVED** [review]

**Comment by SomeTroglodyte** [comment]
I'd support Yair's sugggestion. That still doesn't sound right. Maybe there are just too few words so we read it out of context and therefore it feels weird... I'd throw "Anyone should build" into the ring.

**Comment by xlenstra** [comment]
image
It becomes a bit wide that way, but I suppose its better.

**Review by SomeTroglodyte — APPROVED** [review]

**Pull request merged**
