### PR TITLE
Scroll panes get scrollfocus automatically

### PR DESCRIPTION
**Pull request by rh-github-2015**
Half-elegant approach to the problem #2357 tackled: "Man-in-the-middle" through import aliases.

This one fells far better in use, and is everywhere where it might be relevant [*]. Trade screen is an obvious example. However, the technical approach might be far more susceptible to side effects my testing didn't catch - #2357 is a kludge but should be harmless aside from sometimes awakening expectations that later are not fulfilled.

Special treatment for mapholders - they now get just an initial setScrollFocus (which V1 omitted), here less an issue as the other ScrollThingies do give focus back.

[*]: Even the Minimap though that one no longer actually scrolls? I think?

### CODE REVIEW

**Comment by yairm210** [comment]
This looks OK, but please add a comment on the AutoScrollPane describing the problem and solution

**Comment by rh-github-2015** [comment]
OK, while considering I also renamed the parameters back to really make it a drop-in in all cases.

**Comment by JackRainy** [comment]
FYI: This PR causes the game crashes!

Steps to reproduce:
1. Start a new game.
2. Try to choose a civilization you want to start playing.
Boom! 💥 

> Caused by: java.lang.IllegalStateException: stage must not be null
	at com.unciv.ui.utils.AutoScrollPane$1.exit(AutoScrollPane.kt:47)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:72)
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:188)

**Comment by rh-github-2015** [comment]
> > Caused by: java.lang.IllegalStateException: stage must not be null

Thanks. Effects of stage being null are not new to me, however in this case I assumed events dependent on actual user behaviour cannot fire unless the actor is on a stage... And hey - that's the exit event! How can that even happen before a matching enter? Smells like framework inconsistency. Will try to repro first to understand better, but a simple null guard is probably the only thing we can do.

**Pull request merged**
