### PR TITLE
Creating Turkish translation

### PR DESCRIPTION
**Pull request by yucel**

### CODE REVIEW

**Comment by yucel** [comment]
Will try to update everyday

**Comment by yairm210** [comment]
Cool =)
I think I'll wait until it fills up a bit before merging this, we don't want players to get to the language screen and see "Oh, Turkish at 0%, why is this here" =)

**Comment by zarum2** [comment]
Hey I can do it to :) . If you let me I Can completely done it in a few days

**Comment by yairm210** [comment]
Someone else sunbird a full translation, so closing this :)

**Pull request closed without merging**
