### PR TITLE
Fixed more broken uniques, e.g. polynesian and ethopian national abilities

### PR DESCRIPTION
**Pull request by xlenstra**

### CODE REVIEW

**Comment by Kleznam** [comment]
Yup good job xlenstra but still Naya's great prophet s from the long count don't work

**Comment by xlenstra** [comment]
> Yup good job xlenstra but still Naya's great prophet s from the long count don't work

Did you choose it after there were already `amount of players / 2 + 1` religions in the game? If so, no bug. Otherwise, please post this on discord or open another issue.

**Comment by Kleznam** [comment]
Ahh there only was another religion tho

**Comment by yairm210** [comment]
This is a much more common use case than I expected

**Comment by yairm210** [comment]
Also, unit.getMatchingUniques can provide its own conditional state, so you don't need to set it anywhere else

**Comment by yairm210** [comment]
But only for uniqueType ;)

**Comment by Kleznam** [comment]
I apologize Maya's seem to work with prophets

**Pull request closed without merging**
