### PR TITLE
Change the icons from some units/buildings

### PR DESCRIPTION
**Pull request by SeventhM**
Note: I don't have any of the attribution for any of these. These icons have been in Rekmod since before I started editing it. Maybe ask @ravignir on that one

### CODE REVIEW

**Comment by yairm210** [comment]
These are definitely better images, but regarding attribution - I agree that it's a required parameter.
Would gladly merge any images with attribution, I'm pretty sure we're at 100% attribution and don't want to introduce broken windows

**Comment by SeventhM** [comment]
Doing some digging, I may remove some of those unit icons from this pr. Many of them seem directly or indirectly ripped from civ 5 itself (the only one I can't confirm is the Mehal Sefari)

Still working on finding the buildings. Most of not all of these images apparently comes from https://github.com/k4zoo/Civ5ExpansionMod which seems to have been tracing over civ 5 for some stuff

**Comment by SeventhM** [comment]
> having un-attributed art

Technically, the Heroic Epic is unattributed right now. It too is from the Civ5ExpansionMod, which means like the Grand Temple in this PR, it's a Civ 5 image traced over by Red11 aka k4zoo

**Comment by SeventhM** [comment]
Reverse Image searching the remaining stuff that I know isn't traced over, before I fix this PR
Ceilidh Hall: [cottage](https://thenounproject.com/icon/cottage-16478/) by Ole Sturm
Hydro Plant: Can't find it. It's annoyingly seemingly everywhere, from place claiming it's public domain to Shutterstock claiming it's from IconBunny. IconBunny won't load for whatever reason. Not sure on if this image is allowed
Water Mill: [WaterMill](https://thenounproject.com/icon/watermill-4255/) by Jakub Ukrop
Mehal Sefari: Can't find at all. It's similar to Civ 5's, but suprisingly not a trace. Unconfirmable, but I'm willing to believe Red11/k4zoo made this one.

**Comment by SeventhM** [comment]
> Wow, how did you find/know?

I searched through their message history on discord. They mentioned tracing over Civ 5 back in 2021

**Comment by SeventhM** [comment]
I'll probably look for a replacement missonary and marine later

**Comment by SeventhM** [comment]
> ut that Missionary one is just fine?

You mean k4zoo's or Unciv's. K4zoo's is directly (or traced over) civ 5s. The Unciv one can be hard to see at times

**Comment by SeventhM** [comment]
I'm not sure where k4zoo's trace of civ 5's Grand Temple fits here. This one might be significantly more legit to add than the other traces since it's not a one-to-one copy. So I'm currently searching through images just in case. On an unrelated note there's so many "taj mahal"s that you'd think every large temple was just it. To the point where some of them might as well be Hagia Sophia or whatever...

Thanks to using reverse image search to confuse search engines into searching the noun project, I'm currently looking at either [Sultan Ahmed Mosque](https://thenounproject.com/icon/sultan-ahmed-mosque-3017382/) or [indain mausoleum](https://thenounproject.com/icon/indain-mausoleum-4443767/)

For marines, I'm currently looking at this [rifle](https://thenounproject.com/icon/rifle-147944/). Too bad there's no real distinction to the icons, they're all generic guns. Even Civ 5's icon is just generic gun with strap

**Comment by yairm210** [comment]
BTW we can definitely do this piecemeal, we don't need to wait for 100% completion, add whatever images you want that have attribution and we can continue this discussion later regarding the rest :)

**Comment by SeventhM** [comment]
Tbh, I probably haven't made myself super clear here:
I probably could add in the image for marines and switch this to ready right now. I'm mostly waiting on confirmation if k4zoo's Grand Temple is or isn't allowed


Beyond that, I could probably look for images for other stuff later when I get the time under another PR

**Pull request closed without merging**
