### PR TITLE
changed default tiles colors

### PR DESCRIPTION
**Pull request by ravignir**
I hope the new colors are better - maybe poll this on discord :)
test

### CODE REVIEW

**Comment by krushia** [comment]
I like this a lot, but maybe a bit more contrast between ocean and coast.

**Comment by yairm210** [comment]
The colors are much nicer!
I agree that the oceans need to be darker though

**Comment by ravignir** [comment]
z
how about that?

**Comment by krushia** [comment]
Only problem is the white selection circle thingy is now impossible to see on snow. I wonder if that was the reason for the ugly cyan choice before.

**Comment by ravignir** [comment]
Snow is not completely white, it has a slight blue tint to it. 
snow

**Comment by krushia** [comment]
Okay I can see it. Perfect!

**Pull request merged**
