### PR TITLE
Turkish translations

### PR DESCRIPTION
**Pull request by logicminimal**
need to fix civilizaton phrase on line 821
edit: done

### CODE REVIEW

**Comment by logicminimal** [comment]
what did i do wrong?

**Comment by logicminimal** [comment]
help

**Comment by xlenstra** [comment]
Placeholder `[param]` not found in `Turkish` for entry `[param] Units adjacent to this city heal [amount] HP per turn when healing`

**Comment by logicminimal** [comment]
> Placeholder `[param]` not found in `Turkish` for entry `[param] Units adjacent to this city heal [amount] HP per turn when healing`

thanks, how do you get those information?

**Comment by logicminimal** [comment]
how do i fix the conflicts?

**Comment by logicminimal** [comment]
god...... what's the problem now

**Comment by xlenstra** [comment]
Placeholder `[amount]` not found in `Turkish` for entry `Turns until the next
    diplomacy victory vote: [amount]`

**Comment by xlenstra** [comment]
Somewhere it says 'all checks have failed', and close to that there is a button 'details'. Clicking on that and searching a bit will often yield the exact errors for what went wrong

**Pull request merged**
