### PR TITLE
Added Shrine, option for enabling religion

### PR DESCRIPTION
**Pull request by xlenstra**
This is the first of many PR's which will eventually include all of the religion mechanic: See #4290 . This PR adds two things: a button that enables a button in the new game screen to enable religion (mostly for myself so I can more easily test things), and the shrine, a building for generating faith.

### CODE REVIEW

**Comment by yairm210** [comment]
The game options look good!
The shrine should be hidden (both in tech buttons and as buildable in cities) for non-religion games though. You could either do this by catching every building that provides faith, or by adding a special unique - I think the first is probably better but I'm not sure.

**Comment by xlenstra** [comment]
Good point, I'll look into it

**Comment by xlenstra** [comment]
Shrine should now be hidden, both in the tech and buildings, but is still visible in the civilopedia

**Comment by logicminimal** [comment]
btw the game freezes when i select found pantheon, 3.15.6

**Comment by xlenstra** [comment]
> btw the game freezes when i select found pantheon, 3.15.6

Known bug, fixed in 3.15.7

**Pull request merged**
