### PR TITLE
Update Nations.json

### PR DESCRIPTION
**Pull request by Smashfanful**
Added Starting Bias, Ability names and Adjectives.

### CODE REVIEW

**Comment by yairm210** [comment]
Build fails?

**Comment by Smashfanful** [comment]
It seems so... I don't understand where's the problem...

**Comment by yairm210** [comment]
Try merging the most recent commit in the main repo

**Comment by Smashfanful** [comment]
How?

**Comment by yairm210** [comment]
image


Just like you can create a pull request to merge your branch into mine, you can create one to merge mine into yours

**Comment by Smashfanful** [comment]
And how exactly do I do it?

**Comment by Smashfanful** [comment]
I think it's correct now. Look it by yourself and tell me if that is good.

**Pull request merged**
