### PR TITLE
Update Romanian.properties

### PR DESCRIPTION
**Pull request by alexban011**

### CODE REVIEW

**Comment by alexban011** [comment]
> master 

god dammit!

**Comment by SomeTroglodyte** [comment]
> god dammit

Yup, it's His fault. :rofl:

Hope you can get your master back in sync. My method if I accidentally push stuff to master not in upstream master - is - delete master and start over. May not be the easiest route.

**Comment by alexban011** [comment]
> Hope you can get your master back in sync. My method if I accidentally push stuff to master not in upstream master - is - delete master and start over. May not be the easiest route.

I got it fixed with
git reset --hard HEAD~2 (I had 2 commits)
git push -f origin master

**Comment by SomeTroglodyte** [comment]
Ah yes much easier. I never do force-pushes... 

>  if you didn't push already

... then there is no problem at all

**Pull request closed without merging**
