### PR TITLE
Block repairs in Hostile Tiles

### PR DESCRIPTION
**Pull request by itanasi**
So you can't spam Repair and Pillage while besieging foreign lands

### CODE REVIEW

**Comment by ravignir** [comment]
but why?

**Comment by ravignir** [comment]
it is a civ5 mechanic.

**Comment by ravignir** [comment]
it is even more effective in civ5.

https://user-images.githubusercontent.com/30041793/215749546-bf6aa0b8-7cef-4ccf-b019-f85a5708ec01.mp4

**Comment by itanasi** [comment]
Eh just saw some folks seeming unhappy with the tactic. Can drop

**Pull request closed without merging**
