### PR TITLE
Turkish Translations

### PR DESCRIPTION
**Pull request by logicminimal**
those translations are for 3.15.16, new lines could be added by then i dont know

### CODE REVIEW

**Comment by logicminimal** [comment]
failed :| could someone tell which part is broken

**Comment by xlenstra** [comment]
Placeholder `[Stat]` not found in `Turkish` for entry `Your [ourUnit] plundered [amount] [Stat] from [theirUnit]`

**Comment by logicminimal** [comment]
> Placeholder `[Stat]` not found in `Turkish` for entry `Your [ourUnit] plundered [amount] [Stat] from [theirUnit]`

yep i used a [stat] as it seems. another capital lowercase mismatch

**Comment by yairm210** [comment]
merge translations

**Comment by yairm210** [comment]
Translations branch created

**Comment by yairm210** [comment]
Translations PR created

**Pull request merged**
