### PR TITLE
City Screen improvements

### PR DESCRIPTION
**Pull request by vegeta1k95**
Improvements for city screen:

1) Now purchasable tiles are visualized by new icon + price text (red if player don't have enough gold)
image
image

2) Now clickhandlers for tile group and "worked" icon are separated. Assigning/removing/locking a citizen to tile is done only by clicking the corresponding icon, not the whole tile. This removes the problem when a player who only wants to look at tile info unintentionally reassigns population.
This includes the new possibility to buy tile by clicking "Buy" icon on it.

3) Changed "worked" status clickng rotation to proper cyclic:
Previous: Worked -> Not-worked -> Locked -> Not-worked -> Locked -> ...
Now: Worked -> Locked -> Not-worked -> Worked -> Locked -> Not-worked -> ...

4) Tile cannot be chosen to be worked if it _currently_ has no yields (desert, mountain).

5) Moddability: icons for CityScreen tiles status: Worked/Locked/Buy/Not-worked/CityCenter are separated into own `TileIcons/...` images. Includes new CityCenter icon.

6) Fixes and refactoring: 
- fixed rare bug, which prevented input after simultaneous zoom+panning
- fixed inconsistend dimming of yields 
- added `CityMapHolder` class (analogous to `WorldMapHolder`) with zoom-pan optimization
- new functions `CityExpansionManager.canBuyTile(tile)` and `Civilization.hasGoldToBuy(price)`

### CODE REVIEW

**Comment by yairm210** [comment]
Where did the buy icon come from? Please add to credits

**Comment by yairm210** [comment]
Make the canBuy function accept any stat, as well
Since we also have faith buy and possibly culture and science

**Comment by yairm210** [comment]
All in all though looks good!

**Comment by vegeta1k95** [comment]
> Make the canBuy function accept any stat, as well
> Since we also have faith buy and possibly culture and science

Not sure, which function you refering to. `CityExpansionManager.canBuyTile(tile)` doesn't consider any stat, it just calculates if tile is located properly to be purchasable.
And `Civilization.hasGoldToBuy(price)` is explicitly a function for gold.

**Comment by yairm210** [comment]
I mean the civilization function
I don't see a reason to not make that general, for any stat
But not a blocker

**Pull request merged**
