### PR TITLE
Civilopedia phase7

### PR DESCRIPTION
**Pull request by SomeTroglodyte**
I originally chose to do all terrain-related categories together, as that was a 4-file diff with only a few 10s of lines. But then I tuned and fixed most of what I saw that wasn't quite perfect, so this got big. Also, there's older PR's that will conflict. Therefore draft, let me do the merge work, otherwise this is stable and polished enough I think.

### Appetizers
<details><summary>Terrain</summary>

image

</details>
<details><summary>Terrain feature</summary>

image
</details>
<details><summary>Resource</summary>

image
</details>
<details><summary>Improvement, translated</summary>

image
</details>

### To-do's
In some cases I left todo's that would improve civilopedia display like:
- Ice would see-also the Submarines if their uniques were [terrainFilter] parameterized
- Fountain of Youth would link Rejuvenation is...
- Sorry for the todo in the Battle.kz nuke routines. The 'pedia looked puzzling so I had to look up in source what those uniques actually do - ahem. I can't imagine a Forest protecting other destructible features on the same tile is correct... 4+ copies of code where 1 would do...

### Translations
- Significant double or trailing blanks were something I could not tolerate, so they're gone from those strings I needed. About half of the existing translations were suffering anyway because the translator missed that extra blank - Spanish, Italian, Dutch, just to name a few. I fixed all translations so they don't get lost.
- Trailing colon - No worse than before, maybe not uniformly solved, might revisit later.

@Mape6:
<details><summary>Roh-Notizen von den Tests teils unbearbeitet:</summary>

```
"Moor trockenlegen / Sumpf" ?
"Fabrik / Fabrik / Manufaktur" ?
"nicht frisches Wasser / ohne..."?
+ "Fügt angrgenzenden"
"Mine -> Bergwerk"?
"Eisenbahn / Schienen entfernen" / "Bahnlinie" in Zukunft?
"Verseucht / Verseuchung / Fallout"?
```
... nur so zum Vormerken und/oder Ignorieren
</details>

### Roadmap
- Nations, Tech, Promotions - code already stashed
- Check TranslationFileWriter for ability to write Beliefs and CivilopediaText
- Leverage ability to link _to_ Tutorials (or Difficulties, though I guess none needed to those)
- **Question**: I think allowing the Barbarians a Nation entry would look nicer - there's at least one link somewhere already that tries and fails to show them - if so, implement and tune that
- Repackage Tutorials into actual CivilopediaText json, beautify a little, and start linking _from_ them where appropriate

### CODE REVIEW

**Comment by logicminimal** [comment]
Cool PR but why are there huge spaces on between resource icons and their text?

**Comment by yairm210** [comment]
I find myself disliking the civilopedia texts.
They feel like autolinking and uniques that we haven't yet gotten around to making user-visible, so we're 'patching' this by adding textual descriptions.

**Comment by yairm210** [comment]
Imho they should only be flavour texts.
Which then bends the question, why not description:string.

**Comment by Mape6** [comment]
@SomeTroglodyte 
`"Moor trockenlegen / Sumpf" ?`
Defintiv Sumpf
`"Fabrik / Fabrik / Manufaktur" ?`
Da es eher etwas später im Spiel vorkommt, zumindest bei mir, bin ich für Fabrik.
`"nicht frisches Wasser / ohne..."?`
"ohne" ist besser
`+ "Fügt angrgenzenden"`
Siehe Commit
`"Mine -> Bergwerk"?`
Bergwerk ist ein sehr guter Vorschlag
`"Eisenbahn / Schienen entfernen" / "Bahnlinie" in Zukunft?`
Finde weiterhin Eisenbahn am passendsten. Für eine Bahnlinie bräuchten wir noch Bahnhöfe, einen Fahrplan und natürlich einen Schaffner.
`"Verseucht / Verseuchung / Fallout"?`
Nur "Verseucht" ist nicht ganz selbsterklärend. Habe nun "Radioaktiv verseucht" draus gemacht.

Siehe [Commit](https://github.com/yairm210/Unciv/pull/4644/commits/babe2f80571d4781fd96e87541f95e2758eba795)

**Comment by SomeTroglodyte** [comment]
@Mape6
Ich muß doch ein klein wenig besser erklären in Zukunft.
+ Heißt erledigt. Hier drin. Macht nix.
Fabrik fiel auf weil Gebäude und Feld"verbesserung" gleich heißen, unterschiedlich fände ich besser, mal nachdenken ob Manufaktur auch geeignet
Schaffner ist gut. Nein ich fand im Kontext auf dem Bildschirm klingt Schienen leicht holprig, daher Denkanstoß.
Und Fallout - kennt das nicht eh jeder als Fallout... Mal schaun wie gut das lange da hin paßt.

Moment...  "hat [amount] [Stat] von [theirUnit] Einheit geplündert" - Opfer ist oft eine Stadt, und das klingt dann doof. 

Einfach geistig "mitnehmen", Antwort nicht nötig.

**Comment by SomeTroglodyte** [comment]
> They feel like autolinking and uniques that we haven't yet gotten around to making user-visible, so we're 'patching' this by adding textual descriptions.

Precisely. They were partially inspired by the little stories the original games have for each entry, but they can serve as interim tool to explain something better. And why not? There's two prime examples in here - I had to restrain myself to not code the lookups, branch was getting big anyway. And since in vanilla these would be single-hit routines, this is actually more efficient, just a little less mod-friendly.

> why not description:string

Uniform data when rendering - and uniformity is important for an optimization I still have in the back of my head regarding texture switches. Having two collections over distinct types at that point? Needless complication?

Also, FormattedLine as simple wrapper when no other formatting is used - for such a typical flavour story - would be well under 20% overhead bytes-wise. And when a "story" we might want can look nicer with headers - the option costs little.

**Pull request merged**
