### PR TITLE
Fix incorrect Archer obsolete

### PR DESCRIPTION
**Pull request by AdityaMH**

### CODE REVIEW

**Comment by yairm210** [comment]
Where is this info from? Are you sure this is g&k behavior and not bnw?

**Comment by AdityaMH** [comment]
https://www.civfanatics.com/civ5/info/units/

Also look bowman or slinger

**Comment by AdityaMH** [comment]
Uh, sorry...
wrong visit folder.

**Comment by AdityaMH** [comment]
> Where is this info from? Are you sure this is g&k behavior and not bnw?

Thanks, for noticing this...

**Comment by AdityaMH** [comment]
Bruh, another typo.
Must "for G&K" not "forK"

**Review by xlenstra — APPROVED** [review]

**Comment by xlenstra** [comment]
Checked this in the in-game civilopedia, which agrees with these changes.

**Pull request merged**
