### PR TITLE
Update Romanian.properties

### PR DESCRIPTION
**Pull request by Mtroga**
I changed the missing lines. I hope all it's ok.

### CODE REVIEW

**Comment by yairm210** [comment]
It looks like you're removing a lot of progress?

**Comment by Mtroga** [comment]
I'm not removed anything, just add translation for tutorial part. I don't know what happened, i will correct that.

**Comment by yairm210** [comment]
You have conflicts
@hmlendea You guys should talk since you're both working on the same file and causing conflicts with each other

**Comment by yairm210** [comment]
You know this is still conflicting, right?

**Pull request closed without merging**
