### PR TITLE
did some Turkish translations

### PR DESCRIPTION
**Pull request by logicminimal**
give me translator role pls

### CODE REVIEW

**Review by logicminimal — COMMENTED** [review]
i am going to change iyileştirmeleri with geliştirmeleri in my next translation, they are basically the same thing but in order not use different words for the same thing

**Review by logicminimal — COMMENTED** [review]
Also about 1409, i worded that wrongly yairm i would be happy if you changed sonsuz yunan kültürü to büyük yunan kültürü

**Comment by yairm210** [comment]
You got it :)

**Comment by yairm210** [comment]
merge translations

**Comment by yairm210** [comment]
Translations branch created

**Comment by yairm210** [comment]
Translations PR created

**Pull request merged**
