### PR TITLE
update Belarusian translation

### PR DESCRIPTION
**Pull request by twinflac**

### CODE REVIEW

**Comment by twinflac** [comment]
what happend with docker build?

**Comment by twinflac** [comment]
Screenshot_20240128-145749_Trebuchet

**Comment by yairm210** [comment]
I'm working on that, don't with about it

**Comment by twinflac** [comment]
> I'm working on that, don't with about it
thx, for all your work for this game and this translation

**Comment by twinflac** [comment]
Screenshot_20240128-165643_Fennec

**Pull request merged**
