### PR TITLE
Update Malay.properties

### PR DESCRIPTION
**Pull request by kyliow**
As indicated in the title. The current translation is poor and severely incomplete, will add more in the future.

### CODE REVIEW

**Comment by xlenstra** [comment]
Placeholder `[ourUnit]` not found in `Malay` for entry `An enemy [unit] has destroyed our [ourUnit]`
    Placeholder `[ourUnit]` not found in `Malay` for entry `Enemy city [cityName] has destroyed our [ourUnit]`
    Placeholder `[defender]` not found in `Malay` for entry `[defender] withdrew from a [attacker]`

**Comment by kyliow** [comment]
Hi @xlenstra, these lines seem fine to me though. I don't understand why the checks failed. The tags are clearly not missing.

```
An enemy [unit] has destroyed our [ourUnit] = Sebuah [unit] musuh telah memusnahkan [outUnit] kami
...
Enemy city [cityName] has destroyed our [ourUnit] = Bandar musuh [cityName] telah memusnahkan [outUnit] kami
...
[defender] withdrew from a [attacker] = [Defender] menarik diri daripada [attacker]
```

**Comment by xlenstra** [comment]
> Hi @xlenstra, these lines seem fine to me though. I don't understand why the checks failed. The tags are clearly not missing.
> 
> ```
> An enemy [unit] has destroyed our [ourUnit] = Sebuah [unit] musuh telah memusnahkan [outUnit] kami
> ...
> Enemy city [cityName] has destroyed our [ourUnit] = Bandar musuh [cityName] telah memusnahkan [outUnit] kami
> ...
> [defender] withdrew from a [attacker] = [Defender] menarik diri daripada [attacker]
> ```

The tags appear to be there, but there do seem to be slight misspellings in them. `ourUnit` is misspelled as `outUnit` twice, and `defender` is capitalized in the translation. For the tags to be found, they need to be spelled exactly the same

**Comment by xlenstra** [comment]
Placeholder `[param]` not found in `Malay` for entry `Granted by [param]`

**Pull request merged**
