### PR TITLE
Raze Special Cities

### PR DESCRIPTION
**Pull request by FiretronP75**
Add new ModOptions uniques: Allow raze capital, Allow raze holy city.

### CODE REVIEW

**Comment by yairm210** [comment]
A. Again the 'raze capital' interferes with a victory condition
B. Please use 'if/else's to return false on certain conditions - one big boolean function at the end is much harder to read

**Comment by FiretronP75** [comment]
A - There are already two other things that do this. Do they block the domination victory? Battle.kt 542 (`true` overrides)
```
        if (attackerCiv.isBarbarian() || attackerCiv.isOneCityChallenger()) {
            city.destroyCity(true)
            return
        }

```

**Comment by FiretronP75** [comment]
B - Done!

**Comment by yairm210** [comment]
Now that I think about it we can just check all existing cities that "were original coty" and be done with it
Like, don't go foreach civ, but instead foreach city in all civs

**Comment by FiretronP75** [comment]
Oh you mean just don't worry about the destroyed ones and just keep tracking the still alive capitals as usual? So no further code changes needed?

**Comment by FiretronP75** [comment]
I'm not sure I understand. Happy to do it with further detail.

**Comment by yairm210** [comment]
You know what since this is an "opt in with mod" feature I'm fine with it being in even if I'm not 100% sure of it

**Pull request merged**
