### PR TITLE
Translations refactoring

### LINKED ISSUE #2046: When we build a city named with Chinese character, if we change the language with English, the name of the city will disappear.
for example, we have a city named "北京" in Chinese，then we change the game language with English, the name "北京" will disappear.

### PR DESCRIPTION
**Pull request by JackRainy**
The idea is to get rid of `Nations_SomeLanguage.json` files and do translations from `SomeLanguage.properties` files.
The `SomeLanguage.properties` are generated based on `template.properties` which is extended by strings from the original `Nations.json`.
Also, I have renamed `translationsByLanguage` folder into `translations` folder, that's obvious that translations are always by languages :)
I assume this PR resolves #2046 as well.

### CODE REVIEW

**Comment by r3versi** [comment]
Oh man.. I started working on this too.. :face_with_head_bandage: 

- `TranslationFileReader.generateNationsStrings()` cleanup?
- I think you should also get rid of `Nation.getTranslatedName` and `Nation.translatedName`. 
- You updated every translation files but the master `template.properties`. Also I think the removal of `Very well.` and `Excellent.` is unintended?

good job! :+1:

**Comment by JackRainy** [comment]
> Oh man.. I started working on this too.. 

Ahh, sorry... I have already asked @yairm210 to give the ability of assigning the issue on ourselves while working on it in order to avoid such situations.

> TranslationFileReader.generateNationsStrings() cleanup?

If you mean `var allTranslations = TranslationFileReader().generateNationsStrings().size` line, it is necessary to include the correct number of lines for the percentage calculations.

> I think you should also get rid of Nation.getTranslatedName and Nation.translatedName

Good idea, will work on that.

> You updated every translation files but the master template.properties

The master `template.properties` has been also cleaned up. If you are asking where are the cities, nations, etc. there - they are appending to the template during generation of `TheLanguages.properties` in runtime. No need to store those strings twice (in template and in Nations.json), while `Nations.json` is still needed to define supported civilizations.

> the removal of Very well. and Excellent. is unintended?

No, it is intended removal, since they are already present and translated in the `Nations.json` - no need to have it within `template.properties` twice.

**Comment by JackRainy** [comment]
Also, I have noticed that since 6dc471850eafe13dfcfa537c628a8e72f2b469a8 (half a year ago!) the nation's replies like `neutralLetsHearIt, neutralYes, neutralNo, hateLetsHearIt, hateYes, hateNo, afterPeace` are not used anywhere anymore. Was their usage removed by mistake and we still need to keep them? Or that was intentional and we can remove them from translations?

**Comment by yairm210** [comment]
The replies were used in negotiation. Since negotiation is now asynchronous in order to accommodate multiplayer games, we can probably get rid of them

**Comment by JackRainy** [comment]
>  the removal of Very well. and Excellent. is unintended?
Since the unused greetings have been removed from `Nations.json`, I have returned "Very well", "Sorry" and "Excellent" back.

**Comment by JackRainy** [comment]
@yairm210 , @r3versi , do you expect some more changes from me, or the PR is good and just waiting for the next release?
I have a pack of further changes based on these ones and I am not sure whether it's better to put them here or just wait for merging this and then create new PR.

**Comment by yairm210** [comment]
I'm not 100% sure about this, but you know what, let's do this
RERO-style, if it's not good, let's fail this faster

**Comment by yairm210** [comment]
I'm reminding y'all that currently the game is not completely playable in other languages because the stuff that used to be in the nations files now no longer exists anywhere
Because of the Google Play thing, the release of 3.6.6 still hasn't started rolling out, which gives us some time to add the leader responses etc. and the city names to the template translation file

**Comment by yairm210** [comment]
Sorry, my mistake, only now do I see what you did with the translations, it's all good =)

**Pull request merged**
