### PR TITLE
Update Simplified_Chinese.properties

### PR DESCRIPTION
**Pull request by AutumnPizazz**
Add new content, especially the spy part, correct some minor errors to make it more suitable for native Chinese speakers, and delete redundant spaces

### CODE REVIEW

**Comment by AutumnPizazz** [comment]
What is wrong? I cannot find any error?

**Comment by yairm210** [comment]
Placeholder `[isOrAre]` not found in `Simplified_Chinese` for entry `[civName] is able to provide [unitName] once [techName] [isOrAre] researched.`

**Comment by AutumnPizazz** [comment]
Oh, 'is' or 'are' are never distinguished in Chinese, which could be translated as '是‘ or even omit.
So the translation of this sentence has something strange for Chinese Charactor.

**Comment by AutumnPizazz** [comment]
Now I add a "Redundant Component" to include the isOrAre. It may be okay this time.

**Pull request merged**
