### PR TITLE
Added most translation for malay

### PR DESCRIPTION
**Pull request by fab144**

### CODE REVIEW

**Comment by yairm210** [comment]
Conflicts :)

**Comment by fab144** [comment]
Oh what kind of conflicts?

**Comment by yairm210** [comment]
Same as in other commit, conflicts with other changes people have made

**Comment by yairm210** [comment]
We've changed the way the translation files are handled for a future with less conflicts and less failing builds!
Instructions at https://github.com/yairm210/Unciv/wiki/Translating =D

**Pull request closed without merging**
