### PR TITLE
Missing single quotation mark in quote

### PR DESCRIPTION
**Pull request by Mape6**
Inserted ' in quote of Advanced Ballistics

### CODE REVIEW

**Comment by SomeTroglodyte** [comment]
I would have propagated the change to all translations where a translation exists - after all, the words stay valid, and otherwise the json - to - tr generator would just throw them out, or am I mistaken?

**Comment by Mape6** [comment]
> 
> 
> I would have propagated the change to all translations where a translation exists - after all, the words stay valid, and otherwise the json - to - tr generator would just throw them out, or am I mistaken?

Good question. I tried to figure out how the TranslationFileWriter works in detail but my programming knowledge is not good enough to understand everything. That's why I'm not really sure what happens. But I agree with your suggestion and will change all languages files.

**Comment by SomeTroglodyte** [comment]
:+1: I know that's tedious, especially with needing to ensure some 'intelligent' editor does not change the number of leading or trailing spaces...

**Comment by Mape6** [comment]
The translation file of Thai is completely strange. The quote is missing here.
In the files for Turkish and Vietnamese the tech "Advanced Ballistics" was also missing. I added that.

Probably someone should check all translation files and compare them to each other to find and correct the strings and formats.

**Comment by SomeTroglodyte** [comment]
Isn't thai somehow deactivated? Turkish may lag a little due to its translator renaming it away a while ago.
```kotlin
    // This function is too strange for me, however, let's keep it "as is" for now. - JackRainy
    private fun getLanguagesWithTranslationFile(): List<String> {
(...)
        languages.remove("Thai") // Until we figure out what to do with it
        languages.remove("Vietnamese") // Until we figure out what to do with it
```

**Comment by Mape6** [comment]
Got to know that. Thanks for that hint. I don't need to care about both languages then.

**Pull request merged**
