### PR TITLE
some more German translation

### PR DESCRIPTION
**Pull request by Coruna**

### CODE REVIEW

**Comment by Coruna** [comment]
ugh, maybe I did something wrong. There are way more commits than I wanted to (just tried to keep my fork up-to-date). Hopefully you can use it anyway :)

**Comment by yairm210** [comment]
Sorry, I have no idea what happened here, and my normal methods of gitfixing don't seem to work 0_0

**Comment by yairm210** [comment]
It looks like... you made a copy-commit of my recent commits? But then why is it considered different files in the Diff? 😕

**Comment by yairm210** [comment]
I think I'll just close this...I'm not sure I can get anything helpful from this =(

**Comment by Coruna** [comment]
ok, I'll try to fix it on my side and make a new pull request

**Pull request closed without merging**
