### PR TITLE
Converted stat list to stat tree

### PR DESCRIPTION
**Pull request by yairm210**
current changes do not affect UI at all, since we're still going by the shallow mapping that existed beforehand

The problem:
image

I have no way of knowing which policies, techs, and wonders are contributing to my stat production.
Solution: Turn all lists of stats into trees of stats! This will also help us in the overview screen to dig deeper.

### CODE REVIEW

**Comment by yairm210** [comment]
image

Bless my autism
I don't think there's a good reason to break down the tile stats and specialists, since the city screen gives you a plain view of both of these from the get-go

**Comment by yairm210** [comment]
We can do the exact same with the percentages, but let's do this one step at a time... this PR itself could already have been split into 2 PRs, one for each of the commits 😅

**Comment by xlenstra** [comment]
I'm a bit worried about clutter, especially if this same thing is planned for the bonuses stat list...
image

**Comment by yairm210** [comment]
Hrm you're right, that's a lot to take in, but then again - if someone is in the stat drilldown tab I assume they'd prefer the option to really drill down.
Maybe a toggle?

**Comment by xlenstra** [comment]
> Hrm you're right, that's a lot to take in, but then again - if someone is in the stat drilldown tab I assume they'd prefer the option to really drill down. Maybe a toggle?

Most user intuitive would probably be a toggle for each category, similar to an expander tab but for just 'buildings' or 'policies' instead of for the entirety of culture. That's probably a lot of work to implement, so a global toggle might also suffice

Additionally, in your screenshot of the second number the values don't seem to add up? 7 + 11 + 5 + 3 = 26, not 38, while 7 + 11 + 2 + 3 + 2 + 3 + 5 + 5 = 38, but that double counts all the new shown values.

**Comment by yairm210** [comment]
expanding_drilldown

**Comment by will-ca** [comment]
Could there be a visual indicator for the toggle? Triangle icon next to the header, maybe? I think I would be a bit confused by the changes in layout until/unless I figured it out.

**Comment by yairm210** [comment]
How would you indicate this? A triangle to me indicates 'up' and 'down', not 'expand' and 
'contract', and leaves me more confused than I started.

**Comment by will-ca** [comment]
ExpanderTab already uses a right-pointing triangle to indicate "Closed", and a down-pointing triangle to indicate "Opened".

I think "+"/"-" or OtherIcons/New and OtherIcons/Close might work too.

**Comment by yairm210** [comment]
expanding_drilldown_with_button

**Comment by SomeTroglodyte** [comment]
I don't think there's anything to prevent _nesting_ ExpanderTab's?? Making the inner one visually smaller should also be mostly prepared for.

**Review by xlenstra — APPROVED** [review]

**Comment by yairm210** [comment]
@SomeTroglodyte That won't keep the tidy organization of the inner table though. And I'm not overly fond of the way buildings currently expand, and that's nested expandertabs, so...

**Pull request merged**
