### PR TITLE
Enabled various G&K buildings and units

### PR DESCRIPTION
**Pull request by avdstaaij**
The jsons contain various buildings and units for G&K that are commented out. Since we are now targeting G&K (as stated in #663), it seems to be time time to enable them. This PR enables (and if necessary, adds icons for) all buildings and units that should work as-is, which are:

Buildings:
- Arsenal
- Military Base
- Petra

Units:
- Composite Bowman
- Mobile SAM
- Jet Fighter

Additionally, machine guns now upgrade to Mechanized Infantry (as in G&K), and all "Will be added in G&K" comments have been removed from the jsons.

### CODE REVIEW

**Comment by avdstaaij** [comment]
This also fixes #4078.

**Comment by ravignir** [comment]
What about missing vanilla units/buildings?:
Stealth Bomber
Giant Death Robot
Atomic Bomb
Missile Cruiser
Nuclear Submarine
Hydro Plant

And other G&K units/buildings?
Great Admiral
Privateer
Recycling Center
Bomb Shelter
CN Tower

**Comment by SomeTroglodyte** [comment]
Looks like thorough work :+1:. And rav - little steps. I want Boudicca! No I don't - we got no nation theme music...

**Comment by avdstaaij** [comment]
> What about missing vanilla units/buildings?:
> (,,,)
> And other G&K units/buildings?

This is just for the buildings and units that are already present in the jsons, but commented out, and which will function with only minor changes (hence I refer to it as _enabling_ them). The others are either not already in the jsons or need something else, like a technology, to be added. No need to do everything at once!

**Comment by logicminimal** [comment]
holy shit great work man

**Pull request merged**
