### PR TITLE
Allow removing Fallout from the city tiles

### PR DESCRIPTION
**Pull request by JackRainy**
I have faced the issue that the Fallout is the only "improvement" that can be "built" in the city but then there is no way to remove it. This PR fixes this problem.

P.S> During creation of the PR, I decide to look through the issues and found that #6355 was not fixed but just closed without proper testing. Now it is fixed-fixed.

### CODE REVIEW

**Comment by yairm210** [comment]
??? Fallout shouldn't spawn in city tiles at all.

**Comment by JackRainy** [comment]
They are not spawn themselves but after nuking the city, of course, they appear there.

**Comment by yairm210** [comment]
Yes
The city center improvement should prevent fallout from spawning

**Comment by xlenstra** [comment]
As far as I'm aware, as city centers have the 'indestructible' unique, it should be impossible for fallout on them. Were your tests done with mods that don't have this unique?

**Comment by SomeTroglodyte** [comment]
But UniqueType.Indestructible doesn't work, as can readily be seen from code inspection: All uses are in `doNukeExplosionForTile` and the gating of "Fallout ~~New Vegas~~" is attempted via `tile.hasUnique()` which looks in `getAllTerrains()` - not in improvement.

**Comment by JackRainy** [comment]
@xlenstra , I have used none of mods. It reproduces quite easily - just 1-2 nuclear missiles on the city.
Will revert the changes while doing the fix on another end of the problem :)

**Comment by SomeTroglodyte** [comment]
> It reproduces quite easily

See my comment just above yours

**Comment by JackRainy** [comment]
Closing this, since the problem I was fixing, was not relevant.
The solution comes from the another side - #6640

**Comment by SomeTroglodyte** [comment]
But thanks for stirring the pot!

**Pull request closed without merging**
