### PR TITLE
Make naval tradition provide a general instead of an admiral for now

### PR DESCRIPTION
**Pull request by logicminimal**
i didnt change the +2 movement for admirals to generals as it would make generals pretty op

### CODE REVIEW

**Comment by logicminimal** [comment]
@yairm you can just close this if you dont want this

**Comment by yairm210** [comment]
I'm not sure.
I think this is fine.

**Comment by yairm** [comment]
How did I get CC'd on this :)?

I think you tried to reach yair morgenstern, according to the quoted mail
below..

Regards,

**Comment by logicminimal** [comment]
i couldn't think that there could be someone nicknamed yairm sorry for the ping

**Pull request merged**
