### PR TITLE
update Chinese translation，Russian translation Lost a word ("), please update it immediately！

### PR DESCRIPTION
**Pull request by lishaoxia1985**

### CODE REVIEW

**Comment by yairm210** [comment]
Targeting 2 and 3 shouldn't have the word air
Also, changes in the base json files could have unwanted side effects when loading games so be careful

**Comment by yairm210** [comment]
All the "bonus vs" should not be translated separately, there's a single "bonus vs [type] that deals with them all, please remove

**Comment by yairm210** [comment]
Pretty sure the '6 tiles in every direction' also already exists somewhere else

**Comment by lishaoxia1985** [comment]
1.when i update this translation, i have found that you said about "bonus vs armor/city/mounted" , but the "bonus vs [type] " is only used in start new game screen about unique unit,  and not used in Civilopedia,
so i translate it to make sure the wiki can be showed in chinese. if "bonus vs [type] " be used in all place, i will delete it, but now it's not the fact.
i know battle calculating in game don't use the word such as "bonus vs armor/city/mounted".
2.about "Targeting 2 and 3 shouldn't have the word air", i'm very sorry.
3.'6 tiles in every direction' don't exist somewhere, before i translate it, i have search it in all files.

**Comment by yairm210** [comment]
I added the translation in the Civilopedia, like you said =)

**Comment by yairm210** [comment]
So now remove all the extra "Bonus vs" translations please

**Comment by lishaoxia1985** [comment]
now it's very good.

**Comment by yairm210** [comment]
I'm committing this, but you should know that .toLabel() automatically runs .tr() on the string, so .tr().toLabel() is a redundancy

**Comment by lishaoxia1985** [comment]
sorry, but some times it can't run .tr(), i have tested it. tomorrow i will test again.

**Pull request merged**
