### PR TITLE
Defeat improvements

### PR DESCRIPTION
**Pull request by lyrjie**
* Fixed the issue when disbanding the initial settler: missing `civInfo.destroy()` call
* Added the fog of war update on mapUnit destroy

### CODE REVIEW

**Comment by lyrjie** [comment]
I also wanted to add map reveal when the player is defeated in singleplayer but couldn't come up with a coherent way to implement it

**Comment by r3versi** [comment]
How about something like this?
```
if (viewingCiv.isDefeated()) {
    viewingCiv.exploredTiles.addAll(gameInfo.tileMap.values.map{ it.position })
    viewingCiv.viewableTiles = gameInfo.tileMap.values.toSet()
}
```

**Comment by lyrjie** [comment]
The problem is that `viewableTiles` get refreshed on every turn, so on the next turn after the defeat everything is covered in FoW
I tried putting it into `CivInfoTransientUpdater.updateViewableTiles()`, but it results in the whole map being revealed on game start, since it is first called before `civInfo.units` is filled out and civilization is considered defeated

**Comment by r3versi** [comment]
What about `GameInfo.setTransients()` ?

**Comment by yairm210** [comment]
We can deal with that separately, for now this looks good =)

**Pull request merged**
