### PR TITLE
New options control over Animations

### PR DESCRIPTION
**Pull request by SomeTroglodyte**
Solves #11986 - luxury version

### Screwnshots
<details>

Predefined sets SelectBox (the "Expert" entry allows controlling each anim individually, the other set all individual options to a preset):
image

Expert mode:
image
</details>

### Notes
- Wording up for discussion
- Choice of predefined sets up for discussion - more of them? Which options on for them?
- Nuke untested, haven't got an advanced game here
- Yes my understanding and testing say it's perfectly fine to leave `Gdx.graphics.isContinuousRendering` off - or did I miss anything that animates without using Gdx Actions?
- Default on new installs up for discussion
- Migration does not map `continuousRendering==false` into the new world perfectly - some anims weren't gated at all, to get identical behaviour we would need to create a preset with only the ungated anims on - worth it?

### CODE REVIEW

**Comment by yairm210** [comment]
If anything we want it constantly *on*
The continuous rendering means redrawing the screen when nothing has changed, this affects the cpu usage considerably

**Comment by yairm210** [comment]
Right right
Got confused not sure why

**Comment by AdityaMH** [comment]
Use "custom" instead "expert"?

**Comment by yairm210** [comment]
After vacillating over this, I think this is overcomplexity no one needs.
There should be one big 'disable animation' setting.

**Comment by hippie68** [comment]
The pull request works well. I think disabling all animations saves battery life on my laptop.

**Comment by AdityaMH** [comment]
He left

**Pull request closed without merging**
