### PR TITLE
Update Japanese translation

### PR DESCRIPTION
**Pull request by yuracla**

### CODE REVIEW

**Comment by xlenstra** [comment]
Placeholder `[civName]` not found in `Japanese` for entry `[civName] rewarded you with [influence] influence for completing the [questName] quest.`

**Comment by xlenstra** [comment]
Are you able to merge in the existing translations via 'resolve conflicts'?

**Comment by yuracla** [comment]
I tried but l couldn't.

**Comment by xlenstra** [comment]
In that case, I'll update this PR to include the translations from master, feel free to edit these afterwards

**Pull request merged**
