### PR TITLE
Change the city's name while changing the language

### LINKED ISSUE #2046: When we build a city named with Chinese character, if we change the language with English, the name of the city will disappear.
for example, we have a city named "北京" in Chinese，then we change the game language with English, the name "北京" will disappear.

### PR DESCRIPTION
**Pull request by JackRainy**
Resolves #2046 

I was in doubt where is the best place for this functionality, so I hope the `Translations` is the right one.

### CODE REVIEW

**Comment by yairm210** [comment]
I like the direction, but there are 2 problems with this implementation

One is that new cities will not be translated. So if you're playing and your enemy founds a city, that's lost.
The second is that the cities are checked according to the *owning civ*. Cities get captured, and once captured, that city will not be translated in the future.

I *do* like that you only translate the cities for the nations in the game, that's a clever space-saving right there =)

I would iterate over the nations in the game (even the defeated ones), and for each one would try and translate all of their cities (for city in nation.cities)
This gives you a much simpler check, and covers both situations of future cities being constructed and cities being captured

**Comment by JackRainy** [comment]
Actually, it does iterate through ALL civs, not only viewing civ.

See the line 163:
> // iterate through all civilizations to translate all cities on the map
            currentGame.gameInfo.civilizations.forEach

**Comment by yairm210** [comment]
???
That's what I said, you iterate only through the civs that are in the game, not those that are not in the game

**Comment by JackRainy** [comment]
I am not sure, I understand what you mean.
For example, civ A has captured all the cities of civ B.
Iteration will go through all cities of civ A, and not civ B, because B is destroyed.
However, among cities of civ A, finding the city captured one from B will cause the check at line 168 `if (currentCityIndex < 0)` triggered and initiate the search also for cities of other nations.

**Comment by JackRainy** [comment]
Wait a minute... It seems I understand. You are talking about the multiplayer game, when other players use other languages, right?

This PR solves the problem *only for singleplayer* games.

It is not called at `loadGame()`, so it will not translate the new cities found in other languages. Although, it works fine for singleplayer, because AI always uses your current language and creates new cities in the language you use at the moment.
And yes, it does not check for all other possible languages from other players, which can be present in the save file.

Also, @r3versi has mentioned another problem: having the different number of cities in `Nations_Language1.json` and `Nations_Language2.json` can cause this code crashed. :(

**Pull request closed without merging**
