### PR TITLE
Fix screen bugs when you don't use splitpane in pickscreen

### PR DESCRIPTION
**Pull request by lishaoxia1985**

### CODE REVIEW

**Review by lishaoxia1985 — COMMENTED** [review]
@yairm210 OK, I have fixed New Game Screen bug😄, you can revert back.

**Comment by yairm210** [comment]
There's to much going on here for a single pr.
There's a lot of stuff that of self contained would be trivial to add, but don't if it isn't.
Specifically, if we want to change existing translated texts, we need to change the text in all existing translation files, otherwise we lose existing translations for other languages.

In general, multiple small changes should ideally be contained in multiple small prs.

**Comment by lishaoxia1985** [comment]
I know you mean, so I ONLY edit temperance.json, let you choose when we generate all translation files from it.
about multiple small prs, maybe you can use pick cherry.
Of course, creating a branch is a better idea.
________________________________

**Comment by yairm210** [comment]
I made the changes to the two translation based things, the rest is simpler to add later

**Comment by lishaoxia1985** [comment]
@yairm210 now Fix all screen bugs when you don't use splitpane in pickscreen

**Comment by lishaoxia1985** [comment]
@yairm210 Now it has no conflicts🐯

**Comment by yairm210** [comment]
Seriously though. Split this into separate PRs. Use branches. It's really hard to work like this.

**Comment by lishaoxia1985** [comment]
@yairm210 now you can merge this and revert back to "Fix screen bugs when you don't use splitpane in pickscreen #3760"😄

**Comment by lishaoxia1985** [comment]
@yairm210 🐯

**Pull request merged**
