### PR TITLE
Policy cost modconstants

### PR DESCRIPTION
**Pull request by Dimensiondog**
* docs updated
* basepolicycost
* numpolicyadoptedmultiplier
* policycostexponent

### CODE REVIEW

**Comment by Dimensiondog** [comment]
Yes I couldn't get studio to work so I just worked on github.

**Comment by Dimensiondog** [comment]
Fixed modconstant name and took your advice and made more concise.

**Comment by Dimensiondog** [comment]
> "couldn't get studio to work"? Shouldn't be hard. On apt-based Linuxes [my old notes](https://github.com/SomeTroglodyte/Scratchpad/blob/master/Unciv-notes/Getting-Started.md) might help.

No im just on an older computer and don't have enough ram

**Comment by yairm210** [comment]
This actually runs counter to a long term plan of mine - moddable calculations - so while I don't have a problem with the concept itself, I'll have to say no to this

**Comment by Dimensiondog** [comment]
> This actually runs counter to a long term plan of mine - moddable calculations - so while I don't have a problem with the concept itself, I'll have to say no to this

what is moddable calculations?

**Comment by yairm210** [comment]
Right you're not in Discord, I'll error here what I wrote there


Whoof, where to start... 


Currently, there are a lot of calculations (policy cost and unit upkeep costs are good examples) that hardcoded depend on certain other variables.
Your suggestion is to make the individual elements moddable, `policyBaseCost + (numberOfAdoptedPolicies * numPoliciesCostMultiplier).toDouble().pow(policyCostExponent)` 
But there's also a second part to this calculation, `(policyCultureCost * (1 + cityModifier)).roundToInt()` where cityModifier is also dependant on map size.

That's a heckuva lot of different variables. But what if I don't want policy cost to depend on number of adopted policies? What if I don't want extra cities to affect me? What if instead I want to, in fact have a *completely different calculation*?

---

My long-term plan is to make modders be able to specify these *entirely different* calculations.
Imagine if you will that you could define variables in a json file, like 'policyCost': 'policyBaseCost + (numberOfAdoptedPolicies * numPoliciesCostMultiplier)^policyCostExponent ' - and Unciv would evaluate that string to a number. You could then use any building block numbers that appear in any other calculation to mix things up. Want number of techs to increase policy cost? Number of wonders to decrease it? Whatever! You can use a list of *base game-provided numbers* to define *modded values*.

But wait there's more! If we already have calculated, named numbers, we can use them as inputs for `[amount]` parameters as well!

---

Of course, this will all require **a lot** of work. But we've done even more work than this when defining the filters, and conditionals, and even the uniques themselves.

I would rather not add small pieces to modify what I feel are pretty hardcoded calculations, when I intend to eventually forgo those entirely.

**Comment by yairm210** [comment]
I guess the real question is how non-coder-user-friendly we want this to be

**Comment by Dimensiondog** [comment]
I could probably make moddable constants where it was a json with the formula and modders could just put the formula any formula that would work if put straight into unciv code.
For example:
"policycostformula": 25 + (numberOfAdoptedPolicies * 6).toDouble().pow(1.7)

**Comment by yairm210** [comment]
In any case, this should be closed

**Pull request closed without merging**
