### PR TITLE
some bug fix

### PR DESCRIPTION
**Pull request by lishaoxia1985**
some bug fix:
- Scout won't be built when research "Scientific Theory". 
- Cavalry should won't be built when research "Combustion".
- Fix the word "Can only build water units in coastal cities".
- Fix the bugs when you delete all maps close button disappears and you can't go to main menu.
- Basictests don't check that Scout can't upgrade. 
- If the unit is obsolete it will remove from construction queue.

In fact in the original game Scout can upgrade to Archer only when it enters into ancient ruins.

### CODE REVIEW

**Comment by lishaoxia1985** [comment]
how do you think this? I draw a round rectangle rounded rectangle with the size 400*100 and replace the file civTableBackground.png. 
In fact, I'm not sure replace this file or create a new one. this file will be used in four place: city button, city screen, tech button and notification button.
YueR

**Comment by yairm210** [comment]
Recall that if scouts are being built and they become obsolete, the game will currently crash when trying to change their construction because they have no upgrade.
Not sure what will happen to Cavalry though - their upgrades require a different resource, and I'm not sure how the game handles that TBH - needs investigating

**Comment by yairm210** [comment]
That's the reason the test exists, by the way - because the game will crash upon research if there exists a unit that obsoletes with no upgrade

**Comment by lishaoxia1985** [comment]
I see. I don't know how the original game solve this problem because i don't have this game. please test it in the original game.

**Comment by yairm210** [comment]
I don't have the original game either =)

**Comment by lishaoxia1985** [comment]
@yairm210 I test in the unciv if you don't have resource the building will remove from the queue. I think now about Scout we can do like this. so is cavalry? how do you think? of cource we should add a notification when the building unit remove from the queue.

**Comment by lishaoxia1985** [comment]
@yairm210 If the unit is obsolete it will remove from construction queue. I think it will solve the problem.
Now it will be OK. but I have not add the Notification string in the translation files.😄

**Comment by yairm210** [comment]
I disagree with obsoleting the Cavalry - who says you'll have the oil required for the tank units?

**Comment by yairm210** [comment]
But apart from that everything else looks good =)

**Comment by lishaoxia1985** [comment]
@yairm210 as you wish,  but I don't  think spliting too many commits has significance.

**Pull request merged**
