### PR TITLE
Added various styles for displaying resource icons

### PR DESCRIPTION
**Pull request by vegeta1k95**
Added new option to settings:
image

which changes how resource icons are displayed:

1. Background color coded by yield, res type indicator (current, default)
image
2. Background color coded by type, no indicators 
image
3 Background color coded by type, amount indicator 
image

### CODE REVIEW

**Comment by yairm210** [comment]
I think we'll poll this, maybe replace yield coloring entirely
In any case B is entirely superceded by C so even if we see a split vote we'll only need 2 options

**Comment by yairm210** [comment]
We're currently at 24 vs 8 for C, which is a Definite Majority, so let's replace existing UI entirely :)

**Comment by vegeta1k95** [comment]
That means, remove option and implement only C)?

**Comment by yairm210** [comment]
Yup

**Comment by vegeta1k95** [comment]
Done. Now this is default:
image

**Comment by AdityaMH** [comment]
IMG_20230104_140937

**Pull request merged**
