### PR TITLE
Update Spanish.properties

### PR DESCRIPTION
**Pull request by ArchDuque-Pancake**

### CODE REVIEW

**Comment by ArchDuque-Pancake** [comment]
What happened?

**Comment by SomeTroglodyte** [comment]
You can *read* the checks, you know...
```
* What went wrong:
Failed to apply plugin 'com.android.internal.application'.
> Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8.
```
-> not your problem

**Comment by ArchDuque-Pancake** [comment]
Ah, menos mal, I read it but didn't understand it, nor found something.

**Comment by SomeTroglodyte** [comment]
Yup, not everything in tech -or- life is easy to understand

**Pull request merged**
