### PR TITLE
Support new razing ModOptions uniques

### PR DESCRIPTION
**Pull request by FiretronP75**
Support new ModOptions uniques: Allow raze capital, Allow raze holy city.

### CODE REVIEW

**Comment by yairm210** [comment]
Allowing capital razing makes Domination victory impossible. This is unacceptable for Domination-only victory games.

**Comment by FiretronP75** [comment]
Ah, so that means I need to change how the Domination victory check is done when this option is on. Got it.

**Comment by FiretronP75** [comment]
Oh and I missed the city conquest screen text too.

**Comment by FiretronP75** [comment]
Closed because I need to PR from a branch instead of from my master.

**Comment by FiretronP75** [comment]
Feel free to copy your comment over to the new PR.

**Pull request closed without merging**
