### PR TITLE
Activate Piety bonus

### PR DESCRIPTION
**Pull request by Am-per-Sand**
N.B.
The same condition may be found in `Building.kt`, so 
- may be add a function `isCultural`
or
- add a property `cultural:true` or even `type:[military, cultural, productive, financial, scientific, wonder]` to `Buildings.json` and get rid of `isWonder` there

### CODE REVIEW

**Comment by yairm210** [comment]
The second option is very interesting, since we can connect

**Comment by Am-per-Sand** [comment]
> since we can connect

Do you mean _"keep compatibility with the code that uses `isWonder`_"?

If yes, so may be keeping `isWonder` and gradually introducing `isMilitary:true`, `isCultural:true` to current properties in `Buildings.json` would allow to maintain backward comapatibility?

**Comment by yairm210** [comment]
I'm visualizing this differently.
You have 2 categories of 'what kind of building is this' - 
One is wonder/national wonder/regular,
The other is military/cultural/etc
Since wonders themselves subdivide into the various categories

**Comment by Am-per-Sand** [comment]
Should work fine if you have clear vision of wonder categories.

**Pull request merged**
