### PR TITLE
More civilopedia info for nation and improvement

### PR DESCRIPTION
**Pull request by rh-github-2015**
I might have missed a row or two with significant trailing blanks in the translation file. Also, please double-check - I did look for other uses of the same functions and found none, but I might be daft.

image
image

### CODE REVIEW

**Comment by rh-github-2015** [comment]
Note I left some additional text in for the picker screen use, they're useful there, except improvement uniques which are mixed. Take Inca terrace farms: The +1 per mountain unique is good to know in the picker, the cannot be built on resource one is at that point irrelevant. No easy way to show one but not the other (Working Inca code later).

**Comment by JackRainy** [comment]
Please, add the new strings to the `template.properties` file.

**Comment by rh-github-2015** [comment]
will do

**Comment by rh-github-2015** [comment]
Strange - I forked before atoll and ice, and how/why the template lines for those made it into my local repo but the german ones didn't baffles me. For consistency I re-added them in my local german, so they're here in the commit too...

**Comment by rh-github-2015** [comment]
Darn! I Check out the branch, add the missing trailing blank on the Ice= line, it's there and the file name turns blue. Open and cancel the commit dialogue and it's reverted. What gives?

**Pull request merged**
