### PR TITLE
Update Nations.json

### PR DESCRIPTION
**Pull request by Smashfanful**
Added Empire Civilization names

### CODE REVIEW

**Comment by yairm210** [comment]
... Isn't this just the adjective plus " empire"?

**Comment by Smashfanful** [comment]
Yes. The diplomacy, for example, should show "Nebuchadnezzar of the Babylonian Empire", or "Elizabeth of the British Empire".
I've been thinking about this for a while.

**Comment by yairm210** [comment]
If so, then we don't the "empire" addition since we already have e.g. "French" so we know that that's the "French empire", we don't need an additional parameter to tell us to append " Empire" on the end =)

**Comment by Smashfanful** [comment]
Alright

**Pull request closed without merging**
