### PR TITLE
Update Japanese translation

### PR DESCRIPTION
**Pull request by nukurette**

### CODE REVIEW

**Comment by xlenstra** [comment]
Placeholder `[cityName]` not found in `Japanese` for entry `Barbarians raided [cityName] and stole [amount] Gold from your treasury!`

**Comment by nukurette** [comment]
Sorry. i fixed.

**Comment by yairm210** [comment]
merge translations

**Comment by yairm210** [comment]
Translations branch created

**Comment by yairm210** [comment]
Translations PR created

**Pull request merged**
