### PR TITLE
Czech translation

### PR DESCRIPTION
**Pull request by Iver88**

### CODE REVIEW

**Comment by stoupa007** [comment]
do not overwrite formal to informal languange (vykani na tykani). most of the game uses the first one, so if you find inconsistency fix it the other way rather.

be careful with word endings. "Zajata delnik" is completely wrong.
similarly turns - "tah(y/u)" was there for a reason ...

do not make space before %, in some places this is filled by code and this is done without space.

how could be "terrain & resources" translated to only "teren"?

"hutnictvi" was correct czech term, "metalurgie" if adopted english one.

why you removed period in "radi vas potkavame"? it is complete sentence.

"Surovina [resource] poskytuje" is strange form. where in game is this used with that meaning?

generally, when you fix anything do it on all appearances and in all similar texts, otherwise it will be quite a mess.

**Comment by yairm210** [comment]
Because of recent changes in the translation process, you have conflicts =/
I suggest that you start translating again from the newest version

**Comment by Iver88** [comment]
> do not overwrite formal to informal languange (vykani na tykani). most of the game uses the first one, so if you find inconsistency fix it the other way rather.
> 
> be careful with word endings. "Zajata delnik" is completely wrong.
> similarly turns - "tah(y/u)" was there for a reason ...
> 
> do not make space before %, in some places this is filled by code and this is done without space.
> 
> how could be "terrain & resources" translated to only "teren"?
> 
> "hutnictvi" was correct czech term, "metalurgie" if adopted english one.
> 
> why you removed period in "radi vas potkavame"? it is complete sentence.
> 
> "Surovina [resource] poskytuje" is strange form. where in game is this used with that meaning?
> 
> generally, when you fix anything do it on all appearances and in all similar texts, otherwise it will be quite a mess.

Hi stoupa. I understand you, but I have lot of experience with game game translations. I have maybe ten translators under my wings. I and my team was translated many games like Fallout 76, Surviving Mars, Life is Strange 2 etc. And I work with professional translators and with biggest czech translation group PrekladyHer.eu. So it is my know how and it is based on years of work. This translation is really bad. Trust me.

Formal language is used only when translating software. In game, there is informal one. It looks better. You are player, you are ruler. Not owner of big company with a tie.

"tah(y/u)" is totally confusing version. It is hard to read. There must be "tahů" because this version has more uses. This will be solved in code. I found feature request from another slavic player who requested same feature for Russian language in this case. And czech version is compatible with his one.

"5%" and "5 %" is different version in czech language. First one is "pětiprocentní" and second version is "pět procent". First one is like when you add dot behind a number. https://martin-ulbrich.cz/jazyk-a-literatura/50-vs-50procentni-jak-na-psani-procent-slovy-a-cisly-v-textu

"terrain & resources" there is "terén a suroviny" I checked it.

"metalurgy" because this version is in Civ5 and Civ6 translation used. It is important do translation with evolution. Not revolution.

"Rádi vás poznáváme" - dot is missing because this message is displayed in box where is not dot. https://prirucka.ujc.cas.cz/?id=160

Headings, banners and labels
For headlines, inscriptions and captions (such as newspaper headlines, titles of articles and chapters, tables, graphs and pictures, legends to pictures, captions below photos, signboards, business and institution labels, inscriptions on posters, etc.) line, or if they are sufficiently graphic design different from other text, we do not write a period.

"Surovina [resource] poskytuje" - There was  problem with understanding. I don't have example right now, but I wasn't able catch point for tens of seconds. So I changed it. We are using same approach in another translations. And this version is used in Civ5 and Civ6 as well.

I plan to finish whole translation. You will be proud of it. Trust me. About our another translations. You can see our works here:

https://prekladyher.eu/preklady/life-is-strange-2.533/
https://prekladyher.eu/preklady/fallout-76.538/
https://prekladyher.eu/preklady/surviving-mars.602/

If you are translator of this game, we can do it properly and create team for it.

**Comment by Iver88** [comment]
> Because of recent changes in the translation process, you have conflicts =/
> I suggest that you start translating again from the newest version

I'll resolve it. :)

**Comment by Iver88** [comment]
@yairm210 We are ready to go before something changes again :D

**Comment by stoupa007** [comment]
well, if it means something for you, i work in game development for two decades. on design, code and also on translations. yes, i know that the translation for this game is not nice. i won't call it bad, rather incomplete and with lot of mistakes. what i'm doing is gradually syncing terms and fixing most obvious errors.

informal language is rude on many occasions. and sometimes its insulting even .. :)
point is you came and just started to change basic stones of what is done. changes like this are inconsistent if not finished. I saw lot of projects ended badly because of that.

i know that we need better mechanism for work endings like in "tah(y/u)" and i know that it was discussed. but until this is fixed, previous version is better (regardless of how much i hate such constructions).

issue is not what you find in czech rules, issue is that code generates strings. until the code is tweaked you should use consistent marking. and the value in strings where it is filled by code is 25% regardless of your wish to have "25 %". thus you just created inconsistency.

terrain & resources was fixed, thanks.

"metallurgy" is "hutnictvi" and for centuries always was. revolution is to use (cz)english terms suddenly instead of long time used czech ones. and using sub-optimal translation of another game is quite weak argument.

"Radi vas poznavame" as written is whole sentence. and my point was that in original string it was sentence. i admit if it is used as headline it should be without period but this is same in english so it should be reported as issue to fix in first place (i have to look for this screen in game).

"Surovina [resource] poskytuje" - still no idea where this appear in game. i will have to find it.

in last commit i just stumbled over "Tradition Complete = Tradice je kompletní". although this might be correct, why the heck you did not translate in same way other policies completion? previous version was better to understand just because of it was same pattern for all.

i would like to be proud, you can believe me. but this did not look like work of professional translators to me (yet ;)). where are you working on the translation?

**Comment by Iver88** [comment]
@stoupa007 Ok. I see a problem here. We have to agree who will be leader of czech translation. We have another POV each other. There are two possibilities.

1. I'll remove actual branch and you will be leader and you will have right of veto.
2. I'll be leader and will have right of veto. In exchange I can provide team, experience and game should be translated in relatively short time. We have native speakers in our team as well.

So it is on you. But decision must be final. Without further changes.

**Comment by stoupa007** [comment]
hahaha, well played.

i like the game much and i'm not afraid of any long term work. it is still in development so it won't be short work anyway. and if you ask me, yes, i want the control even if i had to finish it all alone.
any help welcomed though. i suppose there is huge amount of things we can easily agree on .. :)

**Comment by yairm210** [comment]
This translation was done before the big translation changes, and it looks like we can't resolve it in the normal process either =/
So with heavy heart etc, I'm closing this specific PR - you're welcome to add another PR, based off the current master =)
Really sorry for the mess, but it's for the Greater Good in the long term =)

**Comment by Iver88** [comment]
Ok. @stoupa007 You are boss here then. You was first. I remove this branch and start again. I let actual stuff and focus on typos and untranslated texts primary.

**Comment by stoupa007** [comment]
thank you

**Pull request closed without merging**
