### PR TITLE
Added Dutch translations

### PR DESCRIPTION
**Pull request by LouisDeconinck**

### CODE REVIEW

**Comment by LouisDeconinck** [comment]
I'm trying to add Dutch translations, but am quite new to GitHub. 

The first time I made a pull request everything seemed to work fine. Since then I've added more translations to the same file and wanted to submit them as well through pull requests. I now get the error message: "All checks have failed" with the following error: "Error: Process completed with exit code 1.".

Anyone knows what's going on and how to fix this issue?

**Comment by LouisDeconinck** [comment]
fixes #3601

**Comment by yairm210** [comment]
Please attach a before and after screenshot showing the change

**Comment by LouisDeconinck** [comment]
> Please attach a before and after screenshot showing the change

I haven't tested the changes

> Please attach a before and after screenshot showing the change

I haven't been able to test the change. Also, I realized the problem is probably not the color itself, but rather how to colors get overlayed onto each other (see my additional comment in the issue). So feel free to delete the "Update TechPickerScreen.kt" commit from this pull request.

**Comment by yairm210** [comment]
Since the branch belongs to you, only you can do that :)
You can do 'revert specific commit'

**Comment by LouisDeconinck** [comment]
> Since the branch belongs to you, only you can do that :)
> You can do 'revert specific commit'

I didn't find this possibility on Github's web interface, so I did a new commit that restored the old values.

**Comment by yairm210** [comment]
merge translations

**Comment by yairm210** [comment]
Translations branch created

**Comment by yairm210** [comment]
Translations PR created

**Pull request merged**
