### PR TITLE
vpn/proxy issues when creating new mp game

### LINKED ISSUE #6709: Can't create new Multiplayer Games from Desktop
**Platform**
Raspberry Pi OS armhf (32-bit linux arm)

**Version**
4.0.12, 4.0.13

**Describe the bug**
After #6679 i cannot create new games from Desktop in the first place!!!
The Client shows no network error regardless of my internet being turned on or off. It cannot detect network in my Raspberry Pi. Not sure if other Desktops are affected too or not.

**To Reproduce**
Try to create any Online Multiplayer Game from a custom server in Desktop client.

### PR DESCRIPTION
**Pull request by alexban011**
resolves #6709 by opening a connection to dropbox.com (since this is the website we use I figured it made more sense to do this)

Do not merge yet, I'd like someone with linux to test it as well since I do not currently have access to a linux machine 
Tested on Windows with hotspot from my phone (with and without vpn) and on android (with and without vpn)

EDIT: tested on Zorin OS and its not working as of yet. Will follow with an actual fix soon.

### CODE REVIEW

**Comment by alexban011** [comment]
> why there us so many unnecessary commits in this pr? the first four commits are not needed. if you are only adding a few lines you should try to add them all in one commit. I advise making a new branch for each pr you open.

I made a PR which was merged but didn't include those commits, and now they're in my master and I have no clue what to do about them. I don't know how to get rid of them, but I'll try more.

**Comment by touhidurrr** [comment]
> I made a PR which was merged but didn't include those commits, and now they're in my master and I have no clue what to do about them. I don't know how to get rid of them, but I'll try more.

Never open pull requests from master. When you want to do a pr, open a new branch and make changes in them. Then open the pr from it. When your pr is merged / close, just delete that branch.

When opening a new Branch, update your master branch.

Branches are basically copies of the main branch. But not connected. You can make changes in them and delete them.

For now, delete your fork and fork it again. Then open a new branch and open another pr from it.

Also, what do you think of my review?

**Comment by touhidurrr** [comment]
Also, now that I think of it... If you are checking connection to Dropbox / multiplayerServer endpoints anyways than pinging 1.1.1.1 or 8.8.8.8 is just a waste of time. Cause to connect to a hostname the client needs to do dns queries under the hood anyways.
So, just check if a connection to multiplayerServer or Dropbox is possible or not and call it a day.
Also it would be good if you add an error message like 'Dropbox not reachable' or 'example.com' not reachable along the way.

**Comment by SomeTroglodyte** [comment]
[my notes on branches](https://github.com/SomeTroglodyte/Scratchpad/blob/master/Unciv-notes/Working%20in%20the%20IDE%20and%20Contributing.md#branches-are-important) are old but still applicable...

**Comment by SomeTroglodyte** [comment]
... is the procedure on how to replace an irrevocably botched master altogether in there? If you go read it and that is missing, please holler ...

**Comment by touhidurrr** [comment]
@SomeTroglodyte now onto main topic!! Please review my review!!! (+ Anime Effects)

**Comment by alexban011** [comment]
I posted PR #6715 and will close this one

**Pull request closed without merging**
