### PR TITLE
bosanski test.properties

### PR DESCRIPTION
**Pull request by Ivoluka**

### CODE REVIEW

**Comment by yairm210** [comment]
The idea is to *copy* template into a new file - in your case, Bosnian.properties :)

**Comment by Ivoluka** [comment]
Yairm, I was testing how will it look like published but seemed to be seen by you. Honestly though, I want someone to make Bosnian or Serbian or Croatian or Slovenian or Macedonian or Montenegrin languages because unciv have alot languages but this yugoslav countries languages doesn't have? Well I need someone to do it. It's rare that doesn't have it. If someone could help to make these yugoslav countries languages to be in game.

**Comment by Ivoluka** [comment]
Can you help me please, where to copy Template and paste it. Am dyslexic so some things are hard for me.

**Comment by Ivoluka** [comment]
I want to thank you for helping me!

**Comment by Ivoluka** [comment]
Yes and you should probably Slovenian and Macedonian because Macedonia is like Bulgarian but little change for language. For Slovenian, their language is like 10% German mixed with 90% south slavic, so yeah people in South slavs play this game,

**Comment by yairm210** [comment]
@SomeTroglodyte aren't you overthinking this?
Copy the file he changed in its final form, create a new file with those contens
I don't think there's any need to get clever here

**Comment by yairm210** [comment]
Oglh you're right

**Pull request closed without merging**
