### PR TITLE
Adding Server Icons

### PR DESCRIPTION
**Pull request by itanasi**
Potential Icons for unciv Server to use in notifications

### CODE REVIEW

**Comment by yairm210** [comment]
These images are FAR TOO BIG, please shrink them down to 100x100

**Comment by itanasi** [comment]
Done

**Comment by SomeTroglodyte** [comment]
@itanasi - they're not referenced in the entire project except for the atlas and credits. So how and when will they be used? This might merit a wiki entry, no?

**Comment by itanasi** [comment]
They're only being (potentially) sourced for the MP notifications. Specifically the injected ones by touhidurr that say you should support them

**Pull request merged**
