### PR TITLE
Update template.properties

### PR DESCRIPTION
**Pull request by Smashfanful**
Added expansion limitation, denouncation and peace quotes.

### CODE REVIEW

**Comment by JackRainy** [comment]
Are these phrases used in the game somewhere?

**Comment by Smashfanful** [comment]
Yes.

**Comment by JackRainy** [comment]
I did not find any of them in the code. Where have you seen them?

The only exception is `[otherCiv] has denounced us!` but it is already translated.
> [civName] has denounced us! = [civName] ci ha denunciati pubblicamente!

**Comment by Smashfanful** [comment]
Right, but for "game" I thought you meant the original Civ V game, not UnCiv. So, no, they are not in UnCiv

**Comment by JackRainy** [comment]
Since they are not in Unciv, adding them here will affect nothing until #2404 feature is implemented.

**Comment by yairm210** [comment]
This is premature for now, closing this

**Pull request closed without merging**
