### PR TITLE
AS update to 4.0.1, Edit Diplomacy UI in Overview

### PR DESCRIPTION
**Pull request by lishaoxia1985**
YueR

### CODE REVIEW

**Comment by TheRNB** [comment]
Just a small correction, "... of them we know and ARE alive"
civTable.add("[${playerKnowsAndUndefeatedCivs.size - 1}] of them we know and are alive:".toLabel()).pad(5f).colspan(4).row()
"...of the we KNEW and WERE defeated"
civTable.add("[${playerKnowsAndDefeatedCivs.size}] of them we knew and were defeated:".toLabel()).pad(5f).colspan(4).row()

**Comment by yairm210** [comment]
A. I agree with theRNB
B. All player-facing texts need to have an equivalent line added in the translation template.properties

**Comment by lishaoxia1985** [comment]
@TheRNB @yairm210 Have you considered the singular form and the plural form of noun? 😄

**Comment by yairm210** [comment]
Good point
Probably "Known and alive (1)"
"Known and defeated (3)"

That way it works with any number of civs

**Comment by lishaoxia1985** [comment]
@yairm210 👌As you wish, I also add obsolete notification translation.

**Comment by yairm210** [comment]
```
com.unciv.testing.TranslationTests > allTranslationsEndWithASpace FAILED
    java.lang.AssertionError at TranslationTests.kt:125
```

**Comment by lishaoxia1985** [comment]
@yairm210 it's ok.

**Comment by lishaoxia1985** [comment]
@yairm210 now the problem is not my business.😄

**Pull request merged**
