### PR TITLE
Add checks against 0 Strength combat

### PR DESCRIPTION
**Pull request by itanasi**
Adding checks against weird cases with 0 Str Defender or Attacker

Possibly not actually needed?

### CODE REVIEW

**Comment by xlenstra** [comment]
Any unit that has 0 strength is automatically declared a civilian (this is actually the definition), so I don't think these are needed?

**Comment by yairm210** [comment]
Agree with xlenstra, this *shouldn't* be needed, it what situation did you encounter this?

**Comment by itanasi** [comment]
Someone in the Discord somehow got this to happen after modifiers. So some sort of crazy mod that set strength to 0.

Agree, it is very edge case and perhaps we just rule that people shouldn't have modifiers that set strength to 0.

**Comment by xlenstra** [comment]
Like -100% strength or something? I'd say we should just cap the strength after modifiers to be at least 1

**Pull request merged**
