### PR TITLE
Duantao/liberate city

### PR DESCRIPTION
**Pull request by ninjatao**

### CODE REVIEW

**Comment by ninjatao** [comment]
conquerCity is part of PostBattleActions and takes place before movement and XP calculation. But if player got to choose between Annex and Liberate city, it has to happen after the choice is made using PopAlert, therefore AFTER the rest calculations of PostBattleActions. This may cause so many problems.
So there are two options for me:
1. Implement a new choice dialog that blocks the whole process. conquerCity only returns when the choice is made and city is properly transfered. But I have no idea how to do it in Kotlin.
2. Cut PostBattleActions in two, postpone the 2nd part until city is transfered. This way is much easier to me.

Any suggestions?

**Comment by yairm210** [comment]
These should be 2 separate state changes.

One is military unit + city with low health + attack decision = annexed city
Second is annexed city + player decision = resisting city

This helps us later because you can then decide to 'take over' an annexed city at any point in time

**Comment by yairm210** [comment]
Not sure why you have a "conquerer" there, either

**Comment by ninjatao** [comment]
> These should be 2 separate state changes.
> 
> One is military unit + city with low health + attack decision = annexed city
> Second is annexed city + player decision = resisting city
> 
> This helps us later because you can then decide to 'take over' an annexed city at any point in time

When do you think liberating city should take place, in 1st or 2nd part?

**Comment by yairm210** [comment]
Let's make sure we have the same terminology :)
Annex = city is on autopilot
Liberating = city starts resistance timer, after which it's a regular city of yours

At any point in time, you can liberate an annexed city

So, after conquering a city, it becomes annexed. That's in the "unit attack" phase.

Afterwards, we can give the user a choice whether to liberate now, raze now, or leave annexed.

When choosing to raze, we actually liberate (starting the resistance timer) - a city being razed doesn't provide production

**Comment by ninjatao** [comment]
“Liberating = city starts resistance timer, after which it's a regular city of yours”
--------------------------------------------------------------------------------
Liberating city gives it to its founder civ. So it should not be yours. Right?

**Comment by ninjatao** [comment]
You mean liberating cities via diplomacy screen, instead of instant option after conquer?

**Comment by yairm210** [comment]
Ohhhhh
That's what you mean
I thought you mean annex vs conquer

**Comment by yairm210** [comment]
Sorry, by bad, I was the one who used the wrong terminology

image

I thought you were talking about puppet cities

I'll go though it all again =)

**Comment by yairm210** [comment]
Okay so!

If I understand the flow correctly, when you capture a city it becomes *puppeted*

The puppeted city can be given to the original owner upon capture only - that's called "liberating"

Puppeted cities can, at any point, be added to your own cities with resistance and unhappiness - that's called "annexing"

Razing is basically annexing, but also activating "raze".

**Comment by ninjatao** [comment]
Totally agree. Will study what puppet cities do. As far as I remember we also need a "courthouse" building for this.

**Comment by ninjatao** [comment]
Add a courthouse and it is almost done.

**Pull request merged**
