### PR TITLE
Initial AutoPlay implementation

### PR DESCRIPTION
**Pull request by tuvus**
Part of  #10176

This pull request adds the basic AutoPlay features of auto-playing part of the turn, the entire turn and over multiple turns in single-player. This pull request is meant to be only the beginning of implementing the full AutoPlay features. 
Please read the Civilopedia AutoPlay picture to get more details.

Some things to note are: 
- After clicking any of the partial turn actions in the popup menu (such as AutoPlay Military), the nextTurn button shows as disabled even though it isn't really. Doing any sort of click will make it look back to normal again.
- The AutoPlay button is meant to be to between the multiplayer and nextTurn button but will appear on the end if the AutoPlay button is disabled then re-enabled in the options.

- **Why are there fewer options than originally planned?:** Adding conditional statements for if the AI should do some specific action (automate diplomacy, economy, etc.) based on the user AutoPlay settings greatly reduces readability. I felt like it would require a bit more work to organize it than I originally expected. There are a lot of random if(!isHuman()) clauses, and overlap with the regular player automation settings. So I decided to separate the more complex side features from the main feature.

- **Why is multiplayer multiturn support not implemented yet?:** Multiturn AutoPlay in multiplayer is a difficult concept, especially with Multiplayer API v2 being in progress. Adding in the multiplayer multiturn AutoPlay adds in more complexity which I think we should only commit to if the AutoPlay works out.

<details><summary>Pictures</summary>

AutoplayCivilopedia
AutoPlayPartialOptions
AutoPlayButton
AutoPlayMenuePopup

</details> 

If anyone has any tweaks or recommendations, I am more than open to hearing them. Maybe we should rename AutoPlay to something else?
Once again, could someone check that I have the translations right? Is the Civilopedia auto-translated?

### CODE REVIEW

**Comment by AdityaMH** [comment]
Viewing AI compete each other as spectator mode make me boring, and now bring feature make me bored even more.
Also if me using this feature, make me more harder to see reason why my worker disappear or my city being razed  by who.

*too lazy scrolling and reading 100+ notification in one minutes/turn.

**Comment by yairm210** [comment]
I have a literal war going on so I don't have the headspace to review this now
Maybe @SeventhM and @SomeTroglodyte can help

**Comment by tuvus** [comment]
Hmm, I am getting a lot of unresolved reference Errors, and I am not sure why. Did my Kotlin error-checking version update or something? My master branch succeeds at building/running but still has these errors.

Any quick tips would be appreciated. (and yes, I have tried googling it)

**Comment by tuvus** [comment]
Closer. I tried deleting all my local files and re-downloading them but that also didn't work. And then I tried deleting and undoing MainMenuScreen (which was causing GameInfo to have an unresolved reference) and apparently, that worked. So then I re-merged an older AutoPlay branch with master. It's starting to look better but there still are a few more errors.

**Comment by tuvus** [comment]
BAM! Now let's hope nothing else is screwed up.

The thing is, when I switched from my AutoPlay branch to the master the master got the error as well. So deleting it and re-adding it must have fixed git in some way.

**Review by yairm210 — APPROVED** [review]
I'm willing to give this a shot but I am kind of worried, sissy case we can always revert this

**Comment by tuvus** [comment]
There will surely be some minor problems at least. The button is hidden behind a checkbox, so most people might not even notice it.

**Comment by tuvus** [comment]
I also have an extra feature where starting the multiturn AutoPlay autosave so that it can be canceled and the previous turn can be replayed. The feature won't be included in the initial version since it needs more testing.
This feature is the beginning of adding conditional logic for if happens that the user specified they want to manually look over and play.

**Comment by tuvus** [comment]
Does anyone know why UnitMovement.ky has `if (unit.civ.isHuman()) return listOf()`? I haven't looked into it very much yet but if anyone knows the reason why, it might require a change for AutoPlay.

**Comment by tuvus** [comment]
Thanks! I think we can use the cache with AutoPlay. We will just have to clear the cache every time we start a partial AutoPlay.

> That's why I limited the caching to AI units, the AI will only control 1 unit at a time and once it's done with that unit it won't ever move the unit again for the turn
Oof, I had planned on violating this precondition in future updates. I'll have to be a little more careful then.

**Pull request merged**
