### PR TITLE
Try to fix bug I introduced

### PR DESCRIPTION
**Pull request by Kentalot**
sorry!

### CODE REVIEW

**Comment by JackRainy** [comment]
This fix solves the initial problem of the displacement, however, it has the same flaws as mine (which looks more simple and understandable).

For example, in such situation: guess where will the Scout be placed?
Screenshot 2020-02-24 20 52 43

Desert? Hills? No, right into the trap!
Screenshot 2020-02-24 20 53 16

**Comment by Kentalot** [comment]
Ah I see, the distance at 1 set needs to also be filtered on canMoveTo :(

**Comment by Kentalot** [comment]
Can you double check if the version before my changes has the same flaw? if not, then it's a bug we need to fix anyway

**Comment by JackRainy** [comment]
Yes, the same flaw was even before your changes.

**Pull request merged**
