### PR TITLE
Territory stolen notification rewording

### PR DESCRIPTION
**Pull request by yairm210**
"the Aztecs has stolen your territory" is just wrong
As for the PR, is due to removing the exclamation mark, ymmv...

### CODE REVIEW

**Review by SomeTroglodyte — APPROVED** [review]
Still sounds like the scoundrels have absconded with the entirety on someone's territory, not just a few tiles...

Also, the day will come when English.properties: `[civName] has stolen your territory! = Your territory has been stolen by [civName]` will be simpler.. :upside_down_face: 

As for the 0x21: Those languages I understand will be perfectly all right.

**Comment by SomeTroglodyte** [comment]
I think since he's improving the english, and most translators found something much better sounding anyway, so it's fine.

**Comment by yairm210** [comment]
Precisely

**Comment by yairm210** [comment]
Not sure what broke but simplest fix is to redo

**Pull request closed without merging**
