### PR TITLE
Update Brazilian_Portuguese.properties

### PR DESCRIPTION
**Pull request by Ranbut**

### CODE REVIEW

**Comment by yairm210** [comment]
Prepare version

**Comment by yairm210** [comment]
prepare version

**Comment by Ranbut** [comment]
It's now okay to do the merging?

**Comment by yairm210** [comment]
The build pipeline broke due to libraries we depend on changing their behaviour, I'm fixing and this will automerge

**Comment by yairm210** [comment]
prepare version

**Comment by yairm210** [comment]
Version rollout PR created

**Pull request merged**
