### PR TITLE
Update Belarusian.properties

### PR DESCRIPTION
**Pull request by twinflac**

### CODE REVIEW

**Comment by twinflac** [comment]
sorry it is a little trouble with my code editor, a accidently remove all "t" in file

**Comment by twinflac** [comment]
What happend now?

**Comment by yairm210** [comment]
Placeholder `[questName]` not found in `Belarusian` for entry `[questName] (+[influenceAmount] influence)`
    Placeholder `[influenceAmount]` not found in `Belarusian` for entry `[questName] (+[influenceAmount] influence)`

**Comment by yairm210** [comment]
Closing as dead, if not you can reopen it

**Pull request closed without merging**
