### PR TITLE
Update Nations.json

### PR DESCRIPTION
**Pull request by Smashfanful**
Eliminated that pesky useless Sweden part, as it has nothing to do with the Vanilla version. Also tried to change Inca colors, to better tell it from the Ottomans

### CODE REVIEW

**Comment by ravignir** [comment]
Can't you make Inca colors the same as in civ5?
255,184,33
6,159,119

**Comment by stoupa007** [comment]
inca colors have been tweaked for better visibility and recognition IIRC.

**Comment by ravignir** [comment]
one
two
three
four
five

First one is just darker civ5 like colors. Second uses original civ5 outercolor and innercolor was made darker. Third are the original civ5 colors i mentioned earlier. Fourth are Incan colors in unciv before the change to the Ottoman like colors. Fifth is the fix proposed by Smashfanful.

**Comment by stoupa007** [comment]
well, i have to admit this last "fix" is really ugly .. :)
the second is best IMHO.
thanks.

**Comment by krushia** [comment]
The fifth is very hard to read by red-green colorblind users. First is clearest I think. (if issue #231 is to be taken seriously)

**Pull request closed without merging**
