### PR TITLE
Create Greek.properties

### PR DESCRIPTION
**Pull request by ASLST**

### CODE REVIEW

**Comment by xlenstra** [comment]
Turns out there are a few lines with double spaces, which are wrongly interpreted as translations. If you remove those, the tests will stop complaining and your translations will be merged in next version. These lines ending with double spaces are:
- `[civName] and [targetCivName] have signed the Declaration of Friendship!`
- `Introduction to [nation]`
- `By expending your [unit] you gained [Stats]!`

**Comment by ASLST** [comment]
Is it ok now?

**Comment by xlenstra** [comment]
Seem like there is still a double space after the following line:
`By expending your [unit] you gained [Stats]!`


Additionally, you forgot a placeholder tag somewhere:

    Placeholder `[count]` not found in `Greek` for entry `We promised not to settle near them ([count] turns remaining)`

**Comment by SomeTroglodyte** [comment]
@xlenstra, @yairm210   - change the unit test to recognize the double-space-after-`=` thing and give better output?
And - I've seen PR's rejected due to 'not enough translations', which is understandable as offering a very incomplete language to the average play store "customer" isn't that tasty, but blocking a new lang from the merge flow too long has a certain discouraging factor - vague idea - lower the limits and include/merge, but _hide_ unless an opt-in switch is checked?

@ASLST  Kudos for undertaking this task! :+1:

**Comment by SomeTroglodyte** [comment]
Greek
... for [FlagIcons](https://github.com/yairm210/Unciv/tree/master/android/Images.Flags/FlagIcons) matches existing attribution ... ?

**Comment by ASLST** [comment]
If you are asking me, yes it does

**Comment by SomeTroglodyte** [comment]
:laughing:  The question mark meant "include if you want" - I know that I fetched it exactly where the credits.md says the flags come from. It's just gimped to the proper size and format.

**Pull request merged**
