### PR TITLE
Fix Polynesia's Wayfinding

### LINKED ISSUE #6202: Polynesian naval units can no longer enter oceans immediately
The new format for the Polynesian unique takes away an ability they had before: the ability for all naval units, even Triremes and such, to immediately enter ocean tiles. I suggest going back to the old unique, or creating a new unique for overriding the "Cannot enter ocean tiles" unique.

### PR DESCRIPTION
**Pull request by SomeTroglodyte**
Fix #6202 by introducing a UnitsMayEnterOcean UniqueType with mapUnitFilter support which Polynesia can use with "All" instead of "Embarked"

Tested:
* [x] Polynesia's embark and trireme can sail ocean immediately
* [x] Non-Polynesia:  Astronomy still as expected
* [x] Modded `UnitsMayEnterOcean` with a unit filter that's neither "All" nor "Embarked"

### CODE REVIEW

**Comment by yairm210** [comment]
Nice fix!

**Review by yairm210 — APPROVED** [review]

**Comment by SomeTroglodyte** [comment]
In that case - the last test can't affect existing games - ready

**Comment by SomeTroglodyte** [comment]
Nah, the first mod came to mind showed a mistake with that 'specificUnitsCanEnterOcean' path - just a minute...

**Comment by SomeTroglodyte** [comment]
So this now works as expected with a modded polynesia using a "Enables [{Embarked} {Melee}] units to enter ocean tiles <starting from the [Ancient era]>" unique.

I don't like the extra lazy overhead there, but it's clearer than predicting more precisely when the evaluation is needed and it should be faster than potentially evaluating twice. Thought about longer term caching and dismissed it (a mapunit won't change any mapUnitFilter result unless it moves, fights, upgrades or something; and the evaluation is repeated often during a single route-finding call - but imo not worth the risk to miss a cache invalidation reason). Moot anyway unless someone mods something using the feature.

**Pull request merged**
