### PR TITLE
Translation: Update of Spanish

### PR DESCRIPTION
**Pull request by ArchDuque-Pancake**

### CODE REVIEW

**Comment by SomeTroglodyte** [comment]
`Remove [feature] first` is a suggestion on the improvement picker screen - like "you could build a farm here but you would need to remove that forest first"... Your tr() doesn't sound quite like that, but I couldn't come up with a sufficiently short one either.

**Comment by ArchDuque-Pancake** [comment]
Perhaps, altough to me it doesn't look like that in english either. 
But I'll try to think about another option, if not, I would need to see it in game to have a better view.

**Comment by yairm210** [comment]
merge translations

**Comment by yairm210** [comment]
Translations branch created

**Comment by yairm210** [comment]
Translations PR created

**Pull request merged**
