### PR TITLE
Alphabetized the order of nations in the json file and therefore new game screen

### PR DESCRIPTION
**Pull request by xlenstra**

### CODE REVIEW

**Comment by SomeTroglodyte** [comment]
Result language-specific. Good idea to do it in code instead. Like in... [Newgame-Mods-UI - sort Nations](https://github.com/yairm210/Unciv/pull/4522/commits/ed0cf5818964d5e169779427767b9e1e1650d6a9)?

**Comment by yairm210** [comment]
I agree with @SomeTroglodyte that this should be done in code, for multiple reasons:
- mods
- future-proofing
- translation-sensitive sort

**Comment by xlenstra** [comment]
Even then, it brings order to an otherwise unordered json file, so I don't see it being a negative :)

**Comment by SomeTroglodyte** [comment]
Wasting _your_ precious time not negative? Sorry for not preempting that - should have been obvious after the "sort civilopedia entries" issue and already fiddling with the new game screen - which was already underway as you saw.

**Pull request closed without merging**
