### PR TITLE
Fixed resource modifier

### LINKED ISSUE #8585: "Quantity of strategic resources produced by the empire +[relativeAmount]%" not working for values less than 100
itch.io version 4.4.9, Windows 10

The `"Quantity of strategic resources produced by the empire +[relativeAmount]%"` unique doesn't produce anything for values under 100%. Try increasing resources by 25% and instead of turning 4 resources into 5, it stays at 4.

This little mod has a building that increases the strategic resources by 25% for each city. If three or fewer buildings are built, nothing happens, but once four buildings are built, it kicks in, doubling everything.
[StrategicNotIncreasing.zip](https://github.com/yairm210/Unciv/files/10610138/StrategicNotIncreasing.zip)

### PR DESCRIPTION
**Pull request by Gualdimar**
Closes #8585
now a non-integer modifier can be applied

### CODE REVIEW

**Comment by yairm210** [comment]
This is a good question - do percentage extra resources apply at the tile level? At the city level? At the civ level?
The higher up it applies, the more various resources can 'batch together' to give an extra resource

I think the city level, like you have here, is a good middle ground

**Comment by Gualdimar** [comment]
since you mentioned it, unique says "produced by the empire", not "by the tile" or "by the city". 
in my test save civ has 18 Alu + 25% should be 22, but i got only 21
maybe we should refer to the civ5 rules?

**Comment by yairm210** [comment]
In that case all we need is to do the float calculations in the civ-wide getResourceModifier

**Comment by Gualdimar** [comment]
ok, i'll update

**Pull request merged**
