### PR TITLE
Turkish translations again

### PR DESCRIPTION
**Pull request by logicminimal**

### CODE REVIEW

**Comment by logicminimal** [comment]
what is wrong again

**Comment by xlenstra** [comment]
> what is wrong again

All tests pass, so nothing?

**Comment by logicminimal** [comment]
> > what is wrong again
> 
> All tests pass, so nothing?

it saus checks failed

**Comment by xlenstra** [comment]
> > > what is wrong again
> > 
> > 
> > All tests pass, so nothing?
> 
> it says checks failed

Maybe for your commits, but that was due to a problem plaguing every PR. That problem has since been fixed, and your entire PR now has a green checkmark.

**Pull request merged**
