### PR TITLE
Improve `Unique.getReplacementText`

### PR DESCRIPTION
**Pull request by SomeTroglodyte**
As mentioned in #6263, mod update suggestions multiply candidate replacement uniques by the parameter count... This is probably over the top in its sign treatment, but...

<details><summary>Before</summary>

Phasers requires tech Ballistics which does not exist!
Phasers replaces Machine Gun which does not exist!
Holodeck contains 'requiredBuildingInAllCities' - please convert to a "Requires a [Colosseum] in all cities" unique
Penguin Hatchery's unique "[+1 Food, +1 Production, +1 Science] once [Physics] is discovered" is deprecated as of 3.17.10 - removed 3.18.19, replace with "[stats] <after discovering [Physics]>"
Aliens's unique "+[-33]% Production when constructing [Military] units [in all cities]" is deprecated as of 3.17.10 - removed 3.18.5, replace with "[+-33]% Production when constructing [baseUnitFilter] units [cityFilter]", "[+amount]% Production when constructing [Military] units [cityFilter]", "[+amount]% Production when constructing [baseUnitFilter] units [in all cities]"
Cold heart's unique "+[33]% Strength in [Snow]" is deprecated as of 3.17.5 - removed 3.18.5, replace with "[33]% Strength <when fighting in [tileFilter] tiles>", "[amount]% Strength <when fighting in [Snow] tiles>"
Cold heart's unique "+[33]% Strength in [Tundra]" is deprecated as of 3.17.5 - removed 3.18.5, replace with "[33]% Strength <when fighting in [tileFilter] tiles>", "[amount]% Strength <when fighting in [Tundra] tiles>"
Altitude Training's unique "+[10]% Strength in [Hill]" is deprecated as of 3.17.5 - removed 3.18.5, replace with "[10]% Strength <when fighting in [tileFilter] tiles>", "[amount]% Strength <when fighting in [Hill] tiles>"
Breeders's unique "[50]% of food is carried over [in this city] after population increases" is deprecated as of 3.19.2, replace with "[50]% Food is carried over after population increases [cityFilter]", "[amount]% Food is carried over after population increases [in this city]"
</details>

<details><summary>After</summary>

Phasers requires tech Ballistics which does not exist!
Phasers replaces Machine Gun which does not exist!
Holodeck contains 'requiredBuildingInAllCities' - please convert to a "Requires a [Colosseum] in all cities" unique
Penguin Hatchery's unique "[+1 Food, +1 Production, +1 Science] once [Physics] is discovered" is deprecated as of 3.17.10 - removed 3.18.19, replace with "[+1 Food, +1 Production, +1 Science] <after discovering [Physics]>"
Aliens's unique "+[-33]% Production when constructing [Military] units [in all cities]" is deprecated as of 3.17.10 - removed 3.18.5, replace with "[-33]% Production when constructing [Military] units [in all cities]"
Cold heart's unique "+[33]% Strength in [Snow]" is deprecated as of 3.17.5 - removed 3.18.5, replace with "[+33]% Strength <when fighting in [Snow] tiles>"
Cold heart's unique "+[33]% Strength in [Tundra]" is deprecated as of 3.17.5 - removed 3.18.5, replace with "[+33]% Strength <when fighting in [Tundra] tiles>"
Altitude Training's unique "+[10]% Strength in [Hill]" is deprecated as of 3.17.5 - removed 3.18.5, replace with "[+10]% Strength <when fighting in [Hill] tiles>"
Breeders's unique "[50]% of food is carried over [in this city] after population increases" is deprecated as of 3.19.2, replace with "[50]% Food is carried over after population increases [in this city]"
</details>

Auto-updating "Before" makes matters worse, "After", if using G&K as base, would almost work right away (since requiredBuildingInAllCities isn't covered).

### CODE REVIEW

**Comment by yairm210** [comment]
Not 100% sure about this, I can't think my way through all the permutations, but if you say it's good that's enough for me

**Review by yairm210 — APPROVED** [review]

**Comment by SomeTroglodyte** [comment]
> can't think my way through all the permutations

Me neither, so I coded from a "all combos allowed" view in an exaggeratedly detailed manner so I could convince myself no step can go wrong. The alternative would be to document all cases we explicitly want to support then code minimally to realize just those.

The one specific usecase I had in mind was "+[-33]%" which I tested.

Also - idea: unit test? Would mean to include a dedicated set of uniques, a deprecated and a replacement one that are excluded from the normal deprecation cycle and are either clearly recognizable to modders as internal use only or also excluded from docs+generator.

**Comment by SomeTroglodyte** [comment]
> Improve unique replacement for +/- amounts

Actually, this was more about autoreplacing multiplying the unique by the number of parameters, mapping the parameter content in one each and leaving the placeholders in the rest.. `replace with "[10]% Strength <when fighting in [tileFilter] tiles>", "[amount]% Strength <when fighting in [Hill] tiles>` before, `[+10]% Strength <when fighting in [Hill] tiles>` after...

So, "Improve unique replacement for parameter count <> 1"?

**Comment by yairm210** [comment]
Yeah that sounds readable to non-coders

**Pull request merged**
