### PR TITLE
Update Notifications.json

### PR DESCRIPTION
**Pull request by StepanIvasyn**
Add Ukrainian translation. Fixed names is square brackets in Czech.

### CODE REVIEW

**Comment by yairm210** [comment]
We already have a dedicated Chinese translator, @lishaoxia1985 
So I'll accept the Chinese changes if he approves them =)

**Comment by StepanIvasyn** [comment]
I don't touch Chinese but somehow see changes in preview.

**Comment by yairm210** [comment]
????
Okay...? But it looks like they're part of your commit?
I dunno, that's never happened to me before... If you could revert all the Chinese changes then I'll merge
Maybe what happened is you had this file open from before the Chinese changes and you copied it *with the "old" chinese) to the new commit?

**Comment by StepanIvasyn** [comment]
I open file more than 3 hours ago. And Chinese change 2 hours ago.

**Comment by yairm210** [comment]
So that's probably it... how annoying =(

**Comment by StepanIvasyn** [comment]
I wait confirmation from @lishaoxia1985, which more better for me in terms of time. If disapproved reverse changes.

**Comment by lishaoxia1985** [comment]
@yairm210 the newest Translations.kt have bugs, the older one is good.
@StepanIvasyn 😊

**Comment by yairm210** [comment]
I'm confused. So I should merge this?

**Comment by lishaoxia1985** [comment]
its chinese translation is not newest.

**Comment by yairm210** [comment]
K
Then Stepan, either revert changes or just create a new pull request from the latest version... Sorry :/

**Comment by StepanIvasyn** [comment]
Start rework as last time.

**Pull request closed without merging**
