### PR TITLE
New Polish translations

### PR DESCRIPTION
**Pull request by PLynx01**
Translated quite a lot of various lines to Polsih

### CODE REVIEW

**Comment by yairm210** [comment]
Placeholder `[amount]` not found in `Polish` for entry `When declaring friendship, both parties gain a [amount]% boost to great person generation`

**Comment by PLynx01** [comment]
> 
> 
> Placeholder `[amount]` not found in `Polish` for entry `When declaring friendship, both parties gain a [amount]% boost to great person generation`

What should be corrected here?

**Comment by SomeTroglodyte** [comment]
And tell us what in the [wiki](https://github.com/yairm210/Unciv/wiki/Translating#pitfalls) paragraph on this is unclear, so we can improve it.

**Comment by yairm210** [comment]
Are you planning on working on this, or should we close it?

**Pull request closed without merging**
