### PR TITLE
Changing rendering to layer based approach [concept]

### PR DESCRIPTION
**Pull request by GGGuenni**
I changed the rendering so every layer supports the layered rendering approach

I removed the background of some of the terrain features as a test and I think it works great
Variant
I really like the banana jungle vibe :D

With this approach, hill wouldn't do good as a terrain feature though

### CODE REVIEW

**Comment by ravignir** [comment]
I have some ideas/suggestions.
1. Hills atm  are just an overlay of the stony part and the shadows, so it should not be a problem to remove the terrain layer.
hilloverlay

2. We may add second (or more if needed) forest/jungle overlays that will have different density, so the resources/improvements will be more visible.  (one for tile with no improvements/resources, one for resources and one for improvements like lumber mill/trading post)

**Comment by GGGuenni** [comment]
To 1: 
What do you mean by "it should not be a problem to remove the terrain layer"? Do you think hill as a terrain feature wouldn't be a problem?

To 2: 
Currently, the implementation supports general tile variants like it did before and tile variants based on the base terrain.
Possible variants would be: 
Forest, Forest2, SnowForest, GrasslandForest, ...
Academy, SnowAcedemy, ...
Iron, PlainsIron, ...

For improvements, variants based on resources are necessary so Plantation, BananaPlantation, IvoryCamp are possible but I thought about adding support for base terrain variants like DesertSugarPlantation or PlainsIvoryCamp. 
If you want the possibility to alter the resource or terrain feature sprite based on the improvement on top of it I could add that.

Would be nice if you could give me a list of all variant additions you would like to see for terrain features, resources, and improvements.
e.g.
for terrain features: base terrain
for resources: base terrain, improvement
for improvement: base terrain, terrain features, resource

**Comment by ravignir** [comment]
1. yea, hills can just be an another layer like forests.  "it should not be a problem to remove the terrain layer"? - I meant the image I've sent, it is an universal hill "overlay" tile.

2.

> Iron, PlainsIron, ...
> 
> For improvements, variants based on resources are necessary so Plantation, BananaPlantation, IvoryCamp are possible but I thought about adding support for base terrain variants like DesertSugarPlantation or PlainsIvoryCamp.
Base Terrain part is redundant imo.

and to clarify what I've had in mind: You would have three sets of forests/jungles overlay for each of the following: Plains, Grassland, Tundra, Hill, TundraHill. Why three sets? Because default Forest/Jungle would just cover too much of the layer below OR the forests would not cover enough, if the tile has no resources/improvements.  

TerrainImage+(FeatureOverlayImage if necessary - Hill/Marsh/Oasis/Atoll etc)+ResourceLayer+ImprovementLayer+Vegetation Layer(Forest/Jungle and they need to have some variants, because some Improvements/Resources will look bad if placed first).

BaseTerrain, Feature Overlay, Resource, Improvement, Vegetation.
Maybe Resources/Improvements should be the same thing [example: Silver(Snow?), SilverMine(Snow?), SIlverMinePillaged(Snow?) or Deer(Snow?), DeerCamp(Snow?), DeerCampPillaged(Snow?)]? 

Not sure if I've clarified what I had in mind or actully complicated it even more XD

**Comment by GGGuenni** [comment]
The problem is that vegetation is a terrain feature. So as long as I don't add exceptions for forest and jungle explicitly, which I don't think would be a good idea when keeping modability in mind, all the terrain features get rendered in the same layer.
Currently, the order is base terrain, resource, terrain features, improvement.

**Comment by ravignir** [comment]
> 
> 
> The problem is that vegetation is a terrain feature. So as long as I don't add exceptions for forest and jungle explicitly, which I don't think would be a good idea when keeping modability in mind, all the terrain features get rendered in the same layer.
> Currently, the order is base terrain, resource, terrain features, improvement.

that has to be changed anyway, because you can have hill+forests/jungle.

**Comment by GGGuenni** [comment]
That's why I've added support for multiple terrain features per tile earlier in version 3.13.7. So Grassland+Hill+Forest+... is possible.

So we could change the ruleset so vegetation terrain features get a new type Vegetation and check the TerrainType when adding the sprite.

**Comment by yairm210** [comment]
I've been thinking about this constantly for the last two weeks, and the truth is that I don't have a good solution.
No solution I can think of supports both 'resources behind forests' and 'hills as features'.

I will say that considering the new changes, I think the layering should be slightly altered.
But every time I come to write what that alteration should be, I end up stuck again in a endless loop of possible combinations :/

**Comment by yairm210** [comment]
I think the simplest way would be to limit the combinations instead of allowing them.

Something like:

```kotlin
val allTogether = listOf(baseTerrain, *terrainFeatures, resource, improvement).filterNotNull().joinToString("+")

if (ImageGetter.containsImage(allTogether)) return allTogether

else return getTerrainImages() + getImprovementAndResourceImages()

fun getTerrainImages(){
val allTerrains = listOf(baseTerrain, *terrainFeatures).joinToString("+")
if(ImageGetter.containsImage(allTerrains)) return listOf(allTerrains)
else return listOf(baseTerrain, terrainFeatures)
}
```

**Comment by GGGuenni** [comment]
Well, the only way I see now to support both 'resources behind forests' and 'hills as features' is to change all vegetation terrain features into a new type.
We could either add a new property "vegetation" to tileInfo where we save which vegetation is present on this tile or
we could have multiple (two for now) types of terrain features that can be distinguished by their TerrainType inside the ruleset.

**Comment by ravignir** [comment]
What about all resources/features/terrains/improvements having an additional parameter in jsons called layer?

**Comment by yairm210** [comment]
I did think of that, and it's a possibility.

**Comment by yairm210** [comment]
But both are the same idea as far as I'm concerned - adding a metadata tag to the forest layer to tell it to be rendered later.
I don't really like that, because it complicates the nice clean new layering system we have, I'd rather have specific tiles be doubled, but I must admit it does make the tiles look better.

**Comment by yairm210** [comment]
Currently the ordering is very simple:
A. base terrain, terrain features, natural wonder
B. Resource, improvement

Making vegetation render OVER the resource means that you're now separating the vegetation from the base terrain... and currently, "hills+forests" looks different from "hills"+"forests". It's more work than it seems to try and divide the current hills+forests and get resources between them, and I think there is an interesting alternative - we could add a json to the *tileset*, so the tileset can tell us combinations of layers ad what images to render them as.
E.g.
"Grassland+Hills+Jungle+Oil": ["Grassland+Hills", "Oil", "JungleForHills"]

That way every tileset can also make its own decisions of what it decides to layer vs what it decides to make as specific images

**Comment by GGGuenni** [comment]
My first thought about it was that it sounds great to add this info to the tileset. But 

> "Grassland+Hills+Jungle+Oil": ["Grassland+Hills", "Oil", "JungleForHills"]

doesn't that mean that as a tileset creator you have to either render all the tiles out as before or you add a string to the json for every possible tile combination you want to layer? That sounds more tedious to me than just rendering every tile out.

**Comment by yairm210** [comment]
You would only need to add those lines for every combination that *doesn't* fit the normal rules.
And if you think that it would be more tedious, for now we can stay without that and see what tile creators actually have to say :)

**Comment by ravignir** [comment]
> Currently the ordering is very simple:
> A. base terrain, terrain features, natural wonder
> B. Resource, improvement
> 
> Making vegetation render OVER the resource means that you're now separating the vegetation from the base terrain... and currently, "hills+forests" looks different from "hills"+"forests". It's more work than it seems to try and divide the current hills+forests and get resources between them, and I think there is an interesting alternative - we could add a json to the _tileset_, so the tileset can tell us combinations of layers ad what images to render them as.
> E.g.
> "Grassland+Hills+Jungle+Oil": ["Grassland+Hills", "Oil", "JungleForHills"]
> 
> That way every tileset can also make its own decisions of what it decides to layer vs what it decides to make as specific images

That is perfect. I like the idea of JungleForHills, and i would like to have ForestForGrasland, ForestForPlains etc as well.

**Comment by ravignir** [comment]
Anyway, with new layer rendering, it should be easier to make rivers that are actually between the tiles.

**Comment by GGGuenni** [comment]
Ohh Ok sorry I think I misunderstood the idea completely

So the "normal rule" is layer-based rendering in this order
A. base terrain, terrain features, natural wonder
B. Resource, improvement
and if you want to change something in this rule or add a specific sprite (e.g. JungleForHills) for one tile you add that to the json?

I was still stuck with non layer-based rendering as "normal rule" and that seemed tedious to me

**Comment by yairm210** [comment]
I'll close this PR in favor of the new approach, please test it out and see if you have any improvements on it!

**Pull request closed without merging**
