### PR TITLE
Add another confirmation when buying a religious unit in a city that …

### PR DESCRIPTION
**Pull request by WhoIsJohannes**
…doesn't follow a religion founded by the city's civ.

TODO: Need some help with getting translations right. Do I need to add something to English.properties or somewhere else?

### CODE REVIEW

**Comment by WhoIsJohannes** [comment]
Thanks! No idea what I'm doing, but did I do it correctly now?

Am So., 11. Juni 2023 um 23:10 Uhr schrieb SomeTroglodyte <
***@***.***>:

**Comment by WhoIsJohannes** [comment]
Here is a screenshot btw.

Screenshot from 2023-06-11 23-03-05

**Comment by WhoIsJohannes** [comment]
So I just remove that sure buy line?

Il dom 11 giu 2023, 23:25 SomeTroglodyte ***@***.***> ha
scritto:

**Comment by WhoIsJohannes** [comment]
Okay, maybe I got it now?

**Comment by yairm210** [comment]
We should remove the /n's from the text, and use a addGoodSizedLabel in the popup if we're worried it will be too wide. But first let's test how it looks with just slaves, iirc it should word wrap.

**Comment by yairm210** [comment]
@WhoIsJohannes Are you planning on working on this?

**Comment by WhoIsJohannes** [comment]
Sorry, I started my regular job again and we have the second baby, so my
time is very limited. I don't want to promise anything.

Il lun 24 lug 2023, 09:49 Yair Morgenstern ***@***.***> ha
scritto:

**Comment by yairm210** [comment]
Wow!! Congratulations 🎉🎉
No rush, just wanted to know what's up 😁

**Comment by WhoIsJohannes** [comment]
Thanks for picking this up! I don't have time atm to do any development for free, so unfortunately this got stalled. Also you don't need my permissions and you're welcome to take full credit. But I guess you knew that :)

**Comment by WhoIsJohannes** [comment]
Thanks a lot for finishing this! Your dedication to this is very impressive. I'm glad I could contribute a little bit while on paternity leave. Maybe I'll find some time again at some point - wish my day to day work was as exciting :')

**Review by yairm210 — APPROVED** [review]

**Pull request merged**
