### PR TITLE
Aircraft carrier is added

### PR DESCRIPTION
**Pull request by JackRainy**
* Fresh and clean commits based on PR #1723 by @ltrcao
* Corrections to the Carrier stats according to the https://civilization.fandom.com/wiki/Carrier_(Civ5)
* The icon as a separate commit

### CODE REVIEW

**Comment by JackRainy** [comment]
What still annoys me in this solution - introducing new serializable flag `isUnitInCity` [here](https://github.com/yairm210/Unciv/pull/1731/commits/b62977fa78a78d22a92853fecfaf0a5c3d5676c2#diff-886543b5b46160f44f1cc856e19216f5R66). 😞 
However, I do not see the better solution at the moment, how to mark the units which might be transported from the city and which are not.

**Comment by yairm210** [comment]
Okay, looks pretty good!
I understand the units in city vs units in carrier problem, yeah, that's annoying :/

**Comment by JackRainy** [comment]
Maybe, it's too late, but I got a better idea: does it make sense to invert a logic and rename `isUnitInCity` to `isTransported`? Because, being the city is not a key point here, what is important that fact of being transported or not.

**Comment by JackRainy** [comment]
@yairm210 , @ltrcao , if you agree, I will push a hotfix today (before it got into save files).

**Comment by ltrcao** [comment]
That makes sense. I think `isTransported` is an even better generalization than `isUnitInCity`.

Originally, I deliberated adding a similar flag only to do with whether a unit is being carried by something else, but I settled on `isAirUnitInCity` so I didn't need to add a longer check in MapUnit::putInTile, e.g. something like

```kotlin
type.isAirUnit() -> {
    tile.airUnits.add(this)
    if (tile.militaryUnit != null &&
            (tile.militaryUnit!!.type.isAircraftCarrierType() ||
             tile.militaryUnit!!.type.isMissileCarrierType())
        isTransported = true
}
```

versus what is there now. Though, now that I think about it, the xCarrierType() check isn't needed because that check is already done in UnitMovementAlgorithms::canMoveTo.

**Comment by JackRainy** [comment]
I have made a fix in the PR #1742. Now it also checks for city capacity separately from the carrier capacity, so the full carrier still can enter the full city.

**Pull request merged**
