### PR TITLE
Easter eggs: Moddable floating imagery

### PR DESCRIPTION
**Pull request by SomeTroglodyte**
I still like [Xeyes](https://github.com/SomeTroglodyte/Unciv/tree/Xeyes) veddy much - [still](https://github.com/yairm210/Unciv/pull/9128) works, but...

Something completely different: Some art of the very early 20th century, "Calaveras" from a well-known mexican painter, just floats over the main menu screen on the "Día de los Muertos" day. My regards to Manny, Meche, Glottis and Co.

Suggestions from back then researched and date logic implemented, but **free** art is a problem - however with this alternate presentation form it gets much simpler. Just images and attribution - volunteers?

<details><summary>Edit: Fresh 'peek' capture, way to create mentioned in last post</summary>

... Mind you, it ***is*** boring, you have to wait a lot to see them. Unobtrusive as is intended. 30sec Diwali, 30sec Qingming, then switch to a glimpse of the config, Shift-F9, and manny calaveras ...

https://github.com/yairm210/Unciv/assets/63000004/75757392-1e49-425d-ab7f-290faf1a7c0d

</details>

### CODE REVIEW

**Comment by yairm210** [comment]
Pics please
Also this would go in the packed pngs if I'm reading correctly, how much space does it take?

**Comment by yairm210** [comment]
All in all I'm in favor of more inclusivity for easter eggs

**Comment by 00-Evan** [comment]
> @00-Evan I hope you don't mind us copying+regexing your lunar new year table... Feel free to reciprocate.

Not at all, glad you found it useful!

**Comment by yairm210** [comment]
You know what let's do it
Debated this for a long time but I think if it's in then it can be improved

**Pull request merged**
