### PR TITLE
Tile stats are shown on a row, rather than on a column

### PR DESCRIPTION
**Pull request by r3versi**
tilestats

### CODE REVIEW

**Comment by yairm210** [comment]
How does this looks when you have several types, like food, production and gold together?

**Comment by JackRainy** [comment]
Currently, it looks quite good as for my 4.5" screen with 900x600 resolution.
Why do we need this change?
IMG_20200216_141210

**Comment by r3versi** [comment]
@yairm210 It looks like the stats shown in the top right panel. There is room for all the stats :)
@JackRainy This change doesn't affect the World Screen, it is only applied to the City Screen (bottom right panel, where are shown the stats of a selected tile).

**Comment by lishaoxia1985** [comment]
this table should be lower and lower because map and notification stand a large space,  about width,  i think it's very easy beside the language setting to russian. if we can i will make "plains" and "forest" in the same row.

**Comment by JackRainy** [comment]
@r3versi, ah, now I see... Yes, it makes sense there. Either horizontal as you suggested or vertical, left to the text, same as in the world screen.

**Comment by yairm210** [comment]
I'm finding it hard to compare the different configurations in my mind,
If you could post before-after images of a tile with multiple stat types that will be very helpful

**Comment by yairm210** [comment]
Still waiting for the pics =)

**Comment by r3versi** [comment]
Sorry for the wait.

Previous to this PR:
old


This PR:
new

**Comment by yairm210** [comment]
Wow, yeah, that was needed 
Thanks!

**Pull request merged**
