### PR TITLE
German translations 2020 04 24

### PR DESCRIPTION
**Pull request by SomeTroglodyte**

### CODE REVIEW

**Comment by yairm210** [comment]
You seem to be conflicting with other changes

**Comment by SomeTroglodyte** [comment]
Yes, and when I check the 'resolve conflicts' button it only marks 3 blocks, every one going from untranslated to translated. Maybe it doesn't like that I used 'Vile ruler, know'.. on the left side which not too long ago was a 'kow'?

**Comment by yairm210** [comment]
Дивився вночі з телефону, ввечері подивлюсь краще. Дякую тобі за переклади.

**Comment by yairm210** [comment]
merge translations

**Pull request merged**
