### PR TITLE
Correction of Czech tranlations, adding missing keys

### PR DESCRIPTION
**Pull request by sveckarel**
fixed some Czech translations
added char "Ý" to Fonts.kt
added missing keys to translate " BC", "  AC", "Occupied City", "Action" (pls check carefully)

### CODE REVIEW

**Comment by lishaoxia1985** [comment]
it's not a good idea to translate "AD" and "BC", because top bar will become longer and longer. second, in some languages the number should after the word if we translate it.

**Comment by sveckarel** [comment]
May be that isn't best solution for every language, but in czech it makes sense. And other translators can always use english original :-)

**Comment by lishaoxia1985** [comment]
alright, give you a advice: dont add "," when you translate the word, it's not useful.

**Comment by sveckarel** [comment]
OK, so applying any linter will be great

**Comment by yairm210** [comment]
@lishaoxia1985  I'll change the " BC" and " AD" to "[year] BC" and "[year] AD" so that eachlanguage can deal with it as it sees fit

**Pull request merged**
