### PR TITLE
Terrain mods and map editor

### PR DESCRIPTION
**Pull request by rh-github-2015**
Sorry about this being such a monster and being branched from a state several days old. Took a while. I just want to make you aware and maybe get your input on what to do with this.

What it does: The map editor can select mods and properly use terrain, terrainfeature, improvement, resource and nation objects from them. Mod lists are saved with the map: One (same as chosen) is used for re-opening, one (trimmed to actually used stuff) for basing a new game on the map. New game will activate and lock those mods required by the map.

open stuff:
- Modded terrain can't be picked up by the map generators
- Modded terrain cannot have automatic +sight from elevation
- the serializable mod lists on the map are needed for map files, but the also make it into every savegame where they're just ballast. No idea for now how to trim this.
- keep the upstream override resize function from killing the map editor
- did I forget to consider nation staring locations in containsMapEditorObjects()?
- sharing: code a proper reaction to a map requiring a mod that is not present

notes:
- sorry about inserting a localization option for the 'My first map' file name - should have gone into a separate branch, too lazy. I've got 'localized savegame filenames' on my list, too, not in here.
- what I did to ImageGetter may be exaggerated, but I had so many cases of mods getting out of synch or the getter's drawable map out of synch, and this was the end result. Effectively, atlanti are loaded only once, all of them, and kept - no dispose, and the drawable map is still rebuilt to include only active mods - which may be overkill as the mod items are typically very few compared with the 600+ from the base game.

### CODE REVIEW

**Comment by yairm210** [comment]
I see 2 separate issues being dealt with, so how's about we split this into 2 separate PRs.
One PR is about "How does the ImageGetter deal with images from mods?"
The second is "How does the tilemap handle modded terrains?"
I think these two issues are fully separable =)

**Comment by rh-github-2015** [comment]
True but for testing and debugging I had to mix the tasks. I would never have gotten a grip on the ImageGetter stuff if I hadn't had the ability to vary rulesets so freely (and nation-only mods don't do it: no influence on tileset use), and I would never have the editor mods stuff coded with the game crashing all the time...

So - I've got no idea how to split a PR - except of course like always to 'reset' git and github and merge in the changes locally by hand. So - would that be worth it because then I could base this on a more current state than 3.6.12?

**Comment by yairm210** [comment]
Looks good enough for me
I do note that currently, if you load a mod that has a new tileset - that tileset won't be supported,
but new tilesets from mods weren't supported up till now anyway so that's something to deal with later

**Comment by yairm210** [comment]
There appear to be conflicts
The ones that have one part in an onChange are simple enough - more your changes inside the onChange { }
The others probably require testing if it actually works, so I don't want to do them from the editor haphazardly =/

**Comment by rh-github-2015** [comment]
Mods can bring whole new tilesets? Hadn't crossed my mind. Pity creating one for testing isn't trivial... Wait a minute the difference has to be only _barely_ visible. For later.

**Comment by rh-github-2015** [comment]
> There appear to be conflicts
> The ones that have one part in an onChange are simple enough - more your changes inside the onChange { }
> The others probably require testing if it actually works, so I don't want to do them from the editor haphazardly =/

An argument for me to do the merging offline into 3.6.14 as I know (probably) what I did...

     **?**

**Comment by rh-github-2015** [comment]
This one's base is too far behind. Must recreate it.

**Pull request closed without merging**
