### PR TITLE
Update Italian.properties

### PR DESCRIPTION
**Pull request by Smashfanful**

### CODE REVIEW

**Comment by Smashfanful** [comment]
What's wrong, now?

**Comment by yairm210** [comment]
Placeholder `[unit]` not found in `Italian` for entry `May buy [unit] units for [amount] [stat] [cityFilter] starting from the [param] at an increasing price ([amount2])`
    Placeholder `[amount2]` not found in `Italian` for entry `May buy [unit] units for [amount] [stat] [cityFilter] starting from the [param] at an increasing price ([amount2])`

**Comment by Smashfanful** [comment]
> May buy [unit] units for [amount] [stat] [cityFilter] starting from the [param] at an increasing price ([amount2]

Thanks, fixed.

**Comment by SomeTroglodyte** [comment]
https://github.com/yairm210/Unciv/wiki/Translating#pitfalls

**Comment by yairm210** [comment]
merge translations

**Comment by yairm210** [comment]
Translations branch created

**Comment by yairm210** [comment]
Translations PR created

**Pull request merged**
