### PR TITLE
Debug information table

### PR DESCRIPTION
**Pull request by alkorolyov**
Added debugInfo switch in UncivGame class which toggles table with simple debug info on worldscreen.

Could be handy for future debuggins.

### CODE REVIEW

**Comment by yairm210** [comment]
Pics please?

**Comment by alkorolyov** [comment]
Sure! Always forget to add them when changing.


debug
 UI.

**Comment by alkorolyov** [comment]
However I don't know how to overlay the unit action buttons.

image

**Comment by yairm210** [comment]
I really don't see how this helps... if you're going to be debugging anyway, you'd just put a debug point in your code, no?
This doesn't look that good, and the IDE debugging is very powerful, much more powerful than this table could be...

**Pull request closed without merging**
