### PR TITLE
Update Simplified_Chinese.properties

### PR DESCRIPTION
**Pull request by Jerry1962325**
Continue to improve religious and Diplomatic Victory translation

### CODE REVIEW

**Comment by Jerry1962325** [comment]
I have something not understand why some translations missed after 3.16?

**Comment by SomeTroglodyte** [comment]
Translation templates can change. That will automatically drop existing translations for a key that no longer exists. You can always go into the file's history here to look for the missing ones to _adapt them to a new template_.
(https://github.com/yairm210/Unciv/commits/master/android/assets/jsons/translations/Simplified_Chinese.properties)

**Comment by xlenstra** [comment]
Placeholder `[Stats]` not found in `Simplified_Chinese` for entry `You gained [Stats] as your religion was spread to [cityName]`
    Placeholder `[Stats]` not found in `Simplified_Chinese` for entry `You gained [Stats] as your religion was spread to an unknown city`

**Comment by SomeTroglodyte** [comment]
I've just added a paragraph to [the documentation](https://github.com/yairm210/Unciv/wiki/Translating#pitfalls) - you two - think it's understandable?

**Comment by xlenstra** [comment]
> I've just added a paragraph to [the documentation](https://github.com/yairm210/Unciv/wiki/Translating#pitfalls) - you two - think it's understandable?

Looks good

**Pull request merged**
