### PR TITLE
Upgrading to LWJGL 3, which is now the default, as of LibGDX 1.10.1

### LINKED ISSUE #5601: LWJGL and JDK version shenanigans? (JDK version for build incompatible with running? LWJGL version basically unsupported, incompatible with newer JDK?)
**Platform**
```bash
$ uname -a
Linux Hostname 5.4.150-1-MANJARO #1 SMP PREEMPT Thu Sep 30 16:13:54 UTC 2021 x86_64 GNU/Linux
```

**Version**
`Git` master.

**Describe the bug**

Following the instructions on the wiki:

https://github.com/yairm210/Unciv/wiki/Building-locally-without-Android-Studio

Build requires JDK11. However, running apparently requires JDK8, as JDK11 crashes. Thus, it seems I have to switch my Java environment between building and running.

It seems that the version of LWJGL used with GDX here is incompatible with JDK11?

Results with JDK11:

```bash
$ ./gradlew desktop:run && ./gradlew desktop:dist
> Task :desktop:run
Packing textures - 92ms
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.lwjgl.LWJGLUtil$3 (file:/home/SomeUser/.gradle/caches/modules-2/files-2.1/org.lwjgl.lwjgl/lwjgl/2.9.3/3df168ac74e4a8c96562cdff24ad352e255bf89c/lwjgl-2.9.3.jar) to method java.lang.ClassLoader.findLibrary(java.lang.String)
WARNING: Please consider reporting this to the maintainers of org.lwjgl.LWJGLUtil$3
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Inconsistency detected by ld.so: dl-lookup.c: 105: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!

BUILD SUCCESSFUL in 1s
5 actionable tasks: 1 executed, 4 up-to-date

BUILD SUCCESSFUL in 931ms
5 actionable tasks: 5 up-to-date
```

```bash
$ java -jar desktop/build/libs/Unciv.jar 
Packing textures - 42ms
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.lwjgl.LWJGLUtil$3 (file:/SomeDir/Unciv/desktop/build/libs/Unciv.jar) to method java.lang.ClassLoader.findLibrary(java.lang.String)
WARNING: Please consider reporting this to the maintainers of org.lwjgl.LWJGLUtil$3
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Inconsistency detected by ld.so: dl-lookup.c: 105: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!
```

It all works fine if I use JDK11 when building, but then switch to JDK8 to run `Unciv.jar`.

Apparently, this is due to outdated guidelines/boilerplate/tools from GDX, that create projects with LWJGL2 instead of LWJGL3 as a dependency:

https://stackoverflow.com/questions/66580495/libgdx-keeps-giving-me-this-error-error-bad-logic-games-how-do-i-fix-this

At a glance, there does seem to be have been a consensus at LibGDX for a while that the LWJGL3 backend is ready to be the default (and is required for Java versions above 8):

https://github.com/libgdx/libgdx/issues/3673

https://github.com/libgdx/libgdx/issues/4927

Seems to have been finally switched over in July:

https://github.com/libgdx/libgdx/issues/6426 (This issue also reports a number of problems with LWJGL2 and how they're solved by switching to 3.)

https://github.com/libgdx/libgdx/pull/6463

Changing to `.gdx:gdx-backend-lwjgl3` in `build.gradle.kts` did let me avoid the above warnings while running with JDK11.

(It still crashed anyway because it "`Couldn't initialize audio,`" and ran into a `NoSuchMethodError` when trying to start OpenAL. But I think that's another issue.)

**Additional context**

Not totally sure if there's an actionable issue here. Did look through old issues and recent PRs, found #1370 from almost two years ago. Does seem on GDX's end that LWJGL2 is basically unsupported now, and certainly no longer the focus going forwards.

### PR DESCRIPTION
**Pull request by yairm210**
MacOS running problem solved by adding JVM args to desktop build.gradle
Should resolve #5601

### CODE REVIEW

**Comment by will-ca** [comment]
Cool, this branch seems to have fixed using OpenJDK11 for me.

8 still works too.

**Comment by SomeTroglodyte** [comment]
I wish I could remember why exactly I abandoned my lwjgl3 attempts a while ago. This branch crashes for me after a few minutes, but that's not what I found back then...

Sample Crash log (seen others like ArrayIndexOutOfBoundsException, but all coming from Lwjgl3 internal audio code):
```
Exception in thread "main" java.nio.BufferOverflowException
	at java.base/java.nio.DirectByteBuffer.put(DirectByteBuffer.java:443)
	at com.badlogic.gdx.backends.lwjgl3.audio.OpenALMusic.fill(OpenALMusic.java:269)
	at com.badlogic.gdx.backends.lwjgl3.audio.OpenALMusic.update(OpenALMusic.java:237)
	at com.badlogic.gdx.backends.lwjgl3.audio.OpenALLwjgl3Audio.update(OpenALLwjgl3Audio.java:253)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:132)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:116)
	at com.unciv.app.desktop.DesktopLauncher.main(DesktopLauncher.kt:57)
```
Seems outside of anything we could influence, except maybe reverting the MusicController. But - this is still a superficial look, no further analysis yet.

**Comment by yairm210** [comment]
lwjgl3 has only become the default version really recently, there were lots of problems that have since been solved
I, for one, note that the esc key doesn't seem to work. That's less good.

**Comment by SomeTroglodyte** [comment]
There was a reason why I chose keyTyped - but I forgot. Maybe WASD now breaks?

**Comment by yairm210** [comment]
I seem to have a problem with my audio on Ubuntu due to... [Visual Studio Code](https://community.monogame.net/t/openal-problem-on-ubuntu-20-04/12434/4)? I'll try to play with this on my Windows boot and see if I find anything 

All in all though, if in the end it comes down to "Unciv without sound" vs "Unciv on older lwjgl version", I'll opt for the first one. Music is not *that important* a part of Unciv, and I believe that now that lwjgl3 is the default backend we'll be able to solve those problems.

**Comment by SomeTroglodyte** [comment]
Nah, that issue applies to a library for mono, and libGdx does not touch mono. I run Mint 20, Ubuntu 20.04 under the hood, and music _does_ play - until the second chooseTrack.

**Comment by yairm210** [comment]
Welp, I got this (or something similar) as well

```
Exception in thread "main" com.badlogic.gdx.utils.GdxRuntimeException: Error reading audio data.
	at com.badlogic.gdx.backends.lwjgl3.audio.Mp3$Music.read(Mp3.java:90)
	at com.badlogic.gdx.backends.lwjgl3.audio.OpenALMusic.fill(OpenALMusic.java:253)
	at com.badlogic.gdx.backends.lwjgl3.audio.OpenALMusic.update(OpenALMusic.java:237)
	at com.badlogic.gdx.backends.lwjgl3.audio.OpenALLwjgl3Audio.update(OpenALLwjgl3Audio.java:253)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:132)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:116)
	at com.unciv.app.desktop.DesktopLauncher.main(DesktopLauncher.kt:57)
Caused by: javazoom.jl.decoder.BitstreamException: Bitstream errorcode 102
	at javazoom.jl.decoder.Bitstream.newBitstreamException(Bitstream.java:418)
	at javazoom.jl.decoder.Bitstream.readFrame(Bitstream.java:329)
	at com.badlogic.gdx.backends.lwjgl3.audio.Mp3$Music.read(Mp3.java:67)
	... 6 more

```

Oddly enough, it doesn't seem to play thatched _at all_, even after I fixed the downloading bug.

**Comment by yairm210** [comment]
The original version I mean, not the v3 branch

**Comment by SomeTroglodyte** [comment]
> doesn't seem to play thatched at all

Did I forget the compatibility rename? At some point I made the default suffix "Ambient" so only files named accordingly play when no other "mood" is needed, and tracks with "War" or "Peace" are reserved for Diplomacy and not part of that default choice pool. The code to check thatched existence and rename, and to download only under the new name, was in the original design but I left it out for the first PR or two... Yup, forgotten.

**Comment by logicminimal** [comment]
i thought it was ljwgl 3 already

**Comment by yairm210** [comment]
Okay, the more I go down the sound rabbit hole the less I understand.
Just the decision tree in musicTimerTask already confuses the hell out of me, that's a hell of a tree, I counted... 4 nested if's. 
I usually hate to rewrite things from scratch, and this is partly my fault since I didn't really *want* to deep-dive into the sound, but I do think that this could all be much, much simpler if you used sequential functions instead of using the timer ticker.
Music has a very nice music.setOnCompletionListener { }, which is perfect for calling the next piece after the current finishes.

**Comment by SomeTroglodyte** [comment]
...But Music isn't able to do fades...

**Comment by yairm210** [comment]
But Actions can, so you can just make an action that controls the sound with fade out

**Comment by yairm210** [comment]
Since the error doesn't crash the entire game and is both in a different thread and caught and logged, I have no qualms in upgrading first and solving problems later. We're probably going to encounter further problems anyway.

**Comment by yairm210** [comment]
Apparently also solves aarch hardware problems, so yeah, I'm going for it

**Pull request merged**
