### PR TITLE
more ui improvements

### PR DESCRIPTION
**Pull request by sulai**
more fine tuning on the unit controls:

- Workers Construction button is highlighted if they are working on some improvement
- Clicking on the info part of the UnitTable will teleport to that unit.
- Siege units won't show movement hints when set up. They need to pack up before they go. Packing up doesnt cost any movement points.
- on some exclusive unit commands, the unit will deselect to indicate the exclusivity. For example: sleep does not make much sense together with "move", so it will deselect after sent to Sleep.

Various minor issues fixed as well.

Let me know what you think on these :)

### CODE REVIEW

**Comment by yairm210** [comment]
When a siege unit is set up, you won't see blue-tinted tiles, or arrow popups?
If it's the former that's fine
But if it's the latter that means you need to pack up your siege units before you can know how long it will take them to get places, which restricts your decision making

**Comment by sulai** [comment]
> you need to pack up your siege units before you can know how long it will take them to get places, which restricts your decision making

good point indeed!

**Comment by sulai** [comment]
(ups, missclicked on my phone)

**Comment by sulai** [comment]
> Siege units won't show movement hints when set up. They need to pack up before they go. Packing up doesnt cost any movement points.

I removed this completely from the PR, as it doesn't seem to make much sense.

**Pull request merged**
