### PR TITLE
Fix ' 0 turns to lose population' message

### PR DESCRIPTION
**Pull request by Am-per-Sand**
https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.math/ceil.html

### CODE REVIEW

**Comment by yairm210** [comment]
I don't understand
Let's say we have 5 food
And we're losing 2 per turn
Then we'll starve in 3 turns, which is ceil(2.5), not in 2, which is floor (2.5)?

**Comment by ninjatao** [comment]
> I don't understand
> Let's say we have 5 food
> And we're losing 2 per turn
> Then we'll starve in 3 turns, which is ceil(2.5), not in 2, which is floor (2.5)?

Better be floor(storedFood/lossEveryTurn)+1?

**Comment by Am-per-Sand** [comment]
> I don't understand
> Let's say we have 5 food
> And we're losing 2 per turn
> Then we'll starve in 3 turns, which is ceil(2.5), not in 2, which is floor (2.5)?

@yairm210 You are right, I understand what you wanted to obtain, and I confirm your calculations above. However after reconsideration, I think the reason for '0 turns to...' message is 0 in foodstorage. Therefore I propose change to line 135 again.

> Better be floor(storedFood/lossEveryTurn)+1?
> Say city has 6 food and loses 2 per turn. It starves in 4 turns.

@ninjatao :clap: Yes, I think it will produce equal result as my proposal in case of negative food balance and 0 in foodstorage. And even is more elegant.

**Comment by ninjatao** [comment]
> > I don't understand
> > Let's say we have 5 food
> > And we're losing 2 per turn
> > Then we'll starve in 3 turns, which is ceil(2.5), not in 2, which is floor (2.5)?
> 
> @yairm210 You are right, I understand what you wanted to obtain, and I confirm your calculations above. However after reconsideration, I think the reason for '0 turns to...' message is 0 in foodstorage. Therefore I propose change to line 135 again.
> 
> > Better be floor(storedFood/lossEveryTurn)+1?
> > Say city has 6 food and loses 2 per turn. It starves in 4 turns.
> 
> @ninjatao 👏 Yes, I think it will produce equal result as my proposal in case of negative food balance and 0 in foodstorage. And even is more elegant.

I think you could use flood(stored/lossrate) + 1.
Let's say again city has 6 food and loses 2 per turn. It starves in 4{=floor(6/2)+1} turns instead of 3{=ceil(6/2)}. Your proposal here is the same as old logics.

**Comment by Am-per-Sand** [comment]
> 
> 
> > > I don't understand
> > > Let's say we have 5 food
> > > And we're losing 2 per turn
> > > Then we'll starve in 3 turns, which is ceil(2.5), not in 2, which is floor (2.5)?
> > 
> > 
> > @yairm210 You are right, I understand what you wanted to obtain, and I confirm your calculations above. However after reconsideration, I think the reason for '0 turns to...' message is 0 in foodstorage. Therefore I propose change to line 135 again.
> > > Better be floor(storedFood/lossEveryTurn)+1?
> > > Say city has 6 food and loses 2 per turn. It starves in 4 turns.
> > 
> > 
> > @ninjatao 👏 Yes, I think it will produce equal result as my proposal in case of negative food balance and 0 in foodstorage. And even is more elegant.
> 
> I think you could use flood(stored/lossrate) + 1.
> Let's say again city has 6 food and loses 2 per turn. It starves in 4{=floor(6/2)+1} turns instead of 3{=ceil(6/2)}. Your proposal here is the same as old logics.

Yes, that is what I have written above.

**Comment by yairm210** [comment]
The current change will still show 1 turn when losing 1 food and having 1 food left, even though it should be 2 turns, please fix as per @ninjatao's suggestion

**Comment by Am-per-Sand** [comment]
I can't – for I am not the author of ninjatao's suggestion. Anyway, it's one line, so it may be introduced anytime. Closing.

**Pull request closed without merging**
