### PR TITLE
1. rename the unit "Immortal" and the Promotion "Range" 2. fix the korean translation, it lost a (").

### PR DESCRIPTION
**Pull request by lishaoxia1985**

### CODE REVIEW

**Comment by yairm210** [comment]
Instead of 'Range Extension', which sounds a little of in English, please use 'Extended Range'

**Comment by lishaoxia1985** [comment]
@yairm210 OK，i have do that.

**Comment by yairm210** [comment]
Why did you rename the Immortal? I don't get it

**Comment by lishaoxia1985** [comment]
@yairm210 the difficulty and the Persian have the same "Immortal", if we translate it to Chinese, it's very bad, because it have different mean in different place.

**Comment by lishaoxia1985** [comment]
@yairm210 you can find "Immortal" have been translated in "NewGame,SaveGame,LoadGame,Options.json", "Immortal" in "Units,Promotions.json" is independent， so it can be changed.

**Pull request merged**
