### PR TITLE
Fixed PolicyScreen branches requirements text

### LINKED ISSUE #8274: Required policies being shown as incompatible policies in policy picker screen
Windows 10, 64 bit, and Android 12.

4.3.12 from Play Store and 4.3.14 from itch

DeCiv has a policy (Singularity) that requires three other policies and a building as prerequisites. The trouble is that the policy picker screen is saying the opposite - instead of saying that the policies have to be adopted together, it's saying "Cannot be adopted together".

The policy behaves the way it should, remaining locked until the three prerequisite policies are adopted and the required building is built. It's just the description that's got it backwards.

### PR DESCRIPTION
**Pull request by vegeta1k95**
Fixes #8274

### CODE REVIEW

**Comment by yairm210** [comment]
We have a lot if different conditionals, we don't want to face to hardcode each one. Why not just display the entire unique?

**Comment by vegeta1k95** [comment]
The point is to gather all similar conditionals under one sentence, because we don't want repeated boilerplate text, description should be slim:

Instead of:
"Cannot be adopted before X.
Cannot be adopted before Y.
Cannot be adopted before Z.
Cannot be adopted after A.
Cannot be adopted after B.
Cannot be adopted after C."

We want:
"Cannot be adopted before X,Y,Z.
Cannot be adopted after A,B,C"

**Comment by yairm210** [comment]
In that case you should take all conditionals
Unique by conditional type
And "stuff" the comvined results into the original conditional with fillPlaceholders

**Comment by yairm210** [comment]
Alternatively, if you want to work this way, then you should make the 'when' be exhaustive and take into account all conditionals
They usually come in pairs of "before" and "after" so they'll be about half/half

**Comment by vegeta1k95** [comment]
>And "stuff" the comvined results into the original conditional with fillPlaceholders
Did it this way

**Comment by yairm210** [comment]
Looks good!
How does it look for translations?

**Comment by vegeta1k95** [comment]
Done

**Comment by vegeta1k95** [comment]
Additional bugfix for Tiny displays

**Pull request merged**
