### PR TITLE
Can Change Language with No "ttf" Font

### PR DESCRIPTION
**Pull request by lishaoxia1985**
I use this program's code. 
https://github.com/badboy-tian/nativefont
He define a class named "nativefont".
But some code is redundant, I will delete it.

### CODE REVIEW

**Comment by yairm210** [comment]
Okay wow
A. This sounds really good, did you check it works on your phone?
B. How do I recognize if someone doesn't have a native font for the specified language, and what do I do in such situations? Do I disable their picking of that language? Do I use the downloaded tff as a backup plan?

**Comment by lishaoxia1985** [comment]
1.I have check it, every language runs well, but it may run slowly in Chinese in some situation, such as entering into cityinfo screen, switching cities button and stats button in overview screen, etc.. my phone is in Chinese language, in emulator there is no problem.
2.I think it should be tested especially in english or other language's system, I think now android system have most language.if it can shows some languages normally in a txt file, it will run very well.
3.if it don't shows normally in some language, you can use the downloaded tff as a backup plan.before this, we should test.
4.now i want to split the language into two types：Chinese and others, like you do. it may improve performance.

**Comment by lishaoxia1985** [comment]
@yairm210 I think now it's vey good.

**Comment by yairm210** [comment]
This looks really good
But on the other hand it does scare me a bit, because this is the sort of general change that will affect every single thing the user sees
So I think I'll clone this and see how it behaves on my phone

**Comment by yairm210** [comment]
I merged this into a secondary branch for testing purposes

**Comment by yairm210** [comment]
Okay
From an initial check it seems that this is fully Android-dependant
It doesn't even manage to run via the DesktopLauncher because NativeFont, as the name suggests, uses the android-native implementation
Specifically core.java.nativefont.NativeFontAndroid which of course does not exist from the Desktop.

The DesktopLauncher is my primary tool for debugging and testing, so this is a pretty big issue - please make the game runnable via desktop as well (if you want to if/else the platform and have separate resolutions for getFont that's fine)

**Comment by lishaoxia1985** [comment]
@yairm210 I think it's very easy in desktop running.in his website he provides all platform solution by rewriting the getFontPixmap method in NativeFontDesktop,NativeFontAndroid,NativeFontIOS and NativeFontIOSMoe(what's this?).now i need a java development tool. which tool do you use? i'm not sure if android studio can develop Java.if it can do, how do this?now i must read some paper.i will solve this problem.

**Comment by yairm210** [comment]
I use Android studio, which was initially primarily a Java tool but now does both Java and Kotlin
Fun fact: Unciv was originally developed in Java before I migrated it to Kotlin about a year ago

**Pull request merged**
