### PR TITLE
Add Cossack (icon+json+credit)

### PR DESCRIPTION
**Pull request by Am-per-Sand**
n.b. f1f4d31 comment

### CODE REVIEW

**Comment by yairm210** [comment]
Erm
Cossack already exists...

**Comment by Am-per-Sand** [comment]
@yairm210 I have noticed, but take the icon at least, for this revolution star at current icon made me fall off the chair...

**Comment by yairm210** [comment]
Ahhh 
I see
I thought you were adding it in as a new unit
Okay cool

**Comment by yairm210** [comment]
Uh
It seems to have conflicts...?
0_0
Could I trouble you with that?

**Comment by Am-per-Sand** [comment]
I can try to make a new pull request without conflicts as soon as this server becomes operational again.

**Pull request closed without merging**
