### PR TITLE
Next-turn Button color assignment line reworked

### PR DESCRIPTION
**Pull request by SomeTroglodyte**
Actually, just deleting that line might be the better option. I myself would tend to dropping it about 60:40

Next turn button had a dead color assignment statement...
  Color now goes to Label instead of container
  String comparison special casing eliminated
  Clearer code structure
  Chose different colors - from standard palette but close to associated stat

### CODE REVIEW

**Comment by yairm210** [comment]
Do these colors look good, though...?

**Comment by yairm210** [comment]
Also, now that we have the next turn actions, we can bring back the longclick maybe

**Comment by SomeTroglodyte** [comment]
> Do these colors look good, though...?

Precisely. I just wondered why the line did nothing and tried the fixed variant out - surprising really how close SKY comes to that science beaker thing and VIOLENT to the culture note - without going into gimp to pick the hues out of the PNG's.

> longclick

Isn't the [branch](https://github.com/rh-github-2015/Unciv/tree/Longpress-on-next-turn-button) still out there? I could rebase that for you if you'd like, @rh-github-2015 won't mind.

**Comment by yairm210** [comment]
Waitasecond
I thought that SomeTroglodyte and rh-github-2015 are 2 usernames for the same person
Are you different people? 0_0

**Comment by SomeTroglodyte** [comment]
> Waitasecond

I see you got the joke.

**Pull request merged**
