### PR TITLE
City construction queue: Add dependent items, perpetual auto

### PR DESCRIPTION
**Pull request by SomeTroglodyte**
* Queueing stuff when a perpetual is queued leaves the perpetual at the end of the queue
* Queueing a perpetual when a perpetual is queued replaces the old one
* Savegames with perpetuals in the middle of a queue will fix them soon
* Queueing a university right after a library is allowed (or nukes after the manhattan project - in the city building the wonder only. It's generalized and should be mod-proof)
* Tampering with the prerequisites cleans radically without any message for now (e.g. moving the library in the queue down until it would be after the university)

Screenshot ~~s when I find out how (now Powerpoint here which I used last time).~~ below.

### CODE REVIEW

**Comment by SomeTroglodyte** [comment]
@JackRainy: Please, I need someone to go over this - too complex, it likely has unwanted side effects.

**Comment by JackRainy** [comment]
I would suggest @r3versi takes a look since he is the author of the city construction queue, and knows more about it.

**Comment by SomeTroglodyte** [comment]
> @r3versi take a look

I'd like that, but that could take a while: image

Screenshot:
Peek 2020-04-15 22-14

**Comment by JackRainy** [comment]
Thank you for the animation, I have noticed that you can "Buy" the "Gold" for 270 coins - that looks like a bug already.
Screenshot 2020-04-15 23 34 23

**Comment by SomeTroglodyte** [comment]
Better than throwing stuff out when their prerequisite is moved below them - remove from queue still cleans radically, but that's OK I think.
image

>buy gold

Nice! Can't imagine where I could have introduced this, but I'll check right away. And a thousand thanks for #2421 - it wasn't yet merged, I was playtesting this, but I had read it - and then the Americans founded LA right on the map edge, bam. Serves me right for testing on 'archipelago'.

**Comment by SomeTroglodyte** [comment]
What a mess.

**Pull request closed without merging**
