### PR TITLE
Update Terrains.json

### PR DESCRIPTION
**Pull request by Smashfanful**
Added Snow, and updated Desert and Tundra.

### CODE REVIEW

**Comment by yairm210** [comment]
Adding in snow this way would mean adding in random patches of snowy land, so not right now.
This requires more complex map generation than we currently have.

**Comment by Smashfanful** [comment]
Thanks

**Comment by yairm210** [comment]
Therefore, please comment out the addition of snow

**Comment by Smashfanful** [comment]
Done so.

**Pull request merged**
