### PR TITLE
Aircraft Carrier can not attack enemy unit now, AS update to 4.1.3

### PR DESCRIPTION
**Pull request by lishaoxia1985**
You can see this: https://civilization.fandom.com/wiki/Carrier_(Civ5)
Although carrier is Naval Ranged Unit, its ranged strength is null, so it can't be as attacker in original game

### CODE REVIEW

**Comment by yairm210** [comment]
Please make this more generic by having this apply to any ranged unit with 0 attack

**Comment by lishaoxia1985** [comment]
@yairm210 I have edit it, but in **Ruleset.kt**, the method **checkModLinks()** will check whether ranged unit's rangedstrength = 0, so now All checks have failed😭

**Comment by yairm210** [comment]
Hm
I'm debating between a "Cannot attack" unique and enabling 0 rangedAttack, I think the former since that can apply to melee units as well

**Comment by lishaoxia1985** [comment]
I agree to add "Cannot attack" unique, we don't need to edit unit.json and the method checkModLinks()

**Comment by lishaoxia1985** [comment]
@yairm210 OK, now I add "Cannot attack" unique and delete carrier's ranged strength, the method checkModLinks() will not check the unit with the unique "Cannot attack".

**Pull request merged**
