### PR TITLE
Russian translation improvments

### PR DESCRIPTION
**Pull request by Roumaan**
Hey! The previous translation was pretty bad, i've tryed to make it a little better, juuuust a little.  I hope you'll like it.
P.S. Currently I am translating Tutorials file, and approximately tommorow evening i'll sent it here (GMT +3)

### CODE REVIEW

**Comment by Roumaan** [comment]
NOOOOO you added new text T_T 
okay i'll fix the conflict now
But new text i'l send with Tutorials tommorow

**Comment by yairm210** [comment]
Sorry, had I known I would have delayed it :/
Thanks for all your hard work!

Wednesday, 08 August 2018, 10:41pm +03:00 from Roumaan notifications@github.com<mailto:notifications@github.com>:


NOOOOO you added new text T_T
okay i'll fix the conflict now
But new text i'l send with Tutorials tommorow

**Comment by Roumaan** [comment]
Okey now this is fine.

**Comment by yairm210** [comment]
Awesome, it'll enter the next version =)
There's now a version rolling out but chances are within a few days to a week there'll be another =)

**Comment by Roumaan** [comment]
Sorry how could i forget. Tutorials are ready, but I forgot about changes in main translations file. Sorry, it'l be done today

**Pull request merged**
