### PR TITLE
Bring incas into main

### PR DESCRIPTION
**Pull request by rh-github-2015**
Might be about time. After all, they're not strictly vanilla but DLC, but all other pre-GK DLC nations except one are already in (if my ability to count is up to par).

Note: Just a convenience offer. I you'd rather keep them as mod, I could just as well bring the mod up to date instead.

### CODE REVIEW

**Comment by Iver88** [comment]
I think it's better as part of game right now. There is no mod manager and and lot of player doesn't know how to install mod or it's not working for them.

**Comment by RobertGine** [comment]
We also need Denmark which is a pre-GK DLC nation

**Comment by rh-github-2015** [comment]
> We also need Denmark which is a pre-GK DLC nation

Oh yes I did notice - see above "except one"? They're commented out as postponed in master due to needing snow and ice... I wonder who'll notice first that snow and ice are no longer an obstacle?

**Comment by yairm210** [comment]
image
image

No symbol, and colors are off =/

**Comment by rh-github-2015** [comment]
OK - colours, picked here:
image
should then be:
```
		"outerColor": [255,197,51],
		"innerColor": [23,185,147],
```
but where did you find the empty circle?

**Comment by rh-github-2015** [comment]
And I would prefer this icon - close to an original chakana:
Chakana inv
... but still not perfect.

**Pull request merged**
