### PR TITLE
fix untranslated string about politics

### PR DESCRIPTION
**Pull request by nacro711072**
update some politics text. #6131

### CODE REVIEW

**Review by yairm210 — APPROVED** [review]
We don't need .apply when adding onClick since existing function already chains, but that's an existing problem not a new one. Good job!

**Comment by nacro711072** [comment]
> Without digging too deep, this looks well-researched and -done.
> 
> Tiny nag: `String.toTextButton` [exists](https://github.com/yairm210/Unciv/blob/master/core/src/com/unciv/ui/utils/extensions/Scene2dExtensions.kt#L434). I would prefer it to look more like this:
> 
> ```kotlin
> /** Translate a [String] and make a [TextButton] widget from it */
> fun String.toTextButton() = TextButton(this.tr(), BaseScreen.skin)
> /** Translate a [String] and make a [TextButton] widget from it using a specific [style] */
> fun String.toTextButton(style: TextButtonStyle) = TextButton(this.tr(), style)
> /** Translate a [String] and make a [TextButton] widget from it with click handler [onClickAction] */
> fun String.toTextButton(onClickAction: ()->Unit) = toTextButton().apply { onClick(onClickAction) }
> ```
> 
> ... or so, instead of using a runtime `if` that could be resolved at compile time, plus allowing most of your potential uses here a little readability shortcut like `val diagramButton = "Show diagram".TextButton { updateDiagram() }` ... but hey, as it is, it needs to be used where possible, too.

How about this:
```kotlin
fun String.toTextButton(style: TextButtonStyle? = null, onClickAction: (() -> Unit)? = null): TextButton {
    val text = this.tr()
    val textButton = if (style == null) TextButton(text, BaseScreen.skin) else TextButton(text, style)
    if (onClickAction != null) {
        textButton.onClick { onClickAction() }
    }
    return textButton
} 
```

e.g:
```kotlin
val diagramButton = "Show diagram".toTextButton(onClickAction = ::updateDiagram)
```

> 
> Another: template `[numberOfTurns] Turns Left = ` now even more unused?

Maybe, but not sure definitely.

**Comment by yairm210** [comment]
... since the onclick can be applied globally to any actor we don't need to add it inside the totextbutton function, wr can simply chain it wherever relevant

**Comment by nacro711072** [comment]
> ... since the onclick can be applied globally to any actor we don't need to add it inside the totextbutton function, wr can simply chain it wherever relevant

Got it. Reverted~

**Pull request merged**
