### PR TITLE
Healing parity

### PR DESCRIPTION
**Pull request by letstalkaboutdune**
Adjusted healing values for parity with CV

### CODE REVIEW

**Review by xlenstra — APPROVED** [review]
Adjusting the comments isn't really necessary, but otherwise looks good!

**Comment by yairm210** [comment]
This is good enough. Anyone who wants to mod this can add global healing uniques based on tile location.

**Comment by letstalkaboutdune** [comment]
Thank you both! I can resubmit a version without the comments if you prefer. Since it's my first contribution I'm still getting a feel for the style and amount of documentation.

**Comment by xlenstra** [comment]
Imo best is to just add another commit to this PR removing these comments; I'd say documentation should describe the code as it is and not as it used to be so I don't see the added benefit of these comments.
On coding style: I try to follow the official kotlin style guide, but I have some disagreements over indentation with it so I differ a bit from it. Just doing your own thing while keeping relatively close to the style guide should be fine.

**Comment by SomeTroglodyte** [comment]
Welcome Sandworm! I say: History is always viewable through git. Mark some code, Git -> Current File -> Show History for Selection is really wondrous.

**Comment by letstalkaboutdune** [comment]
Thanks for the welcome! That's a really good tip. I suppose since the pull request has already been approved and merged I'll just leave it and know for next time.

**Pull request merged**
