### PR TITLE
Create firing assult gun

### PR DESCRIPTION
**Pull request by Ivoluka**
https://soundbible.com/2091-MP5-SMG-9mm.html

### CODE REVIEW

**Comment by Ivoluka** [comment]
How do you add a sound? I see in other sounds are empty and I don't know this one.

**Comment by Ivoluka** [comment]
I would like to know how do you add it, I seriously don't understand. Is there a miscalculation?

**Comment by yairm210** [comment]
If you're doing it on Github UI, you need to 'upload new file' for the sound file itself
image

And to update credits.md for the sound attribution (made by X on Y, whatever the attribution rules for that are)

**Comment by Ivoluka** [comment]
Uploads are disabled for me. It says "file upload require push access to this repository".

**Comment by yairm210** [comment]
Closing this since nothing has happened, we can reopen if needed

**Pull request closed without merging**
