### PR TITLE
instead some font-sizes  with the one is often used in game and doesn't need to be created again, adjust the construction table in city screen

### PR DESCRIPTION
**Pull request by lishaoxia1985**

### CODE REVIEW

**Comment by yairm210** [comment]
I have no problem with changing font sizes, but removing a working functionality needs to have a good reason, and from what I've seen it's perfectly fine
Can you elaborate on the problems that city name changing causes?

**Comment by lishaoxia1985** [comment]
@yairm210  first,  information bar about unit in the right bottom of the worldscreen can't be changed when we change the name of cities. second, we can't use language input tools.

**Comment by yairm210** [comment]
I understand the "exists in notifications" and "can't input all characters" problems, I don't feel that they're a big enough obstacle that they require removing the feature entirely.

**Comment by lishaoxia1985** [comment]
@yairm210 ok, as you wish.

**Pull request merged**
