### PR TITLE
Added "Options" to the main menu with two experimental switches: Spec…

### PR DESCRIPTION
**Pull request by alkorolyov**
…tator mode, Extended Map editor.

New options added in GameSettings class. New Icon and credits. Also refactored WordScreenOptionsPopup to make it usable with MainMenuScreen.

### CODE REVIEW

**Comment by alkorolyov** [comment]
I had to create one more interface IBackScreen for OptionsPopup for the same reasons as with PlayerPickerTable.
I want OptionsPopup to be usable with any screen implementing IBackScreen, not just WorldScreen.

I know it is quite ugly so if you have any suggestions on refactoring I would be glad to hear it!

**Comment by yairm210** [comment]
What
Why
What value do we get out of obfuscating the worldscreen away? It makes us use the ugly static reference I'm trying to get rid of, and no other screen will really need this options popup

**Comment by alkorolyov** [comment]
Yeah I agree, I was just thinking about adding options popup to the main menu. So we can change game settings before starting/loading the game. But it's only suggestion and if you want options popup only in the worldscreen I will change it :)

**Comment by alkorolyov** [comment]
I removed "Options" from Main Menu so we don't need to mess around worldscreen and interfaces.

**Pull request merged**
