### PR TITLE
use "Aurum" replacing the luxury resource "Gold", use "Siege Ability" replacing the promotion "Siege". Fixes #1804

### LINKED ISSUE #1804: Unit type and promotion have the same string "Siege". Luxury resource and basic resource have the same string "Gold".

### PR DESCRIPTION
**Pull request by lishaoxia1985**
@woone8 @SheepYang1993 @GeneralWadaling basic resource and luxury resource have the same word "Gold". this word has different mean in these two places. basic resource "Gold" is 金钱, luxury resource "Gold" is 黄金.
@yairm210 i advise that all basic resources use the lowercase letter.
the second method is using "Aurum" replace "Gold" in luxury resource. how do you think?

### CODE REVIEW

**Comment by JackRainy** [comment]
I find only one place where this string is used as a basic resource (in the stat page).
Does it make sense to keep it as a luxury resource and change the string in the stat page?

**Comment by lishaoxia1985** [comment]
@JackRainy more and more, such as "+1 Gold", don't only concern about "Gold".

**Comment by JackRainy** [comment]
I assume "+1 Gold" that's a different string and can be translated separately.

**Comment by SomeTroglodyte** [comment]
Or... Use a 'key' in the code which is translated for everybody, even english. Using "Gold~Stat".tr() in the code and Gold~Stat = Gold in English.properties would work would it not? You'd only see it when a translation is missing. So, "Aurum" isn't bad at all, we don't need to display it as such in English.

However, I believe using different 'keys' in different places for the same meaning would invite trouble down the road. Better a consistent rename of one of the two meanings through the board and bite the sour apple of invalidating already existing translations. One could fix them without even speaking the language...

**Comment by lishaoxia1985** [comment]
no,  unless you want to replace gold with 💰, unhappiness with ☹️……, because only a few words have this problem.
second,  this method will increase consumption of cpu and memory.

**Comment by lishaoxia1985** [comment]
@yairm210 now it's OK😄. if you think "Aurum" should be translated into "Gold", you can edit the file "English.properties" directly.

**Comment by lishaoxia1985** [comment]
@yairm210 I split into 2 commits and update tool to android studio 4.1.2.

**Pull request closed without merging**
