### PR TITLE
Update banner.png

### PR DESCRIPTION
**Pull request by letstalkaboutdune**
Increased banner size for testing.

### CODE REVIEW

**Comment by yairm210** [comment]
prepare version

**Comment by yairm210** [comment]
Version rollout PR created

**Comment by letstalkaboutdune** [comment]
@yairm210 have you taken a look at the size of this banner yet? Pretty minor thing, no pressure, I'm just curious.

**Comment by yairm210** [comment]
No not yet
I have an idea of how to handle it though

**Pull request closed without merging**
