### PR TITLE
Fix Goddess of Protection - maybe

### LINKED ISSUE #6488: Defence goddess belief doesn't work
**Platform**
Android 12

**Version**
Download here 4.0.3

**Describe the bug**
I choose the pantheon belief "defence goddess" (+30% damage of city when attack), but it is not displayed in attack overview (is it really work?). It can be seen in attached screenshot

Screenshot_20220404-233430

### PR DESCRIPTION
**Pull request by SomeTroglodyte**
Untested, may perhaps fix #6488

### CODE REVIEW

**Comment by yairm210** [comment]
Hm this feels like a unique that wasn't correctly deprecated, or alternatively that our religion unique tests aren't working 100%

**Comment by SomeTroglodyte** [comment]
Methinks the `baseRulesetHasNoBugs` test should run checkModLinks in a form that runs all checks so they return _all_ UniqueComplianceErrorSeverity types instead of just one severityToReport, that's where most checker intelligence gets lost, UniqueType.UniqueComplianceErrorSeverity.WarningOnly is never evaluated as far as I can see.

**Comment by SomeTroglodyte** [comment]
... but yes this one wouldn't have made it into mod check results anyway. I wonder why. Ah yes - because "[+30]% attacking Strength for cities" is untyped, the deprecated _typed_ unique would have been "[+30]% Attacking Strength for cities". So it just gets the spellcheck treatment which is silent.

**Comment by SomeTroglodyte** [comment]
Yes, `getRelativeTextDistance(UniqueType.StrengthForCitiesAttacking.placeholderText, "[]% attacking Strength for cities")` == `getRelativeTextDistance("[]% Attacking Strength for cities", "[]% attacking Strength for cities")` = 0.1818 which is above the threshold. Ouch. @will-ca - your code? How come one Char different in case makes such a large "distance"? Cuz it fails to see any similarity after the A/a mismatch probably, it gets derailed. Might a dumb `} else if (char1.lowercaseChar() == char2.lowercaseChar()) { dist++; i1++; i2++ } else...` in there help? Yup, relative dist goes to 0.03 and:
<details><summary>screen</summary>

image

</details>

**Comment by SomeTroglodyte** [comment]
Since that upper/lower case fragment improves things even without touching the rest of the ruleset check cardhouse, pushed. With the old Json you _would_ see the spellcheck message for the G&K ruleset in the UI, in green, so you'd really have to go look for it, but it's there.

**Pull request merged**
