### PR TITLE
some translation word and delete some duplicate words

### PR DESCRIPTION
**Pull request by lishaoxia1985**
sorry,i don't know if using the "beatify" in vscode may lead to some problem,so in webpage it seems that there are lots of changes because of delete a blank space etc.,but in fact there are not so much changes.sorry i think you can make the code looks well and easy-reading.

### CODE REVIEW

**Comment by yairm210** [comment]
Please make sure all spacings before translations are the same, I usually  use replace all in notepad++ for this

**Comment by lishaoxia1985** [comment]
@yairm210 I have build it, there is no problem.

**Comment by yairm210** [comment]
The problem is a visual one, not a compile one
If you enter the changes for this request, you'll see that the translations are visually inconsistent, which makes it more difficult to find something you're looking for

**Comment by lishaoxia1985** [comment]
@yairm210 ok i will do it.thank you.

**Comment by yairm210** [comment]
Is this the same as the other request?
If yes, please fix
If not, please close

**Pull request closed without merging**
