### PR TITLE
Implemented most easy things from comments on moddable victory PR

### PR DESCRIPTION
**Pull request by xlenstra**
Also added religious victory condition

Things still to do (but not this PR):
- Tabbed pager for Victory Screen
- (Stat) icons in ranking table
- Count amount of policies adopted in each branch when displaying the milestone button for that branch
- A better way to word `[building] build globally`

### CODE REVIEW

**Comment by SomeTroglodyte** [comment]
Follow-up on #6161 for reference

**Comment by SomeTroglodyte** [comment]
UI stuff - I might do some overhaul myself so don't stress out over that. There's a mouldy old branch somewhere I put off to wait for the under-the-hood changes with a few ideas to also make it more usable in portrait. _If_ I keep neglecting RL.

**Comment by yairm210** [comment]
Conflicts with your uniquifying PR

**Comment by heipizhu4** [comment]
> * A better way to word `[building] build globally`
Could it be 'build [building] in any civilization globally'

**Comment by xlenstra** [comment]
Conflicts fixed in the github editor, hopefully that should be fine

**Comment by SomeTroglodyte** [comment]
`/home/runner/work/Unciv/Unciv/core/src/com/unciv/logic/automation/ChooseBeliefsAutomation.kt: (157, 54): Unresolved reference: ThingToFocus` - that was renamed...

**Review by SomeTroglodyte — APPROVED** [review]
Untested, but code inspection says `just fine`.
(Say, `isMajorityReligionForCiv` - that smells like there should already be a usecase for it elsewhere)

**Pull request merged**
