### PR TITLE
Create BasicHelp_French.json

### PR DESCRIPTION
**Pull request by Smashfanful**
I just hope I didn't made a mess.

### CODE REVIEW

**Comment by yairm210** [comment]
Do you speak french?
Because if this is from Google translation or something, maybe it's better to have nothing at all...

**Comment by Smashfanful** [comment]
Yes, I have translated from Google Translate. I'm sorry if this is bad for you.

**Comment by yairm210** [comment]
Names and single words is one thing, but complex sentences is another, and I know from my own experience that encountering a half-baked translation leaves a worse impression than not encountering a translation at all :/

**Comment by Smashfanful** [comment]
In that case, you did well to refuse this branch,

**Pull request closed without merging**
