### PR TITLE
Fixed typo(Korean)

### PR DESCRIPTION
**Pull request by coding-human**
missed the 'n' in the \n. My mistake.

### CODE REVIEW

**Comment by coding-human** [comment]
Maybe this is why Korean version has some crash when settlers are founding a new city while playing in Korean.
It is all my fault trying to translate all of them in a short time.

**Comment by coding-human** [comment]
If it is possible, please add this apology to the play store description next time.
" 최근 있었던 한국어 번역 오류로 도시 건설 시 게임이 멈추는 현상이 있었습니다. 번역의 속도에만 집중하다 보니 오류를 인지하지 못했습니다. 앞으로 오류 없는 번역을 제공해 드릴 것을 약속드리겠습니다. - 한국어 번역 봉사자 "

**Comment by yairm210** [comment]
That wasn't the problem, there were others - see 2b384c7
I added tests to ensure that Travis will shoult at you if this happens again =)

**Comment by coding-human** [comment]
That 

> That wasn't the problem, there were others - see [2b384c7](https://github.com/yairm210/Unciv/commit/2b384c7d01c42b07786fbc97911843092e779bd4)
> I added tests to ensure that Travis will shoult at you if this happens again =)

That might be also right, but for the errors in the settlers, I already checked the error report and found out this was the problem in Korean translation. I must double-check now. (And remove this bad "insert" button out of my keyboard.)

**Comment by yairm210** [comment]
Yes, it was a problem in the Korean translation, Which I fixed in 2b384c7, open it and you'll see =)

**Comment by coding-human** [comment]
Umm. I checked.

**Pull request merged**
