### PR TITLE
Update Turkish.properties

### PR DESCRIPTION
**Pull request by KircheP**
Changelog
-Fixed a few words and added some stuff in #Diplomacy,Trade,Nations segment -Fully translated New Game Screen 
-Fully translated Multiplayer segment
--Fixed some badly translated words in multiplayer that lacked context. For example İstifa etmek shouldnt be used in a civlike battle context. Correct term for it is Geri cekilmek. 
-Fully translated Map Editor
-Fully translated Labels/Messages
-Fully translated Map Tool Names
-Fully translated Save Game Menu
-Fully translated Options-About tab-Display tab-graphics ui etc subgroup parts -Fully translated Visual hints subgroup
-Fully translated Gameplay tab
-Fully translated Advanced tab
-Fully translated Notifications tab
-Translated Trigger effects
-Translated Trigger causes
-Partially translated World UI Screen

Currently from 30 to 1094 are fully translated into Turkish within this changelog

### CODE REVIEW

**Comment by yairm210** [comment]
I usually manually solve these kinds of conflicts but in this case there are 53 conflict areas, I'm not going to do all that 😓

**Comment by KircheP** [comment]
> I usually manually solve these kinds of conflicts but in this case there are 53 conflict areas, I'm not going to do all that 😓

I see, im new to githubs UI and stuff. Ill do my best to fix conflicts but can you show me where the conflicts or reasons for it so i can understand what is the reason for them

**Comment by Ouaz** [comment]
Can you also fix these two translation errors, because it makes fail the checks of other submitted PRs (how the hell the broken turkish PR has slipped into the rollout commit , I don't know)...

[Line 934](https://github.com/yairm210/Unciv/blob/master/android/assets/jsons/translations/Turkish.properties#L934), `[unit]` is missing: 
`An enemy [unit] has destroyed our tile improvement [improvement] = Bir düşman birimi [improvement] karo geliştirmesini yok etti`

[Line 1483](https://github.com/yairm210/Unciv/blob/master/android/assets/jsons/translations/Turkish.properties#L1483), `[number]` is missing:
`Minimum votes for electing a world leader: [number] = Dünya lideri seçilebilmesi için gereken asgari oy:`

**Comment by KircheP** [comment]
> Please, can you also fix these two translation errors in the turkish file, because it makes fail the checks of other submitted PRs (how the hell the broken PR has slipped into the rollout commit , I don't know)...
> 
> Thanks!
> 
> [Line 934](https://github.com/yairm210/Unciv/blob/master/android/assets/jsons/translations/Turkish.properties#L934), `[unit]` is missing: `An enemy [unit] has destroyed our tile improvement [improvement] = Bir düşman birimi [improvement] karo geliştirmesini yok etti`
> 
> [Line 1483](https://github.com/yairm210/Unciv/blob/master/android/asset

> Please, can you also fix these two translation errors in the turkish file, because it makes fail the checks of other submitted PRs (how the hell the broken PR has slipped into the rollout commit , I don't know)...
> 
> Thanks!
> 
> [Line 934](https://github.com/yairm210/Unciv/blob/master/android/assets/jsons/translations/Turkish.properties#L934), `[unit]` is missing: `An enemy [unit] has destroyed our tile improvement [improvement] = Bir düşman birimi [improvement] karo geliştirmesini yok etti`
> 
> [Line 1483](https://github.com/yairm210/Unciv/blob/master/android/assets/jsons/translations/Turkish.properties#L1483), `[number]` is missing: `Minimum votes for electing a world leader: [number] = Dünya lideri seçilebilmesi için gereken asgari oy:`

As far i can checked both this translating issues and conflicts are due to both PRs are translating the same places
My solution would be scrapping mine own PR and making a new one on top of the other one, i will be working on it tonight after work along with the fixes of #943 and #1483

**Pull request closed without merging**
