### PR TITLE
Update Italian.properties

### PR DESCRIPTION
**Pull request by Smashfanful**

### CODE REVIEW

**Comment by Smashfanful** [comment]
What did I do wrong?

**Comment by SomeTroglodyte** [comment]
```
    Entry {Italian=Puoi costruire edifici [buildingFilter] per [amount] [stat] [cityFilter] a un prezzo crescente ([amount])} has the parameter [amount] more than once
    Entry {Italian=con caselle [tileFilter] adiacenti da [amount] a [amount]} has the parameter [amount] more than once
    Entry {Italian=con caselle [tileFilter] [tileFilter] adiacenti da [amount] a [amount]} has the parameter [amount] more than once
    Entry {Italian=nelle caselle [tileFilter] [tileFilter]} has the parameter [tileFilter] more than once
    Entry {Italian=Ottieni [amount]-[amount] [stat]} has the parameter [amount] more than once
    Entry {Italian=Da una casella a caso a [amount] caselle dalle rovine, puoi rivelare caselle fino a [amount] caselle di distanza ([amount]% di probabilità)} has the parameter [amount] more than once
    Entry {Italian=+[amount]% Attacco per tutte le unità [mapUnitFilter] per [amount] turni} has the parameter [amount] more than once
```

That's accessible with the "Details" link right beside the failing build.

**Comment by Smashfanful** [comment]
> 

Can't sentences with more than one [amount] part have [amount1] and [amount2] instead?

**Comment by yairm210** [comment]
Ahh I see the problem, I took the uniques directly from unique text where they aren't in any existing object and thus you get these

**Comment by Smashfanful** [comment]
> Ahh I see the problem, I took the uniques directly from unique text where they aren't in any existing object and thus you get these

Thanks

**Comment by xlenstra** [comment]
If you merge in master (resolve conflicts), the :heavy_multiplication_x: should go away

**Comment by yairm210** [comment]
Still relevant?

**Pull request closed without merging**
