### PR TITLE
Adding units on map editor.

### PR DESCRIPTION
**Pull request by alkorolyov**
Hi all,

I want to start working on Map Editor and more precisely make current unit editor more "public friendly".

As I see from current implementation there might be several problems, and the main is adding units for the civilizations that hasn't been added during game creation. I checked original Civ 5 WorldBuilder mechanics and it seems we can borrow some ideas from it.

In Civ 5 WorldBuilder there is additional scenario information added to a map file, like player count, starting locations, additional units, technologies and so on. On a game creation screen there is checkbox which lets us choose whether we want to use it and have fixed nations, starting locations and other conditions. Or we can uncheck it and use only geopraphical map information - with any number of players, random starting locations.

What do you think about implementing the same way in Unciv? The main difference that I see is that in Unciv we define a "player" as fixed civilization and in Civ5 we have abstract "player1" which has a property "civilization". In general it shoudn't be a big issue, however some cases might be different, like for example in Civ 5 we can create scenario with two same civilizations fighting each other.

To sum up I propose the next implementation:

- Adding "Load scenario" flag during game creation , which class should it belong?

- When this flag is set, on NewGameScreen we have fixed number of civilizations with predefined starting locations. Number of civilizations = number of starting locations. The civilizations itself are also predefined.

- On MapEditor we first add civilizations by setting their starting locations. On the "Units" tab we have only units for civilizations already added. We forbid adding units of other civilizations if their starting location hasn't been set, except for City states and Barbarians.

- On MapEditor we also forbid having less than two civilizations.

- If flag "Load scenario" is false, we use current implementation for new game creation with small fix - we ignore all starting location and unit information from the mapfile.
  
For the moment it should be enough for the basic version. In future we can figure out how to support starting location for some random civilization.

Looking forward for you feedback before starting the work :)

### CODE REVIEW

**Comment by yairm210** [comment]
You're describing what is essentially a predefined GameParameters to go with a specific map.
The first question, the, is how we save this. 
This sounds like a new class, Scenario, containing a TileMap and GameParameters, and probably a name:String.
Now we have 2 separate issues: How to create such a scenario, and how to load it.
Loading it is more a UI issue than anything else, since the NewGameScreen already contains displays for a custom map and game parameters, we just need to "lock" all of the parameters in place.
Creating it, though, will be more problematic. We can take the GameParameters table from the NewGameScreen and use it for the parameters setup, but what's the process? Do you start by defining the civs and parameters? What happens if once yoy've made a map you decide there should be a change in the parameters?

**Comment by alkorolyov** [comment]
I see what you mean.

Yes it looks like a Scenario class, GameParameters for civs info and TitleMap for units info. For the loading as you wrote there shoudn't be much problem. We just need to add a "Load scenario" checkbox to lock game parameters.

For the creation I believe we can use logic from Civ 5 WorldBuilder. They specify game parameters in map editor, as you suggested for this we can add GameParameters table from the NewGameScreen to a MapEditorScreen. Then the first step is to define number of civilizations and parameters, then we have units and improvments buttons only for selected civs.

As for the changing game parameters there are two options, also taken from Civ 5 logic:

- if one doesn't want to use Scenario information, just play on that map - uncheck "Load scenario" and specify their own game parameters, scenario information from the map will be ignored.

- if we want to use scenario information and want change game parameters - then we need to edit it through MapEditor, like in Civ 5. During game creation and checked "Load scenario" we have game parameters fixed. I believe we can only switch players (like AI or Human) for specific slots - in Civ 5 WorldBuilder they have "playable" option for slot. Like whether human can play this slot in this scenario.

How does it sound to you?

**Comment by alkorolyov** [comment]
Hi @yairm210 ,

I need help and ideas concerning "Load scenario" checkbox.

I decided to start from simple UI modifications for New Game screen. I am getting acquainted with UI responsible for Map Options, Civilizations and Game Parameters on NewGameScreen. From visual point of view I foresee "Load Scenario"  checkbox to be placed on MapOptionsTable (more precisely savedMapOptionsTable). 

However I am not happy to have other tables - playerPickerTable and newGameOptionsTable - to be dependent on MapOptionsTable checkbox. They would also need to be re-rendered when checkbox is changed. Basically the abstractions of the same level on UI are tangled. I would rather have this loadScenario checkbox in the root table of NewGameScreen and re-render two dependent tables (playerPickerTable and newGameOptionsTable) on change.

Also for the moment I have added flag as value to MapParameter class, don't know if it is a good solution?

**Comment by yairm210** [comment]
Hm, I see what you mean.
I think im retrospect that I went at it from a wedding point of view, that we should start small, with the most minimum of functionality.
That means putting off a lot of the "what if" questions for later, and focusing on getting a single scenario loaded for now.
I do think that the scenario information should be at the newGameScreen level, so probably a loadedScenario: Scenario=null to start with
When loading a scenario we can change the existing map and game parameters to reflect this
How do we load a scenario? Not sure, for the initial part it could be a popup with a list of buttons, click on a button

**Comment by alkorolyov** [comment]
Ok, I agree.

Also I have a proposal on organizing the work. I am eager to start coding but most of the time don't really understand where to start from :) I believe with time I will get acquainted with all classes and dependencies but for the moment I can implement some simple, well defined steps. Could you prepare like a set of simple tasks for me, like for junior-junior level :) As soon I will finish the first one - you can review it, I will fix it and we can move on to the next one. I hope with time my lvl will grow so I can tackle more complex steps). 

As for the current task:

1. The first step could be to create a new class Scenario, containing TileMap, GameParameters and string name. Should it be in unciv.logic.map package?
2. Then we should add it to NewGameSceen class -  loadedScenario: Scenario=null.
3. Add "Load Scenario" checkbox at  NewGameScreen level.
4. Add onChange logic to lock or hide? elements on playerPickerTable and newGameOptionsTable tables.

What do you think about this task? Feel free to change or comment it)

**Comment by yairm210** [comment]
Looks fine, but please add a boolean that sets these to false somewhere (including the ability to add units in the map editor) since this is still under construction

**Comment by yairm210** [comment]
I think the minimum functionality is actually comprised of 3 parts: Background for saving/loading scenario files, Creating a scenario file, and loading it.

*Background*
1. Create a new class Scenario, containing TileMap, GameParameters and string name (doesn't really matter where, we can move it around later)
2. Create SaveScenario and LoadScenario functions in MapSaver (save to/ load from scenario name)

*Creating*
We can start by creating a scenario with no special units at all for the first test, 
and so:
1. Add a "Create Scenario" button in map editor menu, which opens a popup containing a game settings table when clicked
2. Create a "Save Scenario" button in the popup, which when clicked creates a Scenario using the current map and the game settings from the table, and saves them using MapSaver.SaveScenario() (can have a default name of "MyFirstScenario" or something, to start with)

*Loading*
1. Add a Scenario parameter to NewGameSceen class - loadedScenario: Scenario=null.
2. Add a Load Scenario checkbox in the NewGameScreen UI, when clicked loads the MyFirstScenario using MapSaver.LoadScenario() and sets the MapSettings and GameSettings in the screen accordingly

**Comment by yairm210** [comment]
This should get us the minimal functionality for "Crete and save a scenario"

**Comment by alkorolyov** [comment]
Could you have a look on first step "Background"?

Also just a few ideas. As I see now we are planning to have a separate files for scenarios and maps. In the original Civ 5 they have scenario information included in the map file. I am OK with both versions, just wanted to know your opinion like what would you choose?

**Comment by yairm210** [comment]
It looks like you've copied the GameParametersTable and PlayerPickerTable as-is
Instead, it is better to use the existing classes, and change them minimally to suit both usages if changes are required

**Comment by alkorolyov** [comment]
I see, sure, I will try to not to copy the existing code. Should I keep the original classes (`GameOptionsTable `and `PlayerPickerTable`) in the "newgame" package? 

While working on this I got a little confused about differences between classes: `Player`, `Nation `and `Civilization`. Could you give me a brief explanation what are their main usages and on which game stage?

Also I would like to change a little bit a logic of Scenario, make a little bit closer to original Civ 5. Currently I have tileMap in both scenario and map files. While loading it could be confusing which tileMap data should we use and from which file. I want to switch to single file approach, like in original Civ 5. Each map file could have additional scenario information - units, starting locations, game parameters. `Load scenario` checkbox only chooses whether to use it while creating new game.

**Comment by yairm210** [comment]
*Nation* is the basic nation info, like "France". This determines name, colors, unique units and buildings etc.
*Civilization* is a specific civ, in a specific game. A civ has certain cities on the map, a certain level of tech, etc. Civilizations are what changes through the various turns - Nations remain constant metadata,
So if we have 2 games with a France civilization, they will be different civilizations (different cities, units etc) but of the same Nation.

Player is what determines who makes the moves for a specific Civilization. Basically divided into Human and AI, and the Human behaves slightly differently in Hotseat and Multiplayer.

**Comment by alkorolyov** [comment]
After few days of painful coding I finally got the first working version (at least on my computer). It is quite ugly and I will definitely rewrite some part of it. There are few main problems that I faced.
1) Personally I don't know how to make universal use of two classes: GameOptionsTable and PlayerPickerTable. They both are used during NewGame creation (NewGameScreen) and in the MapEditor (MapEditorScreen). And those two root screen classes have different parents: CameraStageBaseScreen for MapEditorScreen, and more specific PickerScreen for NewGameScreen. I wanted to create an abstract class, which have methods for both classes, however it works kind of ugly.

P.S. thank you for the class info, it saved me a few hours of figuring out by myself.

**Comment by alkorolyov** [comment]
Hi @yairm210 ,

Could please take a look on this PL, because I have run to conflict, that I cannot resolve.
To sum up - basic load/save scenario works. We just need to fix ui issues. 

Looking forward for your comment :)

**Comment by yairm210** [comment]
Okay, let's try this out! Ya only live once!

**Comment by yairm210** [comment]
I can't seem to save a scenario

```
"C:\Program Files\Android\Android Studio\jre\bin\java.exe" "-javaagent:C:\Program Files\Android\Android Studio\lib\idea_rt.jar=49788:C:\Program Files\Android\Android Studio\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Android\Android Studio\jre\jre\lib\charsets.jar;C:\Program Files\Android\Android Studio\jre\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Android\Android Studio\jre\jre\lib\ext\cldrdata.jar;C:\Program Files\Android\Android Studio\jre\jre\lib\ext\dnsns.jar;C:\Program Files\Android\Android Studio\jre\jre\lib\ext\jaccess.jar;C:\Program Files\Android\Android Studio\jre\jre\lib\ext\localedata.jar;C:\Program Files\Android\Android Studio\jre\jre\lib\ext\nashorn.jar;C:\Program Files\Android\Android Studio\jre\jre\lib\ext\sunec.jar;C:\Program Files\Android\Android Studio\jre\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Android\Android Studio\jre\jre\lib\ext\sunmscapi.jar;C:\Program Files\Android\Android Studio\jre\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Android\Android Studio\jre\jre\lib\ext\zipfs.jar;C:\Program Files\Android\Android Studio\jre\jre\lib\jce.jar;C:\Program Files\Android\Android Studio\jre\jre\lib\jsse.jar;C:\Program Files\Android\Android Studio\jre\jre\lib\management-agent.jar;C:\Program Files\Android\Android Studio\jre\jre\lib\resources.jar;C:\Program Files\Android\Android Studio\jre\jre\lib\rt.jar;C:\Users\LENOVO\Documents\UnCiv\desktop\build\classes\kotlin\main;C:\Users\LENOVO\Documents\UnCiv\core\build\classes\kotlin\main;C:\Users\LENOVO\.gradle\caches\modules-2\files-2.1\com.badlogicgames.gdx\gdx-tools\1.9.10\67524f012868e0cff57531b5bfda2781d00c6b1f\gdx-tools-1.9.10.jar;C:\Users\LENOVO\.gradle\caches\modules-2\files-2.1\com.badlogicgames.gdx\gdx-backend-lwjgl\1.9.10\8f88abd43500d94c486d25f04d642318da72773a\gdx-backend-lwjgl-1.9.10.jar;C:\Users\LENOVO\.gradle\caches\modules-2\files-2.1\com.badlogicgames.gdx\gdx-platform\1.9.10\1907b49f8363dd1ee37d273854a9cc3c741a6e66\gdx-platform-1.9.10-natives-desktop.jar;C:\Users\LENOVO\.gradle\caches\modules-2\files-2.1\io.ktor\ktor-server-netty\1.3.2\d33f460818aaa36265dd6c79cea97b5f57b69109\ktor-server-netty-1.3.2.jar;C:\Users\LENOVO\.gradle\caches\modules-2\files-2.1\io.ktor\ktor-server-host-common\1.3.2\a7329464ff1a10d749855ffedf9b836d7a865a8f\ktor-server-host-common-1.3.2.jar;C:\Users\LENOVO\.gradle\caches\modules-2\files-2.1\io.ktor\ktor-server-core\1.3.2\20a23d66a0c57cb54fd49fae7594c6c64a83d37e\ktor-server-core-1.3.2.jar;C:\Users\LENOVO\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib-jdk8\1.3.70\c706d9a12aa043400daacbb15b61ba662a1eb9a9\kotlin-stdlib-jdk8-1.3.70.jar;C:\Users\LENOVO\.gradle\caches\modules-2\files-2.1\io.ktor\ktor-http-cio-jvm\1.3.2\aeb203001dc089ec3ccc5f5c13ba9bf5ecf3f795\ktor-http-cio-jvm-1.3.2.jar;C:\Users\LENOVO\.gradle\caches\modules-2\files-2.1\io.ktor\ktor-http-jvm\1.3.2\ad2b30b1918b6d7363d2f494d17820398525c777\ktor-http-jvm-1.3.2.jar;C:\Users\LENOVO\.gradle\caches\modules-2\files-2.1\io.ktor\ktor-network\1.3.2\13c7730588ca7449ad7711f9f4d65726bdf9660c\ktor-network-1.3.2.jar;C:\Users\LENOVO\.gradle\caches\modules-2\files-2.1\io.ktor\ktor-utils-jvm\1.3.2\ce8899d0039e9dbd371832d479bd4657c9465ee4\ktor-utils-jvm-1.3.2.jar;C:\Users\LENOVO\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib-jdk7\1.3.70\95aee922bc2a0fff3b7bfa1b6503ff0afe38264a\kotlin-stdlib-jdk7-1.3.70.jar;C:\Users\LENOVO\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-reflect\1.3.70\75a87c4141e55abbaf418b8495550ced8894045d\kotlin-reflect-1.3.70.jar;C:\Users\LENOVO\.gradle\caches\modules-2\files-2.1\io.ktor\ktor-io-jvm\1.3.2\356f730484a2057d8717ea09b6eb1fe70bb0cebf\ktor-io-jvm-1.3.2.jar;C:\Users\LENOVO\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib\1.3.71\898273189ad22779da6bed88ded39b14cb5fd432\kotlin-stdlib-1.3.71.jar;C:\Users\LENOVO\.gradle\caches\modules-2\files-2.1\com.github.MinnDevelopment\java-discord-rpc\v2.0.1\48dd138e04ad017287eb15d358c1e7d06d55c6e7\java-discord-rpc-v2.0.1.jar;C:\Users\LENOVO\.gradle\caches\modules-2\files-2.1\com.badlogicgames.gdx\gdx-backend-headless\1.9.10\d357526e6bb3d36b01b4f833ab42588e5285d487\gdx-backend-headless-1.9.10.jar;C:\Users\LENOVO\.gradle\caches\modules-2\files-2.1\com.badlogicgames.gdx\gdx-freetype\1.9.10\8853e4f08589a9feb4b851187909cfde8810e491\gdx-freetype-1.9.10.jar;C:\Users\LENOVO\.gradle\caches\modules-2\files-2.1\com.badlogicgames.gdx\gdx\1.9.10\79d9ad27bd5e3eb18c9ade61d3a27d7237695d53\gdx-1.9.10.jar;C:\Users\LENOVO\.gradle\caches\modules-2\files-2.1\org.lwjgl.lwjgl\lwjgl_util\2.9.3\751f06b62424da056954c67288fd5c494431e350\lwjgl_util-2.9.3.jar;C:\Users\LENOVO\.gradle\caches\modules-2\files-2.1\org.lwjgl.lwjgl\lwjgl\2.9.3\3df168ac74e4a8c96562cdff24ad352e255bf89c\lwjgl-2.9.3.jar;C:\Users\LENOVO\.gradle\caches\modules-2\files-2.1\com.badlogicgames.jlayer\jlayer\1.0.1-gdx\7cca83cec5c1b2f011362f4d85aabd71a73b049d\jlayer-1.0.1-gdx.jar;C:\Users\LENOVO\.gradle\caches\modules-2\files-2.1\org.jcraft\jorbis\0.0.17\8872d22b293e8f5d7d56ff92be966e6dc28ebdc6\jorbis-0.0.17.jar;C:\Users\LENOVO\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlinx\kotlinx-coroutines-jdk8\1.3.4\316bb893fe9188d1a39b67098f1d8059b1fde3f8\kotlinx-coroutines-jdk8-1.3.4.jar;C:\Users\LENOVO\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlinx\kotlinx-coroutines-core\1.3.4\21598c7ceabbcafb953cd151cd5ad44615a253c0\kotlinx-coroutines-core-1.3.4.jar;C:\Users\LENOVO\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlinx\kotlinx-coroutines-core-common\1.3.4\c7911e1b4855843c0f802ac844cdd19a2b80acb4\kotlinx-coroutines-core-common-1.3.4.jar;C:\Users\LENOVO\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib-common\1.3.71\e71c3fef58e26affeb03d675e91fd8abdd44aa7b\kotlin-stdlib-common-1.3.71.jar;C:\Users\LENOVO\.gradle\caches\modules-2\files-2.1\org.jetbrains\annotations\13.0\919f0dfe192fb4e063e7dacadee7f8bb9a2672a9\annotations-13.0.jar;C:\Users\LENOVO\.gradle\caches\modules-2\files-2.1\net.java.dev.jna\jna\4.4.0\cb208278274bf12ebdb56c61bd7407e6f774d65a\jna-4.4.0.jar;C:\Users\LENOVO\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlinx\atomicfu\0.14.2\b90bce17609cf16bbcf45bfa304fb42ee05ab999\atomicfu-0.14.2.jar;C:\Users\LENOVO\.gradle\caches\modules-2\files-2.1\org.slf4j\slf4j-api\1.7.30\b5a4b6d16ab13e34a88fae84c35cd5d68cac922c\slf4j-api-1.7.30.jar;C:\Users\LENOVO\.gradle\caches\modules-2\files-2.1\io.netty\netty-codec-http2\4.1.44.Final\84fd396e814af4278595e50f8c5089056771d19a\netty-codec-http2-4.1.44.Final.jar;C:\Users\LENOVO\.gradle\caches\modules-2\files-2.1\org.eclipse.jetty.alpn\alpn-api\1.1.3.v20160715\a1bf3a937f91b4c953acd13e8c9552347adc2198\alpn-api-1.1.3.v20160715.jar;C:\Users\LENOVO\.gradle\caches\modules-2\files-2.1\io.netty\netty-transport-native-kqueue\4.1.44.Final\89f995fa15882c726f63ed749b325260c1508972\netty-transport-native-kqueue-4.1.44.Final.jar;C:\Users\LENOVO\.gradle\caches\modules-2\files-2.1\io.netty\netty-transport-native-epoll\4.1.44.Final\c0641bdf67503ce5d83b4d055421ac4bd8e0f218\netty-transport-native-epoll-4.1.44.Final.jar;C:\Users\LENOVO\.gradle\caches\modules-2\files-2.1\org.lwjgl.lwjgl\lwjgl-platform\2.9.3\fbc2afb3e288578e9942578decb6291a490549a0\lwjgl-platform-2.9.3-natives-windows.jar;C:\Users\LENOVO\.gradle\caches\modules-2\files-2.1\org.lwjgl.lwjgl\lwjgl-platform\2.9.3\b1eafe80093381c56415731e1d64279e6140bcd0\lwjgl-platform-2.9.3-natives-linux.jar;C:\Users\LENOVO\.gradle\caches\modules-2\files-2.1\org.lwjgl.lwjgl\lwjgl-platform\2.9.3\6686cf6ddaa20b4290aa6599a09bc0d17369be05\lwjgl-platform-2.9.3-natives-osx.jar;C:\Users\LENOVO\.gradle\caches\modules-2\files-2.1\net.java.jinput\jinput\2.0.5\39c7796b469a600f72380316f6b1f11db6c2c7c4\jinput-2.0.5.jar;C:\Users\LENOVO\.gradle\caches\modules-2\files-2.1\io.netty\netty-codec-http\4.1.44.Final\6135c2b3a01e0e1ab4bd8bba89bdefe2d2b24a4c\netty-codec-http-4.1.44.Final.jar;C:\Users\LENOVO\.gradle\caches\modules-2\files-2.1\io.netty\netty-handler\4.1.44.Final\c82cfba4ff7b79f3e7828c4ccbfebb756603cc8c\netty-handler-4.1.44.Final.jar;C:\Users\LENOVO\.gradle\caches\modules-2\files-2.1\io.netty\netty-codec\4.1.44.Final\4d759f5015a240a0635c59ce7acced9a364836d\netty-codec-4.1.44.Final.jar;C:\Users\LENOVO\.gradle\caches\modules-2\files-2.1\io.netty\netty-transport-native-unix-common\4.1.44.Final\1af95c8d95aa55038d889944f709fa75efa94094\netty-transport-native-unix-common-4.1.44.Final.jar;C:\Users\LENOVO\.gradle\caches\modules-2\files-2.1\io.netty\netty-transport\4.1.44.Final\18a0ce8be8ca639982276efefc0a5604a6523d80\netty-transport-4.1.44.Final.jar;C:\Users\LENOVO\.gradle\caches\modules-2\files-2.1\io.netty\netty-buffer\4.1.44.Final\8b2add255e68d0fcb8ccdfaf07399980d3be840f\netty-buffer-4.1.44.Final.jar;C:\Users\LENOVO\.gradle\caches\modules-2\files-2.1\io.netty\netty-resolver\4.1.44.Final\c644d209302d3fc7770dc0ca257e9f6fe8b38e47\netty-resolver-4.1.44.Final.jar;C:\Users\LENOVO\.gradle\caches\modules-2\files-2.1\io.netty\netty-common\4.1.44.Final\cd09d9093791482acdcbe8e39ad6fdf62ea3ab7d\netty-common-4.1.44.Final.jar;C:\Users\LENOVO\.gradle\caches\modules-2\files-2.1\net.java.jutils\jutils\1.0.0\e12fe1fda814bd348c1579329c86943d2cd3c6a6\jutils-1.0.0.jar;C:\Users\LENOVO\.gradle\caches\modules-2\files-2.1\com.typesafe\config\1.3.1\2cf7a6cc79732e3bdf1647d7404279900ca63eb0\config-1.3.1.jar;C:\Users\LENOVO\.gradle\caches\modules-2\files-2.1\club.minnced\discord-rpc-release\v3.3.0\df54530ca097f94abc9a28d3b5153d8828a3f5b5\discord-rpc-release-v3.3.0.jar;C:\Users\LENOVO\.gradle\caches\modules-2\files-2.1\net.java.jinput\jinput-platform\2.0.5\7ff832a6eb9ab6a767f1ade2b548092d0fa64795\jinput-platform-2.0.5-natives-linux.jar;C:\Users\LENOVO\.gradle\caches\modules-2\files-2.1\net.java.jinput\jinput-platform\2.0.5\385ee093e01f587f30ee1c8a2ee7d408fd732e16\jinput-platform-2.0.5-natives-windows.jar;C:\Users\LENOVO\.gradle\caches\modules-2\files-2.1\net.java.jinput\jinput-platform\2.0.5\53f9c919f34d2ca9de8c51fc4e1e8282029a9232\jinput-platform-2.0.5-natives-osx.jar;C:\Users\LENOVO\Documents\UnCiv\desktop\build\libs\desktop-1.0.1.jar" com.unciv.app.desktop.DesktopLauncher
Packing textures - 1824ms
Loading game basics - 132ms
Loading game basics - 20ms
Mod loaded successfully: Civ IV Scenario
Loading game basics - 32ms
Mod loaded successfully: Scenario
Loading translation file for English - 55ms
Loading percent complete of languages - 3ms
RNG seeded with 1592079193512
Natural Wonders for this game: [Barringer Crater]
RNG seeded with 1592079660645
Natural Wonders for this game: [Cerro de Potosi]
RNG seeded with 1592079663381
Natural Wonders for this game: [Krakatoa, Grand Mesa]
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: Error writing file: scenarios\Test (Local)
	at com.badlogic.gdx.files.FileHandle.writeString(FileHandle.java:383)
	at com.badlogic.gdx.files.FileHandle.writeString(FileHandle.java:369)
	at com.unciv.logic.MapSaver.saveScenario(MapSaver.kt:23)
	at com.unciv.ui.mapeditor.MapEditorMenuPopup$8$1.invoke(MapEditorMenuPopup.kt:144)
	at com.unciv.ui.mapeditor.MapEditorMenuPopup$8$1.invoke(MapEditorMenuPopup.kt:22)
	at com.unciv.ui.utils.CameraStageBaseScreenKt$onClick$1.invoke(CameraStageBaseScreen.kt:150)
	at com.unciv.ui.utils.CameraStageBaseScreenKt$onClick$1.invoke(CameraStageBaseScreen.kt)
	at com.unciv.ui.utils.CameraStageBaseScreenKt$onClickEvent$1.clicked(CameraStageBaseScreen.kt:143)
	at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:88)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:59)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:351)
	at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:360)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:221)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:128)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Error writing file: scenarios\Test (Local)
	at com.badlogic.gdx.files.FileHandle.writer(FileHandle.java:360)
	at com.badlogic.gdx.files.FileHandle.writeString(FileHandle.java:380)
	... 13 more
Caused by: java.io.FileNotFoundException: C:\Users\LENOVO\Documents\UnCiv\android\assets\scenarios\Test (The system cannot find the path specified)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at com.badlogic.gdx.files.FileHandle.writer(FileHandle.java:352)
	... 14 more

Process finished with exit code 0

```

**Comment by alkorolyov** [comment]
"Okay, let's try this out! Ya only live once!"
I like your attitude! =))

Could you please describe how you end up getting this error?
I have tried saving scenarios on both custom and generated files, and it seemed to work correctly.
Could it be because the folder "scenarios" need to be created? However it worked for me even if I deleted it.

**Comment by yairm210** [comment]
I'm running this on Desktop, so if you're running this on Android maybe that's the difference?

**Pull request merged**
