### PR TITLE
Fix promotions being unavailable when it can be reached a slower way

### PR DESCRIPTION
**Pull request by SeventhM**
Previously if a promotion could require 2 promotions from branch A but 1 branch B and the branch B also lead to an earlier promotion from branch A, it erroneously consider that a loop. Solved by copying the logic from the ruleset Validator (going child up to parent, rather than parent to child and passing in the hashset rather than using a global one)

### CODE REVIEW

**Comment by yairm210** [comment]
Can you write a test for this? This is exactly the kind of thing where thinking through it is harder than writing a test to ensure correctness :)

**Comment by SeventhM** [comment]
Sure. While I'm at it, I'll add in a few other things I'm going to PR for anyways

**Comment by SeventhM** [comment]
Actually, double checking how this works... I don't know if I can make a test for this that well. I can look into it further tomorrow, but this all uses an internal class that edits privately. I can remove it from being an internal class, but it will tank far more looking into before I add in the test for this specifically

**Comment by yairm210** [comment]
@SeventhM Are you ready to merge this? Or do you want to keep working on it?

**Review by yairm210 — APPROVED** [review]

**Comment by yairm210** [comment]
Oh I forgot to add this to the previous release :|
Welp

**Pull request merged**
