### PR TITLE
Mod loader resilience

### PR DESCRIPTION
**Pull request by rh-github-2015**
#2200 -> Exclude any mod folder starting with a dot, and in packImages() I just duplicated the Images subfolder existence check that was already done for the main images to the mods loop.

### CODE REVIEW

**Comment by rh-github-2015** [comment]
> So in other words… You need testing from me?
Yes - but how?
The alternative: I do the testing. But for that I would need an _exact_ replica of your mods folder.

**Comment by Iver88** [comment]
I will test it deeply and give you know. And send you folder as well.

**Comment by rh-github-2015** [comment]
Made a savegame saved with a mod that's currently not loaded show an explicit user message should he/she try to load it anyway. Didn't touch the description bottom left you get when selecting it for now.

Also catches the 'mod building has no cost but uses a requiredTech from the base ruleset' problem and shows it explicitly on the console. Closes the cost=0 w/o requiredTech loophole.

Implementation note: I hope that Exception wrapper subclass with no other functionality than being recognizable later is the right choice - I tried other ways to recognize 'that's ours' later and they either broke (e.g. using NoSuchElementException) or were ugly pattern matching.

I should have included francais y espanol as I have set as rule for myself, too tired.

**Comment by rh-github-2015** [comment]
Sorry - after pulling 3.6.10 that building cost block seems different from what I remember seeing before changing it for commit ["Clearer message for a specific mod error..."](https://github.com/yairm210/Unciv/pull/2211/commits/fbb315a51c932c645fce985b26a1c4274d8326f4). My comment elsewhere about how explicitly stating cost in a mod building referencing a base tech requirement would fix a mod - applied to what I started with and to my commit here, but not to 3.6.10. 3.6.10 won't load a mod containing buildings which reference a base game tech as required at all.

I just went over the commit diff and it seems OK, but please double-check.

**Comment by Iver88** [comment]
You are king. I have to test .DS_Store problem as I promised.

**Comment by yairm210** [comment]
This looks good to me!
Tell me when you think it's ready and I'll merge it!

**Comment by rh-github-2015** [comment]
I used this branch as learning scenario, bringing its 'base' from 3.6.9 to 3.6.10 - the push dialog listed 666 commits at least (actually probably less than 30) but the comit list here looks clean. Instead it deleted my mods folder I had no backup of and which was both marked as excluded in the IDE and written into .gitignore ...

It was ready when I changed it from a draft to a normal pull request.

**Comment by Iver88** [comment]
Actual game folder with .DS_Store for testing of your branch - https://mab.to/yBr7GiAzP

**Comment by Iver88** [comment]
I did some changes in mod and can confirm, it works…

Snímek obrazovky 2020-03-22 v 23 06 58

**Pull request merged**
