### PR TITLE
updated Caravel.png, resolves #5317

### LINKED ISSUE #5317: Is this Caravel?
IMG_20210926_012222
Caravela_de_armada_of_Joao_Serrao

### PR DESCRIPTION
**Pull request by touhidurrr**
Portuguese Caravel by Zack McCune from NounProject.com
https://thenounproject.com/icon/portuguese-caravel-1626301/

### CODE REVIEW

**Comment by SomeTroglodyte** [comment]
Needs an update to credits.md. Current line 89 `* [Sail boat](https://thenounproject.com/term/sail-boat/5292/) By Alessandro Suraci for Caravel` -> `* [Portuguese Caravel](https://thenounproject.com/icon/portuguese-caravel-1626301/) by Zack McCune for Caravel`. Otherwise :+1:

**Review by SomeTroglodyte — APPROVED** [review]

**Comment by touhidurrr** [comment]
@SomeTroglodyte ok?

**Comment by SomeTroglodyte** [comment]
```
SomeTroglodyte approved these changes 1 minute ago
touhidurrr commented 44 seconds ago
@SomeTroglodyte ok?
```
:rofl:

**Comment by touhidurrr** [comment]
> ```
> SomeTroglodyte approved these changes 1 minute ago
> touhidurrr commented 44 seconds ago
> @SomeTroglodyte ok?
> ```
> 
> 🤣

UI lag 😕

**Pull request merged**
