### PR TITLE
Fix bug worker will not replace improvement to enable strategy resour…

### PR DESCRIPTION
**Pull request by janarvid**
…ces #9328

- Created a unit test to reproduce the bug
- Fixed the bug using the suggested fix in the issue
- Verified that the test worked
- All other tests also ran successfully

### CODE REVIEW

**Comment by janarvid** [comment]
Thanks for checking @SomeTroglodyte, I'll comment your suggestions and fix later.

**Comment by janarvid** [comment]
Hi, I've now updated the PR to make the test logic more clear and have also added some comments.

1. Yes, you're right about the ! precedence.  I've now removed the parenthesis.
2. I've tried to make the test logic more clear and have also made some comments.
3. Well ... 'sut' is an abbreviation for 'System Under Test' and is commonly used in unit tests.  Since this is not clear for everyone I've changed it to 'workerAutomation'
4. Yes, completely agree with you on the code duplicate problem, I didn't want to make too many changes in my first PR.  I guess many of these functions like 'createCity' and 'addUnit' are/will be used in many tests.  Also objects like ruleset, gameInfo and uncivGame are used in many tests.  I think the best way to do this is to create a new base test class, put these and others in it and then let tests extend this new base class.  But as you say this is for another PR. 
5. Fixed

Hopefully this PR will pass now ...

**Comment by yairm210** [comment]
Looks good, I'm assuming that since Trog looked at this and had no further improvements that it's OK with him as well :)

**Comment by yairm210** [comment]
Had I seen a problem I would have said, but I don't

**Comment by yairm210** [comment]
That's an interesting question - did greeks place coins on eyes, or on eye *sockets*? Was it Obol per Eyeball?

**Pull request merged**
