### PR TITLE
WIP Construction Queue

### PR DESCRIPTION
**Pull request by r3versi**
* Added constructionQueue in addition to currentConstruction: if currentConstruction is done, next construction from Queue is started; if Queue is empty invoke ConstructionAutomation
* Queue utility methods: add, remove, higher prio, lower prio
* Icons to move constructions in queue
* Top left city stats moved to top right panel
* Added current construction and queue construction to top left
* Extended selected construction (containing description) moved to bottom right, it is now displayed alternatively to selected tile
* Max queue size, cannot change queue in puppet city or in other player turn
* Queue and current construction reset on puppeting city

@yairm210 This should be mergeable to the previous commit.

### CODE REVIEW

**Comment by yairm210** [comment]
image

I feel there is Too Much Going On in this screen
But I do think that city queue is important for gameplay... =/

Also, if you remove everything from the queue, you get Nothing
But if you then add something to the queue you get...
image

**Comment by yairm210** [comment]
Actually, probably better to have 2 modes - a "Construction management" mods and a "Population management" mode
Automatically, you should go into Construction Management, since that's the reason you open the city screen 90% of the time
The city stats should be as it was, I think, and it should be the only thing common to both modes - since that's how the population management affects the results of the construction management

**Comment by r3versi** [comment]
If I understood correctly what you meant, the following is how the city screen appears after the changes I made. I had to hack something in `CityInfoTable` to fill the "population" table with content to test the idea, sorry.
 
ui1
ui2

**Comment by yairm210** [comment]
You know I spent about half an hour yesterday trying to think about how to display stuff and this looks better than everything I thought of
I would switch the stats and Scrolls positions but this looks good
We'll need to change some tutorial task text and make sure this is noob-friendly but this looks great!

**Comment by yairm210** [comment]
But tbh if there are small changes to positioning we can do them later.
What we need now is a workable, noob-friendly screen with queuable constructions

**Pull request merged**
