### PR TITLE
New music player

### LINKED ISSUE #2232: Music system improvements
1. Download more royalty free music
2. Shuffle music
3. Support for music from mods placed in "music" subfolder (should be great for traditional soundtrack from nation mod for example)

### PR DESCRIPTION
**Pull request by rh-github-2015**
Brewing for a while, @Iver88 has co-tested, and now re-based on 3.6.15.
Resolves #2232 partly. Some planning for expanded music downloader are done, later, separately.

To properly test it might be easiest to supply a copy of my music folder, but I'm hesitant even though everything is from civ-related open sources... I'd have to compile a precise credits file.

### CODE REVIEW

**Comment by JackRainy** [comment]
Wow! Picking the soundtrack according to the game events? It seems to be the great idea!

Please, make sure not to cause the power consumption increase for those who are gaming without music and sounds - see my PR #2128 for details.

**Comment by rh-github-2015** [comment]
I have seen and replaced code from #2128 - and I think I've respected its intent even if the implementation is quite different. Volume zero will shut down the engine, including watchdog timer and 'com.badlogic.gdx.audio.Music' instances. I took care that the watchdog is as lightweight as possible - worst case it calls setVolume and isPlaying 20 times per second. Both seem relatively lightweight to me. chooseTrack() can be expensive, but that runs relatively rarely. Its file access could be reduced significantly, yes, by caching what files exist, but this way it is resilient against changes in the music folder while the game is running. Symlink a file in - it will have a chance to be picked. Empty out the music folder (again while the game is running) - no problem. On Linux (which surely includes Android) it will finish playing the curent track (the OS keeps the inode internally until all handles are released) even though it's gone, on Win it probably won't let you delete the playing file in the first place. 

But actual testing on a real device - that I didn't do. Volunteers?

**Comment by Iver88** [comment]
I can test it on Mac and Windows.

**Comment by lishaoxia1985** [comment]
do you think about using some net player? 
for example(maybe  it is only used in China): http://listen1.github.io/listen1/
if we use this method even we don't need download the music file. 
the second method is that we can customise the link to music file. we can get the link from sniffing the music website.

**Comment by rh-github-2015** [comment]
Outdated.

**Pull request closed without merging**
