### PR TITLE
Newgame screens and mods

### PR DESCRIPTION
**Pull request by rh-github-2015**
Replacement for #2231, screenshots there still apply

### CODE REVIEW

**Comment by Iver88** [comment]
I love auto-assignment of mod civs.

**Comment by Iver88** [comment]
When nation is selected, I open list of nations and change my mind, I have to scroll down, find same nation which is selected already and select it again. What about ESC and click outside list feature?

**Comment by rh-github-2015** [comment]
> When nation is selected, I open list of nations and change my mind, I have to scroll down, find same nation which is selected already and select it again. What about ESC and click outside list feature?

No Idea yet how to do keys, or 'click outside'. All the 'outside' actually retains its functionality, doesn't it? At least other overlays are like that... Maybe one can abuse that?

**Comment by Iver88** [comment]
I think this is task for #2233 mainly. Right now, actual selected civ is as first so I tested last build, and It's not big problem anymore. You can just click on first civ in list and no need for scrolling down.

**Pull request merged**
