### PR TITLE
Update translation and Android studio to 4.1.2. Fix when Trade Gold = 0 it also shows in offer.

### PR DESCRIPTION
**Pull request by lishaoxia1985**
1. Now android studio gradle plugin is update to 4.1.2.
2. Update translation.
3. Fix when Trade Gold = 0 it also shows in offer. Also make some method being private.

### CODE REVIEW

**Comment by lishaoxia1985** [comment]
@yairm210 the setting "Order trade offers by amount" should be deleted, I test it:
1. when you touch the offer item in list, if the number of item changes, the order of the offer list may also change, it's very ridiculous.
2. it's only used in other civ offer list, not for mine.

**Comment by yairm210** [comment]
- Good catch on the image
- Don't update translation files as this can lead to conflicts
- Some of the 'unused' texts are actually useful, like the "experimental"

**Comment by lishaoxia1985** [comment]
@yairm210 The promotion "Siege I" "Siege II" and "Siege III" also use the picture **_Siege.png_**, if you rename this picture, their icon will not show normally. So I edit _**UnitPromotions.json**_ and _**Units.json**_ in the lastest branch.

**Comment by lishaoxia1985** [comment]
Now I delete commit about Siege.

**Comment by yairm210** [comment]
Just open a new branch for the gold trade fix I think, it'll be easier than getting this pr neck to mergability

**Pull request closed without merging**
