### PR TITLE
Fixed Bosnian

### PR DESCRIPTION
**Pull request by SomeTroglodyte**
See commits individually
Closes #10557 

image

... added trikkyness:
- trailing blanks disappeared
- lines out of sync by one around the `#Trades` comment - manually fixed

... Well, do we want 3%?

### CODE REVIEW

**Comment by twinflac** [comment]
> By the way, should have treated #6478 similarly back then - maybe #10422 too. And Belarusian sits at still 2% (#8801), less than this. Come on, @twinflac , you can do it?
I'm so sorry, i torget it, i will continue working on translation.

**Comment by yairm210** [comment]
@Ivoluka you can now continue working in Bosnian.properties

**Comment by Ivoluka** [comment]
There is alot of words to translate but that will take for 3 hours and I am not happy with that, perhaps no one in the history of mankind has ever passed that, so does me too.

**Comment by Ivoluka** [comment]
Bosnian has 4 million people and perhaps it's 13% people playing this game.

**Comment by Ivoluka** [comment]
Is anyone working for Bosnian language project?

**Comment by Ivoluka** [comment]
My dad wants to play it but he doesn't know English or any other languages. He speaks south slavic to the coast of the adriatic sea.

**Comment by Ivoluka** [comment]
And also, tell me when it's updated added Bosnian language.

**Comment by Ivoluka** [comment]
Well, I started but the project stopped because I have no one to help me like someone beside my room like my friend, but however, I don't have friends, so don't give me wrong.

**Comment by Ivoluka** [comment]
That will at least waste a time on cheerless as if you done it close to finish and you accidentally click button and unsafe the project,

**Comment by Ivoluka** [comment]
So yeah I don't want to waste a cheerless time.

**Comment by Ivoluka** [comment]
Is anyone working for the Bosnian project? I see there is Bosnian flag and perhaps a code, which means that I think that you guys are working.

**Comment by Ivoluka** [comment]
Then who is translating language? Me or you or someone?

**Pull request merged**
