### PR TITLE
Suggested file names for game and map saving internationalized

### PR DESCRIPTION
**Pull request by SomeTroglodyte**
Silly, but some might like it.

### CODE REVIEW

**Comment by yairm210** [comment]
No, I want people to name their maps =/
I'm against having an internationalized name for a name I don't want

**Comment by SomeTroglodyte** [comment]
Agreed. In that case - other PR ensures empty textbox behaves - initialize to blank instead?

**Comment by yairm210** [comment]
Sure

**Comment by SomeTroglodyte** [comment]
OK, #2393 tests good - seems nothing breaks when a map's name is empty...
What about game saves - I always accept the default name, but then again I don't actually play using my native language either.

**Pull request closed without merging**
