### PR TITLE
Added uniques related to improvements

### PR DESCRIPTION
**Pull request by xlenstra**
More specifically, adds a unique for consuming the builder when finishing building something and for the 'take over adjacent tiles' ability of citadels.
Might have conflicts with whatever @SomeTroglodyte is doing with #6576. I'm fine with waiting for that PR to be merged and changing around it (should only be a renaming of a unique).

Part 1 of me going over the way improvements are build and fixing a few simple things (with the end goal of making it more intuitive and moddable, so that for example https://github.com/yairm210/Unciv/pull/4889#issuecomment-900612942 doesn't happen anymore. Additionally, I want to make it finally possible for multiple improvements to improve the same resource, allowing both oil wells and offshore platforms to improve oil). I'm planning on adding these other changes to this same PR, but this is technically fine to be merged as-is.

### CODE REVIEW

**Comment by SomeTroglodyte** [comment]
"Consumes builder when build": "built"
I chose to make the citadel unique text identical to the old civilopediaText, so xlators wouldn't need to re-translate - it _is_ clearer. And the civilopediaText is made obsolete by the unique. But I like your enum name better.
Indestructible deprecated becomes Indestructable?
Units that are _not_ great people but can place something and get consumed - without triggering Halicarnassus - should be possible. This reverts that option (UnitActions.683).

**Comment by xlenstra** [comment]
Thanks for the comments!
> "Consumes builder when build": "built" 

Fixed, for some reason I always mess this conjuagtion up
> I chose to make the citadel unique text identical to the old civilopediaText, so xlators wouldn't need to re-translate - it _is_ clearer. 

I try to keep them relatively short, but I agree on the clarity - changed.
> And the civilopediaText is made obsolete by the unique. 

Good point, I've removed it
> Indestructible deprecated becomes Indestructable? 

I'm not sure what happened, I thought I had autocorrected those afterwards, but somehow their not in this PR. Fixed nonetheless.
> Units that are _not_ great people but can place something and get consumed - without triggering Halicarnassus - should be possible. This reverts that option (UnitActions.683).

I think they still can? On the new line `UnitActions:669` the function `improvement.handleImprovementCompletion(unit)` is called, which in turn calls `unit.consume()` which destroys the unit and, if it is a great person, provides stats?

**Comment by SomeTroglodyte** [comment]
> for some reason I always mess this conjuagtion up

"conjuagtion" -> "conjugation" :rofl: :partying_face: :tada: :+1: :love_you_gesture: :heart_eyes_cat:  ... and isn't it "action" not "agtion"? I imagine _conjuaction_ could have some relation to the 5th pantheon Belief in our ruleset.

> unit.consume() which destroys the unit and, if it is a great person, provides stats?

From the diff display it looked as if your new consume() doesn't test if it's a GP, oh well

> try to keep them relatively short

I admit in this case I thought 'well if that already fits the display then it will just as well from the other source' - without actually looking at a game screen

**Comment by SomeTroglodyte** [comment]
You know, stuff is piling up - don't we _have_ another third cerberus head with collaborator rights to fill up the three merge votes? You, me, who else is active these days and where can I see a list - @JackRainy I guess? Maybe I should put more minutes into review instead of playing.

**Comment by xlenstra** [comment]
> > for some reason I always mess this conjuagtion up
> 
> "conjuagtion" -> "conjugation" rofl partying_face tada +1 love_you_gesture heart_eyes_cat ... and isn't it "action" not "agtion"? I imagine _conjuaction_ could have some relation to the 5th pantheon Belief in our ruleset.

I'll choose not to respond to that :joy:

> > unit.consume() which destroys the unit and, if it is a great person, provides stats?
> 
> From the diff display it looked as if your new consume() doesn't test if it's a GP, oh well

Yup, but that's intentional as that is already done inside the `addStatsPerGreatPersonUsage()` function itself

> > try to keep them relatively short
> 
> I admit in this case I thought 'well if that already fits the display then it will just as well from the other source' - without actually looking at a game screen

image
It's a bit long, but its probably fine

**Comment by SomeTroglodyte** [comment]
`if (!isGreatPerson()) return` - I see.

**Review by SomeTroglodyte — APPROVED** [review]
UniqueDocsWriter result not up to date, but I don't care. The Indestructible deprecation  is a bit fast in 1 step to ERROR, but what the heck, you'll have reasons.

Tiny thing: My nose twitches whenever a pattern just remotely looks like 'dispose - continue using', and the consume case is such a thing. Now our MapUnits are just fine with that, but one _could_ fear some future coder has the same pattern expectations and goes and finds a reason to mess with data after 'destroy' because hey it's disposed anyway... So I'd probably cache out that home tile before destroying, without thinking twice. Nevermind.

`val turnsToBuild` - you know, fields accept Kdoc's and _do_ show them in tooltips (that comment might  be worth one - maybe). What I just learned: `[`references`]` in Kdoc participate in Studio's Alt-F7 "Find Usages" in both directions, and Kdoc style `/** */` _within_ code blocks - so they _don't_ appear as doc anywhere - still work for "Usages". I'm beginning to think that could be very _very_ useful...

**Comment by SomeTroglodyte** [comment]
> [Updated docs I suppose](https://github.com/yairm210/Unciv/pull/6680/commits/be4eddfd9b2c5ea1f2e26963746f17f7f39260b9)

Come to think of it, for feature PR's I think that file should/can be excluded. I do so unless asleep. For any release the run to run TranslationFileWriter will update it anyway - right? I'm actually doubting having TranslationFileWriter in the GUI makes much sense anymore - command line parameter, call it from the auto workflows. And gate UniqueDocsWriter with the same approach, steals debug time.

**Comment by JackRainy** [comment]
> You know, stuff is piling up - don't we _have_ another third cerberus head with collaborator rights to fill up the three merge votes? You, me, who else is active these days and where can I see a list - @JackRainy I guess? Maybe I should put more minutes into review instead of playing.

I was out of the project for a year or more, so I am trying to get in back by looking around what have changed (Diplomatic Victory, Rivers, the new approach with Uniques - are a few of the most obvious innovations). As soon as I more less understand what's going on, I will return for code reviews as well: it's hard doing a _good_ review, something more than static syntax check :) while have no clue what's going on around.

**Comment by SomeTroglodyte** [comment]
> was out of the project

Thought so. Don't worry, you're clever, that clue is just around a corner.

**Comment by yairm210** [comment]
Ah, nice! I see what you did here.
Previous conception was that there were 2 types of improvements - "instant build and consume" and "long build and no consume". What this does is separate the two - "instant build vs long build" is a property of *the builder*, and "consume vs no consume" is a property of *the improvement*.

What we gain in moddability is "instant build no consume" and "long build and consume", what we lose is the ability to have one improvement that can be built by one unit with consumption and by another without consumption. Seems like a fair trade-off.

**Comment by yairm210** [comment]
I'm not sure if to merge this or not, given SomeTrog's parallel work. I approve, but I'll leave the decision to merge up to y'all.

**Review by yairm210 — APPROVED** [review]

**Comment by xlenstra** [comment]
I'm fine with this being merged for now, the plans I had for fixing tile improvements/splitting oil well & offshore platform will go in a new PR anyway due how hard it got out of scope

**Comment by SomeTroglodyte** [comment]
> lose the ability to have one improvement that can be built by one unit with consumption and by another without consumption

Uh, I'd be quite against that, if true. That would be an attractive in-game tradeoff for mods. "Look - build time is 20 turns and you can reuse the Builder, or you spend 500 shields and poof need to build another one"...

> SomeTrog's parallel work

Don't mind me, such can always be synced or reverted from a conflicting PR or... As long as we communicate ideas, the best one will win (idea that is).

**Comment by SomeTroglodyte** [comment]
Build / construct - wording - again, not immediately clear to newcomers. "Can construct" (or build), "Can place immediately", and "Can place immediately consuming" maybe, and a count limitation could - syntactically - be expressed like a conditional??? Dunno.

I worked on my Aliens long ago, wanted them to have limited Workers (because they're lazy). So their specific Worker replacement needed 2x or more shields, had a high hurry modifier, and was only able to do a simple subset of what a Worker could do, and took 50% longer for that - making capturing true Workers a worthwhile adventure. In return, they could place/consuming that penguin hatchery, made to be not quite a bargain via their high price. I had that working just fine, though I don't remember whether the code patches for that were already PR'ed or are still in a certain sleeping local branch (which primarily deals with start locations, idea Aliens have their Spaceship wreck and it's always near their start - startbias = natural wonder).

I'll respect your opinion. If you think the choices available to modders will still be sufficient, go ahead. Code clarity and reliability could be a good tradeoff for limiting modder freedom.

**Comment by xlenstra** [comment]
I agree with SomeTroglodyte that restricting modders in things that used to be possible isn't good, especially if I'm planning on completely reworking the feature the next release again. Thus I would remove the `consumes Builder when built` unique from improvements. As SomeTroglodyte also already made a different PR for the culture bomb unique of the citadel, having a PR only for that also wouldn't make any sense.
Removing those two features from this PR would remove basically everything, so I'm closing this PR. The changes in behaviour will be added to the next PR I make, which will be based of off this PR, but reverting those changes and applying those of SomeTroglodyte, assuming that is merged by the time I open that PR (it probably will be).
It will then also have the uniques for build/build immediately ([amount] times), so that modders will only get more options instead of different ones.

**Pull request closed without merging**
