### PR TITLE
Removed periodic saving of TurnChecker again

### PR DESCRIPTION
**Pull request by GGGuenni**
It also did not work out with smaller files. Seems like I have to find a proper solution to implement #5756

### CODE REVIEW

**Comment by touhidurrr** [comment]
Bruh, @GGGuenni @yairm210 ...
A moment of silence here.
I didn't face the reopened #5756 problem on Android but on Linux AMRHF (Raspberry Pi 3B+).
So, why did you guys edited https://github.com/yairm210/Unciv/blob/master/android/src/com/unciv/app/MultiplayerTurnCheckWorker.kt ???
I believe its not a Android Specific problem. The problem is probably something else.

**Comment by touhidurrr** [comment]
Also note that it CANT be an arm specific problem. We CANT solve bugs happend on Linux Debian by fixing Android specific CODE !!! Android has nothing to do HERE!!!

**Comment by touhidurrr** [comment]
Also what is periodic saving?

**Comment by GGGuenni** [comment]
Well first of how about telling me the device you are using when you make a bug report and not complain later that I didn't get your report. How should I know you are using Debian?

Second I wasn't aware that we've got notification on Linux. I haven't worked on that but will take a look at it 

With periodic saving I mean the saving of the GameInfoPreview everytime the notification worker is running (Well that's periodic)

**Comment by touhidurrr** [comment]
> Well first of how about telling me the device you are using when you make a bug report and not complain later that I didn't get your report. How should I know you are using Debian?

Lol, That's why I said its a moment of silence. I didn't create a new issue cause I thought that I should confirm first if it was a new issue or not. Anyways, probably a mistake from my side. So, what now?

> Second I wasn't aware that we've got notification on Linux. I haven't worked on that but will take a look at it

The problem is not exactly notifications specifics. Neither here or in #5756. In #5756 I complained how it was a waste of data and the game info doesn't refresh when next turn is pressed. I thought you understood it cause you closed with with pr https://github.com/yairm210/Unciv/pull/5789 titled **Improvements to TurnChecker data usage**. And now we are seeing that occasionally the mechanism which downloads and parse game data stops working altogether in Multiplayer UI. As I explained how the **refresh list** button not working. I started the new convo with the comment https://github.com/yairm210/Unciv/issues/5756#issuecomment-1002734269, which and the next conversations doesn't have any mention of notifications not working. Maybe this is a misunderstanding from your side.

> With periodic saving I mean the saving of the GameInfoPreview everytime the notification worker is running (Well that's periodic)

Well Ok. Whats its relation with #5756 and how exactly you saved data? It would be good if you could explain that (just curious).

**Comment by GGGuenni** [comment]
We should revert this commit as it was based on false information.
As long as no android bug report comes up the android worker seems to be working as expected.
Sadly I don't know how to revert a commit without creating another PR so I have to bother you with it @yairm210 sorry

> Well Ok. Whats its relation with #5756 and how exactly you saved data? It would be good if you could explain that (just curious).

I will explain it to you in that issue sometime tomorrow when I've got time again

**Comment by touhidurrr** [comment]
> We should revert this commit as it was based on false information.

Well not exactly false 😒. The logic to download and parse game when the button **refresh list** is clicked, the code for that I saw in the **core** folder maybe. Also, I as mentioned above I didn't actually write that there was any problems with the turnChecker this time. Sigh. I will later open a new issue regarding this maybe. Reading some light Novels now.

**Pull request merged**
