### PR TITLE
Update German.properties 

### PR DESCRIPTION
**Pull request by Haeherfeder**
cleaned names of units

### CODE REVIEW

**Comment by yairm210** [comment]
I'm not a German speaker, but I understood these were because of the difference between male and female forms - @SomeTroglodyte what do you think?

**Comment by Haeherfeder** [comment]
Yes and no, it is possible to us the (maskulin) plural for both, but some persons don't like these form, and say it should done in an other way, but it don't match the spirit of the game (@rh-github-2015 said that, in his first answer to my first translation), and is often harder to read.
Second historical, almost all units were men's .

**Comment by SomeTroglodyte** [comment]
Haeherfeder only touched the tip of the iceberg. The german language file has a lot - but not throughout - of a certain style. 

How to explain - I can think of no good example of forced _linguistic_ political correctness outside germany at the moment (I've only seen something similar in very bad litrpg). There was this movement to use gender-neutralized names and prepositions, and while it has its merit to call attention to a still not quite solved social problem, it never quite made it into everyday language. You hear or read someone using these forms nowadays - it's always clear they're making a statement for emancipation, it never feels quite natural.

An example: Speerwerfer - male, sounds natural. Speerwerferin - female, still sounds natural. Now spell it SpeerwerferIn with a capital I, and clearly refer to a multitude of individuals - it's obvious in written form that you're forcefully merging the gender forms, and when only heard you wonder whether they're talking about amazons, not the historical armies we model in Civ's...

So, while I'm biased in the emancipation question - I'm not for equal rights but for women in power and having all the perks and advantages - this style doesn't fit the setting or the other languages (well, at least 3 of them). Still, your call.

The changes in this PR seem to only touch prepositions and adjectives with their target a placeholder, and yes I too think the result will feel more natural - even if the chance exists to get mismatched gender once in a while, not that I can think of an example. Worse if the placeholder is then filled with e.g. a bomber.

**Comment by yairm210** [comment]
Okay, gotcha
We're going with 'readability' and not 'gender correctness' then

**Comment by yairm210** [comment]
I'll merge this towards the next version ;)

**Comment by Haeherfeder** [comment]
> The changes in this PR seem to only touch prepositions and adjectives with their target a placeholder, and yes I too think the result will feel more natural - even if the chance exists to get mismatched gender once in a while, not that I can think of an example. Worse if the placeholder is then filled with e.g. a bomber.

I think I have removed many of the "In" in the  #2440 pull request.

**Comment by yairm210** [comment]
merge translations

**Pull request merged**
