### PR TITLE
use pixmap replace the png

### PR DESCRIPTION
**Pull request by lishaoxia1985**

### CODE REVIEW

**Comment by yairm210** [comment]
I recall using Pixmap to be very performance intensive when compared to using prebuilt pngs

**Comment by yairm210** [comment]
I'll also need to see for myself how it looks, using rounded rectangle is a stylistic choice that could affect the whole look of the game

**Comment by lishaoxia1985** [comment]
@yairm210
 1. i am not sure it is good or bad, if you accept it, i think some pictures can be replaced with pixmap.
2. i am not sure whether  it uses the android system method when it runs on android, if we do this, the code should be wrote like the font method, how do you think this?
3. in the furture, i deside to make font supporting emoji, for example, 🍎 replace food, 🎵 replace culture and so on.

**Comment by yairm210** [comment]
A. I was thinking of emojis as well, because you can add your own emojis as well :)
B. I'll have to see how it looks
C. Regarding the single font, users have noticed that it has aliasing problems as well and seems to look too sharp. I think I'll set it back, the visual fidelity is more important than the slight performance boost.
Well, we tried 🤷‍♂️

**Comment by lishaoxia1985** [comment]
ok, we should decrease the quantity  of the size of the font as less as we can do.

**Comment by lishaoxia1985** [comment]
@yairm210 it can not run on android.

**Pull request closed without merging**
