### PR TITLE
Abstracted file storage from the multiplayer data retrieval - this sh…

### PR DESCRIPTION
**Pull request by yairm210**
…ould allow implementations of both #5866 and #2679 for other implementations of IFileStorage

### CODE REVIEW

**Review by xlenstra — APPROVED** [review]
This looks surprisingly simple for something on first sight I'd assumed to be quite complex

**Comment by yairm210** [comment]
The real mess isn't in implementing the file saving, it's in handling the different data stores. Do you allow multiple games each from a different store? I think yes, therefore each new multiplayer game you'll need to specify which data store it uses, you'll need a way to configure data stores, it's a whole new mess

**Comment by will-ca** [comment]
Would anything be needed beyond a single UI "Use custom file server" button similar to the single-player "Load from custom location", and I guess either one or two properties in the game specifying the type and state of the FileStorage?

(Hm… I'm thinking maybe one string property for FileStorage type, and a second string property to either pass to a constructor/factory or deserialize as JSON for that type?)

**Review by will-ca — APPROVED** [review]

**Comment by SomeTroglodyte** [comment]
I had always imagined the "store" would be one per-setup global. A player wouldn't be able to easily go back and forth from a game on the  "east-coast server" to one on the "west-coast server", but that's a small price to pay for simplicity???

**Comment by yairm210** [comment]
Works for me, and works as a first step

**Comment by xlenstra** [comment]
One downside of having only a single server to connect to is that you can only play games on that server. If, for example, you and a few friends have their own nextcloud server and play on that, you wouldn't also be able to play games with people from the discord.

**Pull request merged**
