### PR TITLE
Apply the production bonus for Rome civ (#1664)

### PR DESCRIPTION
**Pull request by JackRainy**
Fix for the bug: **Rome national bonus is not applied** #1664

### CODE REVIEW

**Comment by yairm210** [comment]
Explanation please?
I fail to see what the problem was and how this solves it =/

**Comment by JackRainy** [comment]
When I have seen this bug (see steps to reproduce) my thought was: something wrong with `getStatPercentBonusesFromNationUnique`.
I have checked that, and it works fine: the production is increased - for example, I have 1 production and `stats.production` is updated to 1.25 value.
Then I thought it is a visual issue and took a look at the `getCityProductionTextForCityButton` which led me to the `turnsToConstruction`.
And there I found a bug: `cityStatsForConstruction.production` which is equal to 1.25 is truncated down to 1, which means that the city gets no speed up at all.

**Comment by yairm210** [comment]
The thing is, building production - like good, gold, culture etc - is incremented by wole numbers, so if you only have 1 production which is raised to 1.25, then yes, your production is actually still 1

**Comment by JackRainy** [comment]
I see, but is it correct? I would not say so, otherwise such bonuses like +25% (or anything else less than 50% which is rounded down) will give nothing - that's break a natural logic.
See the screenshots with explanations in the bug description: https://github.com/yairm210/Unciv/issues/1664#issuecomment-573408433

**Comment by yairm210** [comment]
They do give, but only when you have enough production that the extra is a while number, not a fraction.
If you have 20 production it will turn to 25, because that's a whole number, but for numbers that are to small it won't be enough.

**Comment by JackRainy** [comment]
I understand what you are saying, that's how it works now in the code.
Anyway, for me it sounds wrong, while it says "+25% bonus"(!), neither "+25% bonus _while your production is large enough_", nor "_+1 per each 4 existing_".
Is it how it works in the original game?
Let's listen for other opinions.

**Comment by yairm210** [comment]
Yup, that's how it works in the original game.

**Comment by yairm210** [comment]
That''s how all the percentages work btw, it's not unique to rome or even to production

**Comment by r3versi** [comment]
Here is what I found out (it's a lot of stuff)

* **Base production** is the sum of the raw production from **Terrains, Buildings, Specialists, Idle population, other things that grant _production points_ (city states etc.)
* Production modifiers (percent) are combined additively and applied to the **base production** giving the **modified production** (that is rounded to the closest lower integer: **floor**)
* Only certain units benefit from _food overflow to production conversion_, this gives extra production (not a modifier) that depends on the overflow amount and is added to the modified production
  * `overflow <= 0 -> 0`
  * `overflow {1, 2, 3} -> {1, 2, 2}
  * `overflow >= 4 -> overflow/4 + 2] (integer division)
* Cities in resistance or anarchy do not produce at all

I ran through the code base and I think what we do is really close to how things works in civ5. The only difference I can see is related to the _food overflow to production conversion_ that here is done at a rate of 1:1. 

So, applying what said above a city having a base production of 1 with a +25% bonus will have a final production of `floor(1.25) = 1`, as expected.

Your change assumes that modifiers are applied to the number of turns needed to complete a construction (wrong) and to be fair, you are only modifying the value that is displayed in the UI, not the actual values. 

Let's wait for yairm opinion, but I think there isn't much to do regarding this :)

**Comment by yairm210** [comment]
I've stated my opinion, that on smaller base values, where the percentages don't add up to 1, you won't see any actual change
About the food overflow, I didn't know it wasn't always 1:1, interesting =)

**Comment by JackRainy** [comment]
Thank you @r3versi for good findings! 
Good to know that it works as in the original game now, sorry for disturbing here.

**Pull request closed without merging**
