### PR TITLE
"Sleep until healed" functionality

### PR DESCRIPTION
**Pull request by JackRainy**
In the original game there is a possibility to make a unit Sleep until it's health fully restored.
That's possible here now.
Unciv 2020-02-01 20 12 06

### CODE REVIEW

**Comment by lyrjie** [comment]
It actually is "Fortify until healed" and it gives the same defense bonuses as "Fortify"

**Comment by JackRainy** [comment]
Thank you for information, I played that too far ago, so don't remember.
Do units without "Fortify" ability also has this option?
Anyway, it is useful for all types of units, so I will add "Fortify until healed" as well.

**Comment by yairm210** [comment]
It depends o the unit. Units that can fortify get 'fortify until healed', those that can't (like cavalry and siege units) get 'sleep until healed'

**Comment by yairm210** [comment]
Fortify is just a 'better kind of Sleep' =)

**Comment by yairm210** [comment]
DAMNNN son, this looks really good!

**Pull request merged**
