### PR TITLE
New wonders: Mausoleum of Halicarnassus, Statue of Zeus

### PR DESCRIPTION
**Pull request by JackRainy**

### CODE REVIEW

**Comment by yairm210** [comment]
image

After the recent changes you made in how translation files are compiled, these tests are no longer necessary and may be removed

**Comment by JackRainy** [comment]
Ahh... (facepalm) Usually I do check the tests but not this time relying on my new translation system.
It works actually pretty well saving me a time not dealing with the template file :)

**Comment by Iver88** [comment]
@JackRainy 

Snímek obrazovky 2020-04-02 v 0 48 33

**Comment by JackRainy** [comment]
@Iver88 , which version do you use?
Did you rebuild the atlas file?
That's from the latest of the `master` branch.
Screenshot 2020-04-02 19 47 04

**Comment by Iver88** [comment]
I just created build and run it.

**Pull request merged**
