### PR TITLE
Air Units take damage in Combat

### PR DESCRIPTION
**Pull request by itanasi**
Air Units now take damage during combat.
Edits to both takeDamage() calculation and calculateDamageToAttacker()
image

Other changes:
- [x] Interception uses highest chance unit to Intercept
- [x] Interception by defending unit not possible
- [x] Interception grants 2 XP
- [x] Air units can't Intercept if they've moved that turn

### CODE REVIEW

**Comment by xlenstra** [comment]
> Is this the way it works in Civ V?

Looking through the code of the original, there are different `Attack` and `AttackAir` functions, as well as `getMeleeCombatDamage` and `GetAirCombatDamage` functions, which at first glance have different calculations. So probably not.
`GetAirCombatDamage` is probably the most relevant function for this change, which can be found in `/CvGameCoreDLL_Expansion1/CvUnit.cpp:9369`

**Comment by itanasi** [comment]
So a few subtle differences.
1) Air units actually get penalized double for lower HP when attacking. And Intercept damage is applied first (obv)
2) Base damage is lower (250 vs 400)
3) Variance is lower (300 vs 400)
4) Defender for Air uses Ranged Combat Strength (except for WATER units)

**Comment by itanasi** [comment]
Oh, even worse. The equations are different for Air Strike DefenderDamageInflicted. Everything reduced (200 base, 200 variance)

**Comment by itanasi** [comment]
Code seems different in the C++ SDK. But testing it in game sure seems like Air Combat damage calc is very similar to Melee.
image
Dumped some expected combat data, all at full HP, into a plot
image
Interestingly the City Bombard ratio seems a bit different. Centered more at 25 than 30

**Comment by itanasi** [comment]
Found the proper XML, and Air, Melee, and Ranged Combat ass use the same 24 base 12 potential extra dmg equations. So this should match behaviors

**Comment by xlenstra** [comment]
This screenshot does seem to be made in BNW instead of G&K, could that explain the difference?

**Review by xlenstra — APPROVED** [review]

**Pull request merged**
