### PR TITLE
"Machu Picchu" typo

### PR DESCRIPTION
**Pull request by Am-per-Sand**
"Pichu"->Picchu"
Hope this matches the rest of the code, but please verify.

### CODE REVIEW

**Comment by yairm210** [comment]
A. Need to add a rename for the building icon
B. As with replacable parts, this will work for new games but we'll need to add fixes for existing games

**Comment by Am-per-Sand** [comment]
> A. Need to add a rename for the building icon

So may be save this for next (major) update. As for the icon I can provide a more accurate one for this wonder (soon), if you keeping the old one will prevent anything unwanted.

> B. As with replacable parts, this will work for new games but we'll need to add fixes for existing games

In which files are these to observe as an example?

**Comment by Am-per-Sand** [comment]
Done for the credits and icon.

As for B., I see 5873ccc848430088c28199c8dcd13bf0a44c3c1f or #592 is needed.

**Comment by yairm210** [comment]
Awesome, I'll take it from here

**Comment by Am-per-Sand** [comment]
Could have done also `game atlas` but github search didn't find there any matching string when searching for Machu Picchu.  :microscope:

**Pull request merged**
