### PR TITLE
Fix paper maker icon

### PR DESCRIPTION
**Pull request by ninjatao**

### CODE REVIEW

**Comment by ninjatao** [comment]
Didn't notice it was already fixed.

**Comment by ninjatao** [comment]
Wait. You have fixed atlas file, but the png file for this icon is still bugged.

**Comment by yairm210** [comment]
Okay
So
This is actually a git/os problem believe it or not

You see, when you change upper/lower case, then git and the os don't recognise this as a change

So, the real easy to solve this is to have 2 commits. 
In the first one, you get rid of the file completely.
In the second one, you add the file back, but with the correct upper/lower casing

**Comment by yairm210** [comment]
Okay, I see you managed to get git to recognise the name change, do ignore everything I said
How did you do that?

**Comment by ninjatao** [comment]
1. git rm
2. rename the file
3. git add
I don't know if there is any easier way, but this does the trick.

**Pull request merged**
