### PR TITLE
Update Japanese.properties

### PR DESCRIPTION
**Pull request by satorope**
As far as I can tell, I corrected the unnatural translation.
I changed the space from "" to " " because the grammar is English.
Translated the inherent abilities of each civilization and the greeting immediately after the start of the game.
Added missing translation. Move it to the appropriate line.
I translated many other things.

Is "Great People" not used ?

### CODE REVIEW

**Comment by xlenstra** [comment]
Placeholder `[cityFilter]` not found in `Japanese` for entry `[amount]% unhappiness from population [cityFilter]`
    Placeholder `[tileFilter]` not found in `Japanese` for entry `No Maintenance costs for improvements in [tileFilter] tiles`
    Placeholder `[amount]` not found in `Japanese` for entry `May buy [baseUnitFilter] units with [stat] for [amount] times their normal Production cost`

**Comment by xlenstra** [comment]
The "" should only be replaced by a " " if Japanese uses spaces, as then they are automatically inserted in some cases. Although I don't know Japanese, the existing translations don't seem to use spaces, so this should probably remain ""?

Great People is used as a header for one of the tutorials, and probably in other places as well

**Comment by yairm210** [comment]
Still relevant?

**Comment by yairm210** [comment]
Closing, you can reopen of relevant

**Pull request closed without merging**
