### PR TITLE
Rework Policy and Diplomacy buttons

### PR DESCRIPTION
**Pull request by SomeTroglodyte**
Addresses Part 1 of #6989 (the longer I think about it, the more convinced I am @Ouaz is right about points 1 and 2). Looks pretty much exactly as in their mock screenshot.

Based on #6945 -> Therefore Draft.

### CODE REVIEW

**Comment by touhidurrr** [comment]
Screenshot_2022-06-16-22-35-53-06_572064f74bd5f9fa804b05334aa4f912
Screenshot_2022-06-16-22-35-43-78_572064f74bd5f9fa804b05334aa4f912

Can you make this seamless. These white lines makes me feel ptsd sometime.

**Comment by touhidurrr** [comment]
Also just for reference, this is the kind of mess we that should be solved here:
Screenshot_2022-06-16-22-08-24-95_5b83b50424e447777d9855d9701553df

**Comment by SomeTroglodyte** [comment]
> Can you also make these seamless

No I can't. Ask Gdx why textures that _have_ seamless coordinates in their objects do not come out pixel perfect.

**Comment by touhidurrr** [comment]
> No I can't. Ask Gdx why textures that have seamless coordinates in their objects do not come out pixel perfect.

Maybe we should open an issue on Gdx then? Dunno ehat to write though. Maybe you should open one.

**Comment by touhidurrr** [comment]
Screenshot_2022-06-18-04-15-13-43_5b83b50424e447777d9855d9701553df

Also Nation Name & Icon should link to Civilopedia.
This is supposed to be a Feature Request but I thought of drop this here since you are already working on this things instead of opening a new issue.

**Comment by SomeTroglodyte** [comment]
> Conflicts

🥺 I know

> fogOfWarButton

9 of 17 of my multiple personalities decided against.

**Comment by touhidurrr** [comment]
This is already borken, details: https://github.com/yairm210/Unciv/issues/7261

**Pull request merged**
