### PR TITLE
Add Personalities.json

### PR DESCRIPTION
**Pull request by Caballero-Arepa**
I went to see the [Civ 5 personalities wiki](https://civilization.fandom.com/wiki/AI_trait_(Civ5)) and here I'm 'translating' their parameters, to the ones that we have at the moment.

As the comment says, in the end it's mostly personal interpretation, but I tried to make the closest [Alexander as in Civ V](https://civilization.fandom.com/wiki/Alexander_(Civ5)#AI_Traits).

<details><summary>Now, a boring explanation why I decided on those params for those stats</summary>
<p>

		"culture": CultureEmphasis + GreatPeopleEmphasis (Policies lead to more GP, either directly or by Faith)
		"faith": ReligionEmphasis + GreatPeopleEmphasis (Faith can buy GP)
		"food": Growth,
		"gold": GoldEmphasis + Infrastructure (Refers to roads, Roads = $)
		"happiness": HappinessEmphasis
		"production": ProductionEmphasis
		"science": ScienceEmphasis + SpaceshipVictory
		"military": (OffensiveUnitProduction + DefensiveUnitProduction + DefensiveBuildingProduction + MilitaryTrainingBuildingsProduction + RangedUnitProduction + MobileUnitProduction + NavalUnitProduction + AirUnitProduction + NukeProduction + AntiAirProduction + AirCarrierProduction (A mix of all the unit params) + LikelinesstobeGuarded (Military = Protection against enemies, less relevant than the unit mix)
		"priorities": {
			"Tradition": Growth + WonderEmphasis + WonderCompetitiveness (Tradion good for Tall > Wonders)
			"Liberty": Expansion + CultureEmphasis + TileImprovements (Free worker) + GreatPeopleEmphasis (Free GP) + DefensiveUnitProduction (Defense = Liberty),
			"Honor": MilitaryTrainingBuildingsProduction + OffensiveUnitProduction + DefensiveBuildingProduction,
			"Commerce": NavalGrowth + NavalUnitProduction + WaterConnection + NavalTileImprovements (All the coastal bonuses) + Diplobalance (Trade = Diplomacy),
			"Patronage": FriendlinesstoCityStates + ProtectionofCityStates + CityStateInfluenceCompetitiveness + GreatPeopleEmphasis + Neediness + WillingnesstoDeclareFriendship - (IgnoreCity-States + ConquestofCityStates + BullyingofCityStates),
			"Piety": ReligionEmphasis + CultureEmphasis, (Piety good for Culture)
			"Rationalism": ScienceEmphasis + SpaceshipVictory + AirUnitProduction (Its not magic, its aerodynamics),
			"Freedom": GreatPeopleEmphasis + DiplomacyVictory + HateWarmongers + DefensiveUnitProduction,
			"Autocracy": Boldness + OffensiveUnitProduction + Expansion + NukeProduction,
			"Order": ProductionEmphasis + DefensiveBuildingProduction,
		},
		"warMongering": LikelinesstoDeclareWar + (Competitiveness + Boldness + Meanness + OffensiveUnitProduction + LikelinesstobeHostile + LikelinesstobeDeceptive) - (Forgiveness + Loyalty + DefensiveUnitProduction + DiplomacyVictory + LikelinesstobeGuarded),

</p>
</details>

### CODE REVIEW

**Comment by PLynx01** [comment]
When will we see the further progress?

We need to decide which personality related-variables will be used.

**Comment by Caballero-Arepa** [comment]
Ooff, I have to finish this quick!

**Comment by PLynx01** [comment]
> Ooff, I have to finish this quick!

Are you sure about these personality-related variables?

Maybe we should add the possibility to define the AI priority of buildings, units, techs and policies?

**Comment by Caballero-Arepa** [comment]
Well, of course it would be great to have more variables to accommodate almost all the ones in CIv V, but for me, it's enough to work with what we have,

**Pull request closed without merging**
