### PR TITLE
Update

### PR DESCRIPTION
**Pull request by lishaoxia1985**

### CODE REVIEW

**Comment by lishaoxia1985** [comment]
Have a Good Time!

**Comment by yairm210** [comment]
Thanks! :D

**Comment by lishaoxia1985** [comment]
I want to update my fork to the newest master one. How I do this? I use a browser. thank you. My english is not very good. 2019年4月23日 19:39，Yair Morgenstern <notifications@github.com>寫道：Thanks! :D

**Comment by Am-per-Sand** [comment]
> I want to update my fork to the newest master one. How I do this? I use a browser. thank you. 

I do it too and I miss such an option from github.com: https://help.github.com/en/articles/syncing-a-fork

**Comment by lishaoxia1985** [comment]
I have some problems:
1.the basic resource and the luxury resource both have a resource named"gold", it is very confused,I advise the basic resource named"gold" and the luxury one named "Gold".Although there is no problem in English. 
2.there is a command called "construct improvement" including "Remove Forest",The sentence does not read smoothly in English.
3.the road or railway can't be removed.

**Comment by lishaoxia1985** [comment]
I have some problems:1.the basic resource and the luxury resource both have a resource named"gold", it is very confused,I advise the basic resource named"gold" and the luxury one named "Gold".Although there is no problem in English. 2.there is a command called "construct improvement" including "Remove Forest",The sentence does not read smoothly in English.3.the road or railway can't be removed. 4.Do you know some apps for free, by which we can edit the github files in Android? I ONLY know fasthub,but if you want to edit files,you must pay the money. I'm a Chinese, and not programmer, so my English is not good. Thank you. 2019年4月25日 12:37，YueR <lishaoxia1985160@sina.com>寫道：I want to update my fork to the newest master one. How I do this? I use a browser. thank you. My english is not very good. 2019年4月23日 19:39，Yair Morgenstern <notifications@github.com>寫道：Thanks! :D

**Comment by Am-per-Sand** [comment]
1...., 2...., 3.... <- could you please create separate [issues ](https://github.com/yairm210/UnCiv/issues)for each of these you mentioned above?

**Comment by lishaoxia1985** [comment]
Thank you very much.  You are so cute. @Am-per-Sand

**Pull request merged**
