### PR TITLE
And new unit pixel and some improvement.

### PR DESCRIPTION
**Pull request by AdityaMH**
I think we will need this unit pixel later.
Also, i improve some unit look better.

Some u̶n̶i̶t̶ p̶i̶x̶e̶l̶ railroad made by ravignir
And all unit pixel improved by me.

### CODE REVIEW

**Comment by yairm210** [comment]
Some of the added units are not ones that exist in the game - e.g. airship
Please remove :)

**Comment by logicminimal** [comment]
the road and railroad texture looks really great good job mate

**Comment by AdityaMH** [comment]
> Some of the added units are not ones that exist in the game - e.g. airship
> Please remove :)

Just tell what i must do to remove.

**Comment by AdityaMH** [comment]
I think this enough now.
some unused unit will used later for g&k and bnw content.

**Pull request merged**
