### PR TITLE
Moddable victories

### PR DESCRIPTION
**Pull request by xlenstra**
As already remarked in #6157.
This PR makes victories moddable, and the changes mod makers make will also be shown on the victory screen.

<details><summary> Pictures </summary>

image
Victory screen without any milestones completed

image

image

Victory screen with a few milestones completed

image
Global victory screen

image

image

</details>

I've tested scientific, cultural, diplomatic and time victory after most major changes were made, so I'm pretty certain they work. Save files from before these changes were implemented load just fine, and creating new games should also work without problem.

### CODE REVIEW

**Comment by SomeTroglodyte** [comment]
Worthy target :+1:!

Random foolish thoughts:

* If the package move of IHasUniques.kt & associated changes were a separate PR - would that make this easier to read?
* The graphic files are deleted and recreated as far as the git history goes - an actual move preserving history is possible, even from A Studio using the refactor menus - but I remember it being fragile somehow.
* Aren't milestones _quite_ similar to uniques?
* "built" / "build", "add" - are the milestones to be read as imperative "do this" or past "when you have done this"? built and add/complete/liberate are different in that respect (sorry, a small Parker joke slipped in).
* `ImageGetter.getUnitIcon("SS Cockpit")` for the action - an alias in the atlas costs only a few lines of text as long as it's the same atlas, but there should be nothing preventing a logical subfolder being repeated in several atlanti. An alias would allow modders more control. I know, most of the actions steal their images, and the file structure is mostly my fault so I could have noticed back then. Maybe sometime separately...

**Comment by SomeTroglodyte** [comment]
... Yup. 
"don't think preserving history is possible" - possible yes (replacement as a change and the move separately must work) - worth it no.

**Comment by SomeTroglodyte** [comment]
Wish to approve this: Check. Will it work: Trust yes, but at this complexity I should test first - done, check.

#### Minor observations from reading code:

#### Wording
- "Build [building]" is a "do this!" imperative, "[building] build globally" isn't. Don't know what a grammar guru would call it... "built" would fit the global one better, but that's still not an imperative matching all others. I can't think of a correct, descriptive and short imperative for that ("Ensure that someone builds [building]"? Ouch). As a non-imp I'd prefer something like "[building] has been built by any Civ" or so.

#### Coding
- Naming of "CompletionStatus" and "ThingToFocus" - the way they're used now, import, top level, no qualifier - context just might get a little unclear. I'd name them Victory.CompletionStatus and Victory.Focus by nesting, but that's only one way. I'd say even a simple rename ThingToFocus->VictoryFocus would be a tad clearer.
- `accompaniedVictory` ... associatedVictory? parent?
- `currentsSpaceshipParts` ... are those fluid or electrical currents? Yea, I know, legacy ballast :)
- by lazy accumulation: I imagine there will be few instances of both Victory and Milestone - pre-initalizing stuff won't cost much, and using a lazy has the tiny extra overhead of a delegate, which might add up quickly if the AI uses victory strategy heavily. But eliminating them would require some setTransients called by the Json reader? Not sure what's best here. Initializing Milestone.params in the constructor is easiest.
- Ungated `println`s in `getComplexRuleset` - are those from this PR? By the 8 blanks on the following line I'd deduce "yes".

#### UI stuff (keeping Screen design changes in this PR small is good, so treat these as ideas for the future only)
- `getVictoryScreenButtons -> MilestoneType.CompletePolicyBranches` - maybe it shouldn't use .finisher for text unconditionally. Maybe "Tradition (4/5)" would be nicer.
- `getVictoryScreenButtons -> MilestoneType.DestroyAllPlayers` doesn't sort. That means.. NewGameScreen order, except grouped by dead-or-alive? Order aside, could be one loop by using partition or groupings - clarity nonwithstanding. Also, _not_ grouping might be a desirable option, too, meaning civ buttons keep their place even when you conquer them (like the policy branch complete buttons). Order, grouping or not, and code duplication arguments apply to AddedSSPartsInCapital too.
- `MilestoneType.CaptureAllCapitals` buttons will never show green as it is designed now. However, your own capital will show a button and if you haven't lost it that's slightly confusing. Either show all capitals, green when you own them, or omit your own if you still own it.
- Our/Global/Rankings - by using a TabbedPager those buttons would show which one is active (fixed header support could serve too)...
- Ranking headers - they could easily _all_ have an icon (Those three are an auto effect of `tr`, I know)

#### Modding
- Redefining a VictoryType by name works, and base rulesets can roll their own independently, But an extensiopn mod can't delete or rename one. Since ModOptions.xxToRemove exist - there? (I would prefer some RulesetObject.removed flag so removal could be more generict, but...) Not that it's likely anybody will need the option.
- Deciv Reflux gets four "Victory type Scientific requires adding the non-existant unit SS * to the capital to win!" messages, a pretty obvious consequence. I'd say that's fine.
- Deciv Redux seems to intend a Science Victory with a Biosphere instead of Spaceship theme. Let's start thinking how to let Deciv have a EnablesConstructionOfSpaceshipParts Unique that doesn't **say** Spaceship-soimething but Biosphere-something instead. And, what if Deciv **wants** to keep the Biosphere Project Components as buildings? ...

<details><summary>Idea:</summary>

```
<i>UniqueType</i>
    @Deprecated(...)
    EnablesConstructionOfSpaceshipParts("Enables construction of Spaceship parts", UniqueTarget.Global),
    EnablesConstructionOfScienceVictoryParts("Enables construction of [comment] [constructionType]", UniqueTarget.Global),
    @Deprecated(...)
    SpaceshipPart("Spaceship part", UniqueTarget.Unit, UniqueTarget.Building),
    ScienceVictoryPart("Science Victory Component [comment]", UniqueTarget.Unit, UniqueTarget.Building),
    AddInCapital("Can be added to [comment] in the Capital", UniqueTarget.Unit),

<i>English.properties</i>
Science Victory Component [comment] = [comment]

<i>Buildings.json</i>
	{
		"name": "Apollo Program",
		"cost": 750,
		"isNationalWonder": true,
		"uniques": ["Enables construction of [Spaceship part] [units]", "Triggers a global alert upon completion", 
			"Hidden when [Scientific] Victory is disabled"],
		"requiredTech": "Rocketry"
	},

<i>Units.json</i>
	/* Spaceship Parts */
	{
		"name": "SS Booster",
		"unitType": "Civilian",
		"movement": 2,
		"cost": 750,
		"requiredTech": "Advanced Ballistics",
		"requiredResource": "Aluminum",
		"uniques": ["Science Victory Component [Spaceship part]", "Cannot be purchased", "Only available <if [Apollo Program] is constructed>", "Uncapturable", "Can be added to [The Spaceship] in the Capital", "Limited to [3] per Civilization"]
	},
	{
		"name": "SS Cockpit",
		"unitType": "Civilian",
		"movement": 2,
		"cost": 750,
		"requiredTech": "Satellites",
		"requiredResource": "Aluminum",
		"uniques": ["Science Victory Component [Spaceship part]", "Cannot be purchased", "Only available <if [Apollo Program] is constructed>", "Uncapturable", "Can be added to [The Spaceship] in the Capital", "Limited to [1] per Civilization"]
	},
	{
		"name": "SS Engine",
		"unitType": "Civilian",
		"movement": 2,
		"cost": 750,
		"requiredTech": "Particle Physics",
		"requiredResource": "Aluminum",
		"uniques": ["Science Victory Component [Spaceship part]", "Cannot be purchased", "Only available <if [Apollo Program] is constructed>", "Uncapturable", "Can be added to [The Spaceship] in the Capital", "Limited to [1] per Civilization"]
	},
	{
		"name": "SS Stasis Chamber",
		"unitType": "Civilian",
		"movement": 2,
		"cost": 750,
		"requiredTech": "Nanotechnology",
		"requiredResource": "Aluminum",
		"uniques": ["Science Victory Component [Spaceship part]", "Cannot be purchased", "Only available <if [Apollo Program] is constructed>", "Uncapturable", "Can be added to [The Spaceship] in the Capital", "Limited to [1] per Civilization"]
	}

<i>Deciv Redux VictoryTypes.json</i>
[
    {
        "name": "Ecosphere Salvation",
        "victoryScreenHeader": "Complete the Biosphere Project\nto win!",
        "milestones": [
            "Build [Biosphere Project]", "Build [Command Center]", "Build [Solar Shade]", "Build [Ocean Processor]", "Build [Atmosphere Processor]"
        ],
        "victoryString": "You have achieved victory through mastery of Science! You have conquered the mysteries of nature and saved the biosphere of our nearly massacred mother earth! Your triumph will be remembered as long as the stars burn in the night sky!",
        "defeatString": "You have been defeated. Your civilization has been overwhelmed by its many foes. But your people do not despair, for they know that one day you shall return - and lead them forward to victory!"
    },
    {
        "name": "Cultural",
        "victoryScreenHeader": "Complete 5 policy branches and\nbuild the Utopia Project to win!",
        "milestones": ["Complete [5] Policy branches", "Build [Utopia Project]"],
        "victoryString": "You have achieved victory through the awesome power of your Culture. Your civilization's greatness - the magnificence of its monuments and the power of its artists - have astounded the world! Poets will honor you as long as beauty brings gladness to a weary heart.",
        "defeatString": "You have been defeated. Your civilization has been overwhelmed by its many foes. But your people do not despair, for they know that one day you shall return - and lead them forward to victory!"
    },
    {
        "name": "Domination",
        "victoryScreenHeader": "Destroy all enemies\nto win!",
        "milestones": ["Destroy all players"],
        "victoryString": "The world has been convulsed by war. Many great and powerful civilizations have fallen, but you have survived - and emerged victorious! The world will long remember your glorious triumph!",
        "defeatString": "You have been defeated. Your civilization has been overwhelmed by its many foes. But your people do not despair, for they know that one day you shall return - and lead them forward to victory!"
    },
    {
        "name": "Diplomatic",
        "hiddenInVictoryScreen": true,
        "milestones": ["[United Nations] build globally", "Win diplomatic vote"],
        "victoryString": "You have triumphed over your foes through the art of diplomacy! Your cunning and wisdom have earned you great friends - and divided and sown confusion among your enemies! Forever will you be remembered as the leader who brought peace to this weary world!",
        "defeatString": "You have been defeated. Your civilization has been overwhelmed by its many foes. But your people do not despair, for they know that one day you shall return - and lead them forward to victory!"
    },
    {
        "name": "Time",
        "hiddenInVictoryScreen": true,
        "milestones": ["Have highest score after max turns"],
        "victoryString": "The world has been convulsed by war. Many great and powerful civilizations have fallen, but you have survived - and emerged victorious! The world will long remember your glorious triumph!",
        "defeatString": "You have been defeated. Your civilization has been overwhelmed by its many foes. But your people do not despair, for they know that one day you shall return - and lead them forward to victory!"
    }
]

<i>Deciv Redux Buildings.json</i>
	// Science victory
	{
		"name": "Biosphere Project",
		"cost": 1500,
		"isNationalWonder": true,
		"uniques": [
			"Enables construction of [Biosphere Project Module] [buildings]",
			"Triggers a global alert upon completion",
			"Hidden when [Scientific] Victory is disabled"
		],
		"requiredTech": "Plastics Recycling"
	},
	{
		"name": "Solar Shade",
		"requiredTech": "Future Materials",
		"uniques": [
			"Consumes [1] [Aluminum]",
			"Science Victory Component [Biosphere Project Module]",
			"Cannot be purchased", "Only available <if [Biosphere Project] is constructed>",
			"Triggers a global alert upon completion",
			"Hidden when [Scientific] Victory is disabled", "Limited to [1] per Civilization"
		]
	},
	{
		"name": "Command Center",
		"requiredTech": "Artificial Intelligence",
		"uniques": [
			"Consumes [1] [Aluminum]",
			"Science Victory Component [Biosphere Project Module]",
			"Cannot be purchased", "Only available <if [Biosphere Project] is constructed>",
			"Triggers a global alert upon completion",
			"Hidden when [Scientific] Victory is disabled", "Limited to [1] per Civilization"
		]
	},
	{
		"name": "Ocean Processor",
		"requiredTech": "Future Power",
		"uniques": [
			"Consumes [1] [Uranium]",
			"Science Victory Component [Biosphere Project Module]",
			"Only available <in cities with a [Harbor]>",
			"Cannot be purchased", "Only available <if [Biosphere Project] is constructed>",
			"Triggers a global alert upon completion",
			"Hidden when [Scientific] Victory is disabled", "Limited to [1] per Civilization"
		]
	},
	{
		"name": "Atmosphere Processor",
		"requiredTech": "Geo Engineering",
		"uniques": [
			"Consumes [1] [Uranium]",
			"Science Victory Component [Biosphere Project Module]",
			"Cannot be purchased", "Only available <if [Biosphere Project] is constructed>",
			"Triggers a global alert upon completion",
			"Hidden when [Scientific] Victory is disabled", "Limited to [1] per Civilization"
		]
	},

```
</details>
... One _could_ modCheck that the [comment] in the EnablesConstructionOfScienceVictoryParts-typed Unique matches the one in the ScienceVictoryPart Uniques, and [constructionType] matches where those are found, but for the actual funcitonality all those would be just comments. There's some rejection code hardcoding a "Apollo not built" message, but all the implementation details should be trivial to adapt and easy to find ... This approach would otherwise pretty much work out of the box. Good idea or do we get counteroffers?

**Review by SomeTroglodyte — APPROVED** [review]

**Comment by SomeTroglodyte** [comment]
Forgot to mention: This can crash DesktopLauncher ***if*** someone manages to downgrade to a pre-this codebase after starting a game with a mod that has a victory name not present in the old enum. Just so we know - `ignoreUnknownFields = true` does _not_ make the parser accept any wellformed json and fill in what fits...

**Comment by SomeTroglodyte** [comment]
P.S. - @SpacedOutChicken , that Idea block in the post above might interest you. Do tell us how you want Deciv's scientific victory to work and read, and we could find the minimal UniqueType changes to fit.

**Comment by xlenstra** [comment]
> Deciv Redux seems to intend a Science Victory with a Biosphere instead of Spaceship theme. Let's start thinking how to let Deciv have a EnablesConstructionOfSpaceshipParts Unique that doesn't say Spaceship-soimething but Biosphere-something instead. And, what if Deciv wants to keep the Biosphere Project Components as buildings? ...

Imo the entire `EnablesConstructionOfSpaceshipParts` unique should be deprecated and replaced with `Only available <after building [Apollo Project]>` on the spaceship parts, which Deciv can name replace with any building they want. Then `Enables construction of biosphere parts` can always be used as an untyped unique without effect on the equivalent of Apollo Project, so I don't think we need to do any extra work?

**Comment by SomeTroglodyte** [comment]
Yup, Deciv Redux patched works perfectly well with EnablesConstructionOfSpaceshipParts working as comment only. That reminds me - we don't need an unique with no actual gameplay effect to display info on a RulesetObject, there's always civilopediaText for purely descriptive stuff.

And "missed" - perfectly fine and not surprising. I keep forgetting how Yair waits for three votes counting the author's and his own, and I approved "early" because all those wouldn't break anything serious.

Btw, I do not approve often enough because I believe an approval _should_ mean I am at least 90% certain a PR improves things without breaking them... Which for me mostly means checking out the source branch and poking around in AS itself + gameplay testing. Sorry I waited so long on this one, I neglected other more important things for it (like finding out the correct chainsaw guide length and buying hardened and normal replacement chains before leaving the coutry :wink:).

**Pull request merged**
