### PR TITLE
Update Dutch.properties

### PR DESCRIPTION
**Pull request by EmperorPinguin**

### CODE REVIEW

**Comment by EmperorPinguin** [comment]
I've got no clue why this is failing, it shows I only changed 1 file.

**Comment by SeventhM** [comment]
> I've got no clue why this is failing, it shows I only changed 1 file.

Unrelated to the PR, probably something yairm needs to fix

**Comment by yairm210** [comment]
prepare version

**Comment by yairm210** [comment]
Version rollout PR created

**Pull request merged**
