### PR TITLE
Preperation for hill to terrain feature conversion

### PR DESCRIPTION
**Pull request by GGGuenni**
I've included every sprite from ravignir except the hill+jungle tiles because jungle can't spawn on a hill in the base ruleset.
I've also added overrideStats to hill inside the Terrains.json and changed isHill to ensure saves made with hill as terrain feature can be properly loaded in the prior version. (multiplayer backward compatibility)
Lastly, I've deleted game.png so it gets repacked. I think that is necessary right?

### CODE REVIEW

**Comment by yairm210** [comment]
There are way too many tiles here.
A lot of them seem redundant.

* Fallout should be a standalone sprite, which is overlayed - this removes many of these combinations
* each resource+improvement that has its own image probably didn't need a special one here

**Comment by yairm210** [comment]
All city images are probably not need since they'll be superceded anyway by era-appropriate city images

**Comment by yairm210** [comment]
Can you even make farms on hills? I don't think you can

**Comment by GGGuenni** [comment]
So if I understand this correctly currently every resource and resource+improvement image needs a separate image for every terrain feature combination it can appear on. That's why the current game.png includes images for Grassland+Forest+Coal (Gold, etc.) but is still missing out on Plains+Forest+Coal (Gold, etc.) which just gets rendered as Plains+Forest. So as long as terrain features block overlaying a separate image is needed for each terrainFeatures+resource[+improvement] tile.

The extra City images can definitely be removed together with the old ones (City.png, Grassland+City.png, etc.) that are still inside the game.png.

Farms can be built on hills that are adjacent to freshwater.

**Comment by yairm210** [comment]
That can be changed if we feel it should.
If suddenly gills being a terrainFeature means that every single resource/improvement now needs special attention to get it to render on hills, that's definitely a sign that we should probably be changing the image rendering.

In fact, the method for determining the renders is now so long (TileGroup.getTileBaseImageLocations, 120+ lines) that I think maybe it needs to be rethunk entirely.

**Comment by ravignir** [comment]
> 
> 
> I've included every sprite from ravignir except the hill+jungle tiles because jungle can't spawn on a hill in the base ruleset.

junglehill
Jungles spawn on hills in civ5, that's why I've included them.
Another thing: jungles do not normally spawn on grassland tiles in civ5. If they do, then it is caused by a bug, and they yield 3 food (2 from grassland, +1 food and -1 production from jungle).

**Comment by yairm210** [comment]
I've added an experimental tile layering option in order to check things out, I think this will resolve a lot of the problems in the existing layering and greatly simplify the images needed for new tilesets.
ALSO I want to use this opportunity to get PROPER TILESETS working from mods, instead of always overwriting the FantasyHex tiles - this will allow us to switch between really different tilesets, and not get a jarring combination of two completey different artstyles if a tile exists in one and not the other.

**Comment by yairm210** [comment]
image

Huh
That was easier than I expected
I'll write it up in the wiki

**Comment by yairm210** [comment]
image
image
image

One side effect o the change is that resources that were previously 'hidden' behind forests are now visible.

**Comment by yairm210** [comment]
Some resources required a bit of fiddling in order to get them to look good on top of forests but it's really doable.

image

**Comment by yairm210** [comment]
I think that considering the changes already implemented, this can be deprecated

**Pull request closed without merging**
