### PR TITLE
Update Translations.json

### PR DESCRIPTION
**Pull request by Smashfanful**
Added more Italian translations

### CODE REVIEW

**Comment by yairm210** [comment]
You have conflicts?

**Comment by Smashfanful** [comment]
There should be no conflicts this time

**Comment by lishaoxia1985** [comment]
@yairm210 I have a suggestion,we don't build all language files in the game,we only put the default language "English" in the game.
if some one need,after  we installed the app,we can download the language file.

**Comment by Smashfanful** [comment]
So you're saying one file per language? So lishaoxia can update the game's Chinese translation and I the Italian translation?

**Comment by yairm210** [comment]
No, no
File per subject, not per language
If it's per language then every translator will need to manually search for whatever isn't in his file, which will make the process much more arduous...

**Comment by yairm210** [comment]
I agree that for decreasing file size, we can play with what each user will get
But the files are so small anyway that this feels like a lot of effort for a small return

**Comment by Smashfanful** [comment]
I suppose you're right. Thanks to all anyway,

**Pull request merged**
