### PR TITLE
indonesian translate

### PR DESCRIPTION
**Pull request by canneling**

### CODE REVIEW

**Comment by xlenstra** [comment]
These translations appear to be exactly the same as the ones you have provided in pull request #5747, which have been merged into the game and have been released for version 3.18.7. Are you planning on adding more translations, or should this pull request be closed?

**Comment by canneling** [comment]
But github say may repo behind 18 commit and 2 commit ahead how i resolve this?

**Comment by xlenstra** [comment]
> But github say may repo behind 18 commit and 2 commit ahead how i resolve this?

Unless you want to go through the trouble of using continuously rebasing your master branch on the new master branch (or deleting your entire repo and then forking again), I'd advise against using your own repo for this. Easiest is just to edit the file directly by clicking the pencil mark on https://github.com/yairm210/Unciv/blob/master/android/assets/jsons/translations/Indonesian.properties
Then after you're done, scroll down and create a pull request. That avoids managing your own repo and always ensures you used the last version of the translations

**Comment by canneling** [comment]
so i suppose to not edit in my repo instead in master branch?  and let my repo not update?

**Comment by canneling** [comment]
im new in open source,hope you can tell me

**Pull request closed without merging**
