### PR TITLE
Create Norwegian.properties

### PR DESCRIPTION
**Pull request by Floxudoxu**
Created Norwegian.properties and some translations.

### CODE REVIEW

**Comment by Floxudoxu** [comment]
> Hey, welcome!
> 
> Dang we will need to update that wiki entry sometime. An entirely new language needs more than the initial translations file. Look for #10573 or #10573 for precedents.
> 
>     * adding a line to completionPercentages.properties is necessary so the next run of our auto templates generator will know the language exists. The number is not relevant for starting a language, it will auto-update later.
> 
>     * adding a flag icon is good otherwise your entry on the language picker will look out of place. Free please and with attribution in credits.md
> 
>     * adding a code line for the country/language ISO codes so Java will know where to sort å or æ &co properly. This one needs testing as Java doesn't recognize everything ISO defines - sometimes it's better to deviate a little.
> 
> 
> So: add "Norwegian=0" in [completionPercentages.properties](https://github.com/Floxudoxu/Unciv/blob/patch-1/android/assets/jsons/translations/completionPercentages.properties) - note the link points to the version in your fork and your branch which backs this PR, just edit there, but please check I got the right link.
> 
> Flag is easy - this one: https://www.flaticon.com/free-icon/norway_197579, scaled to 128px: Norwegian (go to [FlagIcons](https://github.com/Floxudoxu/Unciv/tree/patch-1/android/Images.Flags/FlagIcons) and upload it - "Add file" top right - again double-check that is your fork and branch).
> 
> How to look up your branch's credits.md and how to copy and adapt an existing flag attribution I'll leave to you.
> 
> Sorting is even easier - [already there](https://github.com/yairm210/Unciv/blob/master/core/src/com/unciv/models/metadata/GameSettings.kt#L281-L282), so one can hope they're valid.

Thank you so much for all the additional information! I will work on adding the relevant data before committing again. 
The links you added seem to be correct, so I hope it all goes alright. 

Is there anything else than the three points you mentioned that needs adding for the translation to work, as in are the three points the minimum? I will anyway look around to make sure.

Again, thank you a lot! :)

**Comment by yairm210** [comment]
Placeholder `[civName]` not found in `Norwegian` for entry `Declare war on [civName]?`
    Placeholder `[30]` not found in `Norwegian` for entry `Offer Declaration of Friendship ([30] turns)`
    Placeholder `[naturalWonder]` not found in `Norwegian` for entry `Natural Wonder [naturalWonder] does not exist in ruleset!`
    Placeholder `[amount]` not found in `Norwegian` for entry `Gold cost modifier: [amount]%¤`
    Placeholder `[amount]` not found in `Norwegian` for entry `Science cost modifier: [amount]%⍾`

**Comment by yairm210** [comment]
Looking at that we should probably change the cost modifier texts to be stat-independent

**Comment by Floxudoxu** [comment]
> Actually, I hope I didn't assume too much
It's alright, you guided me enough to figure out what I am supposed to do alongside this file! I am working on the other parts now, however it doesn't seem they are included in this commit... I will try to combine the commits to this one! Alternatively, is there a way to stop this one until I have made all necessary changes? 

> And you're down to one:
com.unciv.logic.TranslationTests > allTranslationsHaveNoExtraPlaceholders STANDARD_OUT
Extra placeholder [by] in Norwegian for entry Somewhere around [city]
Yes I know what 'by' means, but that's a placeholder that will be filled with some city name which will be translated separately.

Thank you for finding that mistake! I didn't notice it wasn't the right name in placeholder. I updated it now.

**Comment by Floxudoxu** [comment]
Do I close this pull request and open another with everything together in one pull request?

**Comment by Floxudoxu** [comment]
> Another auto-generation thing, these belong in Fastlane_short_description and Fastlane_full_description instead. Lines 13-22.

Ah I see. I really appreciate your patience here, and helpful pointers. I will add them where they belong, and remove the folder I created lol.

**Comment by Floxudoxu** [comment]
Ahhh sorry! I'll fix that up too.

**Comment by Floxudoxu** [comment]
That's interesting. Hope it works by the time it gets tested!

By the way, are there no translations for objects such as units, buildings/constructions, etc.?

**Comment by yairm210** [comment]
Okay, looks good, let's get this merged!
After the version rollout the big mass of words-to-be-translated will come

**Pull request merged**
