### PR TITLE
UI Update

### PR DESCRIPTION
**Pull request by lishaoxia1985**
some update:
- Now the button background will be used in button, tech button, textfield and notification
- Remove the method refreshAtlas()
- Add "load game" button in WorldScreenMenuPopup
- Fix the Ottomans uniques, now it likes original game
- Edit tech description, replace ("[stats] on [tileType] tiles", " from improvements: ") with ("The following improvements [stats]:", "The following improvements on [tileType] tiles [stats]:")
- Replace "[amount] Stars" with "✯"

### CODE REVIEW

**Comment by yairm210** [comment]
Pics please 🙂

**Comment by lishaoxia1985** [comment]
@yairm210 it likes previous game, now all button background only use one picture.
YueR

**Comment by yairm210** [comment]
I see you generated the translation files after adding... this caused some conflicts  with other translation changes

**Comment by yairm210** [comment]
In general I advise that you don't generate the translation files because of such conflicts :)

**Comment by lishaoxia1985** [comment]
@yairm210  now it's OK.

**Pull request merged**
