### PR TITLE
Update Buildings.json

### PR DESCRIPTION
**Pull request by Smashfanful**

### CODE REVIEW

**Comment by lishaoxia1985** [comment]
you are wrong,  this word have been not used now.

**Comment by Smashfanful** [comment]
But that's what the game says so. I've always found that line, and there's that.

**Comment by lishaoxia1985** [comment]
you should merge the newest master

**Comment by Smashfanful** [comment]
How?

**Comment by lishaoxia1985** [comment]
in Andriod Terminal(i don't know which TextEditor you use), input below like this:
git remote add upstream https://github.com/yairm210/UnCiv.git
git fetch upstream 
git merge upstream/master
now your local branch will be newest. of course when you input "git merge upstream/master" it may point out " there are some conflicts", you should solve this and input this command again.
after this, you can pull the local branch to the your repositories in github, and create pull request to yairm210/UnCiv.

**Comment by Smashfanful** [comment]
Argh, you do that.

**Comment by yairm210** [comment]
No longer relevant, this text was replaced by "+1 Production from each worked Forest tile"

**Pull request closed without merging**
