### PR TITLE
regenerated game.atlas and game.png

### PR DESCRIPTION
**Pull request by SimonCeder**
Regenerates game.atlas and game.png, so the Carthage icon shows up in game!

### CODE REVIEW

**Comment by SomeTroglodyte** [comment]
Ruins several minutes of work I just put in...

**Comment by SimonCeder** [comment]
sorry, what were you doing?

**Comment by SomeTroglodyte** [comment]
Just a joke, I just brought another PR up to master with atlas regen, then just _seconds_ later - conflixxxzzz. Normal, but the chronological coincidence was quite something.

**Comment by Kote717** [comment]
hey, I'm on the phone need somehow get game.atlas, png out and put in my mod to draw NationIcon. Dunno how to do it on phone. send help.

**Pull request merged**
