### PR TITLE
Reviewed version of the unit's teleportation

### LINKED ISSUE #4923: When the open borders agreement stopped, my submarine was moved from the sea into the lake not connected to the sea
**Platform**
Android 

**Version**
3.16.3

**Describe the bug**
Submarine was in neighbours aquatory when open borders treaty was on. After open borders is finished, submarine was automatically moved out of the borders, which is expected. But in result it was placed to the lake which is not connected to the sea

Screenshot_2021-08-20-12-37-07-129_com unciv app
Screenshot_2021-08-20-12-47-08-897_com unciv app

```

```
</details>

**Expected behavior**

Submarine is placed to sea instead of lake

### PR DESCRIPTION
**Pull request by JackRainy**
Fixes #4923 and resolves issue mentioned in https://github.com/yairm210/Unciv/issues/5798#issuecomment-1094220756 

Here we solve 2 problems:
1) When the military unit was teleported onto the enemy civilian, the latest was not captured.
Now it is.
2) When the unit was teleported it might appear in the place of no return, where it could not reach technically, e.g. in trap between mountains or a ship into the lake, etc.
Now the path to the destination point is something real which could be made by a unit being "escorted" from the expelled territory.

### CODE REVIEW

**Comment by SomeTroglodyte** [comment]
What if the unit could not leave its current tile in any way by normal means? With "path to the destination point is something real" such a unit could not be displaced at all - will it stay, die, change owners, crash the game or teleport the old way?

**Comment by JackRainy** [comment]
If it cannot leave the tile "by meaningful way" there is a fallback (same as it was before) - try to teleport it to one of your cities.
Furthermore, if you have no cities (can it happen?) or the territory of your cities is already occupied with other units (quite a rare case) - it will just gloriously die being tortured in captivity. 😢

**Comment by SomeTroglodyte** [comment]
> tortured in captivity

Do we have a "resistant to torture" unique?

**Review by SomeTroglodyte — APPROVED** [review]
Maximizing English.words.invent("naggyness"):
- "might have" not "Might has" :rofl: 
- My nose twitches at `getUnguardedCivilian` and city tiles If that function can be called at all for city tiles - should a city itself not count as protection? And why test airunits? Isn't a carrier always military? - I'm too lazy to follow that thought.
- `getPathBetweenTiles` - didn't the BFS have a safety limit? Maybe this could do with a max of say 91 (getNumberOfTilesInHexagon(5)) or so?

**Comment by JackRainy** [comment]
> "might have" not "Might has" 🤣

Damn... I need more practice in writing code comments to improve my English :)

>  `getUnguardedCivilian` and city tiles

`canMoveTo` is called before that and contains such check.

> didn't the BFS have a safety limit? 

It has `maxSize` property which may be used as a limit. Probably, it makes sense to use it since in the worst rare case it will go through the whole map and stop there. Not sure how it affects performance, though, let's see.

**Pull request merged**
