### PR TITLE
I cannot feel pain

### PR DESCRIPTION
**Pull request by rh-github-2015**
Really sorry, but such things bother me. Feel free to reject. I hope y'all can laugh heartily at this.

'Impassible' can certainly describe a mountain, but not the in-game property: [wiktionary](https://en.wiktionary.org/wiki/impassible) ('misspelling'), [webster](https://www.merriam-webster.com/dictionary/impassible) ('uncommon')  [search](https://duckduckgo.com/?q=impassible&ia=definition)
IOW, something like the ubiquitous site/sight, there/their, its/it's misuses...

Oh, and the simple way adding 10 bytes to English.properties would work just as well but some told me not to :)

### CODE REVIEW

**Comment by yairm210** [comment]
I did not know that
Good to know!

**Comment by rh-github-2015** [comment]
I should have coded this as easter egg: Show 'Impassible' only on easter sunday (or an equivalent holiday depending on chosen locale) or april fool's day.... Hey, now _there's_ a missing feature! (?)

**Comment by JackRainy** [comment]
Well spotted! 👍

**Comment by yairm210** [comment]
Every time we go through a major translation change, there's about a week of decidedly unfun cleanup of pre-change PRs.
In this case, it was simpler to just do a different commit.

**Comment by rh-github-2015** [comment]
I'm not surprised :)

**Pull request closed without merging**
