### PR TITLE
Update Polish.properties

### PR DESCRIPTION
**Pull request by Remixion**

### CODE REVIEW

**Comment by GreenFreshy** [comment]
Leader of Romę is Oktawian August, not Gajusz Juliusz Cezar.

**Comment by GreenFreshy** [comment]
And "maksymalne" not "maxymalne.

**Comment by Remixion** [comment]
I think more people know Octavian under the name "Galiusz Juliusz Cezar"
and u right that should be "ks" not "x", my mistake.

**Comment by GreenFreshy** [comment]
But Gajusz Juliusz Cezar is a different person than Oktawian August (his full name is Gaius Iulius Caesar Octavianus and this is misleading).

**Comment by Remixion** [comment]
Oh Wikipedia tricked me.

**Pull request merged**
