### PR TITLE
added assets for the Indian

### PR DESCRIPTION
**Pull request by Am-per-Sand**
Please double-check if I my changes to `CityStats.kt` result in correct calculation of happiness!!!

If yes, uncomment `Units.json`, `Buildings.json`, `Nations.json`, update `game.atlas` and this nation is ready to roll.

### CODE REVIEW

**Comment by yairm210** [comment]
It looks like your bar version defers from the current version in a number of places, please merge with the current version

**Comment by Am-per-Sand** [comment]
> Instead of a variable called Indian, var unhappinessFromCity=-3, if(...) unhappinessFromCity*=2

```
var unhappinessModifier = civInfo.getDifficulty().unhappinessModifier
        if(!civInfo.isPlayerCivilization())
            unhappinessModifier *= civInfo.gameInfo.getDifficulty().aiUnhappinessModifier
var unhappinessFromCity=-3f
        if (civInfo.getNation().unique.contains("Unhappiness from number of Cities doubled")) 
            unhappinessFromCity*=2f
        newHappinessList ["Cities"] = unhappinessFromCity * unhappinessModifier
```

Yes, looks better, if that is what you meant. However the problem is that
`civInfo.getNation().unique.contains("Unhappiness from number of Cities doubled")` causes
`Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type String?` in check

> It looks like your bar version defers from the current version in a number of places, please merge with the current version

Isn't it just a result of comparing diffs against an old fork (form a month ago or so)? I am sure I have made changes to the most current raw contents of the files (containing the code).

**Comment by yairm210** [comment]
image

**Comment by Am-per-Sand** [comment]
The only solution I know to correct the above message is to make a new fork, which I will gladly do but the following days.

**Comment by yairm210** [comment]
Use civInfo.getNation().unique == "fulltext" instead

**Comment by sulai** [comment]
> The only solution I know to correct the above message is to make a new fork

Actually it's easier to merge yairm210's master into your branch 🙂 you need a reference to his branch in your local repository though.

Luckily, this is not very hard to do, here is a description on how to do it: https://help.github.com/en/articles/adding-a-remote

**Comment by yairm210** [comment]
I made a pull request to merge my master into yours,
After that you can merge your matter into the Indian branch

**Comment by Am-per-Sand** [comment]
>  you can merge your matter into the Indian branch

Did not work as you require because my master even after pushing your pull remained two commits ahead (some old commits). Not considering it necessary, but I committed this pull from a brand new fork: #800

**Pull request closed without merging**
