### PR TITLE
Delete mod civs and add Austria

### PR DESCRIPTION
**Pull request by N1187**

### CODE REVIEW

**Comment by Smashfanful** [comment]
Austria is a G&K civilization, and we need to implement all Vanilla features, which we're very far from

**Comment by yairm210** [comment]
Please add closing } brace, and keep Austria within the comment (i.e. keep the final */)

**Comment by N1187** [comment]
@Smashfanful Why are you disagreeing for adding Austria if Australia and Philippines are not official civs and will never be added. We have all necessary features for Austria so being it in G&K is no problem whatsoever. Please admit it that you are butthurt for having your favourite fan civs removed from the to do list.

**Comment by yairm210** [comment]
Please keep your language clean

**Comment by yairm210** [comment]
You haven't fixed the closing issues, so I can't do anything with this

**Comment by yairm210** [comment]
...fine, I'll do this myself

**Pull request closed without merging**
