### PR TITLE
Add hungarian translations

### PR DESCRIPTION
**Pull request by pehsa**
- [ ] Buildings.json (90%)
- [ ] Diplomacy,Trade,Nations.json (90%)
- [ ] NewGame,SaveGame,LoadGame,Options.json (90%)
- [ ] Notifications.json (90%)
- [ ] Other.json (90%)
- [ ] Policies.json
- [ ] Techs.json
- [ ] Terrains,Resources,Improvements.json
- [ ] Units,Promotions.json
- [ ] BasicHelp
- [ ] Nations
- [ ] Tutorials

### CODE REVIEW

**Comment by pehsa** [comment]
First, I automate the line appends and the translation with GoogleTranslate. Second, I will check manually the translations and correct them.

**Comment by yairm210** [comment]
The longer you leave these unmerged, the more conflicts you'll need to resolve
I recommend merging add soon as possible

**Comment by yairm210** [comment]
It's been a month, so if we're going to merge this, please make it be non-WIP, and if not, please close it =)

**Comment by yairm210** [comment]
Translation has moved to a per-language translation, in order to avoid conflicts and parsing error. Details here:
https://github.com/yairm210/Unciv/wiki/Translating

**Pull request closed without merging**
