### PR TITLE
Fix Khan unit

### PR DESCRIPTION
**Pull request by SimonCeder**
This PR fixes the Khan unit, so adjacent units only get the healing bonus when they would have healed otherwise.
Also fixes adjacent healing bonuses so they don't also affect the center tile in addition to neighboring tiles.

### CODE REVIEW

**Comment by yairm210** [comment]
I'm like 80% sure that the "adjacent" units includes the center tile. It doesn't make sense that Khan units heal units *next* to them, but not *on the same tile*.

**Comment by SimonCeder** [comment]
It's counterintuitive, but it is how civ V does it, just checked. We could change it of course, but then we'd have to make sure that promotions like medic don't count "double"

**Comment by ravignir** [comment]
o
it says **this** unit and **adjacent** units. Not all units on this tile. There are affects like `all units on this tile and adjacent tiles`, but it is not one of them.

**Comment by SimonCeder** [comment]
Wait.. does medic give extra healing twice to the promoted unit? I'll have to check.

**Comment by yairm210** [comment]
This is extremely odd, but OK.
Another point - the change you've made also affects Medic II, do the effects there still hold up to Civ V?

**Comment by SimonCeder** [comment]
Checked with medic promotion in civ V, it is in fact the case that adjacent unit bonuses do not affect the unit itself.
However as ravignir pointed out, the "enhanced medic" promotion the khan has heals adjacent units, and *this* unit. I added a separate `"[+15] HP when healing"` to the Khan to implement this. Right now the only time it would come into play is if a Khan is damaged by a citadel.

**Pull request merged**
