### PR TITLE
Add city resistance.

### PR DESCRIPTION
**Pull request by ninjatao**
https://github.com/yairm210/UnCiv/issues/152

It still lacks UI indication. Will come up to it later.

### CODE REVIEW

**Comment by yairm210** [comment]
I'll wait until this has ui indication, because without it, this looks like a big - I conquered a city and it has no production for no apparent reason???
Also, won't this make the city starve, as is?

**Comment by ninjatao** [comment]
Some civ5 wiki says population don't starve during resistance. I think it is reasonable because if one population will die otherwise. Suppose resistance length = popu, the city will die out before everybody goes back to work.

**Comment by ninjatao** [comment]
http://civilization.wikia.com/wiki/Conquered_cities_(Civ5)

**Comment by ninjatao** [comment]
Some civ wiki says people don't starve during resistance. I think it makes sense because if otherwise, the whole population will die out given resistance length = population.

**Comment by ninjatao** [comment]
screenshot_20181206-144546
screenshot_20181206-144556
Added icon both in city button and in stats table. Resistance length is displayed in stats table.

**Comment by yairm210** [comment]
Damn, that looks good!
I seem to recall that stationing a military unit in the city makes resistance decrease by 2 each turn, but I couldn't see that in the wiki.

Also, I think that if a city is in resistance and it's captured by its previous owner, then it doesn't enter resistance again, but that would mean adding a new field in cityInfo of previousOwner, which sounds like another, separate job

**Comment by ninjatao** [comment]
I am more like a Civ4 fan on PC ^_^  Not really an expert in civ5 mechanics.

**Pull request merged**
