### PR TITLE
Update Spanish.properties

### PR DESCRIPTION
**Pull request by ArchDuque-Pancake**

### CODE REVIEW

**Comment by SomeTroglodyte** [comment]
Is that an accented "ó" in "no"?

**Comment by ArchDuque-Pancake** [comment]
Yes, "no" and "si" have accent when they are for negation or afirmation.

**Comment by SomeTroglodyte** [comment]
Sí pero no el [no](https://www.spanishdict.com/translate/s%C3%AD%20o%20no)?

**Comment by ArchDuque-Pancake** [comment]
Waiit a minute... let me see...

Oh.. my.. fricking lord... Years of academy wasted! ¡My teacher killed me for those tildes and now turns out the RAE a few years ago changed the rules of them!

**Pull request closed without merging**
