### PR TITLE
Replay functionality

### PR DESCRIPTION
**Pull request by alkorolyov**
Brief description of the prototype:
Each turn NextTurnReplay class would be used to play recorded actions.
ActionMapper class is responsible to apply recorded action to specific civilization.
Action class would be a single state-changing function.
Replay class would store all actions for each civilization in the chronological order

### CODE REVIEW

**Comment by alkorolyov** [comment]
@yairm210 
Basic realization is ready. Sorry for keeping this PL so big. But I didn't want to split core replay logic in different PL.
Now it contains core functionality for storing actions, writing/loading them and playing in replay mode. Currently it works with move/disband actions.

Also all new functionality is hidden behind Unciv.replaySwitch.

**Comment by logicminimal** [comment]
@yairm210 sorry for ping but what will happen to this thread? this thing must be incompatible af by now

**Comment by logicminimal** [comment]
soo what

**Comment by yairm210** [comment]
I'm closing this.
The basic scheme of this is not really compatible with the current development of the game, and if had gone quite out of sync...
I should have probably closed this a long time ago

**Pull request closed without merging**
