### PR TITLE
Removed the sight bonus from hills

### PR DESCRIPTION
**Pull request by avdstaaij**
This strikes off an item from #4697.

### CODE REVIEW

**Comment by logicminimal** [comment]
shouldn't it provide extra sight though, as you technically can see more in real life also? @ravignir ?

**Comment by ravignir** [comment]
No, but hills/mountains have other property: they are visible from further away than unit can normally see in civ5.

**Comment by avdstaaij** [comment]
> No, but hills/mountains have other property: they are visible from further away than unit can normally see in civ5.

This is much more difficult to implement though, and deserves a PR of its own.

**Comment by yairm210** [comment]
I districting recall that Civ V *does* provide extra sight for units in his, though.
Maybe this is only in Vanilla ruleset...

**Comment by yairm210** [comment]
Ravignir is the resident rules expert, so I'll go by his judgement

**Comment by ravignir** [comment]
nohill
archer is standing on a flat land.
hill
archer is standing on a hill.
this is vanilla civ5 (rules have not changed since).

**Pull request merged**
