### PR TITLE
Add Moddable Policy Priorities

### PR DESCRIPTION
**Pull request by HaneulCheong**
With this PR, modders would be able to implement custom policy priorities with the following syntax:
```json
[
    ". . .",
    {
        "name": "Freedom",
        ". . .",
        "priorities": {
            "Neutral": 10,
            "Cultural": 10,
            "Diplomatic": 10,
            "Domination": 10,
            "Scientific": 10
        },
        ". . ."
    },
    ". . ."
]
```

- **Fixed G&K policy eras**
  - Patronage should be unlocked after the Medieval era
  - Freedom should be unlocked after the Industrial era
  - Source: [Fandom Wiki](https://civilization.fandom.com/wiki/Social_policies_(Civ5))
- **Added 'priorities' object to policy branch entries**
  - [x] TODO: Write about this change to the official wiki - efd6ad7e00676adc634cc1147016a454373014fd
  - [x] TODO: Set actual priorities for each branch, both in the Vanilla and G&K - 83f822985abbe4f17d28e4373162abd378eb3dd6
- **Fixed Vanilla policy eras**
  - Freedom should be unlocked after the Renaissance era
  - Source: [Fandom Wiki](https://civilization.fandom.com/wiki/Social_policies_(Civ5))
- **Partial code formatting**
  - Followed the Kotlin Style Guide...as far as I can tell.
  - I don't know most of the work was done by Android Studio.
- **Reworked how the AI chooses a policy to newly adopt**
  ```markdown
  # Branch-based policy-to-adopt decision
  Basically the AI prioritizes finishing incomplete branches before moving on, \
  unless a new branch with higher priority is adoptable.
  
  - If incomplete branches have higher priorities than any newly adoptable branch,
    - Candidates are the unfinished branches.
  - Else if newly adoptable branches have higher priorities than any incomplete branch,
    - Candidates are the new branches.
  - Choose a random candidate closest to completion.
  - Pick a random child policy of a chosen branch and adopt it.
  ```
- **Removed debugging codes**
- **Update Civilization-related-JSON-files.md**
- **Assigned actual priorities to each branch**
  - See https://github.com/yairm210/Unciv/pull/6390#issuecomment-1073784701
  - Also fixed a debugging value in `Ruleset.kt` (-1 -> 0)
- **Merge branch 'master' into policy-ai**
  - ...
- **Merge branch 'master' into policy-ai**
  - ...

### CODE REVIEW

**Comment by SomeTroglodyte** [comment]
Looks like you're a thorough worker. Again.

The downside here is that you overdid the formatting-only changes, especially separating _all_ uniques into rows, which makes the "gist" of the PR much much harder to read. So - do the currently assigned priorities reproduce the old listOf's approximately?

Also - new fields in PolicyManager - isn't that serialized? If yes - You want all that new stuff in saves? Compatibility with pre-PR saves? Or could `@Transient`s do and recreate them on game load?

**Comment by HaneulCheong** [comment]
@SomeTroglodyte

Hey, thanks for the feedback.

> The downside here is that you overdid the formatting-only changes, especially separating _all_ uniques into rows, which makes the "gist" of the PR much much harder to read.

Yeah, I'm aware of that problem...but the JSON formatting had to be done at some point in my honest opinion; All the uniques in a single line for each policy made the whole `Policy.json` quite hard to skim through previously.

Sidenote: If I'm allowed to I would push a PR formatting the whole `json` folders but I'm afraid that would break a lot of PRs, so I'm staying away from that idea, possibly indefinitely. Formatting one at a time like this PR seemed to be my best option.

> So - do the currently assigned priorities reproduce the old listOf's approximately?

The current priorities assigned for testing are: Tradition and Liberty gets 10 priority each, 20 for the three ideologies, and the rest gets 0.

Here's the result: the AI...
1. Adopted either Tradition or Liberty first
2. Completed the chosen branch (1 branch complete)
3. Adopted the other branch not chosen in 1
4. Attempted to complete the branch
5. Switched to one of the ideologies as soon as they become available
6. Completed the chosen ideology (2 branches complete)
7. Finished the incomplete branch in 4 (3 branches complete)
8. Randomly picked one of the remaining branches
9. Completed it (4~ branches complete)
10. Looped back to 8 until all policies were adopted

...Which is just as expected. It's actually better than the previous List since modders can let the AI have random options by assigning the same priority to multiple branches. I will change the priorities to match the previous priority Lists before marking this PR ready for review.

> Also - new fields in PolicyManager - isn't that serialized? If yes - You want all that new stuff in saves? Compatibility with pre-PR saves? Or could `@Transient`s do and recreate them on game load?

I...am completely unaware of that. Yup, and this is exactly why I pushed a draft instead of a full PR, heh. Although I should say the only stuff added to the PolicyManager are read-only properties and a function if I remember correctly, hence no Field variables. Would they also get serialized?

**Comment by HaneulCheong** [comment]
> I will change the priorities to match the previous priority Lists before marking this PR ready for review.

Well actually...about that, our Discord server seems to be a little 'discontent' with how the current AI picks useless policies for certain victory type. Maybe we should switch things up since we're modifying `Policies.json` anyway. We could even utilize the new "random options by the same priority" for more variety in the AI's behaviour.

**Comment by HaneulCheong** [comment]
> Maybe we should switch things up since we're modifying `Policies.json` anyway. We could even utilize the new "random options by the same priority" for more variety in the AI's behaviour.

So here is my proposal:
```markdown
## Vanilla
|     |Neut|Cult|Dipl|Domi|Scie|
|-----|----|----|----|----|----|
|Tradi| 40 | 40 |    |    | 40 |
|Liber| 40 |    | 40 | 40 |    |
|-----|----|----|----|----|----|
|Honor|    |    |    | 10 |    |
|Piety|    | 10 |    |    |    |
|Patro|    |    | 20 |    |    |
|Comme|    | 10 | 10 | 20 | 10 |
|Ratio|    | 10 |    |    | 20 |
|-----|----|----|----|----|----|
|Freed| 30 | 30 | 20 |    | 20 |
|Autoc| 30 |    |    | 30 |    |
|Order| 30 |    | 30 |    | 20 |

## G&K
|     |Neut|Cult|Dipl|Domi|Scie|
|-----|----|----|----|----|----|
|Tradi| 30 | 30 |    |    | 30 |
|Liber| 30 |    | 30 | 30 |    |
|-----|----|----|----|----|----|
|Honor|    |    | 10 | 10 | 10 |
|Piety|    | 10 | 10 | 10 |    |
|Patro|    | 10 | 20 |    | 10 |
|Comme|    | 10 | 10 | 10 | 10 |
|Ratio|    | 10 | 10 | 10 | 20 |
|-----|----|----|----|----|----|
|Freed|*50*|*50*|*50*| 40 |*50*|
|Autoc|*50*| 40 | 40 |*50*| 40 |
|Order|*50*| 40 |*50*| 40 |*50*|
```

...and here are the test results:

```markdown
# G&K Test result

## First test, 6 players
- Germany (Scientific): Tradition - Commerce (Skipped) - Rationalism (Skipped) - Order - Rationalism - Commerce - Patronage
- Greece (Diplomatic): Liberty - Patronage (Skipped) - Freedom - Patronage - Honor - Commerce
- India (Cultural): Tradition - Commerce (Skipped) - Freedom - Commerce - Rationalism - Patronage
- Iroquois (Scientific): Tradition - Patronage (Skipped) - Rationalism (Skipped) - Order - Rationalism - Patronage
- France (Cultural): Tradition - Commerce (Skipped) - Freedom - Commerce - Patronage - Rationalism
- Byzantium (Cultural): Tradition - Commerce (Skipped) - Freedom - Commerce

## Second test, 8 players
- Byzantium (Cultural): Tradition - Patronage (Skipped) - Freedom - Patronage - Piety
- Mongolia (Domination): Liberty - Piety
- Carthage (Domination): Liberty - Honor (Skipped) - Autocracy - Honor - Commerce - Piety
- Babylon (Scientific): Tradition - Honor (Skipped) - Rationalism (Skipped) - Order - Rationalism - Honor - Commerce
- Arabia (Scientific): Tradition - Commerce (Skipped) - Rationalism (Skipped) - Freedom - Rationalism - Commerce - Honor
- Egypt (Cultural): Tradition - Patronage
- Japan (Domination): Liberty - Honor (Skipped) - Autocracy - Honor - Rationalism - Commerce
- Russia (Scientific): Tradition - Commerce (Skipped) - Rationalism (Skipped) - Freedom - Rationalism - Commerce - Honor
```

Very satisfied how it turned out. The AI nations are behaving exactly as I expected.

----

> I...am completely unaware of that. Yup, and this is exactly why I pushed a draft instead of a full PR, heh. Although I should say the only stuff added to the PolicyManager are read-only properties and a function if I remember correctly, hence no field variables. Would they also get serialized?

As far as I can tell, no additional data is being serialized into save files.

**Comment by SomeTroglodyte** [comment]
It's #6379

**Comment by HaneulCheong** [comment]
Of course I missed the 4.0 train... Anyway thanks @SomeTroglodyte.

**Comment by SomeTroglodyte** [comment]
... and the 4.0.0 train missed the 3.19.19 [platform (as well as 9¾)](https://en.wikipedia.org/wiki/Hogwarts#Arrival).

**Pull request merged**
