### PR TITLE
Update Czech.properties

### PR DESCRIPTION
**Pull request by l3sy**
Few edits and filling the missing lines.

### CODE REVIEW

**Comment by stoupa007** [comment]
did you saw the strings in game to know what exactly they mean?

milan should be called "miláno"
if you change some translation, do it consistently - "Okamžitě léčení", is definitely not czech.

renaming of "produkce" is huge change. currently you just created inconsistent translation as the old term is used on much more places (including tutorials and similar).

also why you use foreign term when we have czech ones ("generuje" is awful word)?

**Comment by l3sy** [comment]
hi,
first of all, there are many inconsistencies as it is, in the czech version and the original as well, are you the original author of this version? for sure it will still need work, not nearly "finished"
and yes, i have seen the strings used in the game

as for your "corrections"
1) milán is proper czech name of the city https://cs.wikipedia.org/wiki/Mil%C3%A1n
2) it was "Okamžitě vyléčit" which is not very different and factually wrong
3) i tried to catch all instances of "produkce" but i will search again, it is in my opinion not a good translation
4) "generovat" is a commonly used and understood term especially in video games, what alternatives do you suggest?

**Comment by stoupa007** [comment]
i'm not original author. just fixing (IMO) the translation gradually over few iterations.

1/ wow, never saw this spelling. in most documents i know is "miláno". is the wiki correct?
2/ "Okamžité léčení" would be correct. do you see the difference? just typo .. ;)
3/ "produkce" is not good and "vyroba" is better indeed. no idea if it will make better sense on all appearances (as its kind of keyword in game). just try to look for others apperances.
4/ well, apparently there is no meaningful czech term. but my point is the word was not in original either. if you reword the sentence you can use better formulation.

another issue you should have in mind in length of strings. too long string could break UI. what is the adidtional info that needs this change?
```
+1 gold from worked water tiles in city = +1 zlato za dělníka na vodním políčku ve městě
+1 gold from worked water tiles in city = +1 zlato za každého dělníka na vodním políčku v tomto městě
```

also you use term "populace" on some place and "obyvatel" on another.

i mean those are not big issues, but just some inconsistent fixes.

**Comment by l3sy** [comment]
1) yeah i'm pretty sure it's correct, "miláno" is colloquial term
2) sorry, my bad
3) yes, i will need to learn to use the github search, this is my first attept to do any work here
4) i'm not a czech purist so i don't really see a problem with using some "anglismy" if it is a fitting translation and universally understandable

anyways thanks for the feedback and let's give this great game a translation it deserves

**Comment by stoupa007** [comment]
agreed.

just for the record. i have no problems with merge.

btw: i made some research and even original name of milan exists in two versions based on local language variant. apparently its not worse than original .. :D

**Pull request merged**
