### PR TITLE
Update Simplified_Chinese.properties（2nd attempt）

### PR DESCRIPTION
**Pull request by heipizhu4**
A reboot for #7624

### CODE REVIEW

**Comment by heipizhu4** [comment]
I haven't failed so many checks before... It's way too insane for merging and copying here and there without an error. Maybe I should restart fresh:(

**Comment by heipizhu4** [comment]
Horray!

**Comment by yairm210** [comment]
prepare version

**Comment by yairm210** [comment]
Version rollout PR created

**Pull request merged**
