### PR TITLE
Nuke your enemy!

### PR DESCRIPTION
**Pull request by ninjatao**
Nuclear missile now functions like a one-time bomber unit, destroying everything in range and leaves only fallout.

### CODE REVIEW

**Comment by yairm210** [comment]
Okay wait
A. If the AI doesn't use this, it's a human cheat
B. We'll need to add FantasyHex tiles of the various tile types (grasslands, plains,desert, hills, tundra) with Fallout

**Comment by ninjatao** [comment]
> Okay wait
> A. If the AI doesn't use this, it's a human cheat
> B. We'll need to add FantasyHex tiles of the various tile types (grasslands, plains,desert, hills, tundra) with Fallout

A. There is nothing to stop AI from building and using this weapon. However there are some improvement to do later, like choosing best target for maximum blast damage.
B. Will do.

**Comment by ninjatao** [comment]
Damn, I found myself not good enough for FantasyTiles. Is there any chance I just left a text mark "Fallout" on them?

**Comment by yairm210** [comment]
Not really an option, it would lose the feel of the map...
But we can say in the Discord they that's what's missing sand well probably get results :)

**Comment by yairm210** [comment]
I saw the hills, we kinda missed the edges

**Comment by ninjatao** [comment]
> I saw the hills, we kinda missed the edges

What? Would you like to explain?

**Comment by yairm210** [comment]
Look at the hills+fallout, you'll see that on the top left, and a bit at the top right, there are some regular green areas

**Comment by ninjatao** [comment]
In my imagination, fallout spreads like fog. So maybe that makes sense more or less?  :p

**Comment by yairm210** [comment]
So you have a picture how a bombed area (with gold) looks in-game?

**Comment by ninjatao** [comment]
fallout

**Comment by yairm210** [comment]
Ok, I think that's good enough for the visual side

**Comment by yairm210** [comment]
Now let's see if the AI actually build this if they have the chance
There's no diplomatic repercussions yet, right?

**Comment by ninjatao** [comment]
not yet

**Comment by ninjatao** [comment]
Yes AIs can build wonder, then missiles, and throw them on your city. But it's very very unlikely because AI randomly picks production. Maybe we will need to adjust priority later. Uploading screen captures tomorrow.

**Comment by ninjatao** [comment]
Build wonder
Building missile
bombed

**Comment by yairm210** [comment]
Hm, I'm not entirely sure if I want to add this before the AI properly utilizes this... it's a dilemma =/
In either can I'll need you to pack the images again

**Comment by ninjatao** [comment]
My previous priority was totally overhauled, and I really don't feel like touching that again. ^_^

**Comment by yairm210** [comment]
You know what, I'm stressing over this mainly because I think there will be a lot of unknowns we will discover later...
If we put this behind a game settings option, and have it opt-in (and tell the players it's as of yet incomplete like we did with other things), then I'll 100% merge this.

Because I don't want this sitting away from the main code, I want people to try it out and find where it breaks; on the other hand I don't want to get 100 messages of "game crash plz fix"

**Comment by ninjatao** [comment]
done

**Comment by yairm210** [comment]
Won't let me merge because of conflicts 0_0
I'll deal with this when I get home if you don't first, I promise you that no commit will enter the codebase before this is merged

**Comment by ninjatao** [comment]
yet again merged. 😂

**Comment by yairm210** [comment]
IT IS DONE

**Comment by ninjatao** [comment]
😜

**Comment by ninjatao** [comment]
BTW, I just realized mountains can contain fallout now but no way to be cleaned. No effects anyway. Do you remember what's it like in Civ5? Because I don't.

**Comment by yairm210** [comment]
Hmm interesting, I do not recall

**Comment by ninjatao** [comment]
> https://steamcommunity.com/app/8930/discussions/0/648814844486366761/
> 
> Apparently yes?
> Cool

Wow. Cool.

**Comment by yairm210** [comment]
@lishaoxia1985 commented a few points:
- Nuclear missile requires 2 Uranium (that's a Unique, then)
- Atomic Bomb should come before, as a unit

**Pull request merged**
