### PR TITLE
Update SDK Platforms text. Update photos

### PR DESCRIPTION
**Pull request by itanasi**

### CODE REVIEW

**Comment by yairm210** [comment]
Thanks for this!
The link should remain 'docs'

**Comment by itanasi** [comment]
If you're sure. The images don't show up on the github.io page though

**Comment by yairm210** [comment]
You're right, I didn't notice that :/
So let's try your change, it can't be worse than what we already have
Sorry for the hassle 😔

**Comment by itanasi** [comment]
No idea. I'm just basing this off of this guide/suggestion
https://tomcam.github.io/least-github-pages/adding-images-github-pages-site.html

**Comment by yairm210** [comment]
I'll merge as is and we can test other configurations later

**Pull request merged**
