### PR TITLE
Added Mobile SAM unit

### PR DESCRIPTION
**Pull request by bringert**
Using info from https://civilization.fandom.com/wiki/Mobile_SAM_(Civ5)
and icon from The Noun Project.

### CODE REVIEW

**Comment by Smashfanful** [comment]
There are conflicts in this pull request

**Comment by yairm210** [comment]
There wasn't when this was proposed, they came later
The reason I didn't merge this to begin with is that I feel that we need to introduce the higher tier aircraft together with the SAM, otherwise it'll be unbalanced

**Comment by bringert** [comment]
I've rebased the change now, but good point about adding Mobile SAM together with the Jet Fighter and Stealth Bomber.

It took me a while to figure out why game.atlas and friends weren't updated after my rebase btw. Turns out that desktop/src/com/unciv/app/desktop/DesktopLauncher.kt looks at the file modification time, and after the rebase, Mobile SAM.png was older than the generated files. What's the reasoning behind keeping these modified files in version control anyway? It seems like it would cause a lot of conflicts. Sorry if I missed an FAQ.

**Comment by HadeanLake** [comment]
it probably should have 65 strength, like in in expansions because strength of other units is like in expansions right now.

**Comment by HadeanLake** [comment]
icon should be 100x100. Embedded attribution is required for icons larger than 100px from the Noun Project

**Comment by yairm210** [comment]
Closing as inactive, if you feel this is still relevant and you'll fix I'll reopen

**Pull request closed without merging**
