### PR TITLE
Add Militaristic type city-state.

### PR DESCRIPTION
**Pull request by ninjatao**
Militaristic states give a free land unit every 20 turns when friendly.

### CODE REVIEW

**Comment by ninjatao** [comment]
Related to https://github.com/yairm210/UnCiv/issues/806#

**Comment by yairm210** [comment]
I assume you tested this feature, yes?

**Comment by ninjatao** [comment]
Sure. I tested the features, but not the translation files.

**Comment by ninjatao** [comment]
BTW, good job on this long-waited air combat feature!

**Pull request merged**
