### PR TITLE
Next Turn always available as long-press of the button

### PR DESCRIPTION
**Pull request by rh-github-2015**
Slightly related to #1651.

I'm certain there's a catch - lost science maybe if a pick tech was pending and is skipped - needs more testing, by independent brains.

### CODE REVIEW

**Comment by rh-github-2015** [comment]
So, this is ignored because Travis complains? But it complains about allTerrainSpecificImprovementsCanBeBuilt, allUnitsHaveTranslation and allPromotionsHaveTranslation - neither of which could _possibly_ have _anything_ to do with this change. Please take a look at the **_code_** and tell me it it's a worthwhile idea or not.

**Comment by yairm210** [comment]
It has nothing to do with Travis, and everything to do with the limited amount of time I have on my hands

**Comment by yairm210** [comment]
This looks okay, but there are some things that must be done each turn, and others that are optional.
Free policies and techs, picking a tech, answering trade requests, assigning construction to cities - are a must
Due units are optional

**Comment by rh-github-2015** [comment]
Let's shelve this then. But: Catching long-press how-to demonstrated!

**Pull request closed without merging**
