### PR TITLE
Improve Alert Popup scrolling

### PR DESCRIPTION
**Pull request by SomeTroglodyte**
See #9513 - never intended that. Should have checked. Thing is, distribution into "scrolls if need be" and "static" is automatic in `Scrollability.WithoutButtons` mode as long as the actual buttons are added with Popup's button methods... And AlertPopup bypassed them entirely. So they went to the upper half, where defaults().fillX() is in effect - ugly.

### CODE REVIEW

**Comment by yairm210** [comment]
I'm not sure which is better, both look good to me
I'll poll this on Discord

**Comment by Ouaz** [comment]
That's what I call a big close button. Not jarring, I think it's ok.

**Comment by yairm210** [comment]
Current state of the poll:
IMG_20230612_072305

Let's wait another day

**Comment by yairm210** [comment]
image

Looks like the wide button is what people want

**Comment by yairm210** [comment]
Not sure if to close this, or if there are other parts of this PR that you still want to use

**Pull request merged**
