### PR TITLE
Years per turn improvement

### PR DESCRIPTION
**Pull request by AcridBrimistic**
As described in issue #2592, the years don't match the game speed unlike in Civ5.  This causes the years to sync perfectly with Civ5, at least according to this chart: https://docs.google.com/spreadsheets/d/1CLEuicVNMFUs4xVLnUj3VKzZwhnb2_zh35e6RU-QAns/edit#gid=0

I haven't tested the later years yet, but it seems to work.  The solution I used is somewhat clunky, but it should be workable.  I've never actually made a pull request before, so let me know if I did something terribly wrong.

### CODE REVIEW

**Comment by yairm210** [comment]
I think that with some naming and order, this could be a good solution =)
My problem is with 2 parts:
A. the "magic array" that the code needs to hand-pick apart
B. the if/else list that, if we're genericifying it anyway, we can get rid of
I'm thinking of a helper class, 
`class YearsPerTurn(val untilTurn:Int, val yearsPerTurn:Int)`
and each difficulty gets a list of them:
`val epic = listOf(YearsPerTurn(75,40), YearsPerTurn(150,20) ...)`
And then the if/else can be replaced by `val currentYearsPerTurn = difficulty.firstOrNull{turn < it.untilTurn}.toFloat() ?: 0.5f`
That's the gist of it

**Comment by AcridBrimistic** [comment]
Updated with the new solution.  I have to admit, object-oriented languages aren't my forte.  It works, at least in my minimal testing.  There are a few problems to resolve, as with anything, but it is functionally complete.

It's a bit clumsy, I know there must be a better way to organize it, but I can't think of anything off my head.

Something needs to be added to the  `val yearText = "[" + abs(year) + "] " + if (year < 0) "BC" else "AD"` line to make months display as actual months and not "2025.5 AD"

**Comment by yairm210** [comment]
Looks good enough to start with!
As for the +0.5, how did it look in the original Civ V?

**Comment by AcridBrimistic** [comment]
If I remember correctly, partial years had fractions as months, so for example:

2060.5 AD -> 2060 6/12 AD
2034.25 AD -> 2034 3/12 AD
2118.75 AD -> 2118 9/12 AD

Might be better on a separate line for fast reading.

**Comment by yairm210** [comment]
image
This is on Standard... something is off

**Comment by yairm210** [comment]
Fixed at 7668a21, NP =)

**Pull request merged**
