### PR TITLE
Newgame screen overhaul for portrait mode

### LINKED ISSUE #4463: More than 9 city-states is shown as "…"
**Describe the bug**
When selecting the number of city-states for a game, selecting more than 9 leads to the number being displayed as "…".

**To Reproduce**
0. Open the menu for making a new game.
1. Select a number of city-states more than 9.

**Expected behavior**
The number would show up as a number.

**Screenshots**
9 city states…
"…"  city-states!

**Additional context**
None.

### PR DESCRIPTION
**Pull request by SomeTroglodyte**
#### Features
- Player nation picker now shows current selection, including scrolling the list to it (I kinda liked the animation so I didn't suppress it). Ever wanted to check the properties of the nation you just finished picking? Was two trips...
- Player nation picker will arrange its halves vertically in portrait.
- New game screen will rearrange its columns vertically in portrait.
- Fiddled map options until the generated/custom select layout mostly follows the rest of the map parameter stuff. Left and right properly aligned, grows with exaggeratedly wide advanced map parameter translations, the works, the dropdown just won't follow the width of the three other dropdowns as the current module structure makes them live in independent columns of separate tables.
- ExpanderTab used appropriately.
- Therefore Base and extension mod lists can finally be visually distinguished.
- Mods sorted alphabetically. For some the order in which they were downloaded may be helpful in finding a specfic one quickly, but not for me.
- Game will remember window size when you only use map editor or the other screens without actually loading or starting a game -> saved time testing!
- The city state count is an UncivSlider to resolve #4463 .
- One of the annoying warnings gone ("Names of the parameter # 1 conflict in the following members of supertypes: 'public abstract fun setRightSideButtonEnabled(boolean: Boolean): Unit defined in com.unciv.ui.newgamescreen.IPreviousScreen, public final fun setRightSideButtonEnabled(bool: Boolean): Unit defined in com.unciv.ui.pickerscreens.PickerScreen'. This may cause problems when calling this function with named arguments.") - by removing `fun setRightSideButtonEnabled` from `IPreviousScreen` - still left the inappropriate name.

#### Flaws
- You might not like the DARK_GRAY separators - I think they make the portrait mode prettier, but they cost a bunch of code, so - your call. Material design would do away with them - but who likes material design anyway?
- Map editor uses of the updated classes as yet untested
- Needs unmerged code 'ExpanderTab persistence' to really feel 'practical'
- It still annoys mightily by forgetting everything except in the rare case where you go there from a running game -> *where* should proper persistence of that be stored? GameSettings?
- Old landscape mode and new portrait mode "feel" markedly different. Okay, so I didn't want to redesign the basic model. I just added to the chaos...
- Some comments I set for myself may not be a help to others in the future

#### Gallery  
<details><summary>...</summary>

image
... not too different
image
Same except Polynesia was already the chosen nation for the player I clicked
image image
</details>

### CODE REVIEW

**Comment by yairm210** [comment]
Looks ready to me :)
Once you're satisfied, un-draft and I'll merge :)

**Comment by SomeTroglodyte** [comment]
Was draft to recheck after ExpanderTab persistence is decided. Will merge forward and re-test later.

**Comment by SomeTroglodyte** [comment]
Merging my originally 2 german changes was fun...
@Mape6  "Schleudersitz" - jawoll! Gemeint ist ja, daß 2 menschliche Spieler am selben Computer/Gerät spielen und sich im Stuhl+Schirm+Maus usw. abwechseln... Schleudersitz gefällt mir - fast Loriot. Und "Außergewöhnliches Gelände" wo Du grad dran warst - sorry jedes Pixel zählt, horizontales scrolling in einem schon in drittel geteilten NewGame screen ist - doof.

... Trouble starting a game using King under the Hill... master can start but the dwarves have no units, this branch threw the error toast ... Switched branches again and can't repro - meaning this branch starts King under the Hill as broken as master does ...

Check size obeyed. Check extreme map settings can be seen. Check map editor. Check non-english. OK, push and check delta shown here. Looks good.

**Comment by Mape6** [comment]
Das horizontale scrollen habe ich bei den erweiterten Einstellungen eh immer. Ist recht Auflösungsabhängig. Habe bisher den Portrait Modus nicht probiert aber wenn hier der Bildschirm auch horizontal gedrittelt wird, gibt's es sehr viel zum scrollen...

Bei den erweiterten Einstellungen fällt es mir recht schwer, die Zusammenhänge richtig zu verstehen, daher orientierte ich mich hier direkt am Englisch. 

Ich fand Schleudersitz gut und fand in dem Moment nix besseres. Zumal ich, an der Stelle wo es benutzt wird, den Sinn nicht verstanden hatte. Wo taucht der String im Spiel überhaupt auf?

**Comment by SomeTroglodyte** [comment]
> ("hotpants") Wo taucht der String im Spiel überhaupt auf?

Start a game with >1 human players and without the "online multiplayer" check, then somewhere in diplomacy with the other human - `CivInfo.getLeaderDisplayName()` adds that to `Nation.getLeaderDisplayName()`

**Comment by SomeTroglodyte** [comment]
Added patch inspired by #4630 - sorting Nations in their picker popup, Collation-aware alphabetically, with only Random and Spectator hard at the top. Thanks @xlenstra !

**Pull request merged**
