### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by JTech-Labs**
Create a Code of Conduct to better the project's community.

### CODE REVIEW

**Comment by JTech-Labs** [comment]
For more information @yairm210 visit the [Open Source Guide](https://opensource.guide/code-of-conduct)

**Comment by yairm210** [comment]
I see
We already have a similar set of rules for our Discord server, I'd prefer that they were one and the same
I do like the clear "action - consequence" rules outlined here, but they feel tailored to a large project where no one person can claim ultimate ownership so you need explicit rules for such behaviour.
This is not the case with this project, which is - despite its size - still a *personal* project. I am the owner of this project, and I retain full rights to warn and ban under a variety of circumstances.

The "Pledge" and "standards" look pretty good, I'll keep them mostly intact, but the "Enforcement" needs to be drastically different.

**Comment by metablaster** [comment]
> but they feel tailored to a large project where no one person can claim ultimate ownership so you need explicit rules for such behaviour.

To my understanding code of conduct also applies to users posting issues or commenting on issues.
Although I never understood how one could ban someone from creating an issue or commenting.

**Comment by touhidurrr** [comment]
> To my understanding code of conduct also applies to users posting issues or commenting on issues.
Although I never understood how one could ban someone from creating an issue or commenting.

I guess they wrote it thinking of not just GitHub but an open source community as a whole.

**Comment by touhidurrr** [comment]
I also use Code of Conduct in many of my projects. Even though none of them has as many stars as Unciv. Lol.

**Comment by yairm210** [comment]
You know what, seeing as there have been no real cases that have required such handling, I'm fine with merging this currently as-is and changing it if/when necessary

**Pull request merged**
