### PR TITLE
Sort Maintenace Using Fixed Point

### PR DESCRIPTION
**Pull request by itanasi**
Using suggestion from @SomeTroglodyte, try sorting using fixed point value to avoid float bugginess

### CODE REVIEW

**Comment by yairm210** [comment]
Please add a comment explaining why, because this reads as completely arbitrary

**Comment by itanasi** [comment]
The theory is that with floating point, certain values will be too close and so when comparing A to B you'll have a different result than B to A. So perhaps sorting using fixed point will ensure consistent value ordering.

**Comment by yairm210** [comment]
I mean in the code :)
Imagine being the person who reads this line and it's like: ????

**Comment by SomeTroglodyte** [comment]
And remember, I pointed out a similarity, there's no proof this was behind any crashes, that should also be documented under source control

**Comment by itanasi** [comment]
Ah, good thought. Done!

**Pull request merged**
