### PR TITLE
Update NewGame,SaveGame,LoadGame,Options.json

### PR DESCRIPTION
**Pull request by Smashfanful**
New line

### CODE REVIEW

**Comment by lishaoxia1985** [comment]
i check your repositories, you have not update you branch yet.

**Comment by Smashfanful** [comment]
How do I do that?

**Comment by yairm210** [comment]
It's fine, as long as he's only editing the json files via the Unciv repo he doesn't need to
If he decides to start running it, though, then it becomes a problem.

**Comment by Smashfanful** [comment]
Don't worry, I don't intend to run it

**Pull request merged**
