### PR TITLE
Update NewGame,SaveGame,LoadGame,Options.json

### PR DESCRIPTION
**Pull request by VoyteeG**
Hopefully this time is OK. Some polish additions.  By the way I've noted missing starting eras. Is it correct?
Note 1

### CODE REVIEW

**Comment by yairm210** [comment]
Not sure what eras you think are missing

**Comment by VoyteeG** [comment]
After line "Starting Era" up to line "It looks like we can't make a map with the parameters you requested!". It should be Ancient, Classic, Medival etc....

**Comment by VoyteeG** [comment]
One more question: Should I delete a branch after have been merged?

**Comment by yairm210** [comment]
That's up to you, but if you're creating a new branch every time then that sounds like a good idea

**Pull request merged**
