### PR TITLE
Added thai translation

### PR DESCRIPTION
**Pull request by NoNZeeZ**
Ohhh it took me 3 day to finish this. This work is manual translated by me. I have a little request if you could put my real name to be credit in game because I'm doing my portfolio and I want some evident to claim that I did thai translate in this game. It's ok if you don't want to it just a little sad for me TT

### CODE REVIEW

**Comment by yairm210** [comment]
I think that you've made a good point, maybe we should be adding ALL the contributor names to the credits file

**Comment by yairm210** [comment]
Actually, from here you can see all the contributors:
https://github.com/yairm210/Unciv/graphs/contributors
Would that be good enough for your purposes?

**Comment by NoNZeeZ** [comment]
Yes dev that is good enough for me. But how do I merge my translate file into your res

**Comment by yairm210** [comment]
By the way, under your own user you can see all the contributions you've made to ALL repositories, so for a portfolio that's probably even better :)

**Comment by yairm210** [comment]
I just checked, and apparenly the font renderer doesn't know how to render  the little bits (like ั) correctly
How important are they for understanding the language? Are they critical?

**Comment by NoNZeeZ** [comment]
Yes. All of It, is critical. In thai the ั ะ ำ า  stuff is like vowel in english for example ั in thai [กับ meaning with ] if it without ั it would be กบ it's mean a frog

**Pull request merged**
