### PR TITLE
Update Romanian.properties

### PR DESCRIPTION
**Pull request by cosylynx**
I made a contribution to Romanian translation. Up to rougly line 800 should be translated until now. I'd be happy you introduced  these translation to the game!

### CODE REVIEW

**Comment by xlenstra** [comment]
Placeholder `[civInfo]` not found in `Romanian` for entry `Current leader is [civInfo] with [amount] [stat] generated.`
    Placeholder `[civInfo]` not found in `Romanian` for entry `Current leader is [civInfo] with [amount] Technologies discovered.`
    Placeholder `[resourceName]` not found in `Romanian` for entry `Build [improvementName] on [resourceName] (200 Gold)`
    Placeholder `[civName]` not found in `Romanian` for entry `[civName] is afraid of your military power!`
    Placeholder `[amount]` not found in `Romanian` for entry `+[amount] untradable copies`
    Placeholder `[timeUnit]` not found in `Romanian` for entry `Last refresh: [time] [timeUnit] ago`
    Placeholder `[cityname]` not found in `Romanian` for entry `The city of [cityname] has started constructing [construction]!`

For more info on this, see the [wiki](https://github.com/yairm210/Unciv/wiki/Translating)

**Comment by yairm210** [comment]
Still relevant?

**Comment by cosylynx** [comment]
Yes. Just I can't figure out how to fix the errors. I don't really
understand.

sâm., 25 dec. 2021, 21:09 Yair Morgenstern ***@***.***> a
scris:

**Comment by yairm210** [comment]
You're missing parameters that should appear in the lines that xlenstra mentioned
You can see in other lines how you keep the woods in square brackets untranslated

**Pull request merged**
