### PR TITLE
Update Translations.json

### PR DESCRIPTION
**Pull request by Smashfanful**
Bison and Cocoa are from Brave New World, Copper, Citrus, Salt and Truffles are from Gods & Kings.
Age translations edited.

### CODE REVIEW

**Comment by Am-per-Sand** [comment]
😲 I found even Crab in https://github.com//yairm210/UnCiv/blob/master/android/assets/jsons/TileResources.json

Will you add this Salt to that file too?

**Comment by yairm210** [comment]
Since the translations already exist, I'm fine with them being there, it's a kind of future-proofibg
What I'm against is for non-implemented data to be in the real lists (improvements, buildings, units etc)
Sorry for the confusion

**Comment by Smashfanful** [comment]
CAn someone merge this? I just can't.

**Comment by yairm210** [comment]
As I said, I want to keep the bison and other existing translations...
Undo the removal and I'll merge it

**Comment by yairm210** [comment]
Now it has conflicts as well... 
You know what, I'm just going to close this, add them to a different commit they're still missing

**Pull request closed without merging**
