### PR TITLE
Update Spanish.properties

### PR DESCRIPTION
**Pull request by stixZman**
Spanish translation update

### CODE REVIEW

**Comment by xlenstra** [comment]
> How do we merge our PR, if there is another way than editing one of the files @xlenstra ...

Easiest would be to edit one of your files and close the PR for the other. Altneratively, you can wait until the next release. Your translation will then be merged into master, and then the differences between master and stixZman's translation can be resolved in this PR.

**Comment by xlenstra** [comment]
Are you still planning on fixing these problems, stixZman?

**Comment by xlenstra** [comment]
Closing as this is outdated and unlikely to be fixed. If you disagree, comment, and I'll reopen.

**Comment by ArchDuque-Pancake** [comment]
@stixZman Hi, where can we talk?

**Pull request closed without merging**
