### PR TITLE
The Celtic People Reboot

### PR DESCRIPTION
**Pull request by SomeTroglodyte**
See #4658. Now uses a Conditional, and most code changes are linting or evolution of the system that's due anyway.

Maybe remove unused `ConditionalNeighborTiles` - typed when I assumed I'd find a nicer alternative for "and".

### CODE REVIEW

**Comment by logicminimal** [comment]
did unimproved forest work?

**Comment by SomeTroglodyte** [comment]
Todo:
- Edinburgh and Dublin need to be removed from City states in a way that doesn't immediately break saved games -> CS list needs G&K workover anyway - separate PR.
- Pictish Warrior icon redo - done.
- Find the other unique with a kind of terrain filter "and" and compare: It's Petra, and the scope is different but the approach comparable -> leave proposal as is.

**Comment by AdityaMH** [comment]
Lastest commit make me laugh

**Comment by Mugi1234** [comment]
```
```bbbmmmmmmll
Mmmmmmm. Nnnnnnnnnnmm

, ..   
```
```

**Comment by SomeTroglodyte** [comment]
Reference, among many:
https://en.wiktionary.org/wiki/Llanfairpwllgwyngyllgogerychwyrndrobwllllantysiliogogogoch

The original Civ5 made an achievement out of that, so it's worth mentioning. Also, the village itself is a tourism magnet - though it is not at all located in Boudicca's historical domain.

**Comment by logicminimal** [comment]
> 
> 
> Reference, among many: https://en.wiktionary.org/wiki/Llanfairpwllgwyngyllgogerychwyrndrobwllllantysiliogogogoch
> 
> The original Civ5 made an achievement out of that, so it's worth mentioning. Also, the village itself is a tourism magnet - though it is not at all located in Boudicca's historical domain.

we should also add achievements and/or easter eggs sometime.

**Comment by AdityaMH** [comment]
> Reference, among many: https://en.wiktionary.org/wiki/Llanfairpwllgwyngyllgogerychwyrndrobwllllantysiliogogogoch
> 
> The original Civ5 made an achievement out of that, so it's worth mentioning. Also, the village itself is a tourism magnet - though it is not at all located in Boudicca's historical domain.

But still funny and just imagine how to read this f****ng names.

**Pull request merged**
