### PR TITLE
Repo wiki resync. — Requires #5854.

### PR DESCRIPTION
**Pull request by will-ca**
This is a version of #5854 that also includes the changes to the wiki since then.

Separate PR to avoid having to re-review and re-test everything from #5854.

Once #5854 is merged, the diff for this PR should include only Markdown changes. (I may need to rebase again onto `master` first.)

Checked by visually comparing diffs of Wiki and this branch side-by-side.

Oh, I think I also had a code editor add-on that automatically reformatted and updated the Table of Contents on one of hte pages… The result looks fine though.

### CODE REVIEW

**Comment by yairm210** [comment]
Ayy self conflict

**Comment by will-ca** [comment]
Cool. Rebase fixed it without me even having to do anything.

**Review by xlenstra — APPROVED** [review]

**Comment by will-ca** [comment]
Well now… Let's see if this works.

**Comment by will-ca** [comment]
update wiki

**Comment by will-ca** [comment]
Hoorah!

…Oh, did I not mention the `.mde` files? AFAICT, those are just backups created by `sed` due to the REGEXes used to translate link formats from AS/GH tree format to GH Wiki format. They can be safely ignored.

I'll skim the diff filtered to `*.md`s to make sure there's nothing being clearly broken or accidentally reverted.

**Comment by will-ca** [comment]
@yairm210 The `update wiki` run above also added a footer on all the Wiki pages saying to PR against `/docs/wiki` in the main repo instead. I think the Wiki should be [made publicly read-only](https://docs.github.com/en/communities/documenting-your-project-with-wikis/changing-access-permissions-for-wikis) now, as any edits to it would only conflict with and eventually be overwritten by the next `update wiki` PR (but still recoverable from the Wiki commit history).

**Pull request merged**
