### PR TITLE
 Allow city to acuqire nearby tiles from friendly cities.

### PR DESCRIPTION
**Pull request by ninjatao**
As long as in range 3.

### CODE REVIEW

**Comment by yairm210** [comment]
Why did you make a wrapper function (Aquire Ownership) that just wraps an existing function (take ownership)? Just make that function public

**Comment by ninjatao** [comment]
I was wondering if you have strict rules about public/private methods. ^_^

**Comment by yairm210** [comment]
Nope, readability rules this repo 😈 
Fix that and I'll merge 😉

**Comment by ninjatao** [comment]
Cool.  👍  Updated.

**Comment by ninjatao** [comment]
I will see if I can do that.

**Pull request merged**
