### PR TITLE
Update Romanian.properties

### PR DESCRIPTION
**Pull request by alexban011**

### CODE REVIEW

**Comment by SomeTroglodyte** [comment]
> serverului

_Beautiful_ language 😍. And nice work. Lotsa progress.

**Comment by alexban011** [comment]
> _Beautiful_ language heart_eyes. And nice work. Lotsa progress.

Haha! Thanks ! :)

**Comment by yairm210** [comment]
prepare version

**Comment by yairm210** [comment]
Version rollout PR created

**Pull request merged**
