### PR TITLE
"Replacable Parts" is now "Replaceable Parts"

### PR DESCRIPTION
**Pull request by L314**
#571 Magic happened unmagic'd it. still fixed.

### CODE REVIEW

**Comment by yairm210** [comment]
Wow, this is almost perfect!
Only 1 thing is missing - when loading a game, replace existing tech names and researched tech names

**Comment by L314** [comment]
Do you mean on games previous to the push or any loaded game?

**Comment by yairm210** [comment]
Games that were created before the push will still have the previous name in the saved game state, which could lead to inconsistencies or worse, crashes

**Comment by yairm210** [comment]
I'll deal with the last part now

**Comment by L314** [comment]
Thanks, I just got busy so I wasn't able to fix it quickly. I'll have to checkout how you fixed it

**Pull request merged**
