### PR TITLE
'Swap units' sound and more attack sounds

### PR DESCRIPTION
**Pull request by SomeTroglodyte**
Started as A Tribute To @avdstaaij and got a little out of hand.

#### Now
- Several units have no attack sound at all
- Some have sounds not fitting at all - e.g. Bomber

#### New
- 10 new sounds totaling 168kB. I could offer a 43k chimes that I think sounds as good as the current thus offsetting 65k of that load...
- I hope that's _all_ current units
- I hope the sound for the 'swap' unit action is not too scifi-y
- Most are used several times, the ones which are not - I see them as weak easter eggs. May take some people a long time to hear a certain one for the first time, I hope that'll be a nice surprise.

#### Not addressed
- Units capturing others sound maybe not play their attack sound?
- Less so - capturing cities could have a kind of 'marching' sound?
- Infantry - for the more modern ones 'shot' doesn't quite fit, but I refrained from reassigning them to 'machinegun' for now.

#### List of changes (my work list, unformatted, for reference)
Cannon    -> cannon
Artillery    -> artillery
Rocket Artillery    -> artillery

Caravel    -> cannon
Turtle Ship    -> cannon
Privateer    -> cannon
Frigate    -> cannon
Ship of the Line    -> cannon
Ironclad     -> shipguns
Submarine   -> torpedo
Battleship     -> shipguns
Destroyer     -> shipguns
Nuclear Submarine   -> torpedo
Missile Cruiser     -> shipguns

Triplane    shot   -> machinegun
Fighter shot   -> machinegun
Zero    shot   -> machinegun
Great War Bomber    shot    -> bombing
Bomber  shot    -> bombing
B17 shot    -> bombing
Jet Fighter shot    -> jetgun
Stealth Bomber  shot    -> bombing

Anti-Aircraft Gun   machinegun
Anti-Tank Gun   -> machinegun
Mobile SAM  shot    -> missile
Guided Missile    -> missile
Helicopter Gunship  shot -> machinegun

Landship    -> tankshot
Tank    -> tankshot
Panzer    -> tankshot
Modern Armor    -> tankshot

Great War Infantry  shot
Foreign Legion  shot
Infantry    shot
Marine  -> shot
Paratrooper shot
Mechanized Infantry    -> tankshot

Naresuan's Elephant     shot    -> elephant
War Elephant    horse    -> elephant

### CODE REVIEW

**Comment by ravignir** [comment]
I don't like swap sound. I would prefer the double move sound (whoosh) .

**Comment by SomeTroglodyte** [comment]
> I don't like swap sound. I would prefer the double move sound (whoosh) .

Duly noted. Too 'teleport'. When I saw the comment I immediately associated that one I had already heard, so it had to be the one...

Will try a mix of the existing woosh later.

**Comment by ravignir** [comment]
Yes, better.

**Comment by AdityaMH** [comment]
Worker improve tilescsound?

**Pull request merged**
