### PR TITLE
Update German.properties

### PR DESCRIPTION
**Pull request by jacer2010**
Some additional translation and corrections

### CODE REVIEW

**Review by SomeTroglodyte — APPROVED** [review]
> Social policies = Sozialpolitik

There's multiple policies, so the plural is somewhat relevant. Maybe replace 'politik' as in 'politics' with a translation closer to 'policies' - sorry I got no better idea than 'Richtlinien'. Just food for thought.

Otherwise - looks nicely done.

**Comment by yairm210** [comment]
merge translations

**Comment by yairm210** [comment]
Translations branch created

**Comment by yairm210** [comment]
Translations PR created

**Comment by jacer2010** [comment]
> > Social policies = Sozialpolitik
> 
> There's multiple policies, so the plural is somewhat relevant. Maybe replace 'politik' as in 'politics' with a translation closer to 'policies' - sorry I got no better idea than 'Richtlinien'. Just food for thought.
> 
> Otherwise - looks nicely done.

Thanks for the "food". :) I know what you mean.

The plural of "Politik" (Politiken) is rarely used and sounds wrong. So I changed it to "Sozialpolitik". But I have to say this is also wrong.

Maybe "Herrschaftsformen" (forms of government) is the solution? What do you think.

**Comment by SomeTroglodyte** [comment]
I get you, they all sound wrong. I always thought 'policies' sounds most like the group policies in tinysquishy wingdoze or similar mechanisms for managed fine tuning of systems behaviours... Maybe look in IT manuals for inspiration? [That would still lead to 'Richtlinien'](https://docs.microsoft.com/de-de/mem/configmgr/desktop-analytics/group-policy-settings#group-policy-settings). If I knew a clearly better choice I'd have suggested it.

**Pull request merged**
