### PR TITLE
Support for multiple terrain features Part 1

### PR DESCRIPTION
**Pull request by GGGuenni**
Isn't this sufficient?

### CODE REVIEW

**Comment by yairm210** [comment]
Can you load existing games with this configuration? Does 'next turn' preserve features? If so, it's enough :)

**Comment by GGGuenni** [comment]
Next turn preserved the features but loading an old file removed everything.
But that's fixed now so both are working. Even though line 537 feels pretty weird :D
`terrainFeature = terrainFeature // getter returns field, setter calls terrainFeatures.add()`

**Comment by yairm210** [comment]
This is why I asked to add newTerrainFeature as an intermediate - you now treat terrainFeature sometimes as a field, sometimes as a property

Not only is this confusing in code, it also means it's playing double - meaning it's coupling two separate tasks, 'convert usages of single terrainFeature to usage of list' and 'convert saved values of terrainFeature so saved value of list'.

I don't like it, but I'll accept it, since I trust that you'll be working on the conversions of single-to-list :)

**Comment by yairm210** [comment]
Noooo I just thought of something a second after accepting :(
If I'm reading this right, we don't touch the field after reading from it - meaning, if we remove a forest, it'll be removed from the arraylist but now from the field, and so on nextTurn the forest will be loaded from the field again
Can you check that removing features works?

**Comment by GGGuenni** [comment]
It does work, the forest is not appearing again but I'm not sure why and that is indeed not good... I tested loading an old save removing the forest, save before and after removing click next turn after removing and loading both saves and repeat. 
sorry about that should have stuck to your plan.
Do you want to revert the commit?

**Comment by GGGuenni** [comment]
I don't know why but after serializing and then deserializing every field which wasn't null is now null and all values are properly stored in the array...
If you don't want to revert the changes I would change the getter to
```
get() {
            if (terrainFeatures.firstOrNull() == null && field != null) //if terrainFeatures contains no terrainFeature maybe one got deserialized to field
                terrainFeatures.add(field!!)
            field = null
            return terrainFeatures.firstOrNull()
}
```
This sets every field to null when the map gets loaded
just to be save

**Comment by yairm210** [comment]
There is a major issue that we have to address - currently in the map editor each terrain feature overrides the existing one, but if we can have multiple terrain features then we should have a way to differentiate those that can be together and those that can't, this probably can be solved with a unique on the terrain feature for hill?

**Comment by yairm210** [comment]
Well, we'll need to do that anyway for the map generation, we can just have them be occursOn the other terrain feature.

**Pull request merged**
