### PR TITLE
Custom map size

### PR DESCRIPTION
**Pull request by alkorolyov**
From suggestions chat.
Decided to change `enum class MapSize` to ordinary class in order to be able to store custom `radius`, `width `and `height ` with minimum modification of other code.
Added UI for `Custom` map size option.

### CODE REVIEW

**Comment by yairm210** [comment]
Not entirely sure where you're going with this
I get the 'not enum', but there's still no way for a user to add a 'custom map size', right?
Also, if you've changed the UI, pics please =)

**Comment by alkorolyov** [comment]
Hi,

Sorry, didn't make it clear.
On mapOptions table when user selects mapSize: `Custom`, there are additional inputs for radius or height and width depending on map shape. They are hidden when predefined mapSizes are choosen. Please see it on screenshoots:


custom_map_size_1
custom_map_size_2

**Comment by yairm210** [comment]
If we're changing an existing property in the current maps, we need to address how the change affects current games.
If I were to update, and open up my current game where the mapsize in still jsonified as an enum, would the game load? When I create a new game out of my current game, what happens?

**Comment by lishaoxia1985** [comment]
@yairm210 if it's possible the width should be always ＞the height.

**Comment by lishaoxia1985** [comment]
@alkorolyov I hope you can change the default hexagonal map ⬢ like this:⬣, because it can show more and more in mini map.

**Comment by yairm210** [comment]
@alkorolyov Did you check what happens to existing games with this change?

**Comment by alkorolyov** [comment]
Not yet,

I will try to check tomorrow. After all was wondering if we really need this feature...

**Comment by alkorolyov** [comment]
@yairm210 
Hey, I checked with older saves and apparently it doesn't serialize well from previously saved games/maps.
Could you give me ideas how to address this issues? 
How can we change the loading class from json "on the fly"? Or should we create "oldGameInfo class" then convert it to the new one?

`val game = json().fromJson(GameInfo::class.java, getSave(GameName, multiplayer))`

**Comment by yairm210** [comment]
The main way of doing this is having both the old and new versions live alongside each other - I do this all the time
(for example, right now, with the migration of policies and civ uniques)

What this means practically is that the mapSize class will have a slightly different name (like MapSizeNew or something, IDK), and will be a separate parameter in the map parameters (mapSize instead of size, for instance).
Mark the old, deprecated parameter with an `@Deprecated` with a comment of what version it was deprecated in
In the gameInfo.setTransients(), you'll see a whole bunch of code dedicated to 'migrating' old stuff to new stuff, and there you can put a conversion of the existing old size to the new mapSize

**Comment by alkorolyov** [comment]
Should be ok to merger now. Works with both older an new maps/saves.

**Comment by yairm210** [comment]
I think it's time! I was worried about this for several reasons, but I think that now's a good time to add this and deal with the consequences, rather than avoiding them.

**Pull request merged**
