### PR TITLE
1. In PickTechScreen all the Techs have the same size. 2.The tech in different era has different color. 3.About global status in victory status screen, you can touch the icons of Civs to check its policy tree and tech tree, but close button may lead to worldscreen

### PR DESCRIPTION
**Pull request by lishaoxia1985**

### CODE REVIEW

**Comment by yairm210** [comment]
I'll wait until you correct the bugs to merge this =)

**Comment by lishaoxia1985** [comment]
i'm thinking how to do that: 
1.When you check global status in picking policy tree screen and tech tree screen, right side button should be remove or set other words in button, such as " checking technology tree of civname", it's very good because we don't need to add another label in the screen to explain which civ we are checking.
2. When touch close button you can back the original screen.
3.we can remove our status in victory status if we improve global status screen or only show our status screen when we victory. i'm not sure how do you think about that.

**Comment by yairm210** [comment]
You know what, you can remove the clocks from the victory screen and I'll merge the rest for now

**Comment by lishaoxia1985** [comment]
ok,  besides close button, i think it's good.

**Comment by yairm210** [comment]
I don't think you should be able to see other civ's policy or tech trees...

**Comment by lishaoxia1985** [comment]
i'm not sure. i think you can give a setting for users to see or not to see.

**Comment by yairm210** [comment]
Also, please merge my main branch into yours, we're currently at a 80+ commit difference

**Pull request merged**
