### PR TITLE
Align (reduce) Embarked Defense Strength per Era

### PR DESCRIPTION
**Pull request by itanasi**
Based on #6226 findings from game

### CODE REVIEW

**Comment by SomeTroglodyte** [comment]
Sounds like a case to move the value to a json-read Era property. Also, `}else code` is twice unpretty. Other that that, looks clean and should work just fine.

**Comment by yairm210** [comment]
I completely agree with Trog.
This is a classic value to put in the eras, like embarkedUnitStrength or something

**Comment by itanasi** [comment]
Heh. Was thinking similarly, but didn't want to learn the JSON import code yet. I'll take a look

**Comment by SomeTroglodyte** [comment]
> learn the JSON import code

You don't need to. Era import is already there and will recognize new fields. Unless you use outlandish types or disrupt the default constructor it's auto-magic based on reflection. Since you just want one Int - no worries one should hope.

**Comment by SomeTroglodyte** [comment]
Linked the issue for you. Ya might be interested in [this](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) article.

**Review by yairm210 — APPROVED** [review]

**Pull request merged**
