### PR TITLE
Update Buildings.json

### PR DESCRIPTION
**Pull request by Smashfanful**
Some addings and fixes

### CODE REVIEW

**Comment by yairm210** [comment]
I added quotes for most of this buildings, but I guess I forgot to push the changes.

**Comment by Smashfanful** [comment]
> I added quotes for most of this buildings, but I guess I forgot to push the changes.

So what now?

**Comment by yairm210** [comment]
So I think I'll cancel this merger, tonight I'll push the changes and then you can make other changes to the file

**Comment by Smashfanful** [comment]
Alright, then

**Pull request closed without merging**
