### PR TITLE
delete unnecessary random(randomness.RNG)

### PR DESCRIPTION
**Pull request by lishaoxia1985**

### CODE REVIEW

**Comment by yairm210** [comment]
What does this improve?

**Comment by yairm210** [comment]
Why do you think this randomness unnecessary?

**Comment by lishaoxia1985** [comment]
Because this method is to search all tiles in waterTiles and TilesToCheck, so we can always choose the first or last element in every loop, random is unnecessary.

**Comment by lishaoxia1985** [comment]
In fact, the lake tile is not random, when you create water and land tiles, the lake tiles are determined too.

**Pull request merged**
