### PR TITLE
City-state allies with most influencing civ.

### PR DESCRIPTION
**Pull request by ninjatao**
https://github.com/yairm210/UnCiv/issues/806

### CODE REVIEW

**Comment by ninjatao** [comment]
Maybe add a notification for player's info?

**Comment by yairm210** [comment]
But how is the player supposed to know that once he reaches 60 influence they'll be allies?
We need to add something like 'influence for allies: 40/60'

**Comment by ninjatao** [comment]
Added notifications and tips in diplomacy screen. Also improved status check.

No TEST-RUN yet for the new commit. Please hold for a while.

**Comment by Smashfanful** [comment]
I think we also need notifications for when we're about to lose our Friendship or our Alliance with a City-State

**Comment by ninjatao** [comment]
Tested ok. However there is a very strange problem. If player is allied with a city-state, game throws exception between turns because tileMap of city-state has not been initialized.
I have to call setTransients() to avoid crash. Please let me know if there are better ways.

**Comment by yairm210** [comment]
Tilemap of the...civ? Doesn't civInfo access tileMap via gameInfo?
If not, then where in gameInfo.setTransients is civInfo.setTransients called? Maybe we filter and don't set for city states for done strange reason?

**Comment by ninjatao** [comment]
11-05 00:04:14.275  9271 10931 E AndroidRuntime: FATAL EXCEPTION: Thread-7
 11-05 00:04:14.275  9271 10931 E AndroidRuntime: Process: com.unciv.app, PID: 9271
 11-05 00:04:14.275  9271 10931 E AndroidRuntime: kotlin.UninitializedPropertyAccessException: lateinit property       tileMap has not been initialized
 11-05 00:04:14.275  9271 10931 E AndroidRuntime:    at com.unciv.logic.city.CityInfo.getTiles(CityInfo.kt:120)
 11-05 00:04:14.275  9271 10931 E AndroidRuntime:    at com.unciv.logic.civilization.                                  CivInfoTransientUpdater$updateViewableTiles$2.invoke(CivInfoTransientUpdater.kt:32)
 11-05 00:04:14.275  9271 10931 E AndroidRuntime:    at com.unciv.logic.civilization.                                  CivInfoTransientUpdater$updateViewableTiles$2.invoke(CivInfoTransientUpdater.kt:14)
 11-05 00:04:14.275  9271 10931 E AndroidRuntime:    at kotlin.sequences.FlatteningSequence$iterator$1.                ensureItemIterator(Sequences.kt:277)
 11-05 00:04:14.275  9271 10931 E AndroidRuntime:    at kotlin.sequences.FlatteningSequence$iterator$1.                hasNext(Sequences.kt:265)
 11-05 00:04:14.275  9271 10931 E AndroidRuntime:    at kotlin.collections.CollectionsKt__MutableCollectionsKt.        addAll(MutableCollections.kt:139)
 11-05 00:04:14.275  9271 10931 E AndroidRuntime:    at com.unciv.logic.civilization.CivInfoTransientUpdater.          updateViewableTiles(CivInfoTransientUpdater.kt:32)
 11-05 00:04:14.275  9271 10931 E AndroidRuntime:    at com.unciv.logic.civilization.CivilizationInfo.                 updateViewableTiles(CivilizationInfo.kt:334)
 11-05 00:04:14.275  9271 10931 E AndroidRuntime:    at com.unciv.logic.civilization.CivilizationInfo.                 setTransients(CivilizationInfo.kt:326)
 11-05 00:04:14.275  9271 10931 E AndroidRuntime:    at com.unciv.logic.GameInfo.setTransients(GameInfo.kt:251)
 11-05 00:04:14.275  9271 10931 E AndroidRuntime:    at com.unciv.ui.worldscreen.WorldScreen$nextTurn$1.               invoke(WorldScreen.kt:328)
 11-05 00:04:14.275  9271 10931 E AndroidRuntime:    at com.unciv.ui.worldscreen.WorldScreen$nextTurn$1.               invoke(WorldScreen.kt:36)

**Comment by ninjatao** [comment]
Exception log above pressing Next Turn. It seems that setTransients has not been called for city-state. But should this function be called on loading instead of every turn?

**Comment by yairm210** [comment]
Ahhh I think I get it
You can see that the exception is encountered INSIDE civInfo.setTransients, I think that one transient is dependent on the other, so we need to ensure we set tileMap first

**Comment by yairm210** [comment]
That is,
We need to ensure we set the tilemap for ALL civs, before we update tiles for a single one. In gameInfo.setTransients.

**Comment by ninjatao** [comment]
All set.

**Comment by ninjatao** [comment]
> I think we also need notifications for when we're about to lose our Friendship or our Alliance with a City-State

Let's finish the function before improving user experience.

**Pull request merged**
