### PR TITLE
Forts and citadels (with AI)

### PR DESCRIPTION
**Pull request by JackRainy**
Based on the PR #1856 by @r3versi

### CODE REVIEW

**Comment by rh-github-2015** [comment]
Oh you smuggled a fix for TileEditorOptionsTable's potential null exception bomb into this. I resisted in order to make it a separate PR... Astounding that Studio is perceptive enough to decorate the file with those red squiggly lines but the compiler still eats it and it runs...

**Comment by JackRainy** [comment]
> Oh you smuggled a fix for TileEditorOptionsTable's potential null exception bomb into this.

That's by mistake :) The intention was to have it as a separate PR, just forgot to remove before push.

**Comment by yairm210** [comment]
Okay looks good enough!
We (and by that I mean 'our players, mostly') will have to play around with the AI to see if it builds Too Many Forts, but for now let's bring this in and see what happens!

**Comment by yairm210** [comment]
This has been a LONG standing problem due to the complexity of evaluating anything war-related, and especially versus civilian uses, so let's Bayesian it and start from this as a prior, and we can adjust along the way =)

**Pull request merged**
