### PR TITLE
Android: use best possible device frame rate

### PR DESCRIPTION
**Pull request by vegeta1k95**
Android improvement.

Usually Android devices have adaptable refresh rate: 
- when something going on onscreen, or user touches the screen, refresh rate is automatically set up higher
- when device is idle/nothig going on, refresh rate is set to default 60Hz. 

**Problem:**
But, occasionally (I haven't figured out precisely when) Android device just locks itself on 60Hz screen refresh rate, even if it is capable of more, and doesn't change it independently of touches, animations, etc.
This happens even if phone has 100% battery charge and even if currently plugged to a charger, so very unlikely it is power preserving mechanism.
It happens systemwide in all application which do not **explicitly** request the higher refresh rate.

_This can be tested via developed options FPS toggle._

**Solution:**
This PR allows devices with Android 6(M)+ to lift this restriction and request the highest refresh rate for a game.
So, this means the game will always have:
- Smooth panning and zooming (on 60Hz they seem kind of "laggy")
- Better touch responses.

### CODE REVIEW

**Comment by vegeta1k95** [comment]
Okay, I figured out when refresh lock happens: 
It happens when screen brightness is turned below half (manually or automatically, at night).

I always wondered, why game seems so laggy at night while playing in my bed 😁

**Comment by yairm210** [comment]
Looks good, but this is truly an area where I have no expertise whatsoever so I'm not sure I'm qualified to review
@GGGuenni ?

**Comment by GGGuenni** [comment]
Well, I didn't know this is a thing. [Docs](https://developer.android.com/guide/topics/media/frame-rate) state that using `supportedModes` is not required but this way we always get max refresh rate which is fine. (?)  Honestly, I'm not able to see a difference even between a 75hz and a 144hz monitor so I'm probably also the wrong person to ask 😂 
Is the higher refresh rate noticeable regarding battery life? Android is probably lowering the refresh rate automatically when in battery saving mode right?

> The app does not need to consider the actual supported display refresh rates, which can be obtained by calling [Display.getSupportedModes()](https://developer.android.com/reference/android/view/Display#getSupportedModes()), in order to safely call setFrameRate(). For example, even if the device only supports 60Hz, call setFrameRate() with the frame rate your app prefers. Devices that don't have a better match for the app's frame rate will stay with the current display refresh rate.

**Comment by vegeta1k95** [comment]
> Android is probably lowering the refresh rate automatically when in battery saving mode right?

Android is lowering refresh rate to 60 Hz in the following cases (in order of urgency):

1) Battery save mode
2) Screen brightness below half
3) Screen is idle, nothing happening onscreen

This PR makes game override points 2) and 3): game uses highest refresh rate always, except for battery save mode, in which it is lowered to default 60Hz.

**Review by GGGuenni — APPROVED** [review]
Then it's fine I guess

**Pull request merged**
