### PR TITLE
Support for multiple terrain features per tile

### PR DESCRIPTION
**Pull request by GGGuenni**
I'm creating this PR because I'm a bit lost right now.
I changed the type of terrainFeature from String? to ArrayList\<String\> and every occurrence of it (damn public variables). But there is a lot of potential for bugs here so I don't think this is the way to go.
Any idea how I could make the change more gradually?

### CODE REVIEW

**Comment by yairm210** [comment]
A. Rename 'terrainFeature' to 'newTerrainFeature' with references
B. Recreate terrainFeature as a val
C. Change newTerrainFeature to a property, that encapsulates terrainFeature.
This is step 1, and provides us with a separation between 'data as stored in the game files' and 'data as used in code'. We'll use this later.

**Comment by yairm210** [comment]
Step 2:
A. Create new val terrainFeatures
B. On tileInfo.setTransients copy data from terrainFeature to terrainFeatures, if terrainFeature is not null
C. Redirect newTerrainFeature to terrainFeatures.first()

You now have the same data you had, but within a list, and for all practical purposes the usage it's the same. Technically you can deprecate terrainFeature now.

This should be in a separate PR, after step 1 is merged.

**Comment by yairm210** [comment]
Step 3:
Go through every usage of newTerrainFeature and convert it to use terrainFeatures.
Each one of these changes, by itself, should be mergable - they shouldn't affect each other!
This means we can merge them in gradually and we don't need one big pr for them all which makes things way easier

**Comment by GGGuenni** [comment]
That sounds like a good plan. But is step 1 really necessary? Couldn't I just 

A. Create new val terrainFeatures
B. Make terrainFeature a property that redirects to terrainFeatures.first()
C. On tileInfo.setTransients copy data from terrainFeature to terrainFeatures, if terrainFeature is not null

or is it important to you that terrainFeature has a more distinct name?

**Pull request closed without merging**
