### PR TITLE
Justifiable wars

### PR DESCRIPTION
**Pull request by tuvus**
This PR adds in formal and surprise wars
Part of #11380, #10070

A Civ that has denounced another Civ for 5 turns may declare a formal war instead of a surprise war. A formal war caries the current diplomatic penalties of -5 relations to most Civs for warmongering. If the Civ has not denounced the other civ they will get a warmongering penalty of -20.
Join wars are treated as a formal war.

The type of war that you will declare is shown on the declare war confirmation screen.

<details><summary>Pictures</summary>

_Note, I have fixed the spelling of "suprised" to "surprised" since this picture_

DeclareFormalWar

DeclareSurpriseWar

</details> 

I also added a new Wars tutorial page to help inform players about this. We don't have to add it to another document in order to translate it right?

<details><summary>Picture</summary>

WarsTutorialPage

</details> 

Finally I added in a little AI change that makes them use formal wars around 80% of the time and surprise wars 20% of the time.
In the future I plan to add extra logic that tells the military units to prepare for wars against civilizations that were denounced.

The AI will also prepare for wars by moving their units to the closest city to denounced civilizations. This is just experimental and is a placeholder for a much more robust system.

### CODE REVIEW

**Comment by AdityaMH** [comment]
using civ6 diplomacy logic for civ5 diplomacy. nice.

**Comment by yairm210** [comment]
This *is* a departure from Civ V spec, and thus should be behind some kind of unique in modoptions

**Comment by tuvus** [comment]
Not really?

**Comment by yairm210** [comment]
When I was in basic army training, they showed the How Not To Be Seen sketch, with subtitles 
Maybe a third of the people knew English, I was the only one who knew this was a comedy sketch, *including the commanders*, I was giggling the entire time
Someone somewhere had a *really good* sense of humor 🤣

**Comment by tuvus** [comment]
Closing this idea, the most important part has been implemented in #11688. The rest I will have to think about a way to design it in a moddable way. For now I have other priorities.

**Pull request closed without merging**
