### PR TITLE
Worldscreen keys for Civilopedia and Overview

### PR DESCRIPTION
**Pull request by SomeTroglodyte**
Enhancing usefulness of #3822: E (O was taken by Promote unit) goes to Empire Overview screen, F1 to Civilopedia, V to victory screen.

### CODE REVIEW

**Comment by yairm210** [comment]
I'm sorry, I can't bring myself to like the F1-enabling hack at all :/
How about we stick to using a '?' to open the Civilopedia for now

**Comment by SomeTroglodyte** [comment]
I don't really like the hack either - but I dismissed '?' due to it moving a lot between int'l keyboard layouts, e.g. german requiring a shift... And [allegedly](https://segmentnext.com/2010/09/23/civilization-v-hotkeys-keyboard-shortcuts-guide/) Civ5 has it on F1.

Will mull it over a little.

**Comment by SomeTroglodyte** [comment]
Well I can't come up with a painless _and_ correct way. 'correct' would mean keeping the two pieces separate -> data class(Char, Int) to express what was typed...

CameraStageBaseScreen would have stuff like:
```kotlin
data class KeyCharAndCode(val char: Char, val code: Int = 0)

open class CameraStageBaseScreen : Screen {

    var keyPressDispatcher: HashMap<KeyCharAndCode, (() -> Unit)> = hashMapOf()

    init {
        stage.addListener(
                object : InputListener() {
                    override fun keyTyped(event: InputEvent?, character: Char): Boolean {
                        val key = KeyCharAndCode(character.toLowerCase(), if (character==Char.MIN_VALUE) event.keyCode else 0)

                        if (key !in keyPressDispatcher || hasOpenPopups())
                            return super.keyTyped(event, character)

                        try {
                            keyPressDispatcher[key]?.invoke()
                        } catch (ex: Exception) {}
                        return true
                    }
                }
        )
        ...
```
... which is good - but every single place the dispatcher is used elsewhere would need at least a Char -> KeyCharAndCode(Char) patch ...

So, no _really_ good ideas so far. Still mulling. If this were python I'd know an approach - involving many underscores.

Wait a minute - Kotlin also supports rewriting indexers, but I haven't learned that so far. An overloaded indexer should be doable, so the existing keyPressDispatcher uses could stay unaltered and keyPressDispatcher[Input.Keys.F1] would work, too... This would be an elegant trade-off investing complexity in declaration/implementation for a major gain in usage simplicity... Or am I guessing completely wrong?

**Comment by SomeTroglodyte** [comment]
Freaky holy °/!&"%/§ - that was easy so far - didn't even need to look into documentation just remember seeing all those property accesses being equivalent to get/set in the IDE's little helpers - pity I typed it into the wrong branch...

**Comment by SomeTroglodyte** [comment]
OK - so please freeze this until #3850 is decided.

**Comment by SomeTroglodyte** [comment]
I'm now convinced #3850 + #3851 are the way, closing this

**Pull request closed without merging**
