### PR TITLE
Update French version + duplication + reorganisation

### PR DESCRIPTION
**Pull request by B5656**
I commented some duplication and reorganised some part of the file, but it's begin to be too big too make it clear

### CODE REVIEW

**Comment by yairm210** [comment]
Do you think the translation for should be split into several files, per subject (units/techs/buildings/policies)?

Do you think this would make the translation progress simpler?

When we started with the Translation done it was much smaller and made sense to unify everything, maybe that logic is no longer relevant

@lishaoxia1985  @Smashfanful

**Comment by B5656** [comment]
Make several files could be an idea, but the most important things is to find a proper way to organize the files. Currently, there is a few organisation, by "categories", but I can't say that it's really sorted.

What can I propose if you use the differents files system is :

File Units & fights:
-Unit list
-Unique abilitties List
-Promotion List
-Fight informations list

File Techs & policies : //This part is already well organized
-Techs & description List
-Policies & description List

File Buildings & Wonders :
-Buildings & description List
-Wonders & description List

File Informations :
-Everything that aren't in the others files

But if you choose to spread the translation file you should think of how you will make it work then, I didn't looked how it work, but it could be not easy to do it.

**Comment by yairm210** [comment]
If I take the info as-is and put it in several files, I can definitely make it work

**Comment by lishaoxia1985** [comment]
There is a good method about solving Chinese language show without ttf font in this website.you can use his defined Class directly,  although he write it with java. 
https://github.com/badboy-tian/nativefont <https://github.com/badboy-tian/nativefont,you>

**Pull request merged**
