### PR TITLE
Internet connectivity test before starting a new mp game

### PR DESCRIPTION
**Pull request by alexban011**
It checks for internet connection before starting a new mp game to avoid #6649 

Many thanks to @SomeTroglodyte for most of the code and for explanations (#6675 )

### CODE REVIEW

**Comment by SomeTroglodyte** [comment]
My aren't you lucky - first #6666 now another symmetrical PR number...

If you're starting over, it would have been better not to work in _your_ master, but a separate branch. Numerous +1's - Studio workspace, clearer merging, others can check out your branch a bit easier,... Some arguments in my "scratchpad" repo, I hope I already mentioned it? Just FYI.

That branch I offered - i hope it was clear enough - the architectural parts is what I paid attention to, UI not so much. I trust you will do the tuning and testing of those parts.

**Comment by SomeTroglodyte** [comment]
The diff contains quite some pure formatting changes, making reading it harder. I like do do a _little_ linting around places I'm changing for a "meat and bones" branch, but extensive formatting should be in dedicated PR's - if the reviewer knows it's not meant to change anything, that's easier to see, and the other kind -with less linting- better leads the eye to where the ~~naughty~~ important bits are.

That and the thing with files ending with a newline or not. Personally I wouldn't care, Studio doesn't much, but github shows that nasty red forbidden sign (done as svg so I can't copy it here) - so I tend to make sure the ending `\n` is there........

So far just food for thought. You could point out where any new or changed parts (not in my demo or upstream master) are worth reading...

**Comment by alexban011** [comment]
> My aren't you lucky - first #6666 now another symmetrical PR number...
> 
> If you're starting over, it would have been better not to work in _your_ master, but a separate branch. Numerous +1's - Studio workspace, clearer merging, others can check out your branch a bit easier,... Some arguments in my "scratchpad" repo, I hope I already mentioned it? Just FYI.
> 
> That branch I offered - i hope it was clear enough - the architectural parts is what I paid attention to, UI not so much. I trust you will do the tuning and testing of those parts.

Haha I haven't noticed this PR is also symetrical :)

Should I revert the master and start on another branch?

and the diffrence from your demo is in NewGameScreen.kt. When you press the Start Game button it displays a popup if there is no internet, by using the code in your demo.

**Comment by alexban011** [comment]
I'm gonna lose track so I'm just gonna keep a master in my repo

**Pull request closed without merging**
