### PR TITLE
German translations modscreen

### PR DESCRIPTION
**Pull request by SomeTroglodyte**
... and a meaning fix to @Mape6 's work I found only because I needed a check to confirm I rebased properly

### CODE REVIEW

**Comment by yairm210** [comment]
Resolve conflict plz

**Comment by SomeTroglodyte** [comment]
Sorry, the online resolver is broken and pulling/rebasing/pushing created chaos.

**Comment by yairm210** [comment]
How odd
The online resolver works fine for me
(On desktop, haven't tried on mobile)

**Comment by SomeTroglodyte** [comment]
I'm never surprised about such occurrences. Some sites break even with uBlock Origin only installed but deactivated for the site. <shrug/> ... I'm not even using my dear old PaleMoon for this, but official Ubuntu Chromium (PM is as I see it less compatible mainly due to its Javascript engine compiling at different times subtly altering timings and event sequences - some sites probably just ignore the body onload event when it comes too early os somesuch...), and uBlock is the only plugin (oops, and "Don't Close Window With Last Tab" - which would be superfluous if I knew how to apply google's GPO templates on Linux)...

rambling stops _now_

**Comment by SomeTroglodyte** [comment]
Say, the current german file has surprising leading blanks in e.g. lines 332, 764, 898... 
If I re-do this PR now, those would go, and I'd like to know why they are there beforehand.

**Pull request closed without merging**
