### PR TITLE
Keyboard support for next turn button and unit actions

### PR DESCRIPTION
**Pull request by SomeTroglodyte**
Small convenience feature: keyboard support on world screen. Works in Android emulator, too.

key | function
 --- | ---
space or n | whatever the next turn button currently offers
. | stop movement
f | sleep / fortify / found city
g | great person ability (not construct improvement)
i | improve / great person construct improvement / work boats build
m | start / stop automation
o | promote
p | pillage 
r | build road (only for the legion unit, only the actual UnitActionsTable buttons have a key)
t | set up
u | upgrade
x | start / stop exploration

Conflicts: last one from UnitActions.getUnitActions()  wins, which works nicely e.g. for the settler and 'f'.

### CODE REVIEW

**Comment by SomeTroglodyte** [comment]
Sorry for pushing a gradle plugin version update, dumb oversight. And for commenting out the double initialization, should have been a separate PR.

**Comment by yairm210** [comment]
Looks good!
Personally I was thinking of doing this with InputListeners, but having a hashmap ensures that there aren't 2 separate actions happening on a single keypress, which is good =)
1 point, though - I see that nowhere do you remove actions from the hashmap, which could lead to some combinations of "I select unit A -> I move to unit B -> I press a button and unit A is activated?!"
We should clear all unit keypresses before we assign new ones

**Comment by JackRainy** [comment]
I have 2 questions:
1) How will user get to know these hotkeys? Does it make sense to put a civilopedia page for that?
2) What happens if a user press "f" e.g. for a wounded tank? Will it "sleep" or "sleep until healed"? The same about a warrior - "Fortify" or "Fortify until healed"? Settler - "sleep" or "found a city"?

**Comment by rh-github-2015** [comment]
> nowhere do you remove

True. I'll tell ST to check this tomorrow.

**Comment by SomeTroglodyte** [comment]
>     1. How will user get to know these hotkeys

Quite true. I left this for later. Classic underlining of a single letter? Not seen since Office 95 or so. Civilopedia - definitely. Tedious.


>     2. What happens

Explaned somewhere - last one wins, and order defined by that long function building the actions. So - the Settler founds which is IMO good. All others - my inspection said all ambiguities are resolved to the better choice, but do check yourself. More eyes, more seen. Or test - I was lazy, so I had no contact let alone wounded units, so my assuption 'until healed' wins if present is untested.
But - if a 'choice' is bad, reorganize said function, button order will probably make more sense afterwards. I also wanted to economize - check usefulness, approach and technical quality first, optimize later.

> doing this with InputListeners

My first approach tried to tie some kind of event listener to the actual widget it relates to - but the trivial q&d code kept switching keyboard focus around so at any time only some keys worked, I couldn't find a common parent to tie the focus to and still have the event bubble down, and when the next step would have been to get a multiplexer in at the right level - stage - I took a step back. And discovered WASD. So this is half the lines of that first draft, clearer, and easier to maintain, hopefully.

> nowhere do you remove actions

Ouch! Immediately clear: The actions 'kept' would still apply to the original unit, no risk of improving a tile with an archer. Deselecting enough to demonstrate. Potential crash by disbanding. Latest commit passes my tests. Too ugly?

**Comment by yairm210** [comment]
One option for displaying this to the user is to have it in the button itself
Instead of "Fortify" it would say "Fortify (F)"
If that looks nice in the buttons it makes it immediately readable, and solved the 'unit actions with no corresponding letter' (like, "Sleep" doesn't contain an F)

**Comment by JackRainy** [comment]
> Classic underlining of a single letter?

This is definitely not an option since the translations can be any kind (with or without the letters).

>  configurable via json (or translation files

I like the idea having it configurable, however, I am not sure whether the change is worth it at all. How many customers/players use Desktop version? How many of them use hotkeys in TBS games?

**Comment by SomeTroglodyte** [comment]
Screen
Maybe? Why does Color(0xdfdfdfff) not work? No better way than parsing a string, 4 floats or lerp?

**Comment by yairm210** [comment]
I think that having the text be white is better for both readability and ease of use

**Comment by SomeTroglodyte** [comment]
Sorry I had to dig out the office machine and connect it to get this out.
What about "mouse"over on mobile? Ah - mostly no keyboard. OK. Though it should work - either on a note with stylus, having a certain global option on, or a physical mouse...

**Comment by yairm210** [comment]
I'm in favor of getting this to work first, and then later we can decide to change the android/desktop implementation or see if it's better to not have this on mouseover
Let's MVP this =)
For that, please resolve conflicts ;)

**Comment by rh-github-2015** [comment]
> MVP

[Which one](https://en.wikipedia.org/wiki/MVP_(disambiguation)) is that? Since this is a game: Most Valuable Player? :)

**Comment by SomeTroglodyte** [comment]
> please resolve conflicts

Can't. I can only view - the page https://github.com/yairm210/Unciv/pull/2316/conflicts has only visual UI elements enabled for me (next, prev, spaces and tabs mode).

**Comment by SomeTroglodyte** [comment]
What an experience. After trying to do that locally using git for over half an hour I gave up, killed, merged externally and was done in 10 minutes including rebuilding the IDE cache. Why did it have to hit me for the same file over and over again?

Replacement soon, after testing.

**Pull request closed without merging**
