### PR TITLE
Update Portuguese.properties

### PR DESCRIPTION
**Pull request by Tiger13p**
Language Update Request.

### CODE REVIEW

**Comment by yairm210** [comment]
Placeholder `[PolicyOrNationalWonder]` not found in `Portuguese` for entry `Requires [PolicyOrNationalWonder]`

**Comment by Tiger13p** [comment]
I think it's now repaired, can you check if it's ok, please?

**Comment by yairm210** [comment]
merge translations

**Comment by yairm210** [comment]
Translations branch created

**Comment by yairm210** [comment]
Translations PR created

**Pull request merged**
