### PR TITLE
Improve TranslationFileWriter (less hardcoding, fixes PolicyBranch)

### PR DESCRIPTION
**Pull request by SomeTroglodyte**
Fixes PolicyBranch names as mentioned in a late comment on #6131 
Not reaching the full scope of what the branch set out to find and fix, but as is already an improvement.

Open questions:
- ~~Why does the xltfw write the chance to be destroyed by nukes as requires translation even when already translated (I know why, what's mysterious is why not _all_ uniquetypes are doubled up)~~
- Conditionals seem to have xlt problems

### CODE REVIEW

**Comment by SomeTroglodyte** [comment]
Next discovery: `TranslationFileWriter` processes `UniqueTypes`, OK, and there's some hitch there as shown by `DestroyableByNukesChance` being output twice, once with existing translation copied, and once with "requires translation"... But it also processes `UniqueParameterType` knownValues lists, partially, in a very inconsistent way, which is the root behind "Enemy Land" not being requested for translation.

Unsure how to go about that:
- Remove and make sure the uniques, including conditionals and their parameters, are processed completely
- Make knownValues part of the public class contract and have `TranslationFileWriter` scan all of them

**Comment by SomeTroglodyte** [comment]
The next two pushes now do:
- Beginning of a framework to eliminate `TranslationFileWriter` hard-coding stuff depending on `UniqueParameterType`
- Use it to fix "The Spaceship" and the Fountain of Youth unique not translating - that's a giant hammer to flatten a tiny booger and could instead be done as templates, but - well - allows for more forgetfulness in the future
- A few missed entries that do belong in templates
- A translation run will be neutral on the included German

Next steps can already be seen as comments. Actually I had the system complete when Studio rolled back all my new code when I had only the translation folder right-clicked for Rollback... Getting that to be "neutral" meaning producing identical results won't make sense as the hard-coding is too off-the-mark, e.g. using a different placeholder than the typed Uniques for the same thing, or clear mapping where the hard-coded values belong in the UniqueParameterType's isn't always clear cut, so one has to move forward. Test results were almost neutral, good enough, and promise to be more future-proof. Remember, the whole thing where TranslationFileWriter hard-codes its guessing will be obsolete when all uniques are typed, anyway. At that point, `getTranslationWriterStringsForMatching` can go.

**Comment by SomeTroglodyte** [comment]
> DestroyableByNukesChance being output twice

Actually now I see that's a "Chance"/"chance" case difference, meaning an actual bug probably, thus an easy thing to get rid of

**Comment by SomeTroglodyte** [comment]
Much simpler, all the heavy hard-coding is gone from TranslationFileWriter, and it's a little faster despite less hash based lookups and more looping. The C/c fix follows existing translations and typical [n%] X precedents.

Next - scan conditionals to get that Enemy Land into the xlatoons.

**Comment by SomeTroglodyte** [comment]
OK should have committed all languages. Who'd have thought the test would compare the left side of a french xlt line with the right side of a german equivalent line and vice versa.

**Comment by SomeTroglodyte** [comment]
Hey wow - actually I'm five steps further on, also fixing Enemy Land, Rough terrain/Rough Terrain, "<sigh>", some trailing blanks that treating every line as Unique and therefore .trim()ing it have hidden, and so on. Soon, gotta pause first.

**Comment by yairm210** [comment]
Not a problem, you can have multiple PRs from the same branch, but I see no reason to not include changes so far :)

**Comment by SomeTroglodyte** [comment]
> multiple PRs from the same branch

Sure, but I preferred stashing and rebasing offline, keeping stuff up to date in an already published / partially merged branch gets hard quickly, and one _wants_ to test against the freshest codebase.

**Pull request merged**
