### PR TITLE
Update Brazilian_Portuguese.properties

### PR DESCRIPTION
**Pull request by Ranbut**

### CODE REVIEW

**Comment by xlenstra** [comment]
Placeholder `[amount2]` not found in `Brazilian_Portuguese` for entry `May buy [buildingFilter] buildings for [amount] [stat] [cityFilter] at an increasing price ([amount2])`

**Comment by Ranbut** [comment]
> ```
> Placeholder `[amount2]` not found in `Brazilian_Portuguese` for entry `May buy [buildingFilter] buildings for [amount] [stat] [cityFilter] at an increasing price ([amount2])`
> ```



> May buy [buildingFilter] buildings for [amount] [stat

**Comment by Ranbut** [comment]
Oh ok, sorry about this.

**Comment by GGGuenni** [comment]
Placeholder `[Great Prophet]` not found in `Brazilian_Portuguese` for entry `Minimal Faith required for the next [Great Prophet]:`

**Comment by Ranbut** [comment]
There is some way that I can verify if everything is ok, before requesting the pull?

**Comment by GGGuenni** [comment]
> There is some way that I can verify if everything is ok, before requesting the pull?

Well, there is a possibility to do so by following the [Building Locally](https://yairm210.github.io/Unciv/Developers/Building-Locally/) wiki entry and running the unit tests yourself BUT that's pretty overkill if you just want to translate the game.

It's also no problem and you don't have to apologize for it if the checks on GitHub fail. You can just press `Details` and check why the checks failed yourself or wait for us to extract the reason from the details as they can be quite overwhelming if you don't know what to look for.

To check this yourself, you have to search for an AssertionError and look at the test which is printed right before it.

Happy translating and thanks for your contribution!

**Comment by Ranbut** [comment]
I hope now it's ok, thanks for the help. I have built and run the game, it works normal, but I pretty sure the reason is the text with the error was not called yet, so the game runs normal. But for the unit tests, it just giving me `Tests passed: 0` and `test events not received`.

**Comment by GGGuenni** [comment]
> I hope now it's ok, thanks for the help. I have built and run the game, it works normal, but I pretty sure the reason is the text with the error was not called yet, so the game runs normal. But for the unit tests, it just giving me `Tests passed: 0` and `test events not received`.

To run the tests just right click the tests folder and select `Run 'Tests in Unciv.test...'` 

Your latest commit d0cdb99a966d60a46f80511fda69180e2e445056 has also the problem that it contains merge conflicts (Indicated by `<<<<<<<`, `=======`, and `>>>>>>>`). 

You should also not remove the `\n`, that's a line break. You should in fact don't change any of the English texts on the left side of a =

**Pull request merged**
