### PR TITLE
AbsoluteUnits - Unique Triremes

### PR DESCRIPTION
**Pull request by letstalkaboutdune**
Unique_Trireme

Also increased banner size (2x each dimension) as the previous looked very small, and fixed a typo in a Steam asset filename.

### CODE REVIEW

**Comment by yairm210** [comment]
We display the banner at full size, and on phones - where default is portrait mode - this means the banner will be to wide to fit in the screen.
I'll have to test how this looks and perhaps make changes.

**Comment by letstalkaboutdune** [comment]
> We display the banner at full size, and on phones - where default is portrait mode - this means the banner will be to wide to fit in the screen. I'll have to test how this looks and perhaps make changes.

I thought phone default was landscape mode, and portrait mode had to be enabled with an option. But if we can determine a good resolution, then I'll happily use that. Maybe 2x the dimension is too much.

**Comment by letstalkaboutdune** [comment]
I shrank the banner back down to the original size, because I don't want that issue delaying the release of the new unique sprites.

**Comment by yairm210** [comment]
Please make a new pr including only the bigger banner, for testing 😉

**Pull request merged**
