### PR TITLE
Ui improvements

### PR DESCRIPTION
**Pull request by sulai**
UI/UX mprovements:

- notification scroll does not reset it's scroll position when clicking an entry which scrolls to any position
- tech picker shows current tech centered on the screen
- "you discovered XY" - message is clickable and opens the tech screen, centered to the recently discovered tech

### CODE REVIEW

**Comment by yairm210** [comment]
The first two are good, the last one though I don't really get why anyone would do that? If they want they can just open the tech picker screen with the usual button and it will do the exact same thing?

**Comment by sulai** [comment]
The actual benefit of this is that you can instantly read the description message of the just-discovered technology to get to know what it really unlocks. You can then proceed to take according actions, like say order workers to construct a just-discovered improvement. Quite helpful even for experienced players I think, as I believe only very few players really know all techs by heart. Even more helpful for beginners of course :-)

The underlying idea is to provide more context whenever the player clicks a notification message.

**Comment by yairm210** [comment]
Okay, I get that
Please change the boolean 'open tech' to string 'tech to open' so when you research 2 tags in the same turn (with wonder, great scientist, or research agreement) they won't both open the latest tech

**Comment by yairm210** [comment]
You can't add different notification actions to the notification, because it needs to be serialized and deserialized when facing/losing, so it won't work with interfaces

**Comment by sulai** [comment]
It actually does, you just need to make sure the actions can be (de-)serialized :-)

**Comment by sulai** [comment]
> so when you research 2 tags in the same turn (with wonder, great scientist, or research agreement) they won't both open the latest tech

Good point! I also removed the `techRecentlyFinished` from `TechManager`, as that was quite a workaround to what I wanted to accomplish.

**Comment by yairm210** [comment]
Looks good!
I want a confirmation that you checked the tech opening properly from a loaded game, and I'll merge it

**Comment by sulai** [comment]
I can confirm, just tested all the messages again :slightly_smiling_face:

**Pull request merged**
