### PR TITLE
add chinese, pls try it

### PR DESCRIPTION
**Pull request by GaoSiming988**
add chinese, pls try it

### CODE REVIEW

**Comment by yairm210** [comment]
Hopefully I'll have time to deal with this tomorrow :)
This will be a challenge because it's a whole different font etc, do you have any suggestions which font to use?

**Comment by GaoSiming988** [comment]
hey, I think  the Fonts : UbuntuMono-R.ttf, Deng.ttf or Microsoft YaHei.ttf could be very good to expression chinese/korean/japanese(UTF-8). :)

**Comment by yairm210** [comment]
Yahei weighs around 5X more then the entire app (20MB), Deng 4X (15MB)
Is that really neccesary? That's such a huge file that I may need to separate it into a different package if neccesary  0_0
I'll try UbuntuMono, see if that works

**Comment by yairm210** [comment]
The Ubuntu fonts sunny seen to have the characters you need.

The smallest font I've found so far is around 2 mb, which is still 50% is the current package size.

I'll need to make the font download optional/on request, so Chinese may not enter the next version, sorry, it's more complicated than I anticipated :/

**Comment by GaoSiming988** [comment]
hi, Yair. Yes, no hurry, this can indeed be an option, if the average Chinese Japanese Korean Arab Turks and other ethnic Android phones have their own domestic fonts and characters, that is, without downloading fonts, you can Try opening a preview version that doesn't require fonts. :)

**Comment by GaoSiming988** [comment]
okey, it look like super, i will translate as soon as possible  :)

**Pull request merged**
