### PR TITLE
Allow reverse landscape

### PR DESCRIPTION
**Pull request by dic1911**
by setting android:screenOrientation value to userLandscape

### CODE REVIEW

**Comment by yairm210** [comment]
Looks good!
Did you test this?

**Comment by yairm210** [comment]
Please resolve conflicts

**Comment by dic1911** [comment]
@yairm210 Yes, I have compiled with the change and it worked, for now I need to look into why the conflict is there

**Comment by dic1911** [comment]
@yairm210 I temporary removed my partial translation, the merge conflict is gone, could you please now merge this change so I can push my translation again?

**Pull request merged**
