### PR TITLE
Major update german.properties

### PR DESCRIPTION
**Pull request by natrius**
Straightened out the form of adress, its now the royal version ( i hope i did not miss anything), added missing translations, corrected lot of translations (i did not(!) look at #################### Lines from Tutorials #################### )

### CODE REVIEW

**Comment by natrius** [comment]
Please favor this pull over https://github.com/yairm210/Unciv/pull/3142 as i looked of close to every line and straightened it out :) Hope @scaphander you are not angry that your work is basically obsolete :/ Did not see yours until after i was already finished.

**Comment by scaphander** [comment]
I'm fine with this so far @natrius. Some typos could be fixed after this patch is applied. And i'm not sure if "Kacheln" is the  semantically better word in comparison to "Felder" and possibly all occurences of "Felder" should be replaced then.

But at all, great work and rework.
More brain, more gain.

**Comment by natrius** [comment]
Thanks :) Well i thought its better because "Field = Feld" and the plural "Felder". Thats why i went with "Kacheln". And yes, every "Felder" should be replaced, thought i got'em all. Damn :D

**Comment by yairm210** [comment]
Failed with:

    Placeholder `[amount]` not found in `German` for entry `Golden Age length increased by [amount]%`

**Pull request merged**
