### PR TITLE
Refactor BattleDamage object and test it

### PR DESCRIPTION
**Pull request by Framonti**
This PR is not affiliated with any GitHub issue

* Small refactors for object BattleDamage by introducing helper functions and moving magic constant numbers to dedicated file
* Introduce tests covering most common damage modifiers cases

I suggest looking at the PR commit-by-commit

### CODE REVIEW

**Comment by yairm210** [comment]
To me, an Enum is things that are logically groupable - as in, you will iterate on them, or have a function that accepts any of that group. That way they share a context.

These values share no context whatsoever, they're just a bunch of consts that are used in different places

**Comment by Framonti** [comment]
Hi @SomeTroglodyte , thanks for the typo catch!
I've fixed it

**Comment by Framonti** [comment]
Are there any more changes to be done, or can we merge this PR?

**Comment by yairm210** [comment]
Will be merged on the next version release, that's what approval means

**Comment by Framonti** [comment]
Makes sense, I'm used to having a develop branch but here we're not using a gitflow like that, thanks for let me know.

**Pull request merged**
