### PR TITLE
Create Bulgarian.properties

### PR DESCRIPTION
**Pull request by antonpetrov145**
This is WIP on the Bulgarian translation

### CODE REVIEW

**Comment by yairm210** [comment]
Hi, thanks for contributing!
The translations should go on the *right side* of the " = " - like
Original phrase = translation phrase

**Comment by antonpetrov145** [comment]
I saw that, but only after I uploaded this part. Sorry about that. The next edit will be as it should.

**Comment by yairm210** [comment]
Failed checks:


    Placeholder `[cityName]` not found in `Bulgarian` for entry `[cityName] has expanded its borders!`
    Placeholder `[cityName]` not found in `Bulgarian` for entry `We have conquered the city of [cityName]!`
    Placeholder `[cityName]` not found in `Bulgarian` for entry `An enemy [unit] has attacked [cityName]`
    Placeholder `[cityName]` not found in `Bulgarian` for entry `An enemy [unit] has captured [cityName]`
    Placeholder `[cityName]` not found in `Bulgarian` for entry `An enemy [RangedUnit] has destroyed the defence of [cityName]`
    Placeholder `[cityName]` not found in `Bulgarian` for entry `An enemy [unit] was destroyed while attacking [cityName]`

**Comment by antonpetrov145** [comment]
> Failed checks:
> 
> ```
> Placeholder `[cityName]` not found in `Bulgarian` for entry `[cityName] has expanded its borders!`
> Placeholder `[cityName]` not found in `Bulgarian` for entry `We have conquered the city of [cityName]!`
> Placeholder `[cityName]` not found in `Bulgarian` for entry `An enemy [unit] has attacked [cityName]`
> Placeholder `[cityName]` not found in `Bulgarian` for entry `An enemy [unit] has captured [cityName]`
> Placeholder `[cityName]` not found in `Bulgarian` for entry `An enemy [RangedUnit] has destroyed the defence of [cityName]`
> Placeholder `[cityName]` not found in `Bulgarian` for entry `An enemy [unit] was destroyed while attacking [cityName]`
> ```

What should I do about these problems? I don't know - aren't the values in the square brackets suppose to be got from the game?

**Comment by yairm210** [comment]
It seems that you turned the value of those lines (in both the original language and the translation) from "cityName" to "cityname", recapitalise them and you'll be fine

**Comment by PresleyBG** [comment]
Hello, Creator of this glorious game and Bulgarian! I would like to help my countryman with the translation if possible and if You both agree with that. Can I participate in that?

**Comment by antonpetrov145** [comment]
I'm fine with that :)

**Comment by PresleyBG** [comment]
I have just translated a bit things starting backwards... Sorry if there are some inaccuracies in my translation. And one question: what type should be the file and/or where should I place it? I can't upload *.properties files here.
[unciv.txt](https://github.com/yairm210/Unciv/files/6172515/unciv.txt)

**Comment by antonpetrov145** [comment]
Translation is complete, but it fails on buld

**Comment by antonpetrov145** [comment]
It's all done, but how do I get the file to you?

**Comment by yairm210** [comment]
Done!
From next version, Bulgarian will be available as a language :)

There are many translation texts that are auto-generated from the game files, such as unit, building, tech and policy names - they are now also available here:
https://github.com/yairm210/Unciv/blob/master/android/assets/jsons/translations/Bulgarian.properties

You can click 'edit' on that file to edit a certain copy, which will then create a PR like this one, for further changes

**Pull request merged**
