### PR TITLE
Fixed world wrap coordinates check

### LINKED ISSUE #8723: World wrap: tile positions are not updated
**Version**
4.4.17

**Describe the bug**
When you place the camera near the left edge of the map and click the next turn button, the tiles to the left of the edge disappear. Tiles will not appear until you cross the edge of the center of the screen
I additionally checked on version 4.4.9 and the bug is also present, so it is not related to the latest commits.
May be ralated to [this comment](https://github.com/yairm210/Unciv/pull/8702#issuecomment-1437316770)

**To Reproduce**
1. Load my save(or any other save with a sufficiently explored world wrap map)
2. Position camera near the left edge of the map
3. Click the next turn button

<details><summary>Saved game</summary>

```
H4sIAAAAAAAAANVd3XOjOpb/VzzztFOFswFjwLwl6du3s9XpzrZzbx5SeZBBtpnG4OUjad9U/vc9QiCwEUjCZHemuqsb25LO7xwdnS8JeHvBSRrEkfsW5bsVTtyZ5iUYZdh/DLKt+5bhX5lrXpgXuqWVLRx9/v6uecFLEAZ/oQw6p+7T2z5EB5w8HPbY/ZLvUKRt4tB35zZp+A3tsHuVp1kSIC3DHoybegGOPPx9/RWlmfOQJ2QQU6N/5sUf67lom/7AKUaJt8W++3QfZxlODtrVJgm8PMzyBJetHuKqnft0FQU7FE6+5OkKRT5pTrrD/3dBFEQbbYkAOvz/mAQZ+f8hQft9cbHFk8ctxqF2h9I4gh7XSRz9BV/GyU/S4AaFOPJRon3fZ4GXal/iJMUr5P2c/Aj8ogFII0tyj4gFBsm2eIeKlr9FmyDCOCGNPiVohyYAbXIf4wyo3ORJAuI4aLdAjhG73wZhnMb7LTQg0p4scfISeFj7PQ9CP9XucAZc3oAAS+xxGG+g7TZ4QSHhFnlboAlX99tDWoDwc6+YMcC526M01ZYZ4fYeYJFBJvcJhi+vUVQAuPJimDTS8QqYiqN4dwDa0T5+9XGi/eaRb4pfQbwBzAKZDu0begk2lEgBMMyTAhTeBSnhdUlmPgvWgTchkMvZQSX428inelLplvYjWBeTdQdzlqHkMFlS1dE+4yQjKkighEAcNCLIYMYCOhJwhnYg4Ff4/dMhQjtAqP3A6yTY4IQO/TkMNtsMvgTl9TBahXhyj5Is1X4gP4jh3yBMYgSSpuPHEWH2PkRUJtfAW0AvQZorIikY8yojMqlYu9+iZAdj59AMhcXAoDykOUyMP7lKdimRI503mJIctBtaxd7PQi++5V4IOj35HKRkkWoPGIDEu10OSOjK02D90C6rmM6U/4JAOv6kAW8J6xk+ZBh0Jl4FwOYD8opffg/jVS1qIrIw29Zk84IqkUngEeGUavQNRTFZdBEF/jknEz95gG/KxXgb3SfxhuiS+1YuWdfQtdN16eoWWJJ9HMLMYWiaZnGC/Ru6rl3d0JAf78EU3VctnmCl+gHB+lxao+/rq5M2emGbmusQRn7X/ifHaXaHIgSzTz4nGCYffmx8RSwWjq42NZQvhV0gbOj6JTQglvEex/sQk/Y43cMA0LsxBqxP6HloEsqDKG183ifxrwCU8eC+/chhWpF7A6scv2sRArZR+BhHsLqA12uUEGuBk8kN6CtOQLbFrKHw6pYMBHNAVhGzwIWp/vvTn7A6IvQ82aJ0gn/tQdCgDEGWTlZxQgb+29+1wCt6LDOU3ZLL/7ypTCkqBOa+eaDkqQuqdpFHIM0LmOfAu2ja/IuvMSV9RW1dGNdIfrlz7eDO3zW4msGV9f4MkwI8bEA07g1MIE7fn48Z+BpvCA/gCFyji7Ul2KOMcrbCOJqswA5mkyCaVExzWANF9EtzTLuPxmObs5oWsE4xP2KA+4InfpB6MfhamIv2xPKmhKneuIBBjZ/fCWgqalNGizZJ/BrxMN7H+zxEdDl+nFRLfdH+DbWAyXneIecqZpnE60kV3FDWABGYGTBsPMFXLrDqocINMdMlJ8RWF7FZOU5DMax/afNiSpiXihP730fFn8EoesUltKv6uKyHFviuM/cW9no2n9qO7U1NE5tTx0CL6aW9mmPT0435ygFPAnNK2dPWcR6RyBQiSBaC7xlT7lvjegaNY39ZeD7XJG40O5z40WKtXZPwE4YElPeIRE6Aughgs2br2/QPiEyWOHPhG6x5jZ/+O8c5dp++xRnEpxsQRKFINA0po/oShVE7aoBKAgr4DXCQQL36gawd+PwVbyA0N+xqfv6JXtBFiKLNxW0EYoYoEKJiIDu7vHx/bzhv4kohjsTNuSGaZTAdI9pmM22r9c5mv9Y9LPYdbUcd4bP2CjE99h8YnXr04142tA3S7xCkBhEKb9AeYt6QSnAdok16A9OZ+aCsED3gNM4TD3+CFCMCUQFblfrc0BTO1YlkQyLJhyMOnRPKhWdgVwa7MhmuWXFFW1vweaqzIehP+tEVaVgNPtUZHZtx7bDvHNaxlqTFaFsMj8UwzpnsyXcLhnZxMlvzox4mu6r5q+eShHcl9rIz/XzJek3roaYGY77GMWcczlhDpxCDXQ7FSBeXei0cm3W1WFfKTPkv67lgHc2jKZs1jGH1az15BruaNi5pb4dNQvmFzjoYNWA2nH6kPSa7cmpuzILpxhdUCvV81vOus6sal9NYN1WPWj8WjOKC4VkU49ezX/er9aAWbD1WObn1UjbqL+v1qR9dlT/XM1ZK1K4EyBpfMlrTegibMW0zpm0myEXR5VkjGeYSQpvbHSQLL3gHlrXtdf6Zgp/5gtLtHdr/iUnWYWjQMCm8R9OUnZrDZVYUIag1BM9zmHjQDydA+KmhbL3drqIii58Uyc37M5hw8KK/QXz7/RXyWq75ymK4LCOBz3ECrgLy0QwyKyJLWizSWbGIZkYytaKyXsSpFZXFnv5SEYugWnkr7e4aZhVlQQ7Yk606H5J22vb4WWcZBVRp53FSyQ0/poV2m0UAYhjWylz5xnS1sh0IQJzLKcIWntozzzIWPvL91YIGIHcxpDyvRwFIOa0d8YfRjD/IQlMIQAI2cycdSDENRGCS4dohCP21LwLRx49AjN4IhAmbXBd2mZqOaeF2S4tiN763G99bp33L6zlt045DjkZlrQZGIHO5CIQiayI26uvSLZrNJqUVJRZ1ajeYsxpD6G0BNIW0aPS1T1muhNSkYzY/OI3GeuO6gftoNqwGSLs5kN78UPZeNBDqjWujcW02rp0GUashLaMmWg7jtBXBaYxAUXC0qxENUH6aQm/CavJsNORiHekTbdOkeTSjDZVu0tQbNJt0mqKYNa4hoxruhBzovEIJ/A0QNdx+sF4XfuPgQg6ThbB6yRoFZ+u+7dD+HiVg40i11n3LyKbHbRThZLLESINfl8FfsKpJrTJPSSTwGvjZ1jVm2haTirOrz6mJfAiiwztZk6H/mMDINFOq91/+LDdnig0Ye/IfheGbOLr1Dy3FZHVZtn1p27oxW9iw0kL8UljS337t44gEDZcXlvZKSkwPWzBaW+Jkp5cXOjU3X4M0g/W4Qil+wEmCgsj9PQG7BRbLJ7YyC+gYION9nAbMGejl7DQ73ofwbwpOtPj4GZNSJlnt/5VHm5Dkh53D6XTaOYMlpXVxi02W+vPVjlggiOC6Bu2E191Brf0v5fangKQEbZTLit+xJes7lKTb51psfyQoCvKdvNxYxM9hrbLi1wf3qQwg+maVKgl/qH5dkOe30i0uNCaFa4iBItQ394owuyTEKD5uASIxRdcQN8a7H2TF/wjALLFCSA/7gxSFs4Zk+vH5aMn5SxCGvXPdOWX9iiZY9VSMouXRyfYAUzSdlT6lOeInSBWS7BRW0MjMjnKhnuHLPJ0PV3V9GRyowvVljIlA5yCQmXpdGYTyUhoCrAcUo/8VrxVW8oBlMeVYwP5lyfRyucV43xQVg6kOv39lqY835Sz3npVKORtgQPnrYQBewUAKiJQYh4gUotEOjyayW2NawplaHFArIQp7TfZMLaKpgLLxH5J8vYY0so+GWSYJTRpf0c9iB7HZsCyRyi+1QbNicr1Jv+T5fQZ5CP5Q0j7WaKMZ21ZXnkRixvTOGRNBGWwLZYD1iIirSdrAZc5zuMNNHMcNDw0AFfMUgXnnTZtAzQfTlhYXz8KKvIIiIxxXMXh2OxVynPjgdE0IA0/z/8QNmpxJ6rL8nSrT7+BUSxGN2lwL1REpWhl/5iDl5yMCP5zFUf8EcmyJLCha1puPYzvKfb4zvfBJFEwObZIaYMJOPIhEMVd002Yn7H58jzCcGrxZNzw2Kjk1fKqTlsCa8Ydsr8Uwjv3JvuCtS/gtdoYEAYYEnzLhyoh8VWRvAgCf9vGp5nZP2eyKdfisKFnFNjGZTLizyxlrUhDXdHqsc0wvJ2C8I73ggouZF9eMlgpOOdUXoePkJUyD63TdWV2/oVNILc9x3ao1dXkt7UU1UkgkXqylNx1utufjRVEMwyeMk162OPPfw1s/eON8g9bYeR0F0mjl0DnHWKg7n5aOtHxPeYRCKetQV+e5Wqotkgu/DCHhTcSTyPbBmwQe8shPkNyaEJMoz6xxCAwShiVvzrmlAjnF5lMZlFJZA4JjBfLjxI+zbqQt0X5HaZCK6p+SY0kEks3NosZ5u3ECSmPIDBny/JWykpw5UeSrClTvBKoaBqtRHoVqGdry80T5fU5OKnD2rvhNjMLT0MMWlfhUqz5TTvm4ir95ce6AzcRp76aq3J6ZIPhVir6H2NeRwntepHaGz+bHfD1OclBhXtq8D7dWcv6dz66SNRxgvK3u6HqU4MhSKo4PTd6s7oB8NC7k13h5DGoQE/8v8fsZYbo1WphudRt4hTlssdkPfUgFdUAZyOr2woq5RnUYVibX6JGSrP8h5E6oLaP4ddDpIyoFSeyVJZAtE1htoOdkSIoo+33iOLjMblz98YMiLxLVGoV8acAW5CmTMlHYrM2naENNJXMwOLC6bJOq5hpt6APLUnqv8Drj9P7kYQRonbLr7sCnOk7Iy0sDJY5Pq+WB0huhvF0nYf4gUNWRdkZ5x4fOgcY5WXTGcLwN5HPQcXa6ZSwPrxZ85naValV+yqlsK53Z7HerI6V03TmOWgjENyWqaAYbGAmAfZskH7kBZHMma2zGPj6XszkLSp0LtbjDVjuKNvT8HLvvb+Qc54O3Yuy23ZZPOaTFouoZeJIR17mFWaHd9p8DmJU2sOwW0bN5V+RxnO0kmxNLcYaSSGyr20JbqeYopouMzhtcxJpaH1udisWh0qdvmjjltNRRzBVQtPKbZRD+FARI/KFHK82a3fD748chuBTu4RgCa6YGS5S0OoqWhc3qVZjvgqh986YjyGWcUcIznYNdJY3ZlY/q/CMKMvctPsrz4/K27OPsv7gbungyG3lSxS4mUFLyvAV2/XS7iYCHSQlg4sWwDN41P8fuGoUp1nal67nDu5g+BIWT6HOzf/IortMU1RkaAsnk46pq0T3Ux8EsM3W10sEv9jyj8wsqvI1tzrHAG0RuzhetRNWCA+/U7bnJN78uIEixxeciiyPFAvM8Xt7PO+Yke7+LwAWqno3kbTtJ7RlzdsWExHjZ3dDkV367cVCwpVaIlV9HfFsjBvev6A1oOYS7D3zqDZzOo6kqZlacEfPEVOYSx1IqvyyE9EgeJRsnR2J6FzFfPceFmwS0BcAeB/NhGqtU2RiW5DocY9GzBzhO6u60rVpfNDm8BOlwrPKgHU5HtdggAiV192h715waI4Wk2lEtHIiAy+8Xn5zkUgR9EpnIJt3SOi95MlZit1r1zJjTsXstQszrM4qdoc+JWihBIl3UelAmeH2UNdFRJ26rs2irU7HUqVgdVMZ1ou26yoKr/9IbhPM27JHrFKYESsEmttkJUm1fgNEb8OgoWm+RRCGz96kgdVEZZiRUhhoq6XtsdA7GobvGehvjWY8jOD3I1lPVkCcrSghbLIxf1+AnM8MjsI+tGZXVEOViDOd0y1nHETrLMQK7oHDLy5lFUN7d3OeeS1AdbsjxPN5tUufg5tzAdcZwvMOxYu1TO7crrhLx9qbPf1iAIJhS2gvvD+WG59Cy0f7ZSbq0bNR8jDo3gx2AOA1Y9J0QGQt+d7lQ3gnLsaL2JJNBR4cXZy28Vk1FOjZedNZPPma9LzhmbthpgM6n8snuqi46CzEi/JLlm+EKd+IOh6W27PnRH4tVoboiwjrGOYuFeklkwQn8emhLJ7YL9XMKC07gXPRRLMOUj0K/VKJO35mi1qc0w2qdFl10mGi/B0p1sLJ+robCGcCt3UlnKHR7AAprALcWh06rUiN4tuS8k67ygp9LwBEl9SYPztDKg9kNaNizQkfCNePg6n3CzvFLLt3TNyEKKzmnxMooZEhUY4wnU50HjbNVL7LJOgfSuKFptwgF9RLJ8pQ4iRt0LkpQlpC/60byPALvsRdn3Zet/BCuMudWuiNTkDmr5u89W6b93lPheVHCciZfWc8qZCpuY1Uvazuz6iCOh86v2opjr+oldB+a/LK326huoApcfPVKtTPzQSFy8ZZ9C/mQUmVBjJ+tSQc97F1FH5dGFSTGyfnYC4c+GO04WR97VdG5aGVjxoKgwu63EDtvrAHiVEwT2SuzxqCtuDFNaYs6PWtpRt5pH22+1i/mfX7XNmiHmy924rwDah+iQ/F29jdvG6c4OnqtbvHbA3kb1Jd8h8gzbt7r99STO2LIe4Vh/i61KL6u3zZVlILKV/iR3jB68YLn4q3FGn1bFfisTzGYmAKt9ikAQe7g2tMegh0G6FnxVkSnehHvfQGlvrmafvsAjZaEc9KpenmUsZhfXs4L3m99d+U4uoXW66m9srypeWlaU2eGV9M1Nhx7sXJmK0t//1+r7lI6NYQAAA==
```
</details>

### PR DESCRIPTION
**Pull request by Gualdimar**
Closes #8723.
In init tiles are movedBy -bottomX (line 94), but the topX and bottomX vars used to move the tiles for world wrap remain unchanged. 
And we have tiles.x from 0 to maxX, but bottomX=0-maxX/2 and topX=maxX/2.

So I changed the values of vars topX and bottomX by -bottomX in init.

### CODE REVIEW

**Comment by Gualdimar** [comment]
TileGroupMap.getPositionalVector() uses bottomX, bottomY. 
I`m not shure if bottomY should be shifted too or draw() should use its own vars?

**Comment by vegeta1k95** [comment]
Better not introduce new vars for `draw()`. Render loop is the place where we should keep amount of calculations and var creations as small as possible.

So I think better alter `getPositionalVector()`.

**Comment by Gualdimar** [comment]
After a little digging into the code, I found out that these two functions require different variables:
    _topX/bottomX/topY/bottomY_ - are vars with min/max **world coordinates** relative to the map center and they should always remain so, regardless of where the tiles are drawn. They depend on the size of the map, not on the position of the tiles.
    _draw()_ requires vars in which the min/max position of the drawn tiles in the **stage coordinates** is stored.
So, in my opinion, they should use different variables. And I haven't noticed a decrease in performance

**Comment by vegeta1k95** [comment]
Looks good to me

**Pull request merged**
