### PR TITLE
Scroll indicators are displayed more consistently on the NewGameScreen

### PR DESCRIPTION
**Pull request by devbeutler**
Hi, I felt that 2 thirds of the NewGameScreen not showing scroll indicators was unintentional. It's a minor change, but I thought it was worth adjusting anyway.

### CODE REVIEW

**Comment by yairm210** [comment]
This was intentional - when adding enough players that the player scroll actually scrolls, the addition of the scrollbar messes up the width in such a way that it then slightly scrolls also right-to-left in addition to top-to-bottom, which is really annoying. I tried to find a way to cancel this out using paddings etc. but could not find a way.
If you manage to do so that'll be great :)

**Comment by GGGuenni** [comment]
I think using ".apply { setScrollingDisabled(true, false) }" in addition to ".apply { setOverscroll(false, false) }" should do the trick

**Comment by devbeutler** [comment]
Thank you for your comments, I will look into this further.

**Comment by devbeutler** [comment]
> I think using ".apply { setScrollingDisabled(true, false) }" in addition to ".apply { setOverscroll(false, false) }" should do the trick

This seems to fix the problem! Thank you!

@yairm210 What about the mapOptionsTable? It can be scrolled in both directions, but I don't think the scroll indicators have any effect on it.

**Comment by yairm210** [comment]
Did you try this with a lot of players? How did the player boxes respond when the scroll appeared?

**Comment by devbeutler** [comment]
@yairm210 Hi, just to give you an idea of how the screen behaves with the change suggested by @GGGuenni I have attached a shot clip: 

https://user-images.githubusercontent.com/58529898/107085730-2d551380-67f9-11eb-8622-185f6d9f9b63.mp4

The player boxes are shifted slightly to the left when the scroll bar appears, but no scroll bar is displayed at the bottom and the screen cannot be scrolled along the x-axis.

**Pull request merged**
