### PR TITLE
Improved city button

### PR DESCRIPTION
**Pull request by sulai**
this PR adds a click area to the city button to solve the problem that
- units should render in front
- city button should be clickable before any other tile

### CODE REVIEW

**Comment by yairm210** [comment]
This seems needlessly boilerplate-ish
When making the spinning black circle I managed to make it work in one line:
`spinningCircle.addAction(Actions.repeat(RepeatAction.FOREVER, Actions.rotateBy(90f, 1f)))`
I'm 100% sure that this can be similarly done to the city button
The movement itself can be done by 
`Actions.moveBy(0f,-height,0.4f,Interpolation.swingOut)`

And if you want something else to run afterwards, we can either wrap it in an Actions.afterAction, or more simply create an action sequence:

```kotlin
Actions.sequence(
    Actions.moveBy(0f,-height,0.4f,Interpolation.swingOut),
    Actions.run { isButtonMoved=true }
)
```

Which is much cleaner!

If you're worried about actions getting stuck midway (what if someone clicks the button twice within a 0.4f period and things go out of sync?) then you can use Actions.moveTo instead of moveBy and save the current action to cancel it later but I think that's overplanning for now, let's try and simplify it as much as possible first

**Comment by yairm210** [comment]
Also, I'm confused as to why you have 2 github accounts, sulai and mrimvo, and sometimes use one and sometimes the other, but if you'd rather not talk about it that's fine =)

**Comment by sulai** [comment]
Thanks for your hints, I'm pretty new at libGdx and still figuring it all out =)

> Also, I'm confused as to why you have 2 github accounts, sulai and mrimvo, and sometimes use one and sometimes the other, but if you'd rather not talk about it that's fine =)

That's just me failing to separate work and free time projects ;-)

**Comment by sulai** [comment]
Thanks for your feedback, the code looks much nicer now and I even got rid of the offset variable :-)

**Comment by yairm210** [comment]
Something is wrong here - it's now almost impossible to select units in cities

**Comment by sulai** [comment]
Not sure about this solution, because now units are hidden behind the city button.

**Pull request merged**
