### PR TITLE
Polish translation

### PR DESCRIPTION
**Pull request by VoyteeG**
https://github.com/yairm210/UnCiv/commits?author=VoyteeG

### CODE REVIEW

**Comment by yairm210** [comment]
You seem to have started over of the files entirely...?

**Comment by VoyteeG** [comment]
No, I've posted accidentally few times and I couldn't reverse this. I'm struggling with use of GitHub, never done it before. I don't have time to learn it thoroughly with use of terminal, so I am based on browser interface and desktop app.

**Comment by VoyteeG** [comment]
If you could please support or advice me with this just a little. At the moment it's bit frustrating trying to translate as much as possible without all this technical issues. Also if I commit some error on the previous translation, could you please explain what's need to be corrected.

**Comment by yairm210** [comment]
The problem is in your latest commit:
image
In which you deleted the file entirely

There are ways to 'patch' the problem, but the proper solution was to re-add the file you deleted 
image

The old file data could be easily found by looking at the commit in which you deleted the file
image

**Comment by yairm210** [comment]
Now let's talk about conflicts!
Because you're not the only translator, and you're all working on the same file, if you both edit the same place in the file at the same time Github will want to you say what the final version should look like

So for example:
image

The part beween the <<<< master and the ===== is what **your** file has
The part between the ===== and the >>>>> master is what **my** file has
To resolve the conflict, you'll need to see what the final version should be.

We don't want to lose any of the other translations, so we'll take the bottom one as the base. 
But your translation has probably updated, so we'll take your line of Polish and put it in between the other lines.

image

Now we need to get rid of the <<<<master, ===== and >>>>>master lines
image

And we're done!

**Comment by yairm210** [comment]
It's actually super easy to do once you get the hang of it - copy line, paste line, delete lines, next.
It's just that explaining it inn words makes it look difficult =)

**Comment by VoyteeG** [comment]
Thank you so much for explaining. I will correct this later.

**Comment by VoyteeG** [comment]
Now could you briefly explain correct process for my part of work in this project.
1. Create fork.
2. Copy clone to my PC for editing.
3. Commit back on my fork on hub.
Here I am not sure how to proceed...
4. Create pull request?

**Comment by yairm210** [comment]
1. Fork - this creates your own copy of Unciv
2. Change files in fork - this can be done in 2 ways
  2.a. Git clone your fork to your computer, edit files on your computer, git commit and git push
  2.b. Change the files on the Github website - behind the scenes, it does commit and push as well
3. Create pull request - this creates a commit on **my** version of Unciv, which includes all of the changes you've done on your copy
4. I go over the pull request and can accept, deny or tell you to change things before I accept. Once I decide to merge, they all the changes you've made are now in my copy
(5. Next time I release a version, your changes will be included in it)

**Comment by VoyteeG** [comment]
Amazing guide. Please use this thread for any lost soul in the future 😉 Thank you. 👍🏼

**Pull request closed without merging**
