### PR TITLE
Protect the cities from the fallout spawning

### LINKED ISSUE #6355: Fallout can be created on city tiles, but cannot be removed
**Platform**
Android 10

**Version**
3.19.16, Google Play

**Describe the bug**
Nukes can create fallout on city tiles, but it cannot be removed, because it's on city tile.

**Expected behavior**
Fallout isn't created on city tiles. 

**Screenshots**
Screenshot_20220315-123902_UnCiv

### PR DESCRIPTION
**Pull request by JackRainy**
Fixes #6355 

See also, PR #6631

### CODE REVIEW

**Comment by SomeTroglodyte** [comment]
Is the Indestructible unique now essentially pointless unless someone mods it onto a terrain?

**Comment by JackRainy** [comment]
My personal impression: there are too much those uniques - Indestructible, Irremovable, Unpillagable, DestroyableByNukesChance, DestroyableByNukes, ResistsNukes, ... and so on.
Most probably, all of these give some value of flexibility to modders and have the rights to be there, but I am as a fun of vanilla see less sense of them.

**Comment by JackRainy** [comment]
If you are saying about this check:
> if !tile.hasUnique(UniqueType.Indestructible))
                tile.addTerrainFeature("Fallout")

It has a flaw since it checks the uniques of the _tile_, not its _improvements_.
> fun hasUnique(uniqueType: UniqueType) = getAllTerrains().any { it.hasUnique(uniqueType) }

vs
> getTileImprovement()?.hasUnique(uniqueType)

And the "City center" (with all its uniques like "Indestructible") is the _improvement_, not _terrain_.

**Comment by SomeTroglodyte** [comment]
Now you ave translated my earlier comment. sorry for not being clearer.

**Review by xlenstra — APPROVED** [review]

**Pull request merged**
