### PR TITLE
Technology and construction bars no longer extend past their maximum

### PR DESCRIPTION
**Pull request by xlenstra**
Previously, when you produced more science to finish a technology, the bar would extend past its maximum.
The same was true for constructing things in cities.
Example:
image

This has now probably been fixed. I couldn't get Android Studio running so I wasn't able to test it, but based on my understanding of the code, this should do.

### CODE REVIEW

**Comment by SomeTroglodyte** [comment]
Needs `import kotlin.math.min` to compile (only `CityButton.kt` has it already), and misses the progress bars in the city screen itself - this touches the one on the world screen city buttons. The other would be `ConstructionsTable.kt` line 261. Code should probably be refactored to use one routine for both usecases? Other than that, looks like it would indeed achieve what you intend.

And "couldn't get Android Studio running" - the "running" shouldn't be that hard - if you have >8G RAM - advice depends on OS, and with "running Unciv" my [scratchpad](https://github.com/SomeTroglodyte/Scratchpad/blob/master/Unciv-notes/Getting-Started.md) might help if stuff crops up Yair's getting started didn't cover.

**Comment by SomeTroglodyte** [comment]
Pre-PR effect shown through cheating:
image

**Comment by xlenstra** [comment]
Thanks, with the scratchpad I was able to solve the last issues, and Android Studio is working fine now.
I've included the necessary headers as well as also updated the last bar in the city screen.
I've not refactored the code to use a single routine, this is my first time programming in anything java related so I wanted to start with some low-hanging fruit.
I wasn't planning to add more to this PR, so I'm fine with it being merged.

**Comment by SomeTroglodyte** [comment]
"low-hanging fruit" - sound decision. If only I could rein myself in... So since I cried wolf I should test this, too... A moment...

**Pull request merged**
