### PR TITLE
Added missing religion icons

### PR DESCRIPTION
**Pull request by xlenstra**
This adds in the religions of Judaism, Shinto, Sikhism, Tengriism, Zoroastrianism and Confucianism, including their Icons

### CODE REVIEW

**Comment by SomeTroglodyte** [comment]
That's all of them. Can't we invent some more? A total of 12 or 13 sounds much cooler than 11. "Origoapertaism"?

**Comment by xlenstra** [comment]
BNW split the Christianity into Catholicism, Protestantism and Eastern Orthodox, so we could do that

**Comment by SomeTroglodyte** [comment]
Nah, BNW gave the Inquisition too much weight. I know: "Trekkie-ism" and it's only in the pedia or foundable if your system time is april first. Symbol: https://thenounproject.com/term/vulcan-salute/3890724

**Comment by SomeTroglodyte** [comment]
OK, leave those to mods :cry:

**Comment by ravignir** [comment]
Well in civ5 you can name your religion:
z

**Comment by xlenstra** [comment]
I know, I'll add it in some later update. This was just the icons.


> z

Never heard of that religion before 🤔

**Comment by SomeTroglodyte** [comment]
> Never heard of that religion before

Like Consumerism, Nonsmokerism or Militantism they have their own Pantheon, feverish Followers, and _manic-depressive_ Beliefs...

**Comment by SomeTroglodyte** [comment]
Want Communism in Unciv? OK:
image

**Comment by logicminimal** [comment]
did you really add those icons or are those mods?

**Comment by SomeTroglodyte** [comment]
The mod in question is easy to find with the hints here

**Comment by logicminimal** [comment]
> The mod in question is easy to find with the hints here

which mod is it?

**Pull request merged**
