### PR TITLE
fixed the crash caused by missing curly braces

### PR DESCRIPTION
**Pull request by Damjan94**

### CODE REVIEW

**Comment by Damjan94** [comment]
correct me if I'm wrong, but I don't think it matters, from the compiler point of view.
I agree, that it should be changed, from the readability point of view, tho.
since this is the first project I am contributing to, how would I change it? do I close this pull request, add the braces to the isAdopted if, and create another pull request?

in all reality, since its a simple fix, I am gonna let you fix it, but please give me your thoughts :)

**Comment by yairm210** [comment]
It does matter!
If the first if is true but the second is false,
Then in your code, nothing will happen
But what should happen is that the stats will change!
If(a){
If(b) x()
Y()
}
Means that if not a and b, then still y() happens
Whereas
If(a)
If(b){
x()
Y()
}
Means that if not a and b, then still y() doesn't happen

**Comment by yairm210** [comment]
But I'll merge it ;)

**Comment by Damjan94** [comment]
ok, cool, btw, don't feel bad for rejecting pull requests from me, if it is not useful, just give the reason why it is rejected :) anyways, do you have any issue you would like me to handle?

**Comment by yairm210** [comment]
My last couple of pushes have been around the empire overview screen.
It currently has a cities overview take and q gold and happiness breakdown, but it's not very visually appealing
You can get to it by uncommenting lines 44-47 in worldScreenTopBar
So if you could work on that, that would be good :)

**Pull request merged**
