### PR TITLE
Add options to hide automate actions

### PR DESCRIPTION
**Pull request by drizt**
Added 2 new options

- Show Explore action
- Show Automate action

### CODE REVIEW

**Comment by drizt** [comment]
Options 
no-automate1

Before
no-automate2

After
no-automate3

**Comment by drizt** [comment]
Patch need to save some space on the screen and prevent wrong tapping.

**Comment by drizt** [comment]
It's my first code written on Kotlin.

**Comment by yairm210** [comment]
Under what circumstances should dismantling these options help? These are generally very useful commands

**Comment by drizt** [comment]
I never use them and these commands take a space on the screen. I always manually do all actions with my units.

**Comment by drizt** [comment]
Here resolution is 750x500. Sleep button overlaps Diplomacy button. It's not good.

explore-button

**Comment by yairm210** [comment]
I see.
I think the correct solution is to make the unit actions scrollable in those cases where there is an overlap, and the hiding of specific actions is a patch which solves a specific resulting case but not the underlying problem.

**Comment by drizt** [comment]
Scroll for unit actions is not a solution. It looks like a workaround. Anyway scroll is not solve problem of free space on screen. Many elements overlap world map and I find a way to just clean the space. So main target of this patch it's clear a space.

**Comment by krushia** [comment]
For others the "unnecessary" buttons could be different (personally I don't use sleep, and hardly ever disband). This patch would need to have an option for every button... but I'm not convinced it's the best way to save space.

Perhaps a button that toggles display of all the actions? Or maybe have them automatically hide when panning the map (and show when the user lifts finger off the screen)?

**Comment by yairm210** [comment]
As mentioned, I disagree with this method of cherry picking specific actions to hide... after much thought, I'm closing this

**Pull request closed without merging**
