### PR TITLE
Language picker and new installs

### PR DESCRIPTION
**Pull request by rh-github-2015**
I came across this on a quest for something else, but it has always bugged me that the Big language picker appears when you delete the Autosave, not necessarily when inital config is actually needed. 

But then there's the early Multiplayer ID setter...

So this is what I came up with to ensure
- No visible addition to normal settings files, transparent for 'old' settings files
- Aborting the language picker still calls it next time
- Future code restructuring (uuid rework, new settings.save() calls) is unlikely to affect this
Looks ugly, but I could think of no better way that woldn't break one of these expectations.

"Side effects":
The changes to LanguagePicker itself are cosmetic + plus the setfocus, which is just nicer for mouse users.
Unified the constants in GameSaver
Console logging for broken settings files

Note I'm calling attention to the tiny detail that "INCOMPLETE" truncates, but haven't fixed it (label.setWrap(true) produced unexpected results, and that deterred me)

### CODE REVIEW

**Comment by yairm210** [comment]
I don't like the fact that setGeneralSettings() deals with the isFreshlyCreated by default.
There should be a specific point in the code, in which we explicitly set it to be false. instead of relying on a function that is called from many places - this makes it less obvious where this actually happens.

**Comment by rh-github-2015** [comment]
I know - I just wanted to make sure any new call would automatically be treated as 'these settings are complete', only the one specific UUID setter should declare 'I'm saving, but that does not mean the user has decided'... To minimize side effects. And I very consciously didn't dare to move the ID setter to much later - which might make the whole isFresh thing unnecessary.

Better ideas? a markSettingsOK() or so, called only from LanguagePicker close and Options close?
......... .... .. You're probably right. I was just too lazy to find all save points and think about each one. There's too many of those as Options overdoes it (each click writes to flash twice) - but that's for the next branch I created.

**Comment by yairm210** [comment]
Okay, alternate idea - 
Since the only use of the isFreshlyCreated is to choose to open the language picker screen, how about we do this differently?
How about the language setting is set to an empty screen at the beginning, and we check the language setting to determine whether we open the language picker screen?
I think that makes the whole change be 2 lines of code, we don't add a new parameter, and it's very obvious why we're checking that parameter

**Comment by rh-github-2015** [comment]
Thought about that too.
* Json is set to omit fields that are at their default. Thus, old settings and fresh settings are indistinguishable and we would have everybody re-selecting their language once after updating?? To fix this the only idea I had was some separate property. Leaving the json-visible default as is but changing it right away in a constructor - after some hard thinking I ditched that as well, forgot why.
* Having a UUID-only settings file clearly marked on disk seemed generally worthwhile.

**Comment by rh-github-2015** [comment]
Another detail that itches - GameSaver _sounds_ like it should only concern itself with GameInfo not settings - move all that over to companion of GameSettings would be cleaner to maintain? Is that even a standard pattern? If we want our own 'api' for serialization/deserialization of what's essentially a data class, then have the writer as method and the reader as static which translates to companion here?

**Comment by yairm210** [comment]
I agree that moving settings things to a separate "SettingsSaver" is probably correct
But let's put that off to a different PR...

**Comment by rh-github-2015** [comment]
OK, reverted local 'moving settings code out' - but I don't see why a companion object wouldn't be the right place. Good for code clarity...

Trying to recode - I forgot a requirement: Old settings files from before the userId introduction must _also_ behave transparently. My code does that, but every alternative I try breaks one requirement...

**Comment by rh-github-2015** [comment]
OK, I just forgot that the magic is actually happening in getGeneralSettings. Simplified, better, one line not belonging here cleaned. Thought hard about putting another fresh=false in the options screen, then decided unnecessary. On desktop you clearly cant' reach there with fresh=true, and on Android there are resumes, but those are cleared by the update, right?

**Pull request merged**
