### PR TITLE
I have completed the Tutorial tasks translation for Romania.

### PR DESCRIPTION
**Pull request by FierulMare**
Hello, I have completed the Tutorial tasks translation for Romania. I am planning on helping more on this in the near future. This is my first time doing something like this and helping you. I have just joined your Discord server as well. Please tell me if there is something I'm missing since I am new. I hope the translation is useful. Have a nice day!

### CODE REVIEW

**Comment by JackRainy** [comment]
Hi,
Thank you for the contribution, however, you must not replace the original text. You mudt write it in the format:
`Original text = Translated text`

**Comment by FierulMare** [comment]
> Hi,
> Thank you for the contribution, however, you must not replace the original text. You must write it in the format:
> `Original text = Translated text`

Oh, alright. That makes sense. I ll keep this in mind next time.

**Comment by FierulMare** [comment]
Hello, I have just made another pull request and I think my mistakes are corrected in that one.

**Comment by JackRainy** [comment]
Great! I assume you can close this one and wait till next release when the translation will be included.
As well, you can continue adding the new commits for other lines.

**Pull request closed without merging**
