### PR TITLE
Added UI to show what cities are holy cities to the player

### PR DESCRIPTION
**Pull request by xlenstra**
Added a line both in the religion overview screen and in the religion expander tab in the city screen

### CODE REVIEW

**Comment by SomeTroglodyte** [comment]
Now that I see it, I'd like it better centered.

**Comment by xlenstra** [comment]
> Now that I see it, I'd like it better centered.

Completely agree, so feel free to PR it. My usual technique of spamming `.center()` everywhere didn't seem to yield results so I just gave up on it

**Comment by xlenstra** [comment]
> ```
> Exception in thread "LWJGL Application" kotlin.UninitializedPropertyAccessException: lateinit property civInfo has not been initialized
> 	at com.unciv.logic.city.CityInfo.getCivInfo(CityInfo.kt:31)
> 	at com.unciv.models.ruleset.unit.BaseUnit.canBePurchasedWithStat(BaseUnit.kt:225)
> 	at com.unciv.models.ruleset.unit.BaseUnit.getCivilopediaTextLines(BaseUnit.kt:129)
> ```

Should be fixed in #5057 when I noticed this same crash myself

**Comment by SomeTroglodyte** [comment]
Aw, not another puzzle for me then...

**Pull request merged**
