### PR TITLE
Added some malay translation

### PR DESCRIPTION
**Pull request by fab144**

### CODE REVIEW

**Comment by yairm210** [comment]
You need to resolve conflicts :)

**Comment by fab144** [comment]
How do i resolve it

**Comment by yairm210** [comment]
Explanation here:

https://github.com/yairm210/Unciv/pull/1296

**Comment by fab144** [comment]
Oh on thanks

**Comment by yairm210** [comment]
We've changed the way the translation files are handled for a future with less conflicts and less failing builds!
Instructions at https://github.com/yairm210/Unciv/wiki/Translating =D

**Pull request closed without merging**
