### PR TITLE
Texture packer conditionally

### PR DESCRIPTION
**Pull request by rh-github-2015**
Another late april fool's joke (but it works!):

This saves a little time by skipping game.atlas/game*.png generation if there's no image file in the Image directory tree with a modification time later than its atlas file's.

Note I didn't close a hole: game\d+.png aren't checked. If you want to force a re-gen delete the atlas not a secondary image pack.

### CODE REVIEW

**Comment by JackRainy** [comment]
Wow! Great improvement! Thank you.

**Comment by rh-github-2015** [comment]
> Wow! Great improvement! Thank you.

Nah. Players of the Jar or Apk will hardly notice. Modders just a little. I hope you did proofread the code - don't want another fiasco like that `if (stage==null) return` one I caused.

**Comment by JackRainy** [comment]
I did just a _static_ code-review (from smartphone), and the code looks good.
However, I prefer a _dinamic_ review with Studio, where you can put breakpoints, see the variables and states, try different scenarios - you can find much more interesting things in this way :)

P.S. By the way, why all your PRs contain old "Inca" commits?

**Comment by rh-github-2015** [comment]
> static / dynamic

Thank you. Yes, the debugger is indispensable. Even on hardware smartphone (in that case just remember `adb kill-server & adb devices` before each debug session - saves time)

> all your PRs contain old "Inca" commits

Let's say prejudice. I fully expected that if you can fork purely online without even having installed git, then you _must_ also be able to keep the fork up to date online-only without git. The only way - reverse pull request and merge that. And that regrettably leaves unsightly traces upstream as I later learned. To fix, I'd have to re-fork, and github blocks that being a separate copy so I'd have to completely delete the fork - and then I could not provide fixes to open PR's. And those are at the moment a bit heavy, so I still hesitate. Which in turn means I shouldn't push new stuff, but I can't resist. I don't even understand why all those outdated commits show up, but as long as the file-by-file diffs are OK I ignore them. Sorry. As I said some time ago - M$ TFS experience leading to confused terminology.

Btw - what's your way to keep up? What I learned may not be optimal either (VCS - git - remotes, add upstream manually - once, and when it's time git-fetch as safety guard, then git-pull from upstream/master, then push to your own master, then project sync using rebase strategy).

**Comment by yairm210** [comment]
This is really clever! Thank you ❤️

**Comment by JackRainy** [comment]
> Btw - what's your way to keep up?

I migrated to Git from Perforce 5 years ago and really glad of that.
My setup looks like this:
git flow


Preconditions:
A) Create a fork
B) Setup aliases:
`git remote add origin https://github.com/JackRainy/Unciv.git` - path to the fork
`git remote add upstream https://github.com/yairm210/Unciv.git` - path to the Unciv repo

Workflow (see diagram):
1. Get the latest changes from the Unciv repo: `fetch`, `rebase` and then immediately update the fork by `push`
2. At this point you are ready to start working on the feature. Just create a separate branch for that by `checkout -b`. **Important:** never commit to the master branch! Otherwise, there will be a lot of conflicts on each pull.
3. As soon as all commits are ready, go back to the master (`checkout master`) and update it to the latest from Unciv repo (step 1). Then perform `git rebase master feature1234` to resolve all merge conflicts locally even before making the PR.
4. The branch is updated, tests are green, and you are ready to share, just `push` the branch to your fork. It will appear in Github as ready for pull request, so just create it. That's it.

At any moment working on the *feature1234* (or while waiting for the review) you can switch back to the master (`checkout master`) and start working on another feature starting from the step 1.
If you need to add the commits to the *feature1234* (e.g. got feedback on review) - switch back to the feature branch (`checkout feature1234`), add the new commits and `git push` to the fork. They will appear in the PR automatically.

**Comment by rh-github-2015** [comment]
Wow. You really went out of your way to help me out. 

From a quick glance, that's mostly equivalent to what I'm now doing except for 3. That step 3 I emulate sometimes by copying the end state of a branch 'offline' to a separate folder, start with a fresh branch and merging back in using an external merge. Should be equivalent except you get to merge everything at once and are not forced to resolve the same file over and over again. And all the 'Incas' are thanks to me missing out on step B line 2 initially - really a "WTF why doesn't the system do that automatically" one - and then me finding a workaround (reverse PR) that deviates too much I think... Even that JetBrains video having Tasha something explaining how to 'keep up' skipped that little detail - they had done it but didn't clearly show it. I might be getting too old for this...

**Pull request merged**
