### PR TITLE
Perform housekeeping for Ukrainian translations - symbols, word order…

### PR DESCRIPTION
**Pull request by estorski**
…, and extra translations

### CODE REVIEW

**Comment by yairm210** [comment]
Conflicts

**Comment by estorski** [comment]
Rebased, please recheck

**Comment by OptimizedForDensity** [comment]
As a heads up, you can create branches in your fork of Unciv then make the translation changes on Github. When you go to open your PR, you can choose to merge the translation changes from that branch instead of your master branch. That way, you don't have to constantly force update your pull request if a PR is merged into the Unciv master branch.

**Comment by estorski** [comment]
> As a heads up, you can create branches in your fork of Unciv then make the translation changes in that branch on Github. When you go to open your PR, you can choose to merge the translation changes from that branch instead of your master branch. That way, you don't have to constantly force update your pull request if a PR is merged into the Unciv master branch. Then once your PR is closed and merged into the next version, you can update your master branch to the latest Unciv commit, create a new branch, then make the next set of translations.

Hey hey mate, thanks for the heads up!

I'm working with git locally, and don't have to "update" local `master` every now and then, because why? `master` is no better or worse than any other branch, and translations is the only thing I do to Unciv anyway.

**Pull request merged**
