### PR TITLE
Can choose nativefont or font downloading from internet in gamesettings

### PR DESCRIPTION
**Pull request by lishaoxia1985**
I'm not sure if it can run in desktop, because i don't know how to test java desktop app in android studio. 
about ios, although i have xcode, i don't have an iphone, i will find out some method. if you know how to do, please tell me or give me some information about it by web.

### CODE REVIEW

**Comment by yairm210** [comment]
It looks like the travis build failed :/
Add for iPhone, forget about it, is not important now. If in a few years well want to go iPhone well deal with it then.

**Comment by lishaoxia1985** [comment]
@yairm210 i have delete ios native font.

**Comment by yairm210** [comment]
Build problem solved!
And does it now work for desktop?

**Comment by lishaoxia1985** [comment]
sorry, i'm not sure, because i don't know how to test java in android studio.today i download elipse for java,but i can't test it in this.
on the other hand, my system envoriment is in chinese, so i can't test in no‐chinese system.
my technology is not very good, pardon me.i will find out a method.

**Pull request closed without merging**
