### PR TITLE
Civilopedia phase 8 - Nations and Promotions

### PR DESCRIPTION
**Pull request by SomeTroglodyte**
The usual...

<details><summary>Eye Candy</summary>

image

image

*** Not part of this PR ***
image
</details>

Remarks:
- Nation.kt code duplication is _not_ fine but I need to think about #4656 before resolving that. The last screenshot was done with an experiment that had `Nation.getUniqueString` and its 3 subroutines disabled, so it's not so far off.
- All languages touched only in order to "kill off" the next translateable depending on leading and trailing blanks - and this time the variation in actual blanks in the translations was no better.
- Preparation to move the "first tabstop" (indent=1) because someone keeps asking - will need separate tuning later.
- Displaying 1 movement for air units seemed like it needed to be hidden

### CODE REVIEW

**Comment by yairm210** [comment]
The reason for the spaces of that in Chinese and similar languages, there are no spaces between the options.
A way around this could be to create a "[a] or [b]" template, and recursively use it to fold the list into a single string

**Comment by logicminimal** [comment]
those trailing spaces are really confusing especially when doing translations and looking at some text in the game and seeing there are spaces there for no reason

**Comment by yairm210** [comment]
I know, that's why I explained the problem and suggested a workaround :)

**Comment by SomeTroglodyte** [comment]
With a single string for a list of promotions we'd be back to the old way without links? A link per line means a line per linkable item. But I get "OR [alternative] = " as template might be better. Only way to allow the translator to decide he wants no glue text at all, unless he uses [`\u200B`](https://en.wikipedia.org/wiki/Zero-width_space) which would be just as unmaintainable as significant leading or trailing blanks.

**Comment by SomeTroglodyte** [comment]
... But in that case I'd best not presume and better _delete_ those existing translations I can't understand or second-guess. I mean if I fix " OR  = 或" to "OR = 或" without having an inkling of Chinese that's reasonable because if that symbol can mean OR-with-spaces then it must also be appropriate for the word OR alone. But with placeholder I'm implying a certain order and that I cannot predict.

**Comment by SomeTroglodyte** [comment]
And `.tr()` supporting recursion for nested []'s or even nesting [] inside {} - no it doesn't at the moment, those regexes can't count.

**Comment by SomeTroglodyte** [comment]
In that latest proofreading pass I was a bit surprised our `uniques` aren't all the same collection type... Value of interfaces... But that's for another day.

**Comment by yairm210** [comment]
Even the new "or []" doesn't cut it. What do you do with the space before the "or"? That doesn't exist in Chinese either.
What I was suggesting isn't nesting, but rather like:


```kotlin
val list = listOf("first", "second", "third")
var result= list[0]
for(i in 1..list.length) result = "[$result] OR [${list[i]}]"
```

I'm sure there's a way to do this with .fold{} as well.

**Comment by SomeTroglodyte** [comment]
Actually, as I understand it that would be `.joinToString` and be close to the previous Civilopedia - but I see where I explained badly and that there's a big to-do for phase 10 or 11: Make sure all cases structurally similar to this use the same appoach. I think that's on some list anyway.

Clarification:
image

(a) is how I understand your train of thought - remember, one link per line - not wishing to arbitrarily just link only the first one
(b) is the current PR
(c) is an alternative I probably used for some other of the objects, most compact but likely least practical for diverse translateability
(d) is what I _now_ would propose as best solution. Simplest code, too. For lists of size 1 we'd still do (a)/(c).

(And as you see there is no actual space character before the "OR" in (b) or (c), just padding, but there is in (a)... I probably went at it with an unflexible preconception because there is an existing translation for the standalone word "requires")

**Comment by SomeTroglodyte** [comment]
... waaaaaaaaait, are you _not_ talking about the Civilopedia use but about the `getDescription()` for the picker screen? Ouch. I'd better revert that.

**Comment by yairm210** [comment]
D does indeed seem like the best one :)

**Comment by logicminimal** [comment]
another suggestion: to include multiple ranking of a promotion inside just one
like indtead of accuracy I, II, III there is only accuracy on civilopedia

**Pull request merged**
