### PR TITLE
Bump Gradle to 8.5 and kotlin to 1.9.20

### PR DESCRIPTION
**Pull request by SomeTroglodyte**
#### An Experiment! Implications unclear.

This is what I ended up with after following the second comment in #10725 - it runs all targets, from gradlew commands or from Studio run configurations. Still, somehow the requirement to remove all those `sourceCompatibility` declarations doesn't spark confidence...

### CODE REVIEW

**Comment by SeventhM** [comment]
I'm not as knowledgeable of the different versions, so I'm almost definitely missing something... But is there a reason to move to 8.1.2 instead of 8.1.4 or 8.2.0?

**Comment by SeventhM** [comment]
I keep up to date on Studio kinda just because (I'm torn on the new UI tbh, some of the stuff moved around in ways that I don't like, but it's not the worst UI change I've seen), and it gave me a warning for 8.1.2 that 8.1.4 was newer, so ¯⁠\⁠_⁠(⁠ツ⁠)⁠_⁠/⁠¯. For the record, this pr worked fine on my dev build, even when going to 8.1.4. Haven't tried 8.2.0 yet, but I'm pretty sure it'll work too

**Comment by SeventhM** [comment]
Oh hey
> Configure project :
AGPBI: {"kind":"warning","text":"The option setting 'android.defaults.buildfeatures.buildconfig=true' is deprecated.\nThe current default is 'false'.\nIt will be removed in version 9.0 of the Android Gradle plugin.\nYou can resolve this warning in Android Studio via `Refactor` > `Migrate BuildConfig to Gradle Build Files`","sources":[{}]}

**Comment by SeventhM** [comment]
Am messing around and did an inspection
> 'Enum.values()' is recommended to be replaced by 'Enum.entries' since 1.9

**Comment by SeventhM** [comment]
Not sure if it's related, but I've recently been running into a new set of problems: It'll work fine for whatever session I'm currently working with, but if I move my environment to a different computer, I run into issues with `.idea` that force me to delete pretty much the whole folder. Otherwise, Studio starts complaining about an illegal character somewhere. Idk if it's a issue with how Studio is saving configurations, or something else entirely, but it is annoying

**Comment by yairm210** [comment]
To minimize risk, I added the changes that I could that don't require upgrading

I also upgraded the java version in the deploy so this should pass

**Comment by SeventhM** [comment]
> How?

Studio is on a flash drive for me. Also, I lazily haven't integrated my environment with git. I instead either manually updated stuff or redownload everything. I probably could get hit working with the flash drive, but ¯⁠\⁠_⁠(⁠ツ⁠)⁠_⁠/⁠¯

**Comment by yairm210** [comment]
Lazy loading - developer edition 👍🏿

**Pull request closed without merging**
