### PR TITLE
Fix: Raze exceptions

### PR DESCRIPTION
**Pull request by lyrjie**
Implemented raze [limitations](https://civilization.fandom.com/wiki/Conquered_cities_(Civ5)#Exception), namely:
* Being able to raze cities found by yourself
* Being able to raze original capitals

### CODE REVIEW

**Comment by yairm210** [comment]
I think being able to trace your own cities is an important strategic decision
Also, with the way the domination victory currently works, reaching capitals is give, but this will need to change when we change the domination victory

**Comment by lyrjie** [comment]
So player should be able to raze his own cities? Should I just narrow it down to his own capital then?

**Comment by yairm210** [comment]
I'm saying that as of now, original capitals hold no meaning. When victory can be attained by being the only Civ owning it's original capital, then it will be meaningful, but that will require changes to the AI to target capitals and prioritize it's own

**Comment by yairm210** [comment]
So yeah, at the moment I think I'll close this =)

**Pull request closed without merging**
