### PR TITLE
Implemented #2960 - hills can be of different types 

### LINKED ISSUE #2960: update hill
update hill maybe like this

hillupdate1

-good luck-

### PR DESCRIPTION
**Pull request by HadeanLake**
new hills
default tileset

This will close #2960 
* Hills can be of different types - Desert, snow, grassland, plains, tundra
Hills in old saves will be converted to grassland+hill
Snow hills provide no stats from terrain
Jungle can occur on hill
New hill sprites by Ravignir
Sheep can be found on hills (except snow hills. Nothing can be found on snow hills)
Resource spawning in civ 5 is very complicated - over 9000 lines of lua code and comments - 
[AssignStartingPlots.lua.txt](https://github.com/yairm210/Unciv/files/5182652/AssignStartingPlots.lua.txt)
will not be changed much in this PR

### CODE REVIEW

**Review by yairm210 — COMMENTED** [review]
o_O

Da hell
I can't believe you did this

A couple of notes:

A. Instead of a isHill Boolean parameter, there should be an elevationLevel:int parameter, which will allow us A. to have special types of mountains as well B. to accommodate future height level features (thinking of Endless Legend and Humankind - I can dream, and if we're adding a parameter anyway...), fun isHill() = elevationLevel == 1

B. It's become increasingly clear that we need a single 'does tile for unique filter' function, I think it should be in the tileInfo, TileInfo.fitsUniqueFilter(filterText:String): Boolean

I assume this will require more tweaking in the future, but for a first shot, WOW

**Comment by yairm210** [comment]
I do have another proposal if you're willing.
As with a lot of complex commits, this can be easily separated into "minor changes" and "major changes".
Minor includes the "rare feature" unique, the double image fix, etc.
Those I can commit as soon as they're separated, which will slim this PR down considerably I feel

**Comment by HadeanLake** [comment]
Moved TileInfo.fitsUniqueFilter, "rare feature" unique, the double image into separate PR

**Comment by HadeanLake** [comment]
getHeight() vs elevationLevel
elevationLevel - is where unit is standing. On the ground near feature (natural wonder or vegetation), not on top of it. In civ 5 XMLs known as SEE_FROM
getHeight() - SEE_THROUGH

Civ5/Assets/Gameplay/XML/GlobalDefines.xml:

```
        <Row Name="MOUNTAIN_SEE_FROM_CHANGE">
            <Value>2</Value>
        </Row>
        <Row Name="MOUNTAIN_SEE_THROUGH_CHANGE">
            <Value>2</Value>
        </Row>
        <Row Name="HILLS_SEE_FROM_CHANGE">
            <Value>1</Value>
        </Row>
        <Row Name="HILLS_SEE_THROUGH_CHANGE">
            <Value>1</Value>
        </Row>
```
Civ5/Assets/Gameplay/XML/Terrain/CIV5Features.xml
```
        <ArtDefineTag>ART_DEF_FEATURE_FOREST</ArtDefineTag>
        ...
        <SeeThrough>1</SeeThrough>
        ...
        <ArtDefineTag>ART_DEF_FEATURE_REEF</ArtDefineTag>
        ...
        <SeeThrough>2</SeeThrough>
```
Hill has elevationLevel = 1
Mountain has elevationLevel = 2
Forest/jungle increase height by 1
Natural wonders increase height by 2
cannot see over reef
Great Barrier Reef has Height = 2. Ocean tile is not visible behind it.

this v3
On screenshot: unit with sightDistance=4
can see hill+forest+deer behind hill
cannot see hill+coal begind hill+forest
can see cattle on flat behind hill (observer is on hill)
can see ivory on flat behind hill (observer is on hill and 3 tiles away from ivory)
cannot see mountains behind hill+forest
can see mountain on sightDistance+1 behind forest+furs
cannot see hill+sheep at sightDistance+1 behind forest
cannot see hill+aluminum at sightDistance+1 behind hills
cannot see hill+forest+gold at sightDistance+1 behind hills - features do not increase height at sightDistance+1

Placing forest on observer's tile will not have effect on visibility of other tiles
Tile can be seen on sightDistance+1 if its elevationLevel is higher than getHeight() of any tile between it and observer
Tiles of same getHeight() do not block each other, even if they are at elevation > 0
Standing on hill does not increase sight distance
These mountains can be seen despite having no visible neighbors:
can see mountain behind hill

**Comment by yairm210** [comment]
I think you're trying to do multiple things at once again.
What's the minimum change you can commit to the repo where the game is still stable?

**Comment by HadeanLake** [comment]
Should be good now

**Comment by yairm210** [comment]
I'm really sorry, there is still just Too Much Going On for me to be able to hold all this in my head at once.
I mean there's like a bajillion changes that were made here, and I can hardly tell what's potentially gamebreaking and what isn't.

I'm not even sure this is the right way to go about it, to be honest. There are multiple things here that make me think a different change is in order, where the tileInfo should be built up of terrain layers and then there's no difference between 2 or potentially 4. But this too is a huge change in the game mechanics, and I'm not sure what we're really gaining with this kind of change.

What I mean is this is such a huge change to the underlying mechanics, and it comes to serve such a specific purpose, that I'm thinking of how this could be better built to serve the current gameplay, and only then changing the hills mechanic.

**Comment by HadeanLake** [comment]
NotLikeThis
So all wasted?
`fun isHill() = baseTerrain == Constants.hill` can be merged separately to make it more manageable
https://github.com/HadeanLake/Unciv/commit/693c2b399a614832ce86e614c260c865dcb83216
 In civ 5 tileInfo has enum plotType with 4 possible values: PLOT_HILLS, PLOT_MOUNTAIN, PLOT_OCEAN (named ocean but used for both ocean and lakes) and PLOT_LAND instead of elevationLevel

```
elseif plotType == PlotTypes.PLOT_HILLS and terrainType ~= TerrainTypes.TERRAIN_SNOW then
    allowed_luxuries[self.gold_ID] = true;
    allowed_luxuries[self.silver_ID] = true;
    allowed_luxuries[self.gems_ID] = true;
    if featureType == FeatureTypes.NO_FEATURE then
        allowed_luxuries[self.marble_ID] = true;
    end
elseif plotType == PlotTypes.PLOT_LAND then
    if featureType == FeatureTypes.NO_FEATURE then
        if terrainType == TerrainTypes.TERRAIN_TUNDRA then
            allowed_luxuries[self.fur_ID] = true;
            allowed_luxuries[self.silver_ID] = true;
            allowed_luxuries[self.marble_ID] = true;
```

**Comment by yairm210** [comment]
I'm not saying throw it all away, I'm saying the change should be gradual.
I really don't know where to start with this.
isHill() is probably a good start, as is adding the visibility parameters to the terrains (not sure what to call them though - how do you convert this to the user?)

**Comment by HadeanLake** [comment]
isHill()  is in separated PR.
make features and wonders have `var height = 0` ?
User does not need top know exact height of mountain. Just put few lines in civilopedia - tutorials

> Hills slow down unit movement, but provide a sight advantage by allowing the unit to see over trees and other hills. Moving into a tile with a hill will often consume all of a unit's movement points. Hills block the view of objects behind them.

> You can always see everything within your borders, as well as one tile away from your borders. Most units can see everything within 2 tiles (except for tiles behind mountains and blocking tiles). Units on hills can see over blocked tiles. Certain promotions will extend a unit's sight by 1 tile, and also, a number of mid- to late-game naval units have extended sight as well.

**Comment by ravignir** [comment]
That's sad 😓

**Comment by SomeTroglodyte** [comment]
My take: This would be quite valuable. It has always irked me in the past that Unciv implements hills differently than what I was used to, and I have played with a mini Terrain mod adding a 'foothills' layer meant as being between hills and mountains in virtual height, mobility, resources and defense - so I recoded the map generator if I remember correctly to do more with the actual [perlin noise model](https://en.wikipedia.org/wiki/Perlin_noise) than just cut a plane through it for the coast lines, but at the end threw away the height data and mapped the foothills to a 3D-agnostic separate terrain type... Also the way (at least some) map generators handle temperature and humidity as discrete linear values under the hood then throw them away in favour of a very few multiple-choice categories...

All that made me think - 

What if we kept more of that generator data, say have separate z, h, t coords (height, humidity, temperature) for each tile, maybe limiting them to 4-bit signed integers or so, and map them to the current system much later during gameplay. So z/h/t would span a 3D phase space covering 4096 cells, and we'd have our existing terrain combinations map to 3D slices of that space. Now terrain mods could simply define which space of that 3D box they want to cover... Visibility/occlusion code would work even if we had 7 underwater levels all fleshed out with visuals... And maps may with a little luck look a little more natural as the flat/hill/mtn component terrain type is no longer taken from a Perlin texture separate from the one for coastlines???

So yes, I'd be very much in favour of somehow pursuing this. *Very* big applause to HadeanLake for making this work in their fork (but I know how it is concerning mergeability).

**Comment by yairm210** [comment]
After months of work, this has finally been implemented and deployed by GGGueni!

**Pull request closed without merging**
