### PR TITLE
Fix gold able to over- and underflow

### LINKED ISSUE #4064: My gold vanishes!
I have exactly 2147483646 gold. But Unciv lies:
image

I earn gold - pass a turn. Unciv has _stolen all **my** gold and then some!!!!!!_:
image

## ~~Unacceptable! That outrage has to stop!~~

OK, sorry for the bad joke. Hope someone gets a chuckle out of this...

### PR DESCRIPTION
**Pull request by SomeTroglodyte**
Resolves #4064  :astonished:

### CODE REVIEW

**Comment by yairm210** [comment]
And the proud winner of "most niche PR" is...

**Comment by SomeTroglodyte** [comment]
image O U C H - you actually merged the joke? Wow. _Respect_.

You'll probably even punish me by publishing the attribution in big fat bold on the play store...

**Comment by yairm210** [comment]
I merged this because it makes it easy to see where we're setting the value of the civ gold, to make sure that most interactions only add or decrease, and don't set the value directly.

**Comment by will-ca** [comment]
Oh, so *that's* why this one particular resource has oddly strict rules for setting!

**Pull request merged**
