### PR TITLE
Physical keyboard check controls key label visibility

### PR DESCRIPTION
**Pull request by SomeTroglodyte**
Thanks @JackRainy - this has passed a few tests 100% successfully so far.

### CODE REVIEW

**Comment by SomeTroglodyte** [comment]
No, wait. While this works as intended, hovering does not. 

I've got Lineage which exposes the setting enabling hovering with a finger (which worked in the browser long ago, Lineage 11 if I remember correctly, but does not today on Lineage 16). I've got Stylus hardware - it paints a circle while still 1cm away but no enter/exit events, and no link hovering in the browser. Bluetooth mouse, USB mouse over OTG - browser underlines links but our game doesn't. And reading the whole gdx/backends/android/AndroidInput.java there seems to be no provision to support this. The Configuation object it uses (Android SDK, not Gdx) has the ominous line `@Deprecated public static final int TOUCHSCREEN_STYLUS = 2;`

So I'd guess we'd have to make the hints statically visible on 'droid.

**Comment by yairm210** [comment]
They're now statically visible everywhere, so this fits in well

**Comment by SomeTroglodyte** [comment]
Update: enter and exit _**do**_ fire if you drag an already touching finger or clicked mouse into the actor. Conclusion: LibGdx just doesn't support hovering on Android.

**Comment by yairm210** [comment]
Wait no come back
This is good

**Comment by SomeTroglodyte** [comment]
Well, as copy and paste source it's still here. If you leave out the label visibility only on hover and the try catch guard, it boils down to no more than using Gdx.input.isPeripheralAvailable(Input.Peripheral.HardwareKeyboard) in UnitActionsTable line 84.

Sorry, received a text I'm not taking well, so I might not behave rationally for a while. Feel free to cannibalize what you want.

**Pull request closed without merging**
