### PR TITLE
fix citystate declare war on itself

### PR DESCRIPTION
**Pull request by MindaugasRumsa51**

### CODE REVIEW

**Comment by yairm210** [comment]
You can't become the ally of a CS you are at war with so this would never happen

**Comment by yairm210** [comment]
Unless you managed to make this happen in since game?

**Comment by MindaugasRumsa51** [comment]
this problem is reported in discord various times
as i understood problem is when you declaring war to your ally city state

**Comment by yairm210** [comment]
So this is a guess, and it's in the wrong place.
This code is when city states *become* your ally.

**Comment by MindaugasRumsa51** [comment]
new report about it says that problem related with NUKE

**Pull request closed without merging**
