### PR TITLE
add Lasers (Tech tree + icon + translation) for Modern Armor

### PR DESCRIPTION
**Pull request by Am-per-Sand**
- Lasers temporarily requires only `Combined Arms` (`Tank`) -> `Tank` and even Mounted units may no longer be upgraded without omitting their required techs (`Mobile Warfare` and derivatives) (which now is possible – #629 )
- when **air units** are introduced, Lasers should require also Radar or be changed to G&K or BNW prerequisites
- however in any case of tech tree version Lasers always allow Modern Armor and Jet Fighter – so even now Modern Armor can be moved there

### CODE REVIEW

**Comment by Am-per-Sand** [comment]
sorry, no `game.atlas` from me :sunglasses:

**Comment by yairm210** [comment]
I thought about this for a with, but in the end I don't want any tech paths that don't lead back to future tech
If you can make it lead there that's a different story

**Comment by Am-per-Sand** [comment]
> I don't want any tech paths that don't lead back to future tech
> If you can make it lead there that's a different story

So how about adding a fourth prerequisite to Future Tech:
Combined Arms -> Lasers -> Stealth -> Future Tech?

This would be still be temporary, but staying in line with G&K tech tree could be kept indefinitely if no other changes to current tech tree are made.

**Comment by Am-per-Sand** [comment]
@yairm210 ?

**Pull request closed without merging**
