### PR TITLE
some UI update.

### PR DESCRIPTION
**Pull request by lishaoxia1985**
XueR
YueR

### CODE REVIEW

**Comment by yairm210** [comment]
I like what you did with the specialists, but the color in the civilopedia looks very jarring

**Comment by lishaoxia1985** [comment]
because I lack of sense of beauty.😊

**Comment by yairm210** [comment]
Please separate the civilopedia changes from the rest and I'll merge the rest =)

**Comment by lishaoxia1985** [comment]
@yairm210  OK, i separate it.

**Comment by JackRainy** [comment]
In my opinion, those red buttons looks ugly comparing to the "Close" button which were there before.
Also, some of them too small to be clicked easily.
Screenshot 2020-03-04 08 22 24
Screenshot 2020-03-04 08 23 34

**BEFORE**
Screenshot 2020-03-04 08 27 39
Screenshot 2020-03-04 08 28 24

**Pull request merged**
