### PR TITLE
Update Korean.properties

### PR DESCRIPTION
**Pull request by saud2410**
@JackRainy Please check difference before & after. Wanna contact about Kr. translation. Find @TG #3633 at any channel of https://discord.com/invite/bjrB4Xw .

### CODE REVIEW

**Comment by JackRainy** [comment]
Sorry, @saud2410, I am not competent in Korean to check the quality of translation.

**Comment by saud2410** [comment]
@JackRainy No problem at all. In fact i wanna know about your backgrounds as a former translator. You're not Korean?

**Comment by JackRainy** [comment]
No, I do translations for Ukrainian and Russian.

**Comment by saud2410** [comment]
@woone8 @PenguinDoc 한글 번역하신분 계신가요 잉카 대사 변경점 한번 봐주세요

**Comment by yairm210** [comment]
merge translations

**Pull request merged**
