### PR TITLE
AI diplomacy balancing

### PR DESCRIPTION
**Pull request by tuvus**
This commit changes how the AI values signing friendship, defensive pacts, and declaring war.

From the simulation I have done on the previous versions, the AI declares peace and defensive pacts too often since being able to offer them. This results in an undesirable stalemate were everyone gangs up on one civilization.

<details><summary>Picture of stalemate</summary>

AIDiplomacyStalemate

</details> 

Using AutoPlay, I ran an AI-only simulation (prince difficulty) to see how the AI behaves on larger maps to work out changes. Usually with 6-13 AI.

Here is a list of changes that I have made to the AI's decisions:
DOF = Declaration of Friendship, DP = Defensive Pact
- DOF & DP & Open borders: Each of these now has a declined_X_ flag applied to the DiplomacyManager to prevent repetitive calculations.
- DOF & DP: The more wars the AI has, the more they want to sign a DOF & DP
- DOF: AI wants to ally with Civ's less as the other civ has more friends
- DP: AI does not want to sign DP with other Civs that are mad at their allies
- War: AI now ranks each civ that it has enough motivation to attack based on score and chooses the highest one
- War Motivation: AI now takes into account the other Civ's DP allies
- War Motivation: AI now takes into account relative score, production and 
- War Motivation: AI is less likely to declare war on a Civ that they have a DP with
- War Motivation: AI is more likely to attack Civs based on their wonders
- War Motivation: AI is more likely to attack a Civ if they are at war with their ally

Of course, more balancing will be required and most numbers are arbitrary. So, any suggestions and recommendations are more than welcome.

Note: I used the AutoPlay feature and merged parts of it into this branch. After finishing the simulations, I tried to revert the commits again. I don't think anything has passed through but something could have.

Also, could someone check that I did the score, production, and tech modifiers correctly and logically?

### CODE REVIEW

**Comment by yairm210** [comment]
Another 'too large for my brain' pr, in general I trust you regarding AI but I would rather someone else went over this as well

**Comment by tuvus** [comment]
Agreed, I kind of put (at least) three separate commits into one. It was easier for me to test together to see if they helped avoid a diplomatic stalemate this way.

**Comment by yairm210** [comment]
All I can say is: motivation to attack should (after this pr!) be extracted into a separate class and split into subfunctions...

**Comment by tuvus** [comment]
Aaaahhhhh. I think there are problems with the AI diplomacy balancing and initial AutoPlay implementation branch. I can't seem to merge them into the same branch without the AI diplomacy balancing commits removing part of the AutoPlay features. So I might delete this branch and create a new PR or see if I can do a hard reset and only copy in the two file changes.

I should have a better system set up for future PRs.

**Pull request closed without merging**
