### PR TITLE
Rewrite the font system to render the characters incrementally

### LINKED ISSUE #2374: Some Chinese characters cannot be input
When I changed the city name, I found that some Chinese characters could not be input, such as "莆".Although this situation will not cause anything to happen, it will destroy the game experience..
Screenshot_20200409-170402
Screenshot_20200409-170409

### PR DESCRIPTION
**Pull request by vainiovano**
Fixes #2374

The platform-specific implementations are now loaded like in https://github.com/libgdx/libgdx/wiki/Interfacing-with-platform-specific-code

### CODE REVIEW

**Comment by yairm210** [comment]
Okay, WOW
How long did this take you?
Also, did you notice a performance problem when displaying texts? We could have already-rendered chars on a hashmap if needed, but maybe it's not needed

**Comment by vainiovano** [comment]
I don't remember when I started making this. I wrote the code gradually. I started from the libgdx-freetype source code and removed the unnecessary parts. Then I replaced freetype with the native font implementations.

The already rendered chars are loaded from an array by BitmapFontData. It should be faster than using a hashmap.

**Comment by yairm210** [comment]
THIS IS AMAZING!!!
The initial loading is faster! No more missing characters! No need to worry about "special" languages!
This is a SUPER SIGNIFICANT IMPROVEMENT!!!

**Comment by lishaoxia1985** [comment]
@vainiovano very good. have you thought about deleting skin file about "*.fnt" and using nativefont instead?

**Comment by Wangrenze2004** [comment]
Well, thank  for the repair prepared by the author.

**Comment by Wangrenze2004** [comment]
@yairm210 
In addition, can you provide the download source as soon as possible?
 I can't wait.
awa

**Comment by vainiovano** [comment]
@lishaoxia1985 I could do that

**Comment by lishaoxia1985** [comment]
ok, by the way, this method can be used to show bold font, I think UI can be designed very well. changing the font size according to resolution will be an easy work.

**Pull request merged**
