### PR TITLE
Update Thai.properties

### PR DESCRIPTION
**Pull request by JackRainy**
I have noticed that Thai language is treated a bit... specially.
https://github.com/yairm210/Unciv/blob/master/core/src/com/unciv/models/translations/Translations.kt#L86-L89

I don't know why it is so.
Anyway, I'd like to keep this language file up-to-date.

### CODE REVIEW

**Comment by yairm210** [comment]
Thai is a sad case.
The translator went to the trouble of translating it, but unfortunately the LibGDX framework doesn't support the extra symbols that go above and below the letters... and they're essential for the language
In all honesty, we should delete the Thai translations =(

**Comment by JackRainy** [comment]
Well, other languages also have the symbols above/below letters - å (like this?).
Do we have the problem with them as well?
Maybe, we should wait for the fix in the LibGDX?

**Comment by yairm210** [comment]
Any character with the symbols *baked in* is fine - it's rendered just like any other character
The problem is with *independant symbols* like this:
อั
While it looks like one character, it's actually one character and one symbol above it
And if this hasn't been solved in the last 3 years, we could wait, or we could not.

**Comment by yairm210** [comment]
With heavy heart etc, Thai is getting dumped

**Pull request closed without merging**
