### PR TITLE
Inca abilities: Great Andean Road, Terrace farm

### PR DESCRIPTION
**Pull request by rh-github-2015**
Notes: The json changes are in commented objects only, to bring them more in line with what will work.
I'm going to offer an update to [ExampleIncaMod](https://github.com/yairm210/Unciv-mod-example/tree/master/ExampleIncaMod) soon, which correctly utilizes the capabilities here.
Complements #2216, with both and the updated mod the Incas should be playable very close to Civ5 rules.

### CODE REVIEW

**Comment by yairm210** [comment]
This, too, is conflicting with the recent translation changes =/

**Comment by rh-github-2015** [comment]
> This, too, is conflicting with the recent translation changes =/
Sorry, I do not understand them. As far as I can understand what 'Resolve conflicts' says, your master seems broken and it's complaining my commit reintroduces the lost technologies etc sections...

I'll try to pull your current master an see how this behaves then.

**Comment by rh-github-2015** [comment]
I <expletive> don't understand it. I manually merged my four lines each into a current copy of your master files downloaded as zip and it looks better, but there's still a huge block of nations text it says I'm introducing. Let's see if I can delete the language stuff and create a code-only branch...

**Comment by rh-github-2015** [comment]
Nope, this is beyond me. I treated all three languages identically and what the resolve conflicts button shows is vastly different. French is OK, but I don't get why it should treat the three new lines for the terrace farm as conflict but not the added line for Great Andean Road's description. Wait a minute - opening the resolver again after a few minutes changes what's marked as conflict in the other files completely. First it was onla a large block of several nation's city names, now it's almost the whole file with a few white gaps. Sorry, to me this system seems broken.

I see three options:
* You have an Idea what I am doing wrong and can help
* I throw away everything again and start over with a fresh repo, manually merging from backup with a text editor - again
* I give up

**Comment by yairm210** [comment]
My suggestion: for this commit, discard all changes to the translation files. just, completely ignore the translations. We'll deal with them later.

**Comment by rh-github-2015** [comment]
Discard - con gusto, but how?

**Comment by yairm210** [comment]
Screw it all. Everything goes in, and I'll rely on the translation files' self-healing to get things straight.
I don't like it, but it's the easiest way.

**Pull request merged**
