### PR TITLE
Updated Hungarian Translations

### PR DESCRIPTION
**Pull request by JurDan775**
my (probably) biggest translation update so far!

### CODE REVIEW

**Comment by JurDan775** [comment]
what i did wrong?

**Comment by xlenstra** [comment]
Placeholder `[resourceName]` not found in `Hungarian` for entry `[n] sources of [resourceName] revealed, e.g. near [cityName]`

**Comment by JurDan775** [comment]
oh ok

Xander Lenstra ***@***.***> ezt írta (időpont: 2021. aug. 2.,
Hét 12:21):

**Comment by logicminimal** [comment]
@JurDan775 you could have just pushed a commit instead of closing it down

**Comment by JurDan775** [comment]
i have decided to just start it over bc am just dum

Miraç ***@***.***> ezt írta (időpont: 2021. aug. 2., Hét
13:58):

**Pull request closed without merging**
