### PR TITLE
[Bundle] [RU] L10n Update

### PR DESCRIPTION
**Pull request by summetdev**
Added:
* Show tile yields
* Move to city
* The resistance in [cityName] has ended!
* +[amount]% Production when constructing [unitType] units
* Doubles Gold given to enemy if city is captured

### CODE REVIEW

**Comment by yairm210** [comment]
merge translations

**Comment by summetdev** [comment]
merge translations

**Comment by summetdev** [comment]
summary

**Comment by summetdev** [comment]
Corrected commit descriptions with force push, ready to merge now.

**Comment by yairm210** [comment]
summary

**Pull request merged**
