### PR TITLE
Redo build order AI.

### PR DESCRIPTION
**Pull request by ninjatao**
More flexible build order. Covering https://github.com/yairm210/UnCiv/issues/580.

Still need some time for parameters polishing.

### CODE REVIEW

**Comment by ninjatao** [comment]
I guess it should hold up for about one week for some more priority improvements. I ran some test games already and found something could be improved.

**Comment by yairm210** [comment]
Do you feel it's ready?

**Comment by ninjatao** [comment]
I think it is ready. Please review and merge.

**Comment by yairm210** [comment]
It looks like all the values are divided by cityProduction
But... if they're all divided by it, isn't that equivalent to none of them being divided by it?

**Comment by yairm210** [comment]
What you're trying to find is "relative value" between the buildings, and this looks like a really good way to go about =)
This confuses me though:
if (cityInfo.population.population < foodBuilding.food + 5) {
                    buildingValues[foodBuilding.name] = buildingValues[foodBuilding.name]!! / 2.0f
                }
is this from playtesting?

**Comment by ninjatao** [comment]
Deviding by city production: Totally agree. It was introduced when I was thinking about how to affect priorities with city production rate. More developped cities should build armies and wonders while new cities build granary and workshop. In fact this can be done by comparing relative values of buildable items, as of now. I can remove them later if no other priority adjustment is required.

**Comment by ninjatao** [comment]
For granary and hospital: Cities with less population in long terms may have food issues, such as having many deserts or oceans in range. So they should prefer building granary, lighthouse and hospital. I just failed to find a more delicate expression for that. Any suggestions？

**Pull request merged**
