### PR TITLE
Update French.properties

### PR DESCRIPTION
**Pull request by Ouaz**

### CODE REVIEW

**Comment by yairm210** [comment]
Conflict?

**Comment by SomeTroglodyte** [comment]
The unique in the jsons was using "Chance" with capital C, that one should remain. But I'm not done yet. There will be one more PR changing _all_ translation files soon.

**Comment by Ouaz** [comment]
Do I push again the translation or do I wait your _full_ PR to be merged? Is there a chance of new conflict?

**Comment by SomeTroglodyte** [comment]
Chances are good yours will be merged before I do that PR. Tiny little problems like Caesar not <sigh>'ing anymore in _any_ language...

**Pull request closed without merging**
