### PR TITLE
Do not show the hotkeys for the Android version

### PR DESCRIPTION
**Pull request by JackRainy**
The hotkeys is an improvement for Desktop version only.

### CODE REVIEW

**Comment by SomeTroglodyte** [comment]
Well, I have a tablet with bluetooth mouse (chinese, about 4.5cm long) and bluetooth keyboard - works. Checking availability of a physical keyboard is well outside LibGdx, so I left them in. Then again, they'd continue working without visual hint.

**Comment by JackRainy** [comment]
> Checking availability of a physical keyboard is well outside LibGdx

In fact, LibGdx has something for that:
`Gdx.input.isPeripheralAvailable(Input.Peripheral.HardwareKeyboard)`
Unfortunately, I did not manage to make it work... it returns True even when I expect False.
Need to play with that more...

**Comment by yairm210** [comment]
Also some guy wrote to me about using a keyboard with Android TV, so it seems that this may be niche but it is needed for some

**Comment by yairm210** [comment]
Closing this, if we find a better way to check in the future we can reopen it always

**Comment by SomeTroglodyte** [comment]
> `Gdx.input.isPeripheralAvailable(Input.Peripheral.HardwareKeyboard)`
> Unfortunately, I did not manage to make it work... it returns True even when I expect False.
> Need to play with that more...

Wow. Maybe digging down with go to implementation........? That's how I found out why your reddit/discrap/github links did not open my chosen default browser - 'cuz the upstream programmers devalued xdg-open while using the word 'hack' in the comment... (if anyone asks such a question - tell them to `sudo rm /usr/bin/sensible-browser` - joking, works but hurts distro maintainer decisions)

**Comment by SomeTroglodyte** [comment]
> Gdx.input.isPeripheralAvailable(Input.Peripheral.HardwareKeyboard)

OK, this is hardcoded to true on the desktop backend, hardcoded to false in the ios backend, and on 'oid... Gdx source looks bugged as it checks on AndroidInput init in a plausible way and later in an onConfigChange event a different way that looks broken ('set on a device with a mechanism to hide the keyboard from the user, when that mechanism is closed')... but ... #2430 tests OK with a Mi8+Anker BT kbd (and of course desktop and emulator too), more testing soon.

**Pull request closed without merging**
