### PR TITLE
Update Brazilian_Portuguese.properties

### PR DESCRIPTION
**Pull request by AlexLuis**
I modified some translations of the menus and some constructions, and translate the Babylon

### CODE REVIEW

**Comment by yairm210** [comment]
You're conflicting with a previous change - please resolve all conflicts :)

**Comment by lincolnvs** [comment]
> You're conflicting with a previous change - please resolve all conflicts :)

Solved in #3141

**Comment by yairm210** [comment]
Is this still relevant or should I close this?

**Comment by lincolnvs** [comment]
> Is this still relevant or should I close this?

I think you can close this because I followed his commit in my PR, so his (@AlexLuis) contribution was accepted in #3141 .

**Pull request closed without merging**
