### PR TITLE
Dynamical width of the buttons

### PR DESCRIPTION
**Pull request by JackRainy**
The hardcoded value does not care about the localization, so we need to be more flexible...
| Before | After |
|-|-|
| Screenshot 2020-04-23 00 52 39 | Screenshot 2020-04-23 21 58 06 |

### CODE REVIEW

**Comment by SomeTroglodyte** [comment]
I noticed english truncated once, gone next time I looked, and the long german versions fit nicely without this commit - but what I see in the diff looks like a good idea. The no longer aligned icons don't bother you?

**Comment by yairm210** [comment]
Gah the icons 0_0
This bothers me, a lot
Please add a .left() to the icons

**Comment by JackRainy** [comment]
@yairm210 , merging this PR to master will make:
my commit counter = 💯 commits :)
your commit counter = 2000 commits
repo commits counter = 3700 commits
🎉 🎉 🎉

**Comment by JackRainy** [comment]
image

**Comment by yairm210** [comment]
Wow!

**Comment by yairm210** [comment]
Unfortunately I didn't notice this in time =/

**Pull request merged**
