### PR TITLE
Added gradle task of Atlas texture packing for Android build

### PR DESCRIPTION
**Pull request by vegeta1k95**
New gradle task for packing texture atlases for Android builds.
It is basically a copy of desktop ImagePacker but for a build-script.

### CODE REVIEW

**Comment by yairm210** [comment]
We *intentionally* leave this out of Android to minimize the apk size, since one of our targets is "minimal size for minimal phones"

**Comment by Kuldebar** [comment]
Baldur's Gate Enhanced has an additional 800mb download after initial playstore install. Chromebook Android gamers are increasing. 

Not trying to be argumentative, but even my 30 dollar android go smartphone has 4gb free ATM but I'd never play games on it.

**Comment by vegeta1k95** [comment]
> We _intentionally_ leave this out of Android to minimize the apk size, since one of our targets is "minimal size for minimal phones"

What do you mean? How is APK size influenced by this?

**Comment by yairm210** [comment]
Ah I see, I misunderstood

**Comment by yairm210** [comment]
> Baldur's Gate Enhanced has an additional 800mb download after initial playstore install. Chromebook Android gamers are increasing.
> 
> Not trying to be argumentative, but even my 30 dollar android go smartphone has 4gb free ATM but I'd never play games on it.

About a year ago I was in this position, working with a phone where I needed to remove an app if I wanted to download a new one. And my phone was relatively good compared to a lot of the ones I see ruining Unciv in the Google Play stats.
Anecdotes are not data either way, but this *is* a real issue.

**Pull request merged**
