### PR TITLE
Kotlin 1.5 new warnings - partial - managers

### PR DESCRIPTION
**Pull request by SomeTroglodyte**
This warnings-be-gone has an interesting side **question**: What to do about the bad spelling of Denunciation in DiplomacyFlags? That's serialized into saves I suppose...

### CODE REVIEW

**Comment by xlenstra** [comment]
The way I've done these so far:
- Add an extra flag, so there is both the wrong and right flag
- Deprecate the wrong flag
- Whenever `setTransients` of the object is called, move the wrong flag to the right flag and then remove the wrong flag
- Eventually, remove the deprecation

**Comment by SomeTroglodyte** [comment]
Yup - worth it or hide under carpet is the question. Never fix a working gadget and so on.

**Comment by yairm210** [comment]
> The way I've done these so far:
> 
> * Add an extra flag, so there is both the wrong and right flag
> * Deprecate the wrong flag
> * Whenever `setTransients` of the object is called, move the wrong flag to the right flag and then remove the wrong flag
> * Eventually, remove the deprecation

Precisely!
Since I understand you're currently in college, I will say that this is good practice.
Almost all production systems I've worked on have had some kind of "data migration" at one point or another, often multiple at once, and soft depreciation is a good solution

**Comment by SomeTroglodyte** [comment]
Yup again - that may even exist in my old "Anti-warnings-campaign" branch, I can't even remember. But as `Denunceation` is just an opcode and not displayed, I'll think of it as a 'hide under carpet' case for now.

**Comment by SomeTroglodyte** [comment]
... Since I went pretty arbitrarily about choosing where to patch the new kotlin warnings first, that "issue" is not finished, though we should be more than halfway. I promise I'll go for the rest, including all the old friends, in time.

**Pull request merged**
