### PR TITLE
Show promises not to settle, ask on found city action

### LINKED ISSUE #3976: Request:  Show agreements to not settle new cities near another civilization
I have run into an issue where it wasn't made clear to me that I had previously agreed to a demand from another civilization to not settle new lands near them.  This lead to an immediate loss of relationship that would mark a slow path to war.  If it had been made clear that this demand had been agreed to (be it in the Diplomacy tab or a notification when attempting to settle), this could have been avoided.

_(edited because I learned that this is considered a demand)_

### PR DESCRIPTION
**Pull request by SomeTroglodyte**
Might resolve #3976. Old code, and instead of ditching it I decided to test and offer.

https://user-images.githubusercontent.com/63000004/121965462-59673f00-cd6d-11eb-83ed-79060b241142.mp4

### CODE REVIEW

**Comment by ravignir** [comment]
I have kind of unrelated question, that is: does it trigger when you manually buy tiles in a city? Because that does trigger breaking the promise to not settle in civ5.

**Comment by AdityaMH** [comment]
I think this will resolve #4107 where can't fix AI exploration move, so explorer will cancel his action if start to enter border and show this prompt. Also resolve for declare war to CC CS or declare war by entering other civ border or moving unit to other civ CC by show this prormpt this first.
So, player can declare war without open diplomacy screen first.

**Comment by AdityaMH** [comment]
>Does it trigger when you manually buy tiles in a city? Because that does trigger breaking the promise to not settle in civ5.

I think will better if buy tiles or increase tiles by culture not break the promise.

**Comment by ravignir** [comment]
tile increase by culture does not break it. Buying by gold does, because you control it.

**Comment by SomeTroglodyte** [comment]
@ravignir - please explain the original rules clearer? I can only go by what Unciv does: No promise - at time of city founding only - distance 3 or less is blocked, distance 4 or more is allowed and no diplomatic repercussions. With promise - distance 3 or less blocked, distance 4 to 6 breaks promise, distance 7 or more no repercussions. That is Aerial distance to the nearest contending civ's _city_, not distance to nearest _border_!

This PR did not change these rules in any way, it's just visual.

Actually, documenting rule deviations might go directly in that sticky with the sixes in its Issue number...

And no, this has nothing to do with exploration, pathfinding or related themes. One aspect is purely static info in the diplo screen, the other needs a human-controlled settler having already reached a potential city-founding tile... Uh, oh, did I forget to check that???

**Comment by AdityaMH** [comment]
I mean make same prompt like this to resolve.

**Comment by SomeTroglodyte** [comment]
OK, this needs fixing ASAP - I was under the impression UnitActions as UI wrappers with sound and everything are _not_ used by AI automation - and that's wrong.

**Comment by ravignir** [comment]
> @ravignir - please explain the original rules clearer? I can only go by what Unciv does: No promise - at time of city founding only - distance 3 or less is blocked, distance 4 or more is allowed and no diplomatic repercussions. With promise - distance 3 or less blocked, distance 4 to 6 breaks promise, distance 7 or more no repercussions. That is Aerial distance to the nearest contending civ's _city_, not distance to nearest _border_!
> 
> This PR did not change these rules in any way, it's just visual.
> 
> Actually, documenting rule deviations might go directly in that sticky with the sixes in its Issue number...
> 
> And no, this has nothing to do with exploration, pathfinding or related themes. One aspect is purely static info in the diplo screen, the other needs a human-controlled settler having already reached a potential city-founding tile... Uh, oh, did I forget to check that???

I was wrong with that gold thing. It is completely different diplomacy modifier that works similarly to the "settling to close" one. I will provide more info when i will have some free time.

**Comment by SomeTroglodyte** [comment]
Well, you're our prime source for precise info like that - so one big fat "thank you" to you! (should cover all future instances of such merits :grinning: )

**Pull request merged**
