### PR TITLE
Set Gzip compression level to `Deflater.BEST_COMPRESSION`

### LINKED ISSUE #12685: Suggestion: Use maximum Gzip compression level (level 9) for uploading jsons to the server.
### Before creating

- [X] This is NOT a gameplay feature from Civ VI, BNW, or outside - see Roadmap
- [X] This is NOT a gameplay feature from Vanilla Civ V or from G&K - If so, it should be a comment in https://github.com/yairm210/Unciv/issues/4697

### Problem Description

The assumption is CPU time required for compression / decompression is much lower than network time required to fetch the files larger files and the tradeoff is generally worth it. Using maximum compression level will most likely not change much. However, I suggest the idea of using this setting. This decrease badwidth and storage usage somewhat.

### Related Issue Links

_No response_

### Desired Solution

use Gzip compression level 9

### Alternative Approaches

use something in the middle

### Additional Context

This mostly increases CPU time on client side. As server only needs to decompress these files on `PUT` requests. Any bandwidth decrease is appreciated.

### PR DESCRIPTION
**Pull request by touhidurrr**
resolves #12685

### CODE REVIEW

**Comment by touhidurrr** [comment]
Noob question as I am new to kotlin.
```diff
-        val gzip = GZIPOutputStream(bos)
+        val gzip = object : GZIPOutputStream(bos) {
+            init {
+                def.setLevel(Deflater.BEST_COMPRESSION)
+            }
+        }
```
how does it work?

**Comment by yairm210** [comment]
I was far too hasty merging this
Since we're designed to run on low-end devices, we REALLY need to compare time vs compression for these two options
It's entirely possible we're causing users to wait twice as long for like a 5% decrease in file size, this isn't free real estate

**Comment by yairm210** [comment]
Reverting for the deployment

**Comment by touhidurrr** [comment]
```kt
vall gzip = GZIPOutputStream(bos, Deflater.BEST_COMPRESSION)
```

How did I miss this though... I am pretty sure I read through all `constructors` of `GZIPOutputStream` before writing this. -_-

**Comment by touhidurrr** [comment]
@SomeTroglodyte, read https://github.com/yairm210/Unciv/issues/12685#issuecomment-2558034471. Already did a similar benchmark there for this topic. I covered compression / decompression times and size saving vs level 1 etc in there. Also set iterations to 100 for each test and took the average.

**Pull request merged**
