### PR TITLE
Update Malay.properties

### PR DESCRIPTION
**Pull request by madbada99**
Yayay

### CODE REVIEW

**Comment by yairm210** [comment]
Placeholder `[30]` not found in `Malay` for entry `Offer Declaration of Friendship ([30] turns)`

**Comment by yairm210** [comment]
Are you going to fix this, or should I close it? Seems like a waste
Worst case, you can just remove the problematic line entirely

**Comment by madbada99** [comment]
So i need that 30 friendship

**Comment by yairm210** [comment]
Yes

**Pull request merged**
