### PR TITLE
Fixed error message of ConditionalBuilding

### PR DESCRIPTION
**Pull request by woo1127**
### Before:
unciv conditionalbuilding before

<br>

### After:
unciv conditionalbuilding after

### CODE REVIEW

**Review by yairm210 — APPROVED** [review]
Does this translate correctly into other languages? It looks like it should, but best to check

**Comment by yairm210** [comment]
Oh nope, this still requires adding a line for this translation in the template.properties file

**Comment by woo1127** [comment]
> Oh nope, this still requires adding a line for this translation in the template.properties file

Done adding the line 👍, is this okay ?

**Comment by woo1127** [comment]
May I know what things are still missing for this pull request to be committed ?

**Comment by yairm210** [comment]
Nothing, will enter next versino :D

**Review by yairm210 — APPROVED** [review]

**Comment by woo1127** [comment]
Thanks a lot =)

**Comment by yairm210** [comment]
Error message is

    National Wonder is being built elsewhere = ends without a space at the end

**Comment by woo1127** [comment]
> Error message is
> 
> ```
> National Wonder is being built elsewhere = ends without a space at the end
> ```

What does this mean ? Add a space at the end can solve the problem ?

**Comment by woo1127** [comment]
Done !!

**Review by yairm210 — APPROVED** [review]

**Pull request merged**
